### ISSUE TITLE
UTF-8 decoder reach Maximum call stack size with large csv file

### ISSUE THREAD

**Issue by kangyizhang** [tensorflow/tfjs#1006]
in a node example of parsing csv file (https://github.com/kangyizhang/abalone-test), it got error of 

(node:86070) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Utf8IteratorImpl.<anonymous> (/usr/local/google/home/kangyizhang/tensorflow/abalone/node_modules/@tensorflow/tfjs-data/src/iterators/byte_chunk_iterator.ts:129:58)
    at step (/usr/local/google/home/kangyizhang/tensorflow/abalone/node_modules/@tensorflow/tfjs-data/dist/iterators/byte_chunk_iterator.js:42:23)
    at Object.next (/usr/local/google/home/kangyizhang/tensorflow/abalone/node_modules/@tensorflow/tfjs-data/dist/iterators/byte_chunk_iterator.js:23:53)
    at fulfilled (/usr/local/google/home/kangyizhang/tensorflow/abalone/node_modules/@tensorflow/tfjs-data/dist/iterators/byte_chunk_iterator.js:14:58)
(node:86070) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 
Looks like some code that should use iteration is using recursion either in utf-8 lib or our own code. This might also cause the performance gap between model.fit and model.fitDataset

**Comment by davidsoergel** [comment]
This was fixed in https://github.com/tensorflow/tfjs-data/pull/109.
