### ISSUE TITLE
@tensorflow/tfjs 0.14.2 invalid maxPool and avgPool tests for TensorFlow backend

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#1077]
Running with latest `@tensorflow/tfjs` 0.14.2 - I see the following exceptions with `avgPool` and `maxPool` ops:

```
6) maxPool test-tensorflow {} x=[2,2,3] f=[1,1] s=2 p=1 dimRoundingMode=floor
  Message:
    Error: TF Backend supports only 'valid' and 'same' padding while padding was NUMBER
  Stack:
    Error: TF Backend supports only 'valid' and 'same' padding while padding was NUMBER
        at NodeJSKernelBackend.maxPool (/Users/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:905:13)
        at environment_1.ENV.engine.runKernel.x (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:93:39)
        at /Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:206:22
        at Engine.scopedRun (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:167:19)
        at Engine.runKernel (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:202:10)
        at maxPoolImpl_ (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:92:26)
        at maxPool_ (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:126:10)
        at Object.maxPool (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool_test.ts:98:23)
        at <Jasmine>
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:120:23)

7) avgPool test-tensorflow {} x=[2,2,3] f=[1,1] s=2 p=1 dimRoundingMode=floor
  Message:
    Error: TF Backend supports only 'valid' and 'same' padding while padding was NUMBER
  Stack:
    Error: TF Backend supports only 'valid' and 'same' padding while padding was NUMBER
        at NodeJSKernelBackend.avgPool (/Users/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:954:13)
        at environment_1.ENV.engine.runKernel.x (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:192:26)
        at /Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:206:22
        at Engine.scopedRun (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:167:19)
        at Engine.runKernel (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:202:10)
        at avgPoolImpl_ (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:191:24)
        at avgPool_ (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool.ts:226:10)
        at Object.avgPool (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/pool_test.ts:422:23)
        at <Jasmine>
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:120:23)
```

I'll add to the whitelist for now - but we should probably clean this up in core tests.

**Comment by gaikwadrahul8** [comment]
Hi, @nkreeger 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for support and understanding.
