### ISSUE TITLE
Guide: Using TensorFlow.js in Node.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1162]
How to choose the right node.js binding/package.

- Node.js

**Comment by tafsiri** [comment]
Link to doc https://github.com/tensorflow/tfjs-website/blob/devsite/docs/guides/using-tfjs-in-node.md

**Comment by adammichaelwood** [comment]
This document uses the word "vanilla" to describe the standard JS implementation.
Is this an official usage? I strikes me as culturally specific and potentially unclear.

**Comment by alexellis** [comment]
I'm trying to use the 'toxicity' model with Node.js 10 and am receiving this error:

```
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr: (node:12) UnhandledPromiseRejectionWarning: Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
tfjs-1.1.kja02m9fmp6h@nuc    |     at new BrowserHTTPRequest (/home/app/function/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:75:23)
tfjs-1.1.kja02m9fmp6h@nuc    |    
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr:  at Object.browserHTTPRequest (/home/app/function/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:454:12)
tfjs-1.1.kja02m9fmp6h@nuc    |     at GraphModel.findIOHandler (/home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:144:46)
tfjs-1.1.kja02m9fmp6h@nuc    |     at
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr:  GraphModel.<anonymous> (/home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:163:30)
tfjs-1.1.kja02m9fmp6h@nuc    |     at step (/home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
tfjs-1.1.kja02m9fmp6h@nuc    |     at Object.next 
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr: (/home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:29:53)
tfjs-1.1.kja02m9fmp6h@nuc    |     at /home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:23:71
tfjs-1.1.kja02m9fmp6h@nuc    |     at new Promise (<anonymous>)
tfjs-1.1.kja02m9fmp6h@nuc    |     at __awaiter (
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr: /home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:19:12)
tfjs-1.1.kja02m9fmp6h@nuc    |     at GraphModel.load (/home/app/function/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:158:16)
tfjs-1.1.kja02m9fmp6h@nuc    | (node:12) UnhandledPromiseRejecti
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr: onWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
tfjs-1.1.kja02m9fmp6h@nuc    | (node:12) [DEP0018] DeprecationWarning: Unh
tfjs-1.1.kja02m9fmp6h@nuc    | 2019/03/19 18:55:43 stderr: andled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
tfjs-1.1.kja02m9fmp6h@nuc    | 
```

Can someone advise? 

```js
"use strict"

const toxicity = require('@tensorflow-models/toxicity');
const threshold = 0.9;


module.exports = (event, context) => {
    let err;

toxicity.load(threshold).then(model => {
  const sentences = event.body.sentences;

  model.classify(sentences).then(predictions => {
    // `predictions` is an array of objects, one for each prediction head,
    // that contains the raw probabilities for each input along with the
    // final prediction in `match` (either `true` or `false`).
    // If neither prediction exceeds the threshold, `match` is `null`.

    console.log(predictions);
    context
        .status(200)
        .succeed(predictions);
    /*
    prints:
    {
      "label": "identity_attack",
      "results": [{
        "probabilities": [0.9659664034843445, 0.03403361141681671],
        "match": false
      }]
    },
    {
      "label": "insult",
      "results": [{
        "probabilities": [0.08124706149101257, 0.9187529683113098],
        "match": true
      }]
    },
    ...
     */
  });
});

}
```

**Comment by alexellis** [comment]
@tafsiri FYI your link is giving 404 for me

**Comment by tafsiri** [comment]
@alexellis could you make a new issue for the toxicity related error you are facing. Or comment on this one which sounds similar https://github.com/tensorflow/tfjs/issues/1427

Thanks for the heads up on the dead link.

**Comment by alexellis** [comment]
Will do.
