### ISSUE TITLE
Converting Sentence Encoders

### ISSUE THREAD

**Issue by juharris** [tensorflow/tfjs#1179]
#### TensorFlow.js version
Python: tensorflowjs==0.6.7

#### Describe the problem or feature request
I'd like to use an existing sentence encoder in Node. I've been trying to _convert_ a few of the existing ones from TensorFlow Hub with no success.  Getting any of the encoder to work would be fine for me.

#### Code to reproduce the bug / link to feature request
# Universal Sentence Encoder
```
tensorflowjs_converter     --input_format=tf_hub 'https://tfhub.dev/google/universal-sentence-encoder/2' model/
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 118, in download_and_uncompress
    extract_file(tgz, tarinfo, abs_target_path)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 88, in extract_file
    shutil.copyfileobj(src, dst, buffer_size)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/tarfile.py", line 708, in readinto
    buf = self.read(len(b))
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/tarfile.py", line 699, in read
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/tensorflowjs/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 347, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 403, in convert_tf_hub_module
    module_path, signature)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 352, in load_and_initialize_hub_module
    module = hub.Module(module_path)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/module.py", line 105, in __init__
    self._spec = as_module_spec(spec)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/module.py", line 31, in as_module_spec
    return native_module.load_module_spec(spec)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 99, in load_module_spec
    path = compressed_module_resolver.get_default().get_module_path(path)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 385, in get_module_path
    return self._get_module_path(handle)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 467, in _get_module_path
    return resolver.get_module_path(handle)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 385, in get_module_path
    return self._get_module_path(handle)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 105, in _get_module_path
    self._lock_file_timeout_sec())
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 313, in atomic_download
    download_fn(handle, tmp_dir)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 102, in download
    return resolver.download_and_uncompress(cur_url, response, tmp_dir)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 126, in download_and_uncompress
    raise IOError("%s does not appear to be a valid module." % filename)
OSError: https://tfhub.dev/google/universal-sentence-encoder/2 does not appear to be a valid module.
```

# ELMo
```
tensorflowjs_converter     --input_format=tf_hub 'https://tfhub.dev/google/elmo/1' elmotf/
Using TensorFlow backend.
2019-01-31 10:42:21.275157: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Creating a model with inputs ['text'] and outputs ['module_apply_default/bilm/Reshape_1', 'module_apply_default/aggregation/mul_3', 'module_apply_default/pooling/truediv', 'module_apply_default/concat', 'module_apply_default/concat_1'].
Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'module_apply_default/bilm/embedding_lookup' expects to be colocated with unknown node 'module_apply_default/bilm/embedding_lookup/Read/ReadVariableOp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/tensorflowjs/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 347, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 425, in convert_tf_hub_module
    graph = load_graph(frozen_file, ','.join(output_node_names))
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/justin/miniconda3/envs/tensorflowjs/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Node 'module_apply_default/bilm/embedding_lookup' expects to be colocated with unknown node 'module_apply_default/bilm/embedding_lookup/Read/ReadVariableOp'
```

EDIT: Corrected minor typos.

**Comment by pyu10055** [comment]
@juharris We just pushed a sentence encoder to our model repo. https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder
This is based on the tfhub USE lite.

**Comment by juharris** [comment]
Good enough for me!
