### ISSUE TITLE
Core tests failing at head: ModelManagement List models: 0

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1198]
```Chrome 72.0.3626 (Mac OS X 10.13.6) ModelManagement webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} List models: 0 result FAILED
	Expected object not to have properties
	    localstorage://repeat/QuxModel: Object({ dateSaved: '2019-02-04T18:09:24.196Z', modelTopologyType: 'JSON', modelTopologyBytes: 555, weightSpecsBytes: 109, weightDataBytes: 16 })
	Error: Expected object not to have properties
	    at <Jasmine>
	    at src/io/model_management_test.ts:97:22 <- src/io/model_management_test.js:74:25
```

**Comment by nsthorat** [comment]
This seems to be related to Chrome 72, doesn't show up on Chrome 71.

**Comment by nsthorat** [comment]
This test is also failing:
```
Chrome 72.0.3626 (Mac OS X 10.13.6) ModelManagement webgl {"WEBGL_CPU_FORWARD":true} List models: 1 result FAILED
	Expected 2 to equal 1.
	    at <Jasmine>
	    at src/io/model_management_test.ts:114:48 <- src/io/model_management_test.js:86:49
```
