### ISSUE TITLE
Tensorflow install problems

### ISSUE THREAD

**Issue by Someone202** [tensorflow/tfjs#1281]
I am trying to install tensorflow.js on a windows machine.

I have used the command:
npm i @tensorflow/tfjs-node-gpu

I have python version 2.7 as well as node verion 10.15.1 and node-gyp version 3.8.0 I have installede windows build tools. Whenever I try to install it however I get the following error.

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Coding\AI\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Can anyone help?

**Comment by kangyizhang** [comment]
This should be duplicate of https://github.com/tensorflow/tfjs/issues/1121 and will be fixed by https://github.com/tensorflow/tfjs-node/pull/208

**Comment by nkreeger** [comment]
Please try with 0.3.1 (just published)
