### ISSUE TITLE
[question{ Which version of Tensorflow (libtensorflow) does tfjs-node/-gpu depend on?

### ISSUE THREAD

**Issue by innerop** [tensorflow/tfjs#1311]
hi,

I noticed that I can’t install tfjs-node-gpu unless I first build libtensorflow from Tensorflow-GPU. Given the dependency, what version of the Tensorflow backend is supported by Tensorflow.JS?

I could be misunderstanding the relationship between the two but I’m not sure how tfjs-node can be isolated from change to the Tensorflow backend. For example, what happens when Tensorflow transitions to 2.0 with many breaking changes? Does the tfjs API change too? 

Confused. Any clarification would be appreciated. Thank you.

**Comment by caisq** [comment]
cc @nkreeger

**Comment by innerop** [comment]
Hmm. Looks like I have to build tensorflow-gpu in order to get libtensorflow but the question is how do I inform ld about the location of libtensorflow once I build it?

So in my docker, I install the official NVIDIA tensorflow-gpu for Jetson TX2 SBC (aarch64/Tegra):
 
Successfully installed absl-py-0.7.0 astor-0.7.1 gast-0.2.2 grpcio-1.19.0 markdown-3.0.1 numpy-1.16.2 protobuf-3.7.0 setuptools-39.1.0 six-1.12.0 tensorboard-1.9.0 tensorflow-gpu-1.9.0+nv18.8 termcolor-1.1.0 werkzeug-0.14.1

But when I try to install tfjs-node-gpu, I immediately get the message that ld cannot find the tensorflow library. Is there an ENV var that I need to set? like LD_LIBRARY_PATH? In the docker I do use ldconfig to configure the library location but maybe I have to set the ENV var too. Will try that too, but the message from ld says it can't find '-ltensorflow' which I assume is referring to libtensorflow. Not sure.

> @tensorflow/tfjs-node-gpu@0.3.1 install /node_modules/@tensorflow/tfjs-node-gpu
> node scripts/install.js gpu download

* Downloading libtensorflow

* Building TensorFlow Node.js bindings
/node_modules/@tensorflow/tfjs-node-gpu/scripts/install.js:161
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
/usr/bin/ld: skipping incompatible ./Release/libtensorflow.so when searching for -ltensorflow
/usr/bin/ld: cannot find -ltensorflow
/usr/bin/ld: skipping incompatible ./Release/libtensorflow_framework.so when searching for -ltensorflow_framework
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/tfjs_binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.38-tegra
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/@tensorflow/tfjs-node-gpu
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at cp.exec (/node_modules/@tensorflow/tfjs-node-gpu/scripts/install.js:161:13)
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node-gpu@0.3.1 install: `node scripts/install.js gpu download`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tensorflow/tfjs-node-gpu@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-03T19_53_37_760Z-debug.log

**Comment by adwellj** [comment]
@innerop, just curious if you made any progress on this. I've been sitting on a TX2 dev kit for a while and was wanting to test it out with tfjs-node-gpu :)

**Comment by tdurand** [comment]
Same here, does someone successfully run tfjs-node-gpu on an arm64 like Jetson Nano / TX2 ?

**Comment by josephrocca** [comment]
I'm not sure if my issue is related, but I've followed the instructions at [tensorflow.org/install/docker#gpu_support](https://www.tensorflow.org/install/docker#gpu_support) to install docker, and it seems to work fine with python:
```
sudo docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu    python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```
```
2020-01-19 03:42:35.391400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-01-19 03:42:35.392368: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-01-19 03:42:35.743097: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-19 03:42:35.775753: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.777170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.44GHz coreCount: 36 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-19 03:42:35.777235: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-19 03:42:35.777304: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-19 03:42:35.778680: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-19 03:42:35.779089: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-19 03:42:35.780770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-19 03:42:35.781782: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-19 03:42:35.781843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-19 03:42:35.781927: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.782791: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.783445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-19 03:42:35.783888: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-19 03:42:35.790412: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-01-19 03:42:35.791136: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55de5a9c0610 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-19 03:42:35.791147: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-19 03:42:35.868398: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.868726: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55de5aa25fd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-01-19 03:42:35.868740: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2020-01-19 03:42:35.868848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.869143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2070 computeCapability: 7.5
coreClock: 1.44GHz coreCount: 36 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2020-01-19 03:42:35.869162: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-19 03:42:35.869168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-01-19 03:42:35.869177: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-01-19 03:42:35.869183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-01-19 03:42:35.869189: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-01-19 03:42:35.869194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-01-19 03:42:35.869199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-19 03:42:35.869226: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.870044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:35.870298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-01-19 03:42:35.870317: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-01-19 03:42:36.048792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-19 03:42:36.048819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-01-19 03:42:36.048824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-01-19 03:42:36.048955: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:36.049400: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:42:36.049666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4344 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
tf.Tensor(-1445.1068, shape=(), dtype=float32)

```

But when I try running this with node within the same docker container it doesn't work:
```
require("@tensorflow/tfjs-node-gpu");
```

```
2020-01-19 03:11:42.878871: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-19 03:11:42.911124: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-01-19 03:11:42.911643: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x65743b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-19 03:11:42.911656: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-19 03:11:42.912223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-19 03:11:42.940115: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 03:11:42.940368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.44
pciBusID: 0000:01:00.0
2020-01-19 03:11:42.940481: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.940582: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.940722: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.940773: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.940830: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.940916: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 03:11:42.943308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-19 03:11:42.943319: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-01-19 03:11:43.002417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-19 03:11:43.002435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-01-19 03:11:43.002440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
```

**Comment by rthadur** [comment]
As mentioned [here](https://github.com/tensorflow/tfjs/issues/3287#issuecomment-656935658) , tfjs-node depend on tf core version 1.5.0
