### ISSUE TITLE
Unable to run Body-pix via npm

### ISSUE THREAD

**Issue by Akhiladdh** [tensorflow/tfjs#1332]
I created a Sample.js file with below contents
`import * as bodypix from '@tensorflow-models/body-pix';
const outputStride = 16;
const segmentationThreshold = 0.5;
const imageElement = document.getElementById('image');
// load the BodyPix model from a checkpoint
const net = await bodyPix.load();
const segmentation = await net.estimatePersonSegmentation(imageElement, outputStride, segmentationThreshold);
console.log(segmentation);
`
When I run it with npm as node sample.js, I am getting below error.
`
root@53ce841ee5c5:/home/Container_data/Test_models/TensorFlowModels/tfjs-models# node test.js
/home/Container_data/Test_models/TensorFlowModels/tfjs-models/test.js:1
(function (exports, require, module, __filename, __dirname) { import * as bodypix from '@tensorflow-models/body-pix';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
`
Can someone help me resolve this?

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow.js) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Akhiladdh** [comment]
@rthadur Sure Thank you!
