### ISSUE TITLE
Update tfjs-node to depend on tfjs@1.0.0.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tfjs#1348]
This is going to require:

- Changing the calls to browserHTTPRequest to the new API: https://github.com/tensorflow/tfjs-core/blob/master/src/io/browser_http.ts#L434
- Adding fill / ones / onesLike kernels.

**Comment by huan** [comment]
Yes, please fill the kernel backends...

They are all throw exception currently... :(

https://github.com/tensorflow/tfjs-core/blob/1d6a1ce0b908bf8e9edcccb11d7a3feed5611c97/src/kernels/backend.ts#L592-L598

```
$ node -r ts-node/register translation.ts --epochs 30 ~/git/javascript-concist-chit-chat/dist/fra.txt 
2019-03-10 01:02:10.543593: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Number of samples: 10000
Number of unique input tokens: 69
Number of unique output tokens: 93
Max sequence length for inputs: 16
Max sequence length for outputs: 59
Saved metadata at:  /tmp/translation.keras/metadata.json
Orthogonal initializer is being called on a matrix with more than 2000 (262144) elements: Slowness may result.
Orthogonal initializer is being called on a matrix with more than 2000 (262144) elements: Slowness may result.
Epoch 1 / 30
(node:3502) UnhandledPromiseRejectionWarning: Error: Not yet implemented
    at NodeJSKernelBackend.KernelBackend.zerosLike (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/kernels/backend.ts:597:11)
    at environment_1.ENV.engine.runKernel.$x (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/ops/tensor_ops.ts:467:50)
    at /home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/engine.ts:206:22
    at Engine.scopedRun (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/engine.ts:167:19)
    at Engine.runKernel (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/engine.ts:202:10)
    at zerosLike_ (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/ops/tensor_ops.ts:467:21)
    at Object.zerosLike (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
    at Object.$x (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/ops/unary_ops.ts:349:21)
    at _loop_1 (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/src/tape.ts:171:43)
    at Object.backpropagateGradients (/home/zixia/git/tfjs-examples/translation/node_modules/@tensorflow/tfjs-core/dist/tape.js:158:9)
(node:3502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nsthorat** [comment]
This is done now.

**Comment by huan** [comment]
Cheers!
