### ISSUE TITLE
util_1.promisify is not a function

### ISSUE THREAD

**Issue by cagnulein** [tensorflow/tfjs#1364]
import * as tf from '@tensorflow/tfjs-node';
and
import * as tf from '@tensorflow/tfjs-node-gpu';

fails with:

file_system.js:58 Uncaught TypeError: util_1.promisify is not a function
    at Object.<anonymous> (file_system.js:58)
    at Object.265../io_utils (file_system.js:360)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.263.../package.json (index.js:31)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.1.@babel/polyfill (main.js:18)
    at o (_prelude.js:1)
    at r (_prelude.js:1)

import * as tf from '@tensorflow/tfjs'; works fine

tfjs version 1.0.0
tjfs-node version 0.3.2
thjs-node-gpu version 0.3.2
node-v10.15.3

**Comment by bileschi** [comment]
One should not import both tfjs-node *and* tfjs-node-gpu.  Please use one or the other.

see for instance:
https://github.com/tensorflow/tfjs-examples/blob/77d802f07b19f022098820ba5093082e34a5ca5e/jena-weather/train-rnn.js#L91

**Comment by cagnulein** [comment]
> One should not import both tfjs-node _and_ tfjs-node-gpu. Please use one or the other.
> 
> see for instance:
> https://github.com/tensorflow/tfjs-examples/blob/77d802f07b19f022098820ba5093082e34a5ca5e/jena-weather/train-rnn.js#L91

i'm not using them together, i said that import * as tf from '@tensorflow/tfjs-node'; creates the issue and even if i use import * as tf from '@tensorflow/tfjs-node-gpu'; i have the same issue.

**Comment by bileschi** [comment]
Ah.  Sorry.  Misunderstood.

**Comment by bileschi** [comment]
Can you work with the tfjs-node examples from tfjs-examples?
For instance, can you build and run the jena-weather example here?
https://github.com/tensorflow/tfjs-examples/tree/master/jena-weather

```
yarn
yarn train-rnn
```

**Comment by cagnulein** [comment]
argh, running jena-weather i encountered another issue :(

C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather>yarn train-rnn --gpu
yarn run v1.13.0
$ babel-node train-rnn.js --gpu
C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\babel-plugin-transform-runtime\lib\index.js:31
      this.setDynamic("regeneratorIdentifier", function () {
           ^

TypeError: this.setDynamic is not a function
    at PluginPass.pre (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\babel-plugin-transform-runtime\lib\index.js:31:12)
    at transformFile (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\core\lib\transformation\index.js:78:27)
    at runSync (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at transformSync (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\core\lib\transform.js:22:38)
    at compile (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\register\lib\node.js:73:20)
    at compileHook (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\pirates\lib\index.js:93:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (C:\Work\Tensorflow\Tensorflow.js\tfjs-examples\jena-weather\node_modules\pirates\lib\index.js:104:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Hernanm0g** [comment]
hi.

Same error with 
`import * as tf from '@tensorflow/tfjs-node'`
in node v12.16.1

When installing utils
`npm i utils`
got this error
_Uncaught TypeError: The "original" argument must be of type Function_

Any idea?

**Comment by rthadur** [comment]
Closing this due to lack of activity, feel to reopen. Thank you

**Comment by cswkim** [comment]
I'm also getting this error with node v14.4.0. Any luck?

**Comment by rogdevil** [comment]
I am also getting the same error .. can you guys please open it again ... thanks for all your support !! i am using node 14.15.0

**Comment by rthadur** [comment]
@rogdevil please open a new issue with the template https://github.com/tensorflow/tfjs/issues/new/choose

**Comment by thekingslee** [comment]
I am getting this issue with @tensorflow/tfjs-node@4.22.0 on Node v24.1.0

My program fails in line:
```
 const decoded = tf.node.decodeImage(imageBuffer);
```

The error I get says: `"util_1.isNullOrUndefined is not a function"`

@bileschi @cagnulein were you able to find a fix??
