### ISSUE TITLE
Tensorflow Node.js and Java Bindings

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tfjs#1421]
#### TensorFlow.js version
1.13.1

#### Browser version
Node.js

#### Describe the problem or feature request
Conflicts between Tensorflow Java and JavaScript bindings.
In my project I'm running Tensorflow Java bindings (because it existed before TF.JS bindings).
It seems that as soon as I load the Node.js bindings, the Java bindings will fail to load:

In `@tensorflow/tfjs-node/deps/lib` I have the node bindings
```
ls -l node_modules/@tensorflow/tfjs-node/deps/lib
total 388432
-r-xr-xr-x  1 loretoparisi  staff  182985692  1 Gen  1970 libtensorflow.so
-r-xr-xr-x  1 loretoparisi  staff   14136480  1 Gen  1970 libtensorflow_framework.so
```

while let's say in `/root/jni` there are the Java bindings:

```
total 294152
-r-xr-xr-x  1 loretoparisi  staff     331921 28 Giu  2018 LICENSE
-r-xr-xr-x  1 loretoparisi  staff   12019756 28 Giu  2018 libtensorflow_framework.so
-rw-r--r--  1 loretoparisi  staff   12019756 28 Giu  2018 libtensorflow_framework_darwin.so
-rw-r--r--  1 loretoparisi  staff  124911544 28 Giu  2018 libtensorflow_jni.dylib
```

where Java bindings are loaded through the `-Djava.library.path=` library path (see the repo below for an example).

What happens is this 

1. The Node.js Tensorflow loads perfectly through the `require('@tensorflow/tfjs-node');`. 
I can see the typical logging.

```
2019-03-19 19:21:41.644954: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
``` 

And also the module works in inference. As soon as I load the java module, I get the 
`UnsatisfiedLinkError` caused by the native library:

```
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: darwin, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:101)
	at serving_utils.SentenceClassificationModel.<init>(SentenceClassificationModel.java:42)
	at serving_utils.SentenceClassificationModel.<init>(SentenceClassificationModel.java:25)
	at musixmatch_nlp.MXMSentimentTensorflowAnnotator.<init>(MXMSentimentTensorflowAnnotator.java:32)
	... 19 more
```

**NOTE**
Without the TF.JS module running, the Java bindings works, i.e. the `UnsatisfiedLinkError` is not thrown and the module is loaded correctly.

#### Code to reproduce the bug / link to feature request
Run Java Bindings from here https://github.com/loretoparisi/tensorflow-java
and in the same run-time run the TF.JS bindings

**Comment by loretoparisi** [comment]
**[UPDATE]**
Further findings: the issue happens in both cases when reversing the order of Java / Node.js modules loading into the system:

1. Load TF.JS `require('@tensorflow/tfjs-node');` **then** Load Tensorflow Java (with ` -Djava.library.path=`)

The error was:
```sh
Caused by: java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: darwin, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.
```

2. Load Tensorflow Java (with ` -Djava.library.path=`) **then**  Load TF.JS `require('@tensorflow/tfjs-node');` 

The error was raised `dlopen`

```sh
Registration of backend tensorflow failed
Error: dlopen(/node_modules/@tensorflow/tfjs-node/build/Release/tfjs_binding.node, 1): Symbol not found: __ZN10tensorflow10DeviceBase16eigen_cpu_deviceEv
  Referenced from: /node_modules/@tensorflow/tfjs-node/build/Release/libtensorflow.so
  Expected in: /Users/loretoparisi/webservice/jni/darwin/libtensorflow_framework.so
 in /node_modules/@tensorflow/tfjs-node/build/Release/libtensorflow.so
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/node_modules/bindings/bindings.js:84:48)
    at /node_modules/@tensorflow/tfjs-node/dist/index.js:49:60
    at Environment.registerBackend (/node_modules/@tensorflow/tfjs-core/dist/environment.js:439:27)
    at Object.<anonymous> (/node_modules/@tensorflow/tfjs-node/dist/index.js:48:8)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)

============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
```

**Comment by rthadur** [comment]
Closing this due to lack of activity, feel to reopen. Thank you
