### ISSUE TITLE
errors executing async models loaded via tf.loadGraphModel.

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1449]
#### TensorFlow.js version

```
"@tensorflow-models/coco-ssd": "^1.0.0",
"@tensorflow-models/mobilenet": "^1.0.0",
"@tensorflow-models/universal-sentence-encoder": "1.0.1",
"@tensorflow/tfjs": "1.0.0",
"@tensorflow/tfjs-node": "1.0.1",
```

Error also occurs on tfjs 1.0.2

#### Node version
Node 11.11

#### Describe the problem or feature request
The following error occurs when making a prediction with either coco-ssd or universal-sentence-encoder (which are both models with control flow ops). But doesn't happen with mobilenet.

```
node:59415) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at /Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:295:99
    at Array.map (<anonymous>)
    at GraphExecutor.<anonymous> (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:295:58)
    at step (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:56:23)
    at Object.next (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:37:53)
    at fulfilled (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_executor.js:28:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

From doing some console logging it looks like the tensors in the graph are undefined during executeAsync.

Note that I only get this error when using the node backend (tfjs-node), if i use the vanilla cpu backend (tfjs) it works.

#### Code to reproduce the bug / link to feature request

```
// const tf = require('@tensorflow/tfjs'); // using this import works
const tf = require('@tensorflow/tfjs-node');
const cocossd = require('@tensorflow-models/coco-ssd');
const mob = require('@tensorflow-models/mobilenet');
global.fetch = require('node-fetch');
const useLoader = require('@tensorflow-models/universal-sentence-encoder');

// This works
const model = await mob.load();
const res = await model.classify(tf.randomNormal([224, 224, 3]));
console.log(res);

// This fails.
const cocomodel = await cocossd.load();
const cocoa = await cocomodel.detect(tf.randomNormal([224, 224, 3]));
console.log(cocoa)
  
// this fails
console.time('Loading Universal Sentence Encoder');
const use = await useLoader.load();
console.timeEnd('Loading Universal Sentence Encoder');
```

**Comment by tafsiri** [comment]
Further info on this. This bug doesn't occer when using the following import pattern (where both tfjs and tfjs-node are required).

```
const tf = require('@tensorflow/tfjs');
require('@tensorflow/tfjs-node');
```

**Comment by pyu10055** [comment]
@tafsiri can you share your package.json file? I suspect that what you including multiple models, they installed different versions of tfjs.

**Comment by tafsiri** [comment]
Here are my dependencies. I only have one model loaded in my actual project, the multiple models in the example above was just to confirm that it wasn't specific to universal-sentence-encoder

```
"dependencies": {
    "@tensorflow-models/universal-sentence-encoder": "1.0.1",
    "@tensorflow/tfjs": "1.0.1",
    "@tensorflow/tfjs-node": "1.0.1",
    "d3-dsv": "^1.1.1",
    "lodash": "^4.17.11",
    "node-fetch": "^2.3.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "clang-format": "^1.2.4",
    "cross-env": "^5.2.0",
    "http-server": "^0.11.1",
    "parcel-bundler": "^1.12.3"
  }

```

**Comment by pyu10055** [comment]
@tafsiri I believe tfjs-node has tfjs as dependencies, you don't need to install tfjs separately. Can you try to remove tfjs from your package.json file?

**Comment by tafsiri** [comment]
@pyu10055 If i do that I get the following error

```
(node:56574) UnhandledPromiseRejectionWarning: Error: Found more than one (2) load handlers for URL 'https://storage.googleapis.com/tfjs-models/savedmodel/universal_sentence_encoder/model.json'
    at GraphModel.findIOHandler (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:147:23)
    at GraphModel.<anonymous> (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:163:30)
    at step (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
    at Object.next (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:29:53)
    at /Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:19:12)
    at GraphModel.load (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:158:16)
    at Object.<anonymous> (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:377:48)
    at step (/Users/yassogba/projects/intent-classifier/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
```

**Comment by pyu10055** [comment]
@tafsiri This is IOHandler error, probably https are register with both browser and node handlers.
Do you have repo or codepen for me to reproduce?

**Comment by tafsiri** [comment]
@pyu10055 This repo code demonstrates it https://github.com/tafsiri/use-text-classifier/blob/master/training/train.js, update the package.json to remove the other models. However on your point about that I thought all the models specify tfjs as a peerDependency, so they won't install their own copy.

Also see https://github.com/tensorflow/tfjs/issues/1454

**Comment by pyu10055** [comment]
@tafsiri @caisq The multiple io handler issue seems to be root in this code
https://github.com/tensorflow/tfjs-node/blob/3f8f64a420711b3cf542bc97ce97cf3d78c471e1/src/io/node_http.ts
which register a handler for http url as the same time as core browser_http class.
If we allow multiple handlers, we need to update the model loaders to use a particular
handler (the last one)?

**Comment by pyu10055** [comment]
@tafsiri is this issue resolved?

**Comment by tafsiri** [comment]
No longer an issue on latest tfjs.
