### ISSUE TITLE
Conflicting load handlers for pre-trained USE model with Node

### ISSUE THREAD

**Issue by ejonokuchi** [tensorflow/tfjs#1454]
### System information
- Mac OS Mojave - 10.14.1
- Node.js - 10.15.1
- relevant npm packages (fresh copies as of the time of this post):
    - @tensorflow-models/universal-sentence-encoder@1.0.1
    - @tensorflow/tfjs@1.0.2
    - @tensorflow/tfjs-node@1.0.2
    - express@4.16.4
    - node-fetch@2.3.0

### Issue

Kind of related to #1427. Using the [pre-trained USE model](https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder) in a simple Express server endpoint to embed text.

When I use the `tfjs-node` bindings, I get the following error:
```
Error: Found more than one (2) load handlers for URL 'https://storage.googleapis.com/tfjs-models/savedmodel/universal_sentence_encoder/model.json'
    at GraphModel.findIOHandler (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:147:23)
    at GraphModel.<anonymous> (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:163:30)
    at step (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
    at Object.next (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:29:53)
    at .../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:23:71
    at Promise._execute (.../node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (.../node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (.../node_modules/bluebird/js/release/promise.js:79:10)
    at __awaiter (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:19:12)
    at GraphModel.load (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:158:16)
    at Object.<anonymous> (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:377:48)
    at step (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
    at Object.next (.../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:29:53)
    at .../node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:23:71
    at Promise._execute (.../node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (.../node_modules/bluebird/js/release/promise.js:483:18)
```

Here's the relevant source code (called from the controller). To get rid of the error, you can comment out this line: `require('@tensorflow/tfjs-node')`. But then you lose the performance boost of the node backend.

```
// Override fetch in tensorflow js
global.fetch = require('node-fetch');
// Use tensorflow js node backend
require('@tensorflow/tfjs-node');

const universalSentenceEncoder = require('@tensorflow-models/universal-sentence-encoder');

/**
 * Encode a variable length string as a sentence embedding via the Universal Sentence Encoder.
 *
 * @param {*} text - the input string
 */
exports.embed = async function embed(text) {
  const result = universalSentenceEncoder.load().then(model => model.embed(text));
  return result;
};
```

**Comment by chenqing** [comment]
I think just comment this and not require another fetch , in tfjs-node 1.0.2 , this works.
`//global.fetch = require('node-fetch');`

**Comment by ejonokuchi** [comment]
No, it doesn't with the USE module (`@tensorflow-models/universal-sentence-encoder@1.0.1`).

The error is being thrown from here: https://github.com/tensorflow/tfjs-converter/blob/master/src/executor/graph_model.ts#L99-L101.

I've just commented this out for now—but I wonder why it's necessary to throw an error if you're going to just choose the first load handler in L102 anyway?

**Comment by rstor1** [comment]
I have a similar issue trying when trying to use speech commands but that repo does not seem to be taking on issues so thought I would look here. Here is what I get when using **global.fetch:** `Error: Found more than one (2) load handlers for URL 'https://storage.googleapis.com/tfjs-models/tfjs/speech-commands/v0.3/browser_fft/18w/model.json'`.

But when I comment that out I get: `ReferenceError: fetch is not defined` 

I am just using the tutorial:
```
async function app() {
    recognizer = speechCommands.create('BROWSER_FFT');
    await recognizer.ensureModelLoaded();
    predictWord();
};
```
and `recognizer` becomes undefined in `predictWord()`.

**Comment by rthadur** [comment]
as per #1449 this has been resolved in latest version.
