### ISSUE TITLE
Issues regarding running demo code for posenet

### ISSUE THREAD

**Issue by basicvisual** [tensorflow/tfjs#1467]
Hi , I have some issues to run the demo codes for posenet model. After downloading the repository , I go to the posenet directory . There I execute the command 

`/repos/tfjs-models/posenet$ npm i @tensorflow-models/posenet` 
I have the following configuration , when i have a look into the log file i get the following 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@tensorflow-models/posenet' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @tensorflow-models/posenet
8 silly fetchNamedPackageData @tensorflow-models/posenet
9 silly mapToRegistry name @tensorflow-models/posenet
10 silly mapToRegistry scope (from package name) @tensorflow-models
11 verbose mapToRegistry no registry URL found in name for scope @tensorflow-models
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/@tensorflow-models%2fposenet
15 verbose request uri https://registry.npmjs.org/@tensorflow-models%2fposenet
16 verbose request no auth needed
17 info attempt registry request try #1 at 4:53:26 AM
18 verbose request id 36a6e11f0dbb95d5
19 verbose etag W/"358c0a9eecf22c261d3423968e56d351"
20 verbose lastModified Wed, 06 Mar 2019 16:47:11 GMT
21 http request GET https://registry.npmjs.org/@tensorflow-models%2fposenet
22 http 304 https://registry.npmjs.org/@tensorflow-models%2fposenet
23 verbose headers { date: 'Fri, 29 Mar 2019 11:53:26 GMT',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'set-cookie': [ '__cfduid=d64ad2b8a4bb45f1eda41a6655ac2a3e91553860406; expires=Sat, 28-Mar-20 11:53:26 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
23 verbose headers   'cf-cache-status': 'HIT',
23 verbose headers   'cache-control': 'public, max-age=300',
23 verbose headers   'cf-ray': '4bf1a4b38813cb02-ARN',
23 verbose headers   etag: '"358c0a9eecf22c261d3423968e56d351"',
23 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
23 verbose headers   'last-modified': 'Wed, 06 Mar 2019 16:47:11 GMT',
23 verbose headers   vary: 'Accept-Encoding',
23 verbose headers   'x-amz-meta-rev': '16-ca4cc9c55e57b7a296bb0b66e9cb25a7',
23 verbose headers   server: 'cloudflare' }
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 29 Mar 2019 11:53:26 GMT',
24 silly get     connection: 'keep-alive',
24 silly get     'set-cookie': [ '__cfduid=d64ad2b8a4bb45f1eda41a6655ac2a3e91553860406; expires=Sat, 28-Mar-20 11:53:26 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
24 silly get     'cf-cache-status': 'HIT',
24 silly get     'cache-control': 'public, max-age=300',
24 silly get     'cf-ray': '4bf1a4b38813cb02-ARN',
24 silly get     etag: '"358c0a9eecf22c261d3423968e56d351"',
24 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
24 silly get     'last-modified': 'Wed, 06 Mar 2019 16:47:11 GMT',
24 silly get     vary: 'Accept-Encoding',
24 silly get     'x-amz-meta-rev': '16-ca4cc9c55e57b7a296bb0b66e9cb25a7',
24 silly get     server: 'cloudflare' } ]
25 verbose etag https://registry.npmjs.org/@tensorflow-models%2fposenet from cache
26 verbose get saving @tensorflow-models/posenet to /home/ubuntu/.npm/registry.npmjs.org/_40tensorflow-models_252fposenet/.cache.json
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install @tensorflow-models/posenet as a dependency of itself
44 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
44 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
44 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
44 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
44 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
44 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
45 verbose cwd /home/ubuntu/repos/tfjs-models/posenet
46 error Linux 4.15.0-46-generic
47 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "@tensorflow-models/posenet"
48 error node v4.2.6
49 error npm  v3.5.2
50 error code ENOSELF
51 error Refusing to install @tensorflow-models/posenet as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]

```
`Ubuntu 16.04 
vmware
npm version 3.5.2 
yarn version 0.22 
`
Am i in the right directory level  ? 
I tried to run the npm command in the following directory level 'repos/tfjs-models' then i get the following error 

```
`├── @tensorflow-models/posenet@1.0.0  extraneous
└── UNMET PEER DEPENDENCY @tensorflow/tfjs@^1.0.0
npm WARN @tensorflow-models/posenet@1.0.0 requires a peer of @tensorflow/tfjs@^1.0.0 but none was installed.
npm WARN tensorflow-models@0.0.1 No repository field.
`

```
I was wondering what is the correct way ? and how can one compile if any changes made in the `src` directory

**Comment by basicvisual** [comment]
I think , be executing the following `npm i @tensorflow-models/posenet` command in the `repos/tfjs-models/posenet/demos` , is the right way to proceed ?

**Comment by ericmcgregor** [comment]
I am unable to run the demo folder locally as well.  I get the following error:

Uncaught (in promise) Error: got multiplier type of object when it should be a number.
    at Object.v [as assert] (util.ts:106)
    at Object.<anonymous> (posenet.esm.js:2)
    at posenet.esm.js:2

I don't know why this issue is closed.  The instructions in the demo folder clearly do not work and I'm not sure how to fix the error.
