### ISSUE TITLE
Error loading model with rnn layer and stacked cells

### ISSUE THREAD

**Issue by oorooroot** [tensorflow/tfjs#1476]
#### TensorFlow.js version
"@tensorflow/tfjs-node": "^1.0.2"
#### Browser version
node.js v10.15.1
#### Describe the problem or feature request
Trying to load previously saved model causes error:
```Error: The RNN cell should have an attribute `stateSize` (tuple of integers, one integer per RNN state).```
#### Code to reproduce the bug / link to feature request
```
const m = tf.sequential();
m.add(tf.layers.dense({units: 1, inputShape: [10, 20]}));
const cells = [
	tf.layers.lstmCell({units: 4}),
	tf.layers.lstmCell({units: 8}),
];
const rnn = tf.layers.rnn({cell: cells, returnSequences: true});
m.add(rnn);

await m.save('file://./models/test1');
let m2 = await tf.loadLayersModel('file://./models/test1/model.json');
console.log(m2);
```

**Comment by Palabola** [comment]
Same problem here, it seems that saving or loading LSTM models are broken in TFJS.

**Comment by caisq** [comment]
@oorooroot @Palabola Thank you for reporting the issue and the very helpful reproduction code snippet. We can reproduce the error and understand its root cause. We'll push a fix to it soon. 

Sorry for the inconvenience.

**Comment by jungwook** [comment]
running the exact same code.... I still get errors.... this time:

(node:18630) UnhandledPromiseRejectionWarning: Error: Duplicate weight name: rnn_RNN1/kernel
    at new ValueError (/Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/errors.js:68:28)
    at Sequential.Container.loadWeights (/Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/engine/container.js:532:27)
    at /Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/models.js:302:27
    at step (/Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/models.js:54:23)
    at Object.next (/Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/models.js:35:53)
    at fulfilled (/Users/jungwook/Documents/Development/Tensor/node_modules/@tensorflow/tfjs-layers/dist/models.js:26:58)

Can you follow up please?

Thank you.

**Comment by rthadur** [comment]
@jungwook please open a new issue using the [template](https://github.com/tensorflow/tfjs/issues/new).

**Comment by jungwook** [comment]
Still not working
