### ISSUE TITLE
Error with require('@tensorflow/tfjs-node'), initialization of backend tensorflow failed.

### ISSUE THREAD

**Issue by Ashnxious** [tensorflow/tfjs#1579]
#### TensorFlow.js version
@tensorflow/tfjs-node@1.1.2
#### Browser version
None
#### Describe the problem or feature request
An error occurs when I require @tensorflow/tfjs-node
#### Code to reproduce the bug / link to feature request
Install node.js version 12.2.0, python 2.7.16, and add python to path.
Then on the command line, type (as admin)
`npm install -g --production windows-build-tools`
the windows-build-tools module, for node-gyp, is necessary to install @tensorflow/tfjs-node.

Then create a new directory(Tensor in my case) and initialize npm, and then install @tensorflow/tfjs-node module locally. Also install rollup. Finally, add a new file index.js, and type
`var tf = require('@tensorflow/tfjs-node');`
then save it and
`node index.js`

> Initialization of backend tensorflow failed
Error: A dynamic link library (DLL) initialization routine failed.
\\\\?\\c:\\Users\\User\\Documents\\Tensor\\node_modules\\@tensorflow\\tfjs-node\\build\\Release\\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:800:18)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (c:\\Users\\User\\Documents\\Tensor\\node_modules\\bindings\\bindings.js:84:48)
    at Object.factory (c:\\Users\\User\\Documents\\Tensor\\node_modules\\@tensorflow\\tfjs-node\\dist\\index.js:48:60)
    at Engine.initializeBackend (c:\\Users\\User\\Documents\\Tensor\\node_modules\\@tensorflow\\tfjs-core\\dist\\engine.js:237:48)
    at Engine.<anonymous> (c:\\Users\\User\\Documents\\Tensor\\node_modules\\@tensorflow\\tfjs-core\\dist\\engine.js:200:35)
    at step (c:\\Users\\User\\Documents\\Tensor\\node_modules\\@tensorflow\\tfjs-core\\dist\\engine.js:48:23)

**Comment by billTeston** [comment]
@Ashnxious  i have the same problem i was wondering if you solve the issue?

**Comment by nkreeger** [comment]
Do you mind trying the steps here?

https://github.com/tensorflow/tfjs-node/blob/master/WINDOWS_TROUBLESHOOTING.md

**Comment by Ashnxious** [comment]
Sorry for the late reply. In any case, I removed windows OS and installed Linux, Ubuntu 18.04. Now it works normally.
