### ISSUE TITLE
(tfjs-node) Cannot install on Windows

### ISSUE THREAD

**Issue by theodorDiaconu** [tensorflow/tfjs#1584]
#### Mentions
- I have followed the trouble shooting guide
- I have tried with all possible msvs versions

#### TensorFlow.js version
1.1.2

Can't install it. Cloned it and tried a local node-gyp build. 

```
C:\Projects\tsflow\tfjs-node>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  deps-stage
    * Symlink of C:\Projects\tsflow\tfjs-node\build\Release\tensorflow.dll failed, creating a copy on disk.
  (node:13416) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'C:\Projects\tsflow
  \tfjs-node\deps\lib\tensorflow.dll' -> 'C:\Projects\tsflow\tfjs-node\build\Release\tensorflow.dll'
  (node:13416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
  inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (re
  jection id: 1)
  (node:13416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reject
  ions that are not handled will terminate the Node.js process with a non-zero exit code.
  generate_def
  fs.js:114
      throw err;
      ^

CUSTOMBUILD : error : ENOENT: no such file or directory, open 'C:\\Projects\\tsflow\\tfjs-node/deps/include/tensorflow/
c/c_api.h' [C:\Projects\tsflow\tfjs-node\build\tfjs_binding.vcxproj]
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at files.map (C:\Projects\tsflow\tfjs-node\scripts\generate_defs.js:23:40)
      at Array.map (<anonymous>)
      at Object.<anonymous> (C:\Projects\tsflow\tfjs-node\scripts\generate_defs.js:23:23)
      at Module._compile (internal/modules/cjs/loader.js:701:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
      at Module.load (internal/modules/cjs/loader.js:600:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
      at Function.Module._load (internal/modules/cjs/loader.js:531:3)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Pc\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pc\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Projects\tsflow\tfjs-node
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by theodorDiaconu** [comment]
After doing `npm i` in the cloned repo and running node-gyp build it worked. But having it rebuild itself didn't. Something is weird.
