### ISSUE TITLE
Error when trying to npm install @tensorflow/tfjsnode

### ISSUE THREAD

**Issue by jonasgroendahl** [tensorflow/tfjs#1651]
System information:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

```
* Downloading libtensorflow
[==============================] 33391315/bps 100% 0.0s
* Building TensorFlow Node.js bindings
/home/jonas/projects/tensorflow/node_modules/@tensorflow/tfjs-node/scripts/install.js:165
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
make: g++: Command not found
make: *** [Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-1038-oem
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jonas/projects/tensorflow/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at /home/jonas/projects/tensorflow/node_modules/@tensorflow/tfjs-node/scripts/install.js:165:13
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
npm WARN rollup-plugin-visualizer@1.1.1 requires a peer of rollup@>=0.60.0 but none is installed. You must install peer dependencies yourself.
npm WARN tensorflow@1.0.0 No description
npm WARN tensorflow@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@1.1.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tensorflow/tfjs-node@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It's not quite clear what's going wrong?

**Comment by kangyizhang** [comment]
Hi @jonasgroendahl 

can you try this https://github.com/nodejs/node-gyp/issues/809#issuecomment-173867266? It seems to be an issue with the binding tool node-gyp.
