### ISSUE TITLE
tfjs-node-gpu - CUBLAS_STATUS_NOT_INITIALIZED : Blas xGEMM launch failed

### ISSUE THREAD

**Issue by piercus** [tensorflow/tfjs#1660]
#### TensorFlow.js version

`@tensorflow/tfjs-node-gpu@1.1.2`

#### OS

Ubuntu 18.04

#### CUDA version

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Cudnn version is 7.4.2 (install made from linux `cudnn-10.0-linux-x64-v7.4.2.24.tgz`)

#### Graphic card

`GeForce RTX 2070` with NVIDIA drivers `418.67`

#### Describe the problem or feature request

When using convolutionnal layer CUDA is crashing with error `CUBLAS_STATUS_NOT_INITIALIZED` and `Message: Blas xGEMM launch failed : a.shape=[1,1,4], b.shape=[1,4,12], m=1, n=12, k=4` (see details below)

I have tried the following : 
* Same problem occurs on Ubuntu 16.04
* Same problem with CUDA 10.1
* Cannot reproduce on `@tensorflow/tfjs-node-gpu@0.3.2` with CUDA 9.0
* `rm ~/.nv``not working (idea from https://github.com/tensorflow/tensorflow/issues/9489)

### Code to reproduce the bug 

Code to reproduce

```js
const tf = require('@tensorflow/tfjs-node-gpu');

const channels = 1;
const width = 4;
const height = 4;
const units = 12;

const input = tf.input({shape: [height, width, channels]});

const conv1 = tf.layers.conv2d({
	kernelSize: 3,
	filters: 1
}).apply(input);

const flatten = tf.layers.flatten({}).apply(conv1);

const dense512 = tf.layers.dense({units: units}).apply(flatten);

const model = tf.model({inputs: input, outputs: dense512});

model.compile({
	optimizer: 'adam',
	loss: 'categoricalCrossentropy'
});

model.fit(tf.zeros([1, width, height, channels]), tf.oneHot([0], units))
```

Outputs

```
2019-06-13 16:07:24.849505: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-13 16:07:24.976430: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-13 16:07:24.977353: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3cf7350 executing computations on platform CUDA. Devices:
2019-06-13 16:07:24.977373: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-06-13 16:07:24.997190: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3499940000 Hz
2019-06-13 16:07:24.997377: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x3cf5aa0 executing computations on platform Host. Devices:
2019-06-13 16:07:24.997395: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-13 16:07:24.997530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
totalMemory: 7.77GiB freeMemory: 7.66GiB
2019-06-13 16:07:24.997569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-13 16:07:24.998676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-13 16:07:24.998689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-13 16:07:24.998695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-13 16:07:24.998781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7455 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:02:00.0, compute capability: 7.5)
(node:28032) Warning: N-API is an experimental feature and could change at any time.
Epoch 1 / 1
2019-06-13 16:07:26.936151: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-06-13 16:07:27.012357: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-06-13 16:07:27.012395: W tensorflow/stream_executor/stream.cc:2130] attempting to perform BLAS operation using StreamExecutor without BLAS support
(node:28032) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 13
Message: Blas xGEMM launch failed : a.shape=[1,1,4], b.shape=[1,4,12], m=1, n=12, k=4
    at NodeJSKernelBackend.executeSingleOutput (/<localdir>/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:192:43)
    at NodeJSKernelBackend.batchMatMul (/<localdir>/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:335:21)
    at NodeJSKernelBackend.fusedBatchMatMul (/<localdir>/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:340:27)
    at /<localdir>/node_modules/@tensorflow/tfjs-core/dist/ops/fused_ops.js:141:25
    at /<localdir>/node_modules/@tensorflow/tfjs-core/dist/engine.js:384:26
    at Engine.scopedRun (/<localdir>/node_modules/@tensorflow/tfjs-core/dist/engine.js:338:23)
    at Engine.runKernel (/<localdir>/node_modules/@tensorflow/tfjs-core/dist/engine.js:382:14)
    at matMul_ (/<localdir>/node_modules/@tensorflow/tfjs-core/dist/ops/fused_ops.js:140:31)
    at Object.matMul (/<localdir>/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:46:29)
    at Object.dot (/<localdir>/node_modules/@tensorflow/tfjs-layers/dist/backend/tfjs_backend.js:367:26)
(node:28032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Related topics

This might be related to 
* https://github.com/tensorflow/tfjs/issues/1469
* https://github.com/tensorflow/tensorflow/issues/9489

In https://github.com/tensorflow/tensorflow/issues/9489 they suggest this might be a memory issue, but as you see in the reproduction code, the memory used for this should be very small.

Thank you for your help on this

**Comment by caisq** [comment]
@piercus Do you have any other processes trying to use the GPU at the same time?

**Comment by piercus** [comment]
@caisq This is the only process running on this GPU. 

I have another GPU (GTX 970 is not compatible with tfjs cause `with Cuda compute capability 5.2`) where i run other GPU processes, and i do `export CUDA_VISIBLE_DEVICES=0` to make sure tensorflowjs uses the RTX 2070 GPU.

**Comment by piercus** [comment]
I have made more investigation on this, and this error appeared with tensorflow.so version 1.13.1.

## Reproduction steps

```
git clone git@github.com:tensorflow/tfjs-node.git
cd  tfjs-node
yarn
yarn enable-gpu
yarn test
```

* to change the libtensorflow.so version i changed it manually (see https://github.com/tensorflow/tfjs-node/pull/268) and rerun `yarn enable-gpu`

* to make only the required test run, i hardcoded it into https://github.com/tensorflow/tfjs-node/blob/master/src/run_tests.ts#L78

* i changed CUDA version each time by setting `export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64`

## Results

### With tensorflow.so version 1.12.0 (and cuda-9.0) 

running `node_modules/@tensorflow/tfjs-core/dist/ops/conv2d_test.js` from `tfjs-node` reporository is running well

```
2019-06-26 11:38:55.198846: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-26 11:38:55.315894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:38:55.316706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
totalMemory: 7.77GiB freeMemory: 7.66GiB
2019-06-26 11:38:55.316722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-26 11:42:40.438076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-26 11:42:40.438103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-26 11:42:40.438110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-26 11:42:40.438249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7379 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:02:00.0, compute capability: 7.5)
Running tests against TensorFlow: 1.12.0
Started
(node:4393) Warning: N-API is an experimental feature and could change at any time.
...................


19 specs, 0 failures
Finished in 5.676 seconds
```
###  With tensorflow.so version 1.14.0 (and cuda-10.0) 


```
2019-06-26 11:37:01.365878: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-26 11:37:01.397046: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3499880000 Hz
2019-06-26 11:37:01.397271: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3c8c140 executing computations on platform Host. Devices:
2019-06-26 11:37:01.397298: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-26 11:37:01.398059: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-06-26 11:37:01.429467: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.430368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
2019-06-26 11:37:01.430532: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-26 11:37:01.431437: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-26 11:37:01.432266: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-06-26 11:37:01.432456: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-06-26 11:37:01.433523: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-06-26 11:37:01.434329: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-06-26 11:37:01.436702: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-26 11:37:01.436784: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.437716: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.438663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-26 11:37:01.438688: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-26 11:37:01.520364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-26 11:37:01.520395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-06-26 11:37:01.520406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-06-26 11:37:01.520579: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.521403: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.522291: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-26 11:37:01.523056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7455 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:02:00.0, compute capability: 7.5)
Running tests against TensorFlow: 1.14.0
Started
(node:4033) Warning: N-API is an experimental feature and could change at any time.
2019-06-26 11:37:09.951438: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
.2019-06-26 11:37:10.964481: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-26 11:37:11.003521: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2019-06-26 11:37:11.003564: W tensorflow/stream_executor/stream.cc:1916] attempting to perform BLAS operation using StreamExecutor without BLAS support
F2019-06-26 11:37:11.067875: I tensorflow/stream_executor/stream.cc:1865] [stream=0x4e3e5e0,impl=0x4e3d300] did not wait for [stream=0x4113c70,impl=0x4e343f0]
2019-06-26 11:37:11.067898: I tensorflow/stream_executor/stream.cc:4813] [stream=0x4e3e5e0,impl=0x4e3d300] did not memcpy host-to-device; source: 0x2f88e80
2019-06-26 11:37:11.067946: F tensorflow/core/common_runtime/gpu/gpu_util.cc:342] CPU->GPU Memcpy failed
[1]    4033 abort (core dumped)  ./node_modules/.bin/ts-node src/run_tests.ts
```

### Remarks

* `1.13.1` behaves as `1.14.0`
* Reproduced in a preinstalled nvidia-docker environment so i feel cuda-10 install is ok

## Questions

* Would it be possible to define an environment variable like `TF_VERSION` that will override default version when doing `TF_VERSION=1.12.0 npm install tfjs-node-gpu` ?
* Does it mean that problem comes from the C library ? How can i run unit test on conv2d at C level directly ?

**Comment by josephrocca** [comment]
After adding the `nvidia` runtime to docker, and running this image ([mentioned here](https://github.com/tensorflow/tfjs/issues/1760)):
```
sudo docker run --gpus all --rm --runtime=nvidia -it nvcr.io/nvidia/cuda:10.0-runtime-ubuntu18.04 bash
```

I'm seeing the same error message mentioned in the original post (CUBLAS_STATUS_NOT_INITIALIZED : Blas xGEMM launch failed):

```
2020-01-19 05:27:55.799086: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-19 05:27:55.831144: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-01-19 05:27:55.831711: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5bb9360 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-19 05:27:55.831723: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-19 05:27:55.832431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-19 05:27:55.862491: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.863151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.44
pciBusID: 0000:01:00.0
2020-01-19 05:27:55.863299: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-19 05:27:55.864250: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-19 05:27:55.865111: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-19 05:27:55.865323: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-19 05:27:55.866247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-19 05:27:55.867022: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-19 05:27:55.869149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-19 05:27:55.869248: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.869847: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.870118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-01-19 05:27:55.870133: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-19 05:27:55.946434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-19 05:27:55.946455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-01-19 05:27:55.946459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-01-19 05:27:55.946541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.946939: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.947301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:27:55.947528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4586 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-01-19 05:31:43.622472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-19 05:31:43.679517: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-01-19 05:31:43.679549: W tensorflow/stream_executor/stream.cc:2041] attempting to perform BLAS operation using StreamExecutor without BLAS support
Error: Invalid TF_Status: 13
Message: Blas xGEMM launch failed : a.shape=[1,22,256], b.shape=[1,256,512], m=22, n=512, k=256
    at NodeJSKernelBackend.executeSingleOutput (/root/tox/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:193:43)
    at NodeJSKernelBackend.batchMatMul (/root/tox/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:336:21)
    at engine_1.ENGINE.runKernelFunc.a (/root/tox/node_modules/@tensorflow/tfjs-core/dist/ops/matmul.js:97:27)
    at /root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:528:55
    at /root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:388:22
    at Engine.scopedRun (/root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.tidy (/root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:387:21)
    at kernelFunc (/root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:528:29)
    at /root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:539:27
    at Engine.scopedRun (/root/tox/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
2020-01-19 05:31:55.201081: I tensorflow/stream_executor/stream.cc:1990] [stream=0x64decd0,impl=0x64c4bc0] did not wait for [stream=0x6328710,impl=0x64d00d0]
2020-01-19 05:31:55.201106: I tensorflow/stream_executor/stream.cc:4938] [stream=0x64decd0,impl=0x64c4bc0] did not memcpy host-to-device; source: 0xe9daa00
2020-01-19 05:31:55.201198: F tensorflow/core/common_runtime/gpu/gpu_util.cc:342] CPU->GPU Memcpy failed
Aborted (core dumped)
```

The JS code to reproduce this is:
```js
const toxicity = require("@tensorflow-models/toxicity");
(async function() {
  let model = await toxicity.load(0.9);
  let r = await model.classify("hello");
  console.log(r);
})();
```
My operating system is Ubuntu 19.04 (well, Pop OS 19.04, but so far as I'm aware there's not much difference at the low level).

In case it's at all relevant, I was originally getting a `Could not load dynamic library 'libcudnn.so.7'` message before downloading `libcudnn.so.7` from [here](https://developer.nvidia.com/rdp/cudnn-download) and putting it in `/usr/local/cuda/lib64`. These were the full logs:

```
2020-01-19 05:17:49.234735: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-19 05:17:49.263192: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-01-19 05:17:49.263939: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x75c0e20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-19 05:17:49.263968: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-19 05:17:49.264687: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-19 05:17:49.291927: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-19 05:17:49.292345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.44
pciBusID: 0000:01:00.0
2020-01-19 05:17:49.292598: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-19 05:17:49.293536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-19 05:17:49.294333: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-19 05:17:49.294560: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-19 05:17:49.295583: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-19 05:17:49.296478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-19 05:17:49.296531: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-10.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-01-19 05:17:49.296537: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-01-19 05:17:49.374801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-19 05:17:49.374820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-01-19 05:17:49.374825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
```

I'm using `@tensorflow/tfjs-node-gpu` version `1.5.1`. As mentioned [here](https://github.com/tensorflow/tfjs/issues/1311#issuecomment-575964894) I couldn't get the `tensorflow/tensorflow:latest-gpu` docker image to work. I'll probably go and have a play with that a bit more now though.

**Comment by rivertam** [comment]
I won't comment on the actual error itself, but as a code monkey the worst part of this is that it seems to be uncatchable. If I could catch it, I could give a nice error to the user and try again, but as it is it seems to just create an asynchronous exception I can't detect except by using global error handlers (which is what I'm going to try to do next).

**Comment by yeldarby** [comment]
Were you ever able to figure this out? I'm getting this same error starting from the `nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04` base.

**Comment by OdaNeo** [comment]
> Were you ever able to figure this out? I'm getting this same error starting from the `nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04` base.

I get the same error too. Do you have any solution?
