### ISSUE TITLE
Cannot load PoseNet module in Nodejs

### ISSUE THREAD

**Issue by eli-z** [tensorflow/tfjs#1720]
#### TensorFlow.js version
1.2.2
#### Nodejs version
8.12, 10.16
#### PoseNet version
2.1.1
#### Browser version
No browser
#### Describe the problem or feature request
Posenet module cannot be loaded in nodejs environment, trying to load it thwors an error
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@tensorflow-models/posenet'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/eliz/posenet-test/dist/index.js:18:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`
#### Code to reproduce the bug / link to feature request
Setup a new nodejs typescript project, install posenet and tensorflow,
type the following code into index.ts
`import * as posenet from '@tensorflow-models/posenet';
require('@tensorflow/tfjs-node');

async function main() {
    const net = await posenet.load({
        architecture: 'MobileNetV1',
        outputStride: 16,
        inputResolution: 513,
        multiplier: 0.75
    });
}

main().then(() => console.log('loaded'));`

run the script and get the error

**Comment by piercus** [comment]
I'm facing same problem

I think problem is coming from the npm package not containing `dist/index.js`

### 2.1.1

```shell
curl -O https://registry.npmjs.org/@tensorflow-models/posenet/-/posenet-2.1.1.tgz
tar -tf posenet-2.1.1.tgz | grep index
```

result is 

```
package/dist/index.d.ts
```

This package version does not contain any `dist/index.js` file


### 2.1.0

```shell
curl -O https://registry.npmjs.org/@tensorflow-models/posenet/-/posenet-2.1.0.tgz
tar -tf posenet-2.1.0.tgz | grep index
```

result is 

```
package/dist/index.d.ts
package/dist/index.js
```

### Workaround

On nodejs, version 2.1.0 should work

**Comment by tafsiri** [comment]
cc @dsmilkov might have been an issue at publish time?
