### ISSUE TITLE
KeyError: 'class_name' when converting tfjs_layers_model to keras

### ISSUE THREAD

**Issue by photown** [tensorflow/tfjs#1754]
#### TensorFlow.js version
tensorflowjs 1.2.3
keras 2.2.4-tf
tensorflow 1.14.0

#### Browser version
Not relevant / only using tensorflowjs_converter

#### Describe the problem or feature request
I downloaded the ResNet50 model for posenet from the PoseNet detection demo [here](https://storage.googleapis.com/tfjs-models/demos/posenet/camera.html). It includes the model JSON and 23 shards. I wanted to convert the model to keras using tensorflowjs_converter. I ran this command:

> tensorflowjs_converter --input_format=tfjs_layers_model --output_format=keras_saved_model /path/to/model-stride32.json /path/to/output

The output I get is:
2019-07-18 00:52:04.285078: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394515000 Hz
2019-07-18 00:52:04.286245: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1b5da70 executing computations on platform Host. Devices:
2019-07-18 00:52:04.286321: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/home/antoan/venv/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(main())
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 605, in main
    FLAGS.output_path)
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 255, in dispatch_tensorflowjs_to_keras_saved_model_conversion
    model = keras_tfjs_loader.load_keras_model(config_json_path)
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 218, in load_keras_model
    use_unique_name_scope=use_unique_name_scope)
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 65, in _deserialize_keras_model
    model = keras.models.model_from_json(json.dumps(model_topology_json))
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/home/antoan/venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 81, in deserialize
    layer_class_name = config['class_name']
KeyError: 'class_name'

**Comment by pyu10055** [comment]
@photown Unfortunately this model is not tf_layers_model, it is tf_graph_model, it cannot be converted to keras model.

**Comment by photown** [comment]
Thanks for the info. Is there anything I can do convert a tf_graph_model to tflite or something readable for tensorflow lite for Android?

**Comment by rthadur** [comment]
@photown please follow this [link](https://www.tensorflow.org/lite/convert/python_api)

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by chuan92** [comment]
> @photown please follow this [link](https://www.tensorflow.org/lite/convert/python_api)

the link doesn't answer the question, tfjs_graph_model can't be converted to other formats in tfjs-converter

**Comment by rthadur** [comment]
@chuan92 thank you , above link was for tf-graph_model not tfjs_graph_model.

**Comment by willfu** [comment]
@rthadur is there a way to convert the tfjs_graph_model to keras model? so that we can use it on Android. Thanks.

**Comment by kangyizhang** [comment]
@photown @willfu 

Like Shanqing mentioned at https://github.com/tensorflow/tfjs/issues/1808#issuecomment-557099119, it is not possible to convert tfjs_graph_model to keras_saved_model. 

If you have a tfjs_graph_model, you should have a tensorflow model (in keras, tf_hub, tf_saved_model, or tf_frozen_model format, see details here: https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#format-conversion-support-tables) and the tfjs_graph_model was converted from tf modell. 
`A tf.GraphModel can only be created by loading from a model converted from a TensorFlow SavedModel using the command line converter tool and loaded via tf.loadGraphModel().` 

You can convert the original model into a format you want to use on mobile native platforms.
