### ISSUE TITLE
tfjs-examples: Simple object detection: yarn train --gpu fails

### ISSUE THREAD

**Issue by iandanforth** [tensorflow/tfjs#1777]
#### TensorFlow.js version
1.2.2

#### Browser version
Windows Version	10.0.17134 Build 17134
Node v10.15.0

### Problem description

**Install appears to succeed (with warnings)**

```
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@tensorflow/tfjs > @tensorflow/tfjs-data@1.2.2" has unmet peer dependency "seedrandom@~2.4.3".
warning "@tensorflow/tfjs > @tensorflow/tfjs-core > rollup-plugin-visualizer@1.1.1" has unmet peer dependency "rollup@>=0.60.0".
[5/5] Building fresh packages...
Done in 139.97s.
```

**Training with the gpu flag fails**

```
$ yarn train --gpu
yarn run v1.17.3
$ node train.js --gpu
Training using GPU.
cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 4
(node:14276) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\C:\Users\Ian\projects\tfjs\tfjs-examples\simple-object-detection\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v3\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Ian\projects\tfjs\tfjs-examples\simple-object-detection\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
(node:14276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.74s.
```

**Comment by rthadur** [comment]
@iandanforth thank you , did you get chance to go over troubleshooting guidelines here for [Windows](https://github.com/tensorflow/tfjs-node/blob/master/WINDOWS_TROUBLESHOOTING.md)

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
