### ISSUE TITLE
TFJS Cannot be Used in Angular Production Build

### ISSUE THREAD

**Issue by clover113** [tensorflow/tfjs#179]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.9.0
#### Browser version
N/A
#### Describe the problem or feature request
In my Angular 2 project, tfjs runs smoothly with 'ng serve' and 'ng build'. But, when I try to compile the project using 'ng serve --prod' or 'ng build --prod', the command fails and returns:
> Unhandled rejection Error: ENOENT: no such file or directory, open '/home/bhat/Dev/Projects/TS/twox/node_modules/_@tensorflow_tfjs-layers@0.4.0@@tensorflow/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at LicenseExtractor.readPackageJson (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseExtractor.js:126:23)
    at LicenseExtractor.parsePackage (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseExtractor.js:23:32)
    at ModuleProcessor.processPackage (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/ModuleProcessor.js:39:46)
    at ModuleProcessor.processFile (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/ModuleProcessor.js:36:21)
    at fileCallback (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:101:61)
    at moduleCallback (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:108:21)
    at /home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:120:29
    at Array.forEach (native)
    at Compiler.emitCallback (/home/bhat/Dev/Projects/TS/twox/node_modules/_license-webpack-plugin@1.3.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:86:32)
    at next (/home/bhat/Dev/Projects/TS/twox/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /home/bhat/Dev/Projects/TS/twox/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/home/bhat/Dev/Projects/TS/twox/node_modules/_bluebird@3.5.1@bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/home/bhat/Dev/Projects/TS/twox/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)

It fails when it is at the stage of '95% emitting'. From the error message it is probably that node_modules/_@tensorflow_tfjs-layers@0.4.0@@tensorflow/ lacks package.json.

#### Code to reproduce the bug / link to feature request
1. Create an Angular project.
2. Install TFJS and import.
3. Code something with TFJS.
4. Type 'ng build --prod'

**Comment by tafsiri** [comment]
Hi @clover113, I'm not terribly familiar with Angular, but it looks like the LicenseExtractor plugin/module is having some issue. tfjs-layers definitely has a package.json though. https://github.com/tensorflow/tfjs-layers/blob/master/package.json

You might want to look through your node_modules folder (in the @tensorflow directory) to see if things are laid out as expected. You should be able to find the package.json in '.../node_modules/@tensorflow/tfjs-layers/'

Else I'd try seeing if there are any issues on LicenseExtractor or Angular about this. You could also try our mailing list in case other people are using Angular and might have suggestions.

**Comment by tafsiri** [comment]
Thanks @clover113, let us know if you do run into a bug stemming from the library.
