### ISSUE TITLE
Converting Image classification model

### ISSUE THREAD

**Issue by CharlesCousyn** [tensorflow/tfjs#2050]
**TensorFlow.js version**
Python: tensorflowjs==1.2.7

**Describe the problem or feature request**
I'd like to use an existing model of image classification in the browser using the _tensorflowjs_converter_ command. (The command works correctly when using the mobilenet2 model url: `https://tfhub.dev/google/imagenet/mobilenet_v2_130_224/classification/3`)

**Code to reproduce the bug / link to feature request**
### Using Pnasnet
```
tensorflowjs_converter --input_format=tf_hub 'https://tfhub.dev/google/imagenet/pnasnet_large/classification/3' /home/charles/pnasnet/output
Traceback (most recent call last):
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 175, in download_and_uncompress
    self._extract_file(tgz, tarinfo, abs_target_path)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 151, in _extract_file
    buf = src.read(buffer_size)
  File "/usr/lib/python3.6/tarfile.py", line 708, in readinto
    buf = self.read(len(b))
  File "/usr/lib/python3.6/tarfile.py", line 699, in read
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 649, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 653, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 615, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 478, in convert_tf_hub_module
    module_path = hub.resolve(module_handle)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 39, in resolve
    return registry.resolver(handle)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 103, in __call__
    self._lock_file_timeout_sec())
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 402, in atomic_download
    download_fn(handle, tmp_dir)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/compressed_module_resolver.py", line 100, in download
    response, tmp_dir)
  File "/home/charles/.local/lib/python3.6/site-packages/tensorflow_hub/resolver.py", line 189, in download_and_uncompress
    raise IOError("%s does not appear to be a valid module." % self._url)
OSError: https://tfhub.dev/google/imagenet/pnasnet_large/classification/3 does not appear to be a valid module.
```

**Comment by CharlesCousyn** [comment]
The problem was due to the university network I used, using with my personal internet connexion fixed the problem.
