### ISSUE TITLE
Unknown op '_FusedConv2D' with MobileNet2

### ISSUE THREAD

**Issue by CharlesCousyn** [tensorflow/tfjs#2054]
### TensorFlow.js version
Node GPU version 1.2.7

#### Describe the problem or feature request
When trying to make classification with model from https://tfhub.dev/google/imagenet/mobilenet_v2_130_224/classification/3 using tensorflowjs_converter, the method `const predictions = await model.predict(input);`, I am getting this error

#### Error
```
TypeError: Unknown op '_FusedConv2D'. File an issue at https://github.com/tensorflow/tfjs/issues so we can add it, or register a custom execution with tf.registerOp()
    at D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\operations\operation_executor.js:86:23
    at Object.executeOp (D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\operations\operation_executor.js:90:7)
    at D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\executor\graph_executor.js:202:56
    at D:\search_activities_image\node_modules\@tensorflow\tfjs-core\dist\engine.js:349:22
    at Engine.scopedRun (D:\search_activities_image\node_modules\@tensorflow\tfjs-core\dist\engine.js:359:23)
    at Engine.tidy (D:\search_activities_image\node_modules\@tensorflow\tfjs-core\dist\engine.js:348:21)
    at Object.tidy (D:\search_activities_image\node_modules\@tensorflow\tfjs-core\dist\globals.js:164:28)
    at GraphExecutor.execute (D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\executor\graph_executor.js:191:28)
    at GraphModel.execute (D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\executor\graph_model.js:260:36)
    at GraphModel.predict (D:\search_activities_image\node_modules\@tensorflow\tfjs-converter\dist\src\executor\graph_model.js:220:21)

```

**Comment by kangyizhang** [comment]
@CharlesCousyn The FusedConv2D op has been added in the latest package (1.2.9). Please give it a try.

**Comment by CharlesCousyn** [comment]
It fixes my problem :) 
But now I have:
`Error: Activation: relu6 has not been implemented for the Node.js backend`
This seem to be fixed: https://github.com/tensorflow/tfjs/pull/2016
I guess I can wait few days
