### ISSUE TITLE
tfjs-converter types_pb2.DataType has no attribute DT_FLOAT

### ISSUE THREAD

**Issue by kemio** [tensorflow/tfjs#2076]
#### TensorFlow.js version
tensorflowjs_coverter 1.2.9 at Colab with Python3

#### Describe the problem or feature request
Get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 6, in <module>
    from tensorflowjs.converters.converter import pip_main
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/__init__.py", line 24, in <module>
    from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 41, in <module>
    from tensorflowjs.converters import fuse_prelu
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/fuse_prelu.py", line 200, in <module>
    register_prelu_op()
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/fuse_prelu.py", line 42, in register_prelu_op
    value.list.type.extend([types_pb2.DataType.DT_FLOAT])
AttributeError: 'EnumTypeWrapper' object has no attribute 'DT_FLOAT'
```

#### Code to reproduce the bug / link to feature request
!sudo pip3 install tensorflowjs
Then:
!sudo tensorflowjs_converter
or
!sudo tensorflowjs_converter --input_format=tfjs_layers_model --output_format=keras /content/mydrive/MeLi/as.m5/model.json as.m5.h5

**Comment by gitathrun** [comment]
Same problem here, after I install tensorflowjs, this problem happens when I import the library

```
import tensorflowjs
```
errors:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ff9028db9621> in <module>()
----> 1 import tensorflowjs

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflowjs/__init__.py in <module>()
     19 
     20 # pylint: disable=unused-imports
---> 21 from tensorflowjs import converters
     22 from tensorflowjs import quantization
     23 from tensorflowjs import version

/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/__init__.py in <module>()
     22 from tensorflowjs.converters.keras_tfjs_loader import deserialize_keras_model
     23 from tensorflowjs.converters.keras_tfjs_loader import load_keras_model
---> 24 from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model

/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py in <module>()
     39 from tensorflowjs.converters import common
     40 from tensorflowjs.converters import fold_batch_norms
---> 41 from tensorflowjs.converters import fuse_prelu
     42 
     43 # enable eager execution for v2 APIs

/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/fuse_prelu.py in <module>()
    198     prelu_fn(tf.constant(1.0), tf.constant(1.0))
    199 
--> 200 register_prelu_op()

/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/fuse_prelu.py in register_prelu_op()
     40 
     41   value = attr_value_pb2.AttrValue()
---> 42   value.list.type.extend([types_pb2.DataType.DT_FLOAT])
     43   attr = op_def_pb2.OpDef.AttrDef()
     44   attr.name = 'T'

AttributeError: 'EnumTypeWrapper' object has no attribute 'DT_FLOAT'
```

So, what is the problem here, is protobuf got any major upgrade?

**Comment by rthadur** [comment]
This was fixed already and will see the changes in next release , please refer to similar [issue](https://github.com/tensorflow/tfjs/issues/2014) here. Thank you

**Comment by rajumgokak** [comment]
!sudo pip3 install tensorflowjs
# Then:
!sudo tensorflowjs_converter

just replace model.h5 with your trained weight 
!tensorflowjs_converter --input_format=keras '/content/drive/MyDrive/model.h5' "/content/drive/MyDrive/json"

you are good to go your file will me converted !
