### ISSUE TITLE
lstm-text-generation example - training with node.js results in error: "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dtype' of undefined"

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2077]
I'm following the instructions to to run the training-lstm-example, using @tensorflow/tfjs-node (on cpu) on Mac OSX.

When I run the command, as instructed in the tutorial:

```sh
yarn train shakespeare \
    --lstmLayerSize 128,128 \
    --epochs 120 \
    --savePath ./my-shakespeare-model
```

I get an error:

```
Epoch 1 of 120:
(node:28883) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dtype' of undefined
    at NodeJSKernelBackend.batchMatMul (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:336:37)
    at NodeJSKernelBackend.fusedBatchMatMul (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:370:27)
    at /Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/ops/fused_ops.ts:172:23
    at /Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/engine.ts:462:22
    at Engine.scopedRun (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/engine.ts:404:19)
    at Engine.runKernel (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/engine.ts:459:10)
    at matMul_ (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/ops/fused_ops.ts:171:22)
    at Object.matMul (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:45:24)
    at Object.dot (/Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-layers/src/backend/tfjs_backend.ts:407:22)
    at /Users/danoved/Source/lstm-tutorial/tfjs-examples/lstm-text-generation/node_modules/@tensorflow/tfjs-layers/src/layers/recurrent.ts:1897:17
```

For reference, before this error it says:

```
> cpu backend was already registered. Reusing existing backend factory.
> Platform node has already been set. Overwriting the platform with [object Object].
> 2019-09-21 16:21:04.042496: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Orthogonal initializer is being called on a matrix with more than 2000 (65536) elements: Slowness may result.
> Orthogonal initializer is being called on a matrix with more than 2000 (65536) elements: Slowness may result.
> Compiled model with learning rate 0.01
> _________________________________________________________________
> Layer (type)                 Output shape              Param #
> =================================================================
> lstm_LSTM1 (LSTM)            [null,60,128]             112640
> _________________________________________________________________
> lstm_LSTM2 (LSTM)            [null,128]                131584
> _________________________________________________________________
> dense_Dense1 (Dense)         [null,91]                 11739
> =================================================================
> Total params: 255963
> Trainable params: 255963
> Non-trainable params: 0
```

**Comment by oveddan** [comment]
This is resolved.  The issue occured when using node v 12.10.0.  When I downgraded to 10.15.3 the issue went away.
