### ISSUE TITLE
IndexError: list index out of range when converting tf_saved_model to tfjs_graph_model

### ISSUE THREAD

**Issue by neilreid** [tensorflow/tfjs#2267]
#### TensorFlow.js version
1.2.10

#### Describe the problem or feature request
After retraining Mobilenet V2_100_224 using https://github.com/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb above error occured 
#### Code to reproduce the bug / link to feature request
https://github.com/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb
#### Last few debug lines including error
2019-10-25 00:54:05.005493: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: __inference__traced_restore_4718
2019-10-25 00:54:05.013342: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: __inference_loss_fn_1_4731
2019-10-25 00:54:05.219866: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: __inference_pruned_5844
2019-10-25 00:54:05.288454: W tensorflow/core/common_runtime/eager/context.cc:371] Added two functions with the same name: __inference_call_fn_6251
2019-10-25 00:54:05.305968: W tensorflow/core/graph/graph_constructor.cc:632] Node 'StatefulPartitionedCall' has 71 outputs but the _output_shapes attribute specifies shapes for 657 outputs. Output shapes may be inaccurate.
Traceback (most recent call last):
  File "/.pyenv/versions/venv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 649, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 653, in main
    convert(argv[0].split(' '))
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 609, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 359, in convert_tf_saved_model
    model = load(saved_model_dir, saved_model_tags)
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 407, in load
    export_dir)
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 57, in __init__
    meta_graph.graph_def.library))
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 296, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/.pyenv/versions/3.6.8/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 91, in function_def_to_graph
    op.outputs[output_index].set_shape(shape)
IndexError: list index out of range

**Comment by pyu10055** [comment]
@neilreid can you give a try with the latest tensorflow.js converter pip (1.3.1.1), there couple fixed added and we are relying on TF 1.15.
Please let us know if you still see the problem, and if possible please provide the saved model files directly, thanks.

**Comment by neilreid** [comment]
thanks for the response, I will try, but there is no issue @tensoflow\tfjs@1.2.3 with tensorflow 2.0.0-dev20190605, it would be better if we move to TF2 completely.

**Comment by pyu10055** [comment]
@neilreid actually TF 1.15 is newer than tensorflow 2.0.0-dev20190605, do you mind try converting again with the latest converter? Thanks.
