### ISSUE TITLE
GraphModel benchmark is failing: "TypeError: Cannot read property 'producer' of undefined"

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#2299]
#### TensorFlow.js version
1.3.0

Starting today, we're seeing this error when the step "3/26: dense-tiny_GraphModel" of the nightly benchmark runs:

LOG: '3/26: dense-tiny_GraphModel'
Chrome 78.0.3904 (Linux 0.0.0) TF.js Layers Benchmarks Benchmark models FAILED
	TypeError: Cannot read property 'producer' of undefined
	    at <Jasmine>
	    at GraphModel.<anonymous> (/tmp/karma-typescript-bundle-761638JkMsPu30NrR.js:76676:55)
	    at step (/tmp/karma-typescript-bundle-761638JkMsPu30NrR.js:76552:23)
	    at Object.next (/tmp/karma-typescript-bundle-761638JkMsPu30NrR.js:76533:53)
	    at fulfilled (/tmp/karma-typescript-bundle-761638JkMsPu30NrR.js:76524:58)

To reproduce the error:
```sh
cd tfjs/integration_test
yarn benchmark --layers
```

**Comment by caisq** [comment]
cc @nsthorat @dsmilkov
