### ISSUE TITLE
TypeError: forwardFunc is not a function

### ISSUE THREAD

**Issue by Glunky** [tensorflow/tfjs#2329]
Hi!
I dont know does this problem apply to you, but it seems to be. If it is not, im sorry.

So here is an error and i donk know what i should to do. May you can help me?
![ucZDChN3RKQ](https://user-images.githubusercontent.com/42372955/68222272-d102b300-fffb-11e9-8425-6911314a127a.jpg)

**Comment by dsmilkov** [comment]
This looks like a mismatch between the version of tfjs-core and tfjs-node. Can you update to the latest `@tensorflow/tfjs` and `@tensorflow/tfjs-node`. Also it might help is to remove `node_modules` and rerun `npm install`.

**Comment by Glunky** [comment]
> This looks like a mismatch between the version of tfjs-core and tfjs-node. Can you update to the latest `@tensorflow/tfjs` and `@tensorflow/tfjs-node`. Also what might help is to remove `node_modules` and rerun `npm install`.

It works, thx))

**Comment by RezaRahmati** [comment]
Same issue here on Win 10
```
        "@tensorflow/tfjs": "^3.7.0",
        "@tensorflow/tfjs-node": "^3.7.0",
        "@tensorflow/tfjs-node-gpu": "^3.7.0",
```

I deleted node_modules and reinstall still same error

```
(node:13876) UnhandledPromiseRejectionWarning: TypeError: forwardFunc_1 is not a function
    at C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4706:55
    at C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4529:22
    at Engine.scopedRun (C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4539:23)
    at Engine.tidy (C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4528:21)
    at kernelFunc (C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4706:29)
    at C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4727:27
    at Engine.scopedRun (C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4539:23)
    at Engine.runKernelFunc (C:\projects\digital-verification\cr-api\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4723:14)
    at mul_ (C:\projects\digital-verification\cr-api\node_modules\face-api.js\node_modules\@tensorflow\tfjs-core\dist\ops\binary_ops.js:327:28)
    at Object.mul (C:\projects\digital-verification\cr-api\node_modules\face-api.js\node_modules\@tensorflow\tfjs-core\dist\ops\operation.js:46:29)
```

**Comment by anjanesh** [comment]
> Can you update to the latest `@tensorflow/tfjs` and `@tensorflow/tfjs-node`.

How do I do that ?

```
  "dependencies": {
    "@tensorflow-models/toxicity": "^1.2.2",
    "@tensorflow/tfjs": "3.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.2.0",
    "parcel-bundler": "^1.6.1"
```

**Comment by ThirashaPraween** [comment]
install `@tensorflow/tfjs` latest version, but **do not import it**. Then Import the model. It's fixed for me the issue.

**Comment by muarachmann** [comment]
> install `@tensorflow/tfjs` latest version, but **do not import it**. Then Import the model. It's fixed for me the issue.

How?

**Comment by ThirashaPraween** [comment]
Don't know the reason but it's worked for me with the latest `@tensorflow/tfjs` and react version.

**Comment by davadeola** [comment]
Ensure you don't import @tensorflow/tfjs in your component
