### ISSUE TITLE
The specified module could not be found. tfjs_binding.node

### ISSUE THREAD

**Issue by kimvu** [tensorflow/tfjs#2341]
"@tensorflow/tfjs-node": "^1.3.1"
Python 2.7.17
OS: Windows 10 64bit
Browser: Google Chrome version 78.0.3904.70 (64-bit)

I tried version @tensorflow/tfjs-node@1.2.3 (answer from stackoverflow) , which doesn't have the problem, but it had other issues. 

The error is procuced by a single: `require('@tensorflow/tfjs-node')`

Been trying to figure out this error for a while now, i've tried:
- npm install -g -production windows-build-tools
- made sure my path doesn't have whitespace
- made sure that tfjs_binding.node actually is in my node_modules
- replaced the bindingPath variable with the exact path to tfjs_binding.node 

```
C:\Users\kim_1\Desktop\league_stats\src\ml\logistic-regression>node index.js
internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\kim_1\Desktop\league_stats\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\kim_1\Desktop\league_stats\node_modules\@tensorflow\tfjs-node\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

**Comment by kangyizhang** [comment]
hi @kimvu what's the node version you are using?

**Comment by kimvu** [comment]
Hi @kangyizhang, my node version is v12.13.0

**Comment by kangyizhang** [comment]
There is an issue of loading tfjs-node with node v12.13.0 and v10.17.0

You can use node v10.16.3

Please keep an eye on updated in https://github.com/tensorflow/tfjs/issues/2003. I'll close this issue.

**Comment by kimvu** [comment]
I changed my nodeversion to 10.16.3, and stil get the same error. @kangyizhang

**Comment by f-w** [comment]
Problem persists. @tensorflow/tfjs-node@1.7.4, node@14.5.0, OS: Windows 10 64bit.

```
Error: The specified module could not be found.
\\?\C:\...\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
```
The file exists barring prefix `\\?`.

**Comment by mcormier** [comment]
I had the same issue.  I upgraded to node version 16.13 and I upgraded @tensorflow/tfjs-node to 3.12.0 and the problem disappeared.
