### ISSUE TITLE
BodyPix - running segmentPerson in node.js throws an error: ReferenceError: HTMLImageElement is not defined

### ISSUE THREAD

**Issue by oveddan** [tensorflow/tfjs#2398]
Running BodyPix `segmentPerson` in node.js throws an error:

ReferenceError: HTMLImageElement is not defined

Code that causes error:

```javascript
const bodyPix = require('@tensorflow-models/body-pix');
const fs = require('fs');

const tfjs = require('@tensorflow/tfjs-node');

async function loadImage(path) {
  const file = await fs.promises.readFile(path);

  const image = await tfjs.node.decodeImage(file, 3);

  return image;
}

async function main() {
  const image = await loadImage('./assets/dance.jpg');

  const net = await bodyPix.load({
    architecture: "ResNet50",
    quantBytes: 1,
    outputStride: 16
  });

  const personSegmentation = await net.segmentPerson(image, {
    internalResolution: "full",
    segmentationThreshold: 0.5
  });
}


main();
```

Full stack trace:
(node:6250) UnhandledPromiseRejectionWarning: ReferenceError: HTMLImageElement is not defined
    at Object.getInputSize (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/util.js:41:26)
    at BodyPix.segmentPersonActivation (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:213:25)
    at BodyPix.<anonymous> (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:248:35)
    at step (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:43:23)
    at Object.next (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:24:53)
    at /Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:14:12)
    at BodyPix.segmentPerson (/Users/danoved/Source/bodypix-posenet-node/node_modules/@tensorflow-models/body-pix/dist/body_pix_model.js:241:16)

**Comment by oveddan** [comment]
I've opened a PR to fix.  Would like to get feedback on how I check if it's in the browser or not.
