### ISSUE TITLE
Error installing node-gpu

### ISSUE THREAD

**Issue by samfultonschool** [tensorflow/tfjs#2428]
#### TensorFlow.js version
^1.3.2
#### Browser version
none
#### Describe the problem or feature request
I am trying to install @tensorflow/tfjs-node-gpu on windows 10. I installed everything listed in the npm page needed for GPU support. GPU is 2070. 
Here is the output when running ```npm install @tensorflow/tfjs-node-gpu```
```
> @tensorflow/tfjs-node-gpu@1.3.2 install C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

GPU-windows-1.3.2.zip
* Downloading libtensorflow
[==============================] 14700238/bps 100% 0.0s
[==============================] 1647474/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/GPU-windows-1.3.2.zip
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node-gpu@1.3.2 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\FFF\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\FFF\\Desktop\\scripts\\tf-test-download\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\Users\\FFF\\Desktop\\scripts\\tf-test-download\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v10.16.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\FFF\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4 --napi_version=4 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\FFF\\Desktop\\scripts\\tf-test-download\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tf-test-download@1.0.0 No description
npm WARN tf-test-download@1.0.0 No repository field.

+ @tensorflow/tfjs-node-gpu@1.3.2
added 87 packages from 89 contributors and audited 151 packages in 34.396s
found 0 vulnerabilities
```
#### Code to reproduce the bug / link to feature request
This was in a clean node-modules/package.json, no other overlapping versions of tfjs.

**Comment by samfultonschool** [comment]
Here is the output when I try to run code using the module 
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'c:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\tfjs_binding.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Waiting for the debugger to disconnect...
Error: Cannot find module 'c:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\tfjs_binding.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by kangyizhang** [comment]
hi @samfultonschool 

1. what is your node version?
2. can you check what is inside `c:\Users\FFF\Desktop\scripts\tf-test-download\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\`?
3. do you have issue of installing `@tensorflot/tfjs-node`?

**Comment by samfultonschool** [comment]
@kangyizhang Thanks for the quick response :)
My node version is v10.16.3 due to the fact it was suggested to switch to this to solve the error in another thread. Inside of napi-v4 there is just tensorflow.dll. I did have trouble installing tfjs-node before but that error seemed to be caused by the fact I also installed regualr tfjs before that. Now when I make a new project and new node_modules tfjs-node works, but not gpu.

**Comment by kangyizhang** [comment]
@samfultonschool Thanks for the info. Please keep using v10.16.3 as the latest node is having issue (which you have seen in another thread). 

Both tfjs-node and tfjs-node-gpu should work on windows with node v10.16.3. The error should be caused by mis-configured CUDA drivers. Please make sure that:
1. [CUDA toolkit 10.0](https://developer.nvidia.com/cuda-10.0-download-archive) is installed
2. [cuDNN](https://developer.nvidia.com/cudnn) (>=7.4.1) SDK is downloaded and path is added. This has been the most often reason the the error above. Here is a tutorial from nvidia: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#install-windows (note the version number might be different).

**Comment by gblue1223** [comment]
I've configured as @kangyizhang said but still not working.
Furthermore, I've reinstalled MS Build tools with `npm install --production windows-build-tools` in the project folder but, failed to build tjfs-node-gpu (tjfs-node built successfully).
By the way, Is there any way to see MSBuild log?

[System Info]
```
OS: Windows10 64bit
Mem: 64GB
GraphicCard: GeForce RTX 2080 TI
CUDA: 10.0
cuDNN: cudnn-10.0-windows10-x64-v7.6.5.32
```

[Log]
```
C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu>npm run install

@tensorflow/tfjs-node-gpu@1.3.2 install C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu
node scripts/install.js gpu download

GPU-windows-1.3.2.zip
* Downloading libtensorflow
[==============================] 50534544/bps 100% 0.0s
[==============================] 633020/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --verbose --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--verbose',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.16.3 | win32 | x64
node-pre-gyp verb command install [ 'napi_build_version=4' ]
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\tfjs_binding.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/GPU-windows-1.3.2.zip
node-pre-gyp http 404 https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/GPU-windows-1.3.2.zip
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/GPU-windows-1.3.2.zip
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node-gpu@1.3.2 and node@10.16.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.3.2/GPU-windows-1.3.2.zip
node-pre-gyp verb command build [ 'rebuild', 'napi_build_version=4' ]
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4\\tfjs_binding.node',
gyp verb cli   '--module_name=tfjs_binding',
gyp verb cli   '--module_path=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4',
gyp verb cli   '--napi_version=4',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=4',
gyp verb cli   '--node_napi_label=napi-v4',
gyp verb cli   '--python=C:\\Python27\\python.exe' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | win32 | x64
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in the PATH
gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.3
gyp verb command install [ '10.16.3' ]
gyp verb install input version string "10.16.3"
gyp verb install installing version: 10.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.16.3
gyp verb build dir attempting to create "build" dir: C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\build
gyp verb build dir "build" dir needed to be created? C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.17763
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.14393
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows81SDK
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\greenblue\\.node-gyp\\10.16.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\greenblue\\.node-gyp\\10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\greenblue\\.node-gyp\\10.16.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4\\tfjs_binding.node',
gyp verb cli   '--module_name=tfjs_binding',
gyp verb cli   '--module_path=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4',
gyp verb cli   '--napi_version=4',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=4',
gyp verb cli   '--node_napi_label=napi-v4' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | win32 | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\greenblue\.node-gyp\10.16.3
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\greenblue\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\greenblue\\AppData\\Roaming\\nvm\\v10.16.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--loglevel=verbose" "--fallback-to-build" "--module
=C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\Users\\greenblue\\Documents\\Work\\MnR\\hu
manDetection\\yolo\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v4" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\greenblue\AppData\Roaming\nvm\v10.16.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --loglevel=verbose --fallback-to-build -
-module=C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\greenblue\Documents\Work\MnR\humanDetection\yol
o\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v4 --napi_version=4 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\greenblue\\Documents\\Work\\MnR\\humanDetection\\yolo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--verbose" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\greenblue\Documents\Work\MnR\humanDetection\yolo\node_modules\@tensorflow\tfjs-node-gpu
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
```

**Comment by kangyizhang** [comment]
@gblue1223 I just updated the pre-built binary, please try again. 

To get build logs, you can fork the [repo](https://github.com/tensorflow/tfjs) , go to folder `tfjs-node-gpu`, and run `node-pre-gyp install --verbose --build-from-source`

**Comment by gblue1223** [comment]
Thanks @kangyizhang

I've got `tfjs_backend.cc(1134): error C2131` message and after look at the line I found wrong code which is `char name[strlen(input_op_name_array[i])];`.

However the latest source code already fixed 15days ago.
It seems does not up to date on the npm.

So, I've updated `tfjs_backend.cc` to new one and it works~!

**Comment by kangyizhang** [comment]
Glad to hear it works. Yes the current published version has a bug on Windows. We'll release new version soon.
