### ISSUE TITLE
window not defined reference error

### ISSUE THREAD

**Issue by darkdebo** [tensorflow/tfjs#2453]
I got this type of error after installation:
/home/debo/node_modules/vega-embed/build/vega-embed.js:3874
  const w = window;
            ^

ReferenceError: window is not defined
    at /home/debo/node_modules/vega-embed/build/vega-embed.js:3874:13
    at xhtml (/home/debo/node_modules/vega-embed/build/vega-embed.js:2:83)
    at Object.<anonymous> (/home/debo/node_modules/vega-embed/build/vega-embed.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.

**Comment by tutmoses** [comment]
I solved this by just commenting out that line.

`// const w = window;`
