### ISSUE TITLE
KeyError: u'DecodeWav' running tensorflowjs_converter

### ISSUE THREAD

**Issue by pschlette** [tensorflow/tfjs#246]
#### TensorFlow.js version
Tensorflowjs `0.1.2` (per `pip show`), installed on the tensorflow `1.8.0` docker image 

#### Browser version
n/a - error is in `tensorflowjs_converter`

#### Describe the problem or feature request
I'm working off of the ["Simple Audio Recognition" tutorial](https://www.tensorflow.org/versions/master/tutorials/audio_recognition); my only changes are some adjustments to the parameters and using my own set of classified clips to train the model. After training the model, I have what I think tensorflow calls a "session bundle" (with a bunch of checkpoint files). I'd like to run this model in a browser, so I ran it through the `tensorflowjs_converter`. When I do, I get a stacktrace starting at: `KeyError: u'DecodeWav'`.

`DecodeWav` is in this [list of Tensorflow ops](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/core/ops/ops.pbtxt) I've seen referenced in other issues, so I'm wondering:

* If the issue is that the `DecodeWav` op is unsupported by TensorflowJs, could support be added?
* Why did the converter crash rather than politely list the unsupported ops?

#### Code to reproduce the bug / link to feature request
Where the output of a trained model from following the "Simple Audio Recognition" tutorial is in `tensorflow-output/speech_commands_train`:
```
tensorflowjs_converter \
  --input_format=tf_session_bundle \
  --output_node_names='thwack' \
  'tensorflow-output/speech_commands_train' \
  'tensorflow-output/web_model'
```

I get the output...
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Tensorflow has deprecated the Session Bundle format,  please migrate to SavedModel.
Loaded meta graph file '/tmp/speech_commands_train/low_latency_conv.ckpt-260.meta
2018-04-29 21:14:10.601245: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 129, in main
    FLAGS.output_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 184, in convert_tf_session_bundle
    input_meta_graph=input_checkpoint + '.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 256, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 109, in freeze_graph_with_def_protos
    input_meta_graph_def, clear_devices=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1927, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 741, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 457, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'DecodeWav'
```

**Comment by pyu10055** [comment]
This looks like some error loading the model by tensorflow, @pschlette can you confirm this model is loadable by python? if possible, can you share the session bundle model with us? thanks.

**Comment by pschlette** [comment]
Sure - you can see the model here: https://bitbucket.org/pschlette/skip-counter/src/master/training/tensorflow-output/speech_commands_train/

I don't have a great grip on all the different ways models can be serialized or how to convert between the various formats, but I tried using the [load_session_bundle_from_path](https://github.com/tensorflow/tensorflow/blob/c856366b739850a9f4b0bf1469de7f052619042b/tensorflow/contrib/session_bundle/session_bundle.py#L35) method on the advice of an SO post to load the model and got a very similar error after I renamed the `.meta` file to `export.meta`:
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From load_my_session.py:3: load_session_bundle_from_path (from tensorflow.contrib.session_bundle.session_bundle) is deprecated and will be removed after 2017-06-30.
Instructions for updating:
No longer supported. Switch to SavedModel immediately.
2018-05-03 17:47:03.638826: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "load_my_session.py", line 3, in <module>
    load_session_bundle_from_path("./tensorflow-output/speech_commands_train")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/session_bundle/session_bundle.py", line 146, in load_session_bundle_from_path
    saver = saver_lib.import_meta_graph(meta_graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1927, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 741, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 457, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'DecodeWav'
```
So maybe this doesn't have much to do with the tfjs converter after all.

**Comment by pyu10055** [comment]
@pschlette thanks for the update, I agree this is most likely TensorFlow issue, but as indicated in the log, the session bundle is deprecated. I will close this issue for now, you should raise this to TensorFlow repo. Thanks!
