### ISSUE TITLE
Error: The specified module could not be found. How to fix?

### ISSUE THREAD

**Issue by Glunky** [tensorflow/tfjs#2536]
####  Chrome 78 on Windows 10

Hi! My programm returns me an error:
```
internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\vkont\Downloads\node-webrtc-examples-master\node-webrtc-examples-master\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\vkont\Downloads\node-webrtc-examples-master\node-webrtc-examples-master\node_modules\@tensorflow\tfjs-node\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-webrtc-examples@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-webrtc-examples@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vkont\AppData\Roaming\npm-cache\_logs\2019-12-11T13_25_16_214Z-debug.log
```
Before all worked fine, but not now. If i update all 3 tfjs all works fine, but in my case i can use only 1.2.9. version. Is it possible to fix this issue without updating?

**Comment by kangyizhang** [comment]
There is an issue of using tfjs-node before 1.3.1 with node version later than 10.16.3. You can either use node @10.16.3, or install latest version of tfjs-node. You only need to install tfjs-node, it will automatically install tfjs and tfjs-core.

**Comment by adi-dev** [comment]
I have removed all `@tensorflow` modules and installed only `npm install -g @tensorflow/tfjs-node` (and tried -gpu too) but still the same error.
