### ISSUE TITLE
Importing keras saved model fails due to issue with higher rank tensor embeddings (?)

### ISSUE THREAD

**Issue by ksabr** [tensorflow/tfjs#2571]
Hi there,

I'm running into a problem with loading a saved keras model which has an embedding layer applied to rank 3 tensors. Please find further details below:

#### TensorFlow.js version
1.4.0

#### Browser version
74.0.3729.131

#### Describe the problem or feature request

I am trying to load a model created via the Python API, and I get the following error message:

```
(node:25209) UnhandledPromiseRejectionWarning: Error: "inputLength" is 20, but received input shape has shape ,128,20
    at new ValueError (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/errors.js:68:28)
    at Embedding.computeOutputShape (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/layers/embeddings.js:106:19)
    at /home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/engine/topology.js:780:41
    at Object.nameScope (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/common.js:41:19)
    at Embedding.Layer.apply (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/engine/topology.js:719:25)
    at processNode (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/engine/container.js:1091:23)
    at Container.fromConfig (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/engine/container.js:1141:25)
    at Object.deserializeKerasObject (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/utils/generic_utils.js:291:29)
    at Object.deserialize (/home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/layers/serialization.js:29:28)
    at /home/research-code/anonymisation/js/node_modules/@tensorflow/tfjs-layers/dist/models.js:288:45
(node:25209) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25209) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The problematic bit of the model seems to be embeddings of 3D tensors. Here's the relevant part of the (Python-created) model summary:

```
input_2 (InputLayer)            [(None, 128, 20)]    0     
__________________
embedding_1 (Embedding)         (None, 128, 20, 25)  900100      input_2[0][0]                    
```

#### Code to reproduce the bug / link to feature request

The Python code below creates a model which I cannot then import in tfjs:

```
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.models import Model

inputs = Input(shape=(128, 50), dtype=tf.int32)
    
embedding_layer = tf.keras.layers.Embedding(
        100,
        30,
        input_length=50,
        trainable=True,
        mask_zero=True
    )

embeddings = embedding_layer(inputs)

model = Model(inputs, embeddings)

model.save('bug_js/model.hd5', save_format='h5')
```

Please let me know if you have any ideas how to proceed. I should add that with a different model which doesn't use the rank-3 embedding, everything works fine.

**Comment by rthadur** [comment]
Hello, this sort of question is better suited for StackOverflow. This issues list is for bugs and feature requests. Thanks and please use the tag 'tensorflow.js' on your StackOverflow question to makes sure it's discoverable.
