### ISSUE TITLE
Firebase and Tensorflow-automl not working together

### ISSUE THREAD

**Issue by ozican** [tensorflow/tfjs#2586]
Hello everybody. I have a very strange issue.

When I use tfjs-node without firebase, it works very well. I can get my predicts with online image links. But when I import firebase and after sign-in (only sign-in, not using) I get `TypeError: response.arrayBuffer is not a function` that error. I can not load my model.

index.js
```
firebase.auth().signInWithEmailAndPassword('email', 'pass')
.then(() => {
  console.log('signed')
  notConfirmedFortunes.findNotConfirmedFortunes(firebase);
})
```

```
const automl = require('@tensorflow/tfjs-automl');
var firebase = require('firebase');
let model = null;
require('@tensorflow/tfjs-node');

async function loadModel() {
    model = await automl.loadImageClassification('https://xxxxxx.com/graph/model.json');
}

async function findNotConfirmedFortunes() {
    if(model == null) {
        setTimeout(() => {
            loadModel();
            findNotConfirmedFortunes()
        }, 15000)
    }
    else {
        // firebase.database().ref(`***/**path to database**/*****/`)
        // .on('child_added', function(snapshot) { 
        //     predictImages.predict(snapshot.val(), model)
        // })
    }
}

module.exports={
    findNotConfirmedFortunes
}

findNotConfirmedFortunes()
```

Here is my envoriment;

```
{
  "name": "confirmation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow/tfjs-automl": "^1.0.0",
    "@tensorflow/tfjs-converter": "^1.4.0",
    "@tensorflow/tfjs-node": "^1.4.0",
    "firebase": "^7.5.0",
    "jpeg-js": "^0.3.4",
    "xmlhttprequest": "^1.8.0"
  }
}


```

**Comment by ozican** [comment]
```
(node:21613) UnhandledPromiseRejectionWarning: TypeError: response.arrayBuffer is not a function
    at /Users/yagizozandikbas/Desktop/confirmation/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:97:90
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/yagizozandikbas/Desktop/confirmation/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:97:48)
    at step (/Users/yagizozandikbas/Desktop/confirmation/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:48:23)
    at Object.next (/Users/yagizozandikbas/Desktop/confirmation/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:29:53)
    at fulfilled (/Users/yagizozandikbas/Desktop/confirmation/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:20:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21613) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```

**Comment by kangyizhang** [comment]
@ozican 
looks like `node-fetch` is disabled in firebase environment. Can you try to call `tf.fetch(modelUrl)` (https://js.tensorflow.org/api/latest/#fetch) in firebase and check the response?

**Comment by roeyb** [comment]
you could add this to your Firebase Functions index file:
`global.fetch = require('node-fetch');`

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
