### ISSUE TITLE
In node.js. UnhandledPromiseRejectionWarning: RangeError: byte length of Float32Array should be a multiple of 4

### ISSUE THREAD

**Issue by Honghe** [tensorflow/tfjs#2651]
#### TensorFlow.js version
```
| +-- @tensorflow-models/body-pix@2.0.4
| +-- @tensorflow/tfjs-converter@1.5.1
| +-- @tensorflow/tfjs-core@1.5.1
| `-- @tensorflow/tfjs-node@1.5.1
`-- npm@6.13.4
```

```
  "dependencies": {
    "@tensorflow-models/body-pix": "~2.0.4",
    "@tensorflow/tfjs-node": "~1.5.1",
    "@tensorflow/tfjs-converter": "~1.5.1",
    "@tensorflow/tfjs-core": "~1.5.1"
  }
```

#### Browser version
on node.js.  
node.js v12.14.0

#### Describe the problem or feature request
log:
```
2020-01-07 20:12:59.633346: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-01-07 20:12:59.663360: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
2020-01-07 20:12:59.664383: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5688330 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-07 20:12:59.664425: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(node:20931) UnhandledPromiseRejectionWarning: RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at _loop_2 (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:206:26)
    at Object.decodeWeights (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:223:9)
    at GraphModel.<anonymous> (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:178:52)
    at step (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:48:23)
    at Object.next (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:29:53)
    at fulfilled (/home/ubuntu/jack/demo_bodypix_npm/node_modules/@tensorflow/tfjs-converter/dist/src/executor/graph_model.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:20931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(base) 
```

#### Code to reproduce the bug / link to feature request
```
const tfjs = require('@tensorflow/tfjs-node');
const bodyPix = require('@tensorflow-models/body-pix');
const fs = require('fs');
const path = require('path');

async function loadMode() {
    const net = await bodyPix.load({
        architecture: "ResNet50",
        quantBytes: 4,
        outputStride: 16,
        modelUrl: "http://0.0.0.0:8000/ResNet50/model-stride16.json"
    });
    return net;
}
```
and the model I served locally:
```
├── model_resnet50_quant4_stride16
│   ├── ResNet50
│   │   ├── group1-shard10of23.bin
│   │   ├── group1-shard11of23.bin
│   │   ├── group1-shard12of23.bin
│   │   ├── group1-shard13of23.bin
│   │   ├── group1-shard14of23.bin
│   │   ├── group1-shard15of23.bin
│   │   ├── group1-shard16of23.bin
│   │   ├── group1-shard17of23.bin
│   │   ├── group1-shard18of23.bin
│   │   ├── group1-shard19of23.bin
│   │   ├── group1-shard1of23.bin
│   │   ├── group1-shard20of23.bin
│   │   ├── group1-shard21of23.bin
│   │   ├── group1-shard22of23.bin
│   │   ├── group1-shard23of23.bin
│   │   ├── group1-shard2of23.bin
│   │   ├── group1-shard3of23.bin
│   │   ├── group1-shard4of23.bin
│   │   ├── group1-shard5of23.bin
│   │   ├── group1-shard6of23.bin
│   │   ├── group1-shard7of23.bin
│   │   ├── group1-shard8of23.bin
│   │   ├── group1-shard9of23.bin
│   │   └── model-stride16.json
```

![image](https://user-images.githubusercontent.com/1092722/71947412-bde0af00-3207-11ea-81db-641291ed9a8f.png)

My detailed code: https://github.com/honghe/demo_bodypix_node/blob/master/src/main.js

**Comment by kangyizhang** [comment]
@Honghe After you installed the `@tensorflow-models/body-pix` package, you do not need to provide modelUrl field when loading the weights. Can you try again without the modelUrl field in bodyPix.load config? I guess the error is because of mis-hosted weights file.

**Comment by Honghe** [comment]
@kangyizhang I set the `modelUrl` to local server for a better loading performance, the `resnet50_quant4_stride16` model is about 90MB. The model files was downloaded from `https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/group1-shard${i}of23.bin`.

**Comment by rthadur** [comment]
Closing this due to lack of activity, feel to reopen. Thank you
