### ISSUE TITLE
Expo fetch import error

### ISSUE THREAD

**Issue by lfuszara1** [tensorflow/tfjs#2681]
#### TensorFlow.js version

@tensorflow/tfjs 1.5.1

@tensorflow/tfjs-react-native 0.1.0-alpha.3

#### Versions

Android 10 on mobile

Windows 10 on PC

Expo SDK version 36.0.0

Node.js 12.14.1

#### Describe the problem or feature request

`import { fetch } from '@tensorflow/tfjs-react-native'`

Is generating error:

TypeError: null is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular)

Without this line I have:

```
Error: Unable to resolve module `./http@http://192.168.1.7:19001/node_modules\expo\AppEntry` from ``:

None of these files exist:
  * http@http:\192.168.1.7:19001\node_modules\expo\AppEntry(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
  * http@http:\192.168.1.7:19001\node_modules\expo\AppEntry\index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\lib\transformHelpers.js:267:42
    at C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\Server.js:1305:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\Server.js:99:24)
    at _next (C:\Users\lukas\Desktop\Projekty\HearObjects\node_modules\metro\src\Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'environment_1.env().platform.fetch')]
* HTTPRequest@http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:162543:50 in <unknown>
* http@http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:162781:27 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:161455:29 in <unknown>
* [native code]:null in forEach
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:161454:22 in getHandlers
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188344:54 in findIOHandler
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188362:33 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188248:25 in step
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188150:73 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27123:9 in tryCallTwo
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27287:25 in doResolve
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27146:14 in Promise
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188127:36 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188485:34 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188248:25 in step
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188150:73 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27123:9 in tryCallTwo
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27287:25 in doResolve
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27146:14 in Promise
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:188127:36 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:203017:47 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202905:25 in step
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202807:73 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27123:9 in tryCallTwo
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27287:25 in doResolve
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27146:14 in Promise
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202784:36 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202987:44 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202905:25 in step
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202807:73 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27123:9 in tryCallTwo
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27287:25 in doResolve
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27146:14 in Promise
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:202784:36 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123695:63 in loadCocossdModel$
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25759:23 in tryCatch
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25934:32 in invoke
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25759:23 in tryCatch
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25835:30 in invoke
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25865:19 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27123:9 in tryCallTwo
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27287:25 in doResolve
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27146:14 in Promise
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25864:29 in callInvokeWithMethodAndArg
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25869:157 in enqueue
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25885:69 in async
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123690:42 in loadCocossdModel
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123726:72 in componentDidMount$
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25759:23 in tryCatch
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25934:32 in invoke
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25759:23 in tryCatch
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25835:30 in invoke
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:25845:21 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27114:16 in tryCallOne
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:27215:27 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:30669:17 in _callTimer
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:30705:19 in _callImmediatesPass
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:30924:33 in callImmediates
* [native code]:null in callImmediates
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:2712:35 in __callImmediates
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:2489:34 in <unknown>
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:2695:15 in __guard
* http://192.168.1.7:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false:2488:21 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

#### Code to reproduce the bug / link to feature request

App.js

```
import React from 'react';
import { StyleSheet, Text, View, StatusBar, ActivityIndicator, TouchableOpacity, Dimensions, Image } from 'react-native';
import { Camera } from 'expo-camera';
import * as tf from '@tensorflow/tfjs';
import * as cocoSsd from '@tensorflow-models/coco-ssd';
import * as Permissions from 'expo-permissions';
import * as jpeg from 'jpeg-js';
import * as FileSystem from 'expo-file-system';
import { Buffer } from 'buffer'
import { Asset } from 'expo-asset';

export default class App extends React.Component {
  state = {
    isTfReady: false,
    isModelReady: false,
    isCameraReady: false,
    predictions: null,
    image: null,
  };
  
  async getPermissionAsync() {
    await Permissions.askAsync(Permissions.AUDIO_RECORDING)
    await Permissions.askAsync(Permissions.CAMERA_ROLL)
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    this.setState({ isCameraReady: status });
  }

  async loadTf() {
    await tf.ready();
  }
  
  async loadCocossdModel() {
    const model = await cocoSsd.load();
  }
  
  async componentDidMount() {
    await this.getPermissionAsync();
    
    await this.loadTf();
    this.setState({ isTfReady: true });
    await this.loadCocossdModel();
    this.setState({ isModelReady: true });
  }
  
  imageToTensor(rawImageData) {
    const TO_UINT8ARRAY = true;
    const { width, height, data } = jpeg.decode(rawImageData, TO_UINT8ARRAY);
    const buffer = new Uint8Array(width * height * 3);
    let offset = 0;
    for (let i = 0; i < buffer.length; i += 3) {
      buffer[i] = data[offset];
      buffer[i + 1] = data[offset + 1];
      buffer[i + 2] = data[offset + 2];
      offset += 4;
    }
    return tf.tensor3d(buffer, [height, width, 3]);
  }
  
  async classifyImage() {
    try {
      const response = await FileSystem.readAsStringAsync(this.state.image, { encoding: FileSystem.EncodingType.Base64 });
      const rawImageData = await Buffer.from(response, 'base64');;
      const imageTensor = this.imageToTensor(rawImageData);
      const predictions = await this.model.classify(imageTensor);
      this.setState({ predictions });
      console.log(predictions);
    } catch (error) {
      console.log(error);
    }
  }
  
  async takePicture() {
    try {
      const cameraData = await this.camera.takePictureAsync()
      this.setState({ image: cameraData.uri });
    } catch (e) {
      console.log(e)
    }
    await this.classifyImage();
  }

  render() {
    const { isTfReady, isModelReady, isCameraReady, predictions, image } = this.state

    if (isCameraReady === null) {
      return <View />
    }
    else if (isCameraReady === false) {
      return <Text> No access to camera</Text>
    }

    return (
      <View style={styles.container}>
        <Camera
          ref={ref => {
            this.camera = ref;
          }}
          autoFocus={false}
          type={Camera.Constants.Type.back}
          style={styles.preview}
        />
        <StatusBar barStyle='light-content' />
        <TouchableOpacity
          style={styles.imageWrapper}
          onPress={isModelReady ? this.takePicture : undefined}>
          {image && <Image source={{uri: image}} style={styles.imageContainer} />}

          {isModelReady && !image && (
            <Text style={styles.transparentText}>Tap to choose image</Text>
          )}
        </TouchableOpacity>
        <View style={styles.predictionWrapper}>
          {isModelReady && image && (
            <Text style={styles.text}>
              Predictions: {predictions ? '' : 'Predicting...'}
            </Text>
          )}
          {isModelReady &&
            predictions &&
            predictions.map(p => this.renderPrediction(p))}
        </View>
      </View>
    );
  }
}

const { width: winWidth, height: winHeight } = Dimensions.get('window');

const styles = StyleSheet.create({
   preview: {
    height: winHeight,
    width: winWidth,
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 1000,
    backgroundColor: '#fff',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageWrapper: {
    width: winWidth,
    height: winHeight,
    padding: 10,
    borderColor: '#cf667f',
    borderWidth: 5,
    borderStyle: 'dashed',
    marginTop: 40,
    marginBottom: 10,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center'
  },
  predictionWrapper: {
    height: winHeight,
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'absolute',
  },
});
```

metro.config.js

```
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
    babelTransformerPath: require.resolve(
      'react-native-typescript-transformer',
    ),
  },
  resolver: {
    assetExts: ['bin', 'txt', 'jpg', 'png', 'ttf'],
    sourceExts: ['js', 'json', 'ts', 'tsx', 'jsx'],
    blacklistRE: blacklist([/platform_node/])
  },
};
```

package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@tensorflow-models/coco-ssd": "^2.0.1",
    "@tensorflow/tfjs": "^1.5.1",
    "@tensorflow/tfjs-react-native": "^0.1.0-alpha.3",
    "buffer": "^5.4.3",
    "expo": "~36.0.0",
    "expo-asset": "^8.0.0",
    "expo-camera": "^8.0.0",
    "expo-gl": "^8.0.0",
    "expo-gl-cpp": "^8.0.0",
    "expo-permissions": "^8.0.0",
    "jpeg-js": "^0.3.6",
    "metro-config": "^0.56.4",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-fs": "^2.16.2",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-typescript-transformer": "^1.2.13",
    "react-native-unimodules": "^0.7.0",
    "react-native-web": "^0.12.0-rc.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@types/react": "~16.9.0",
    "@types/react-native": "~0.60.23",
    "babel-preset-expo": "~8.0.0",
    "typescript": "~3.6.3"
  },
  "private": true
}
```

tsconfig.json

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  }
}
```

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by lfuszara1** [comment]
I created question on StackOverflow, without tag [tensorflow-tfjs] because I had information about tag not exists.
[How to repair tfjs error on adding fetch from @tensorflow/tfjs-react-native?](https://stackoverflow.com/questions/59764168/how-to-repair-tfjs-error-on-adding-fetch-from-tensorflow-tfjs-react-native)
