### ISSUE TITLE
[tfjs-react-native] React Native apk error, expo-gl-cpp

### ISSUE THREAD

**Issue by lfuszara1** [tensorflow/tfjs#2689]
#### Versions:

```
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@tensorflow-models/coco-ssd": "^2.0.1",
    "@tensorflow/tfjs": "^1.5.1",
    "@tensorflow/tfjs-converter": "^1.5.1",
    "@tensorflow/tfjs-react-native": "0.1.0-alpha.2",
    "buffer": "^5.4.3",
    "expo-file-system": "^8.0.0",
    "expo-gl": "^8.0.0",
    "expo-gl-cpp": "^8.0.0",
    "expo-permissions": "^8.0.0",
    "jpeg-js": "^0.3.6",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-camera": "^3.15.1",
    "react-native-fs": "^2.16.2",
    "react-native-orientation-locker": "^1.1.8",
    "react-native-tts": "^3.1.1",
    "react-native-unimodules": "^0.7.0",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  }
```

#### TensorFlow.js version

1.5.1

#### Describe the problem or feature request

Created apk is generating error:

```
java.lang.NoSuchMethodError: no non-static method "Le/a/b/f;.flush()V"
	at expo.modules.gl.cpp.EXGL.EXGLContextSetFlushMethod(Native Method)
	at e.a.b.c.run(Unknown Source:42)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:224)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:919)
```

#### Code to reproduce the bug / link to feature request

```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle
cd android\
gradlew assembleRelease
```

**Comment by rthadur** [comment]
Looks like this is not an issue from tfjs-react-native , instead it is related to EXPO-GL-CPP , please check for similar issue [there](https://github.com/expo/expo/issues/3787)  , Thank you
