### ISSUE TITLE
Implement ops for converted audio models: Mfcc, DecodeWav, AudioSpectrogram

### ISSUE THREAD

**Issue by pschlette** [tensorflow/tfjs#271]
#### TensorFlow.js version
`0.3.0`

#### Describe the problem or feature request
I generated a model using the ["Simple Audio Recognition" tutorial](https://www.tensorflow.org/versions/master/tutorials/audio_recognition), which I'd like to run in a browser. I tried to convert it for use with TensorFlow.js, but I had some issues loading the model when I ran the `tensorflowjs-converter`, as described in this issue: https://github.com/tensorflow/tfjs/issues/246.

I tried resolving this by adding the line:
`from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio`
to `converters/converter.py` in the `tensorflowjs` pip package. This fixed the exception when loading the model and now the converter lists the missing ops:
```
Unsupported Ops in the model
Mfcc, DecodeWav, AudioSpectrogram
```

Could these ops be implemented for TensorFlow.js?

**Comment by davidsoergel** [comment]
Thanks for the request!  We are working to expand the coverage of TensorFlow Ops in TF.js.  I can't say when these will be done, but user feedback does help up prioritize.

I vaguely recall that spectrograms are a special case-- @nsthorat, was this one of those situations where the browser implementation differs subtly from the TF implementation and so breaks imported models?

**Comment by pyu10055** [comment]
@pschlette I have been playing with the audio model, those three preprocessing ops, would more likely not be part of the tensorflow core ops. I will try to create an example first.

**Comment by satbecse** [comment]
I am getting the same error 

(python_new) C:\Users\st3015>tensorflowjs_converter --input_format=tf_frozen_model --output_node_names=AudioSpectrogram,Mfcc,Reshape,Conv2D,Relu,MaxPool,MatMul --skip_op_check=SKIP_OP_CHECK  /tmp/my_frozen_graph.pb  /tmp/web_model
Using TensorFlow backend.
Traceback (most recent call last):
  File "c:\users\st3015\anaconda3\envs\python_new\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\st3015\Anaconda3\envs\python_new\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\converter.py", line 352, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_pb.py", line 331, in convert_tf_frozen_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_pb.py", line 128, in optimize_graph
    graph_def=graph.as_graph_def(), graph=graph)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\training\saver.py", line 1561, in export_meta_graph
    **kwargs)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 1000, in export_scoped_meta_graph
    **kwargs)
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 585, in create_meta_graph_def
    stripped_op_list_for_graph(meta_graph_def.graph_def))
  File "c:\users\st3015\anaconda3\envs\python_new\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 202, in stripped_op_list_for_graph
    raise ValueError("Op %s is used by the graph, but is not registered" % op)
ValueError: Op Mfcc is used by the graph, but is not registered



Can you please help me on this ? 

Versions :
======
(python_new) C:\Users\st3015>tensorflowjs_converter --version
Using TensorFlow backend.

tensorflowjs 0.8.6
Dependency versions:
  keras 2.2.2
  tensorflow 1.13.1


(python_new) C:\Users\st3015>python --version
Python 3.6.8 :: Anaconda, Inc.

**Comment by kongkip** [comment]
I have the same issued when I try to load the model in android.

 java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Encountered unresolved custom op: DecodeWav.
   Node number 0 (DecodeWav) failed to prepare

**Comment by Naveen3Singh** [comment]
@kongkip You got anything yet?

**Comment by kongkip** [comment]
Hi,
Instead of doing that, I created a package by extending
tf.keras.layers.Layer by creating an audio preprocessor which generates
spectrograms and it turned out that the ops are in TFlite.

On DecodeWav, I preprocess the data before basing through the spectrogram
layer hence the not included when converting the model to TFlite.
