### ISSUE TITLE
[tfjs-converter] can't convert custom layers

### ISSUE THREAD

**Issue by AndreMaz** [tensorflow/tfjs#2721]
#### TensorFlow.js version
v1.5.2
#### Describe the problem or feature request
I've tried to convert the model from [date-conversion-attention](https://github.com/tensorflow/tfjs-examples/tree/master/date-conversion-attention) example but it seems that the converter does not support custom layers. It produces the following error:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 645, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 649, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 625, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 366, in dispatch_tfjs_layers_model_to_tfjs_graph_conversion
    model = keras_tfjs_loader.load_keras_model(config_json_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 218, in load_keras_model
    use_unique_name_scope=use_unique_name_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/keras_tfjs_loader.py", line 65, in _deserialize_keras_model
    model = keras.models.model_from_json(json.dumps(model_topology_json))
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 303, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 937, in from_config
    config, custom_objects)
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1893, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1875, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/andmaz/.local/lib/python2.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: GetLastTimestepLayer
```

The custom layer that it complains about is this one:
https://github.com/tensorflow/tfjs-examples/blob/908ee32750ba750a14d15caeb53115e2d3dda2b3/date-conversion-attention/model.js#L21-L50

#### Code to reproduce the bug / link to feature request
1. run the `train.js` script and wait until it generates the model
2. run `tensorflowjs_converter --input_format tfjs_layers_model --output_format tfjs_graph_model dist/model/model.json out/graph-model`

**Comment by rthadur** [comment]
Currently we don't support custom layers like this, only workaround is to write equivalent of this layer type in Python. Thank you 
cc @shanqing-cai

**Comment by AndreMaz** [comment]
Ok. I thought that it would work because the converter seems to [support](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md#tensors---slicing-and-joining) the ops that are present in the custom layer. Anyway, thanks for the info.
