### ISSUE TITLE
Session fail to run with error: indices = 1 

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/tfjs#2746]
#### TensorFlow.js version 
1.5

#### Browser version
NA

#### Describe the problem or feature request
`tf.saved_model` with embeddings fails on `model.predict` in tfjs-node.

#### Code to reproduce the bug / link to feature request
```js
const model = await tf.node.loadSavedModel(savedModelPath);
const input = {
        "f1": tf.tensor(['dfsdfsdf']),
        "f2": tf.tensor([1719.0]),
        "f3": tf.tensor(['ouipoio']),
        "f4": tf.tensor(['trterte']),
        "f5": tf.tensor(['sdsddsf']),
        "f6": tf.tensor(['tretert']),
        "f7": tf.tensor(['sdfsdf']),
        "f8": tf.tensor([12.0]),
        "f9": tf.tensor(['defg']),
        "f10": tf.tensor(['abcd'])
}
const output = model.predict(input);
```
All the features other than f8 and f2 numerical columns have embeddings. My Python code looks very similar to https://www.tensorflow.org/tutorials/structured_data/feature_columns. All my [embedding feature columns](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) have `num_oov_buckets=1` if that helps in any way.
After training I saved it using `model.save("some_path", save_format='tf')`.

And here is the full stack trace,

```
2020-02-12 01:14:46.522724: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-12 01:14:46.562096: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1072cbfc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-12 01:14:46.562129: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Loading model from <PROJECT_HOME>/saved_model/keras_saved_model
2020-02-12 01:14:46.923646: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: <PROJECT_HOME>/saved_model/keras_saved_model
2020-02-12 01:14:46.943722: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-02-12 01:14:47.070512: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2020-02-12 01:14:47.328407: I tensorflow/cc/saved_model/loader.cc:151] Running initialization op on SavedModel bundle at path: <PROJECT_HOME>/saved_model/keras_saved_model
2020-02-12 01:14:47.575025: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 651378 microseconds.

(node:99068) UnhandledPromiseRejectionWarning: Error: Session fail to run with error: indices = 1 is not in [0, 1)
	 [[{{node sequential/dense_features/f9/f9_weights/GatherV2}}]]
    at NodeJSKernelBackend.runSavedModel (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:1556:43)
    at TFSavedModel.predict (<PROJECT_HOME>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:347:52)
    at predict (<PROJECT_HOME>/MY_FILE.js:28:26)
    at main (<PROJECT_HOME>/MY_FILE.js:47:5)
(node:99068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pyu10055** [comment]
@Nithanaroy Is this using the saved model direct execution or you have converted the saved model to tfjs format?

**Comment by Nithanaroy** [comment]
It is a direct execution without conversion

**Comment by pyu10055** [comment]
@Nithanaroy Can you check in your TF board graph, what is the second input to the node
sequential/dense_features/f9/f9_weights/GatherV2
Is it a constant or an input tensor? The error is indicating the value for the indices input of gather op is wrong. Can you check if that is related to your inputs. Thanks

**Comment by Nithanaroy** [comment]
I was able to make it work. It is expecting the tensor definition to contain the shape as well.
```js
const input = {
        "f1": tf.tensor(['dfsdfsdf'], [1, 1], "string"),
        ...
}
const output = model.predict(input);
```

**Comment by pyu10055** [comment]
@dsmilkov Hi Daniel can you check if string tensor creation set the shape properly?
seems the tf.tensor(['sdfsdf']) behaves differently than tf.tensor(['sdfsdf'], [1,1], 'string')?

**Comment by dsmilkov** [comment]
- `tf.tensor(['sdfsdf'])` infers shape of `[1]`
- `tf.tensor(['sdfsdf'], [1, 1], 'string')` gives shape of `[1, 1]`.

Both are working as intended.  If you want to infer shape of `[1,1]`, you have to do `tf.tensor([['sdfsdf']])`

**Comment by Nithanaroy** [comment]
Ah makes sense. Thanks Daniel and Ping. 

Any advice on a similar workflow https://stackoverflow.com/questions/60201536/how-to-avoid-64-bit-data-types-to-run-my-python-estimator-model-natively-on-tfjs
