### ISSUE TITLE
missing binding error

### ISSUE THREAD

**Issue by kennyviperhk** [tensorflow/tfjs#2750]
[`tensorflow.js`]

#### TensorFlow.js version
1.5.2
#### Browser version
Chrome 80.0.3987.100
#### Describe the problem or feature request

after installing tfjs, while running

Error: Cannot find module ..../node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node

folder is empty

![Screenshot 2020-02-13 at 3 23 37 PM](https://user-images.githubusercontent.com/4047303/74410769-d7af8a80-4e74-11ea-9f94-fbbfc3739610.png)

```

/project_folder/node_modules/@tensorflow/tfjs-node/dist/index.js:1
Error: Cannot find module '/project_folder/node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node'
Require stack:
- /project_folder/node_modules/@tensorflow/tfjs-node/dist/index.js
- /project_folder/profile-maker.js
- /project_folder/server.js
- /project_folder/tests/routes/user-routes.js
- /project_folder/node_modules/mocha/lib/mocha.js
- /project_folder/node_modules/mocha/lib/cli/one-and-dones.js
- /project_folder/node_modules/mocha/lib/cli/options.js
- /project_folder/node_modules/mocha/lib/cli/cli.js
    at Object.<anonymous> (/project_folder/node_modules/@tensorflow/tfjs-node/dist/index.js:46:16)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/project_folder/profile-maker.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/project_folder/server.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/project_folder/tests/routes/user-routes.js:1)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at /project_folder/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/project_folder/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/project_folder/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/project_folder/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/project_folder/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/project_folder/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/project_folder/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/project_folder/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/project_folder/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/project_folder/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/project_folder/node_modules/mocha/lib/cli/cli.js:73:11)
    at Generator.next (<anonymous>)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project_folder/node_modules/@tensorflow/tfjs-node/dist/index.js',
    '/project_folder/profile-maker.js',
    '/project_folder/server.js',
    '/project_folder/tests/routes/user-routes.js',
    '/project_folder/node_modules/mocha/lib/mocha.js',
    '/project_folder/node_modules/mocha/lib/cli/one-and-dones.js',
    '/project_folder/node_modules/mocha/lib/cli/options.js',
    '/project_folder/node_modules/mocha/lib/cli/cli.js'
  ]
}


```

#### Code to reproduce the bug / link to feature request

Install via yarn

OSX 10.14.6
node v12.9.1
yarn 1.21.1

D iu, [13.02.20 14:32]
node v12.9.1

D iu, [13.02.20 14:32]
yarn 1.21.1

D iu, [13.02.20 14:44]
[ Photo ]

Note to the issue:
a) in package.json we did import dependencies "@tensorflow/tfjs-node": "^1.5.1",
b) it only happens on some of the dev machines

thanks!

**Comment by rthadur** [comment]
@kennyviperhk thanks for reporting , can you please try these things 

1. remove dependency of @tensorflow/tfjs in package.json. tfjs-node will install @tensorflow/tfjs with corresponding version.
2. use the exact version of @tensorflow/tfjs-node (remove ^ before the version number). Delete node_modules, yarn.lock and package-lock.json, then install dependencies.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
