### ISSUE TITLE
tfjs-node failes to build

### ISSUE THREAD

**Issue by TheHidden1** [tensorflow/tfjs#2758]
OS : Windows X64
PYTHON : 2.7

Hi! 
i get this error when i try to  install tfjs-node : 
```bash
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.5.2/CPU-windows-1.5.2.zip
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@1.5.2 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Projects\\NGElectron\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v4\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=D:\\Projects\\NGElectron\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v4" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=4" "--node_napi_label=napi-v4"
gyp ERR! cwd D:\Projects\NGElectron\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Projects\NGElectron\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node --module_name=tfjs_binding --module_path=D:\Projects\NGElectron\node_modules\@tensorflow\tfjs-node\lib\napi-v4 --napi_version=4 --node_abi_napi=napi --napi_build_version=4 --node_napi_label=napi-v4' (1)  
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Projects\NGElectron\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\NGElectron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Projects\NGElectron\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
```

the prebuild binaries seems to be missing from  this url : [https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.5.2/CPU-windows-1.5.2.zip](https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/1.5.2/CPU-windows-1.5.2.zip)

![image](https://user-images.githubusercontent.com/31354864/74586860-26cbfb80-4fec-11ea-8217-97d3a4947620.png)

i am doing something wrong , if so a little help would be appreciated

**Comment by rthadur** [comment]
@TheHidden1 thanks for reporting , please follow the similar issue [here](https://github.com/tensorflow/tfjs/issues/2428) , could you please let us know what version of tfjs-node-gpu you are using ?

**Comment by yhwang** [comment]
@TheHidden1 one thing is worth mentioning that:
You can make sure if you install the prerequisites that are listed here: https://github.com/nodejs/node-gyp#on-windows

Seems there is no pre-build node binding of version 1.5.2 for your platform. However, if you fulfill the prerequisites in the link above, you should be able to build the binding in your machine while doing the npm/yarn install.
