### ISSUE TITLE
Loading saved model with optimizer.

### ISSUE THREAD

**Issue by Linkyz** [tensorflow/tfjs#2961]
_#### TensorFlow.js version
@tensorflow/tfjs-node": "^1.3.2"
Node 13.8.0
#### Describe the problem or feature request

```
UnhandledPromiseRejectionWarning: Error: Unknown metric meanAbsolutePercentageError
    at new ValueError (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\errors.js:68:28)
    at Object.get (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\metrics.js:126:15)
    at _loop_2 (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:646:52)
    at handleMetrics (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:662:25)
    at _loop_1 (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:665:17)
    at D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:668:17
    at Object.nameScope (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\common.js:41:19)
    at LayersModel.compile (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:586:18)
    at LayersModel.loadTrainingConfig (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\engine\training.js:1592:14)
    at D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\models.js:291:31
    at step (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\models.js:54:23)
    at Object.next (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\models.js:35:53)
    at fulfilled (D:\Dev\AI\AITraining\node_modules\@tensorflow\tfjs-layers\dist\models.js:26:58)

```

#### Code to reproduce the bug / link to feature request

```
 model.save(path,{includeOptimizer:true});
 tf.loadLayersModel('file://'+directoryPath)

```
Hello,
I'm currently having issues when I try to load a saved model with his optimizer.
Saved metrics seems to not be recognized by the loader.
The training works well, I can save and load the model without the optimizer.
I'm just using Mean Absolute Percentage Error as metrics.
I'm using this : tf.metrics.meanAbsolutePercentageError._
Thanks

**Comment by kangyizhang** [comment]
hi @Linkyz 

where did you get this model?

**Comment by Linkyz** [comment]
I made this model myself.
I train it then I save it.
I can't load the model when I save it with the optimizer.
