### ISSUE TITLE
Error while converting tensorflow frozen model 

### ISSUE THREAD

**Issue by Giorat** [tensorflow/tfjs#306]
#### TensorFlow.js version
tensorflow/tfjs-converter
version:  0.3.1

#### Describe the problem or feature request
Running this command when trying to convert a Tensorflow model PB
> tensorflowjs_converter --input_format=tf_frozen_model --saved_model_tags=serve ./model.pb  ./js/

I get this error 
 `c:\users\giora\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From c:\users\giora\anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "c:\users\giora\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\giora\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\giora\Anaconda3\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "c:\users\giora\anaconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 237, in main
    FLAGS.output_path, quantization_dtype=quantization_dtype)
  File "c:\users\giora\anaconda3\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion.py", line 288, in convert_tf_frozen_model
    graph = load_graph(frozen_model_path, output_node_names)
  File "c:\users\giora\anaconda3\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion.py", line 65, in load_graph
    for node in output_node_names.split(','):
AttributeError: 'NoneType' object has no attribute 'split'
`

#### Code to reproduce the bug / link to feature request
I made it using customvision.ai.
You can download this model from here: https://www.dropbox.com/s/bb7n78hq5owyjr0/tf_model_pb.zip?dl=0

Then try converting it using tfjs-converter from here: https://github.com/tensorflow/tfjs-converter/

**Comment by bileschi** [comment]
I suspect the issue is that the --outut_node_names needs to be set ... investigating

**Comment by Giorat** [comment]
How can I know what should be the --output_node_names value? Is it find-able with the pb file?

I used [this notebook to test the pb file](https://colab.research.google.com/drive/1RVjA23q9WJHEHd9yh8ljoK-nNjOv3sk1) and used 'loss:0' as output_layer but using it as --output_node_names  give others errors.

> ValueError: Name "'loss:0'" appears to refer to a Tensor, not a Operation.

**Comment by bileschi** [comment]
Typically I would use `saved_model_cli`
https://www.tensorflow.org/versions/r1.2/programmers_guide/saved_model_cli

I wonder if the artifact produced from customvision.ai isn't technically a saved_model?

**Comment by bileschi** [comment]
Can you try modifying your colab to export a `SavedModel`?
https://www.tensorflow.org/programmers_guide/saved_model

**Comment by EddieOne** [comment]
output_node_names is the same as final_tensor_name when training. Usually, `final_result` by default.

**Comment by Giorat** [comment]
How can I convert a pb file to SavedModel @bileschi ?

**Comment by EddieOne** [comment]
In most cases, a pb file is a frozen SavedModel. It needs to be optimized for inference before converting though. The [first few steps here](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2/#0) will get you a model ready for tfjs-converter. Note the `:0` part of the tensor name will not work.

**Comment by bileschi** [comment]
I'm not sure you can convert your current artifact to SavedModel.  I suspect you need to generate a SavedModel directly using the API in that link.  Does the `simple_save` API, described here, work for you?
https://www.tensorflow.org/programmers_guide/saved_model

**Comment by Giorat** [comment]
I managed to convert this PB model to TFJS format. I found out the correct operation and node names with 

`print(tf.contrib.graph_editor.get_tensors(tf.get_default_graph()))
 print(sess.graph.get_operations())`

then optimize the graph and reduce complexity 
`
python -m tensorflow.python.tools.optimize_for_inference --input=model.pb --output=optimized_graph.pb --input_names="Placeholder" --output_names="loss"
`

finally export to web format
`
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='loss' --saved_model_tags=serve ./optimized_graph.pb  ./js
`

**Comment by tmk1991** [comment]
@Giorat  - Where did you put those print lines?

**Comment by Giorat** [comment]
@tmk1991 I should have used them in this notebook trying to convert the pb model.

https://github.com/Giorat/pocketbotanist/blob/master/python/tensorflow_pb_to_tfjs_webformat.ipynb

All the comments should help you achieve it.

**Comment by gope153** [comment]
Can someone assist me? I try to find out which the correct output node names are since 1 week now. I printed them of many models a dozen time, but i can't figure out which the correct one is. I tried with faster rcnn inception v2 and ssd mobilenet v2 and my own trained models. But there are many many nodes. How do i find the correct one? I tried to work with Placeholder and loss as well as in the description above but no success. Also tried tutorials of tensorflow. Maybe im just missing a simple point, can someone point it out?
