### ISSUE TITLE
Project fails to start with tfjs-node or tfjs-node-gpu but runs okay with tfjs

### ISSUE THREAD

**Issue by adi-dev** [tensorflow/tfjs#3103]
I managed to install globally tfjs-node and tfjs-node-gpu (python 2.7.11 and vs2017 15.9.22 after finding out this is required prior installation). There was no error or messages during installation. When I try to use it in my project as `const tf = require('@tensorflow/tfjs-node');` or `const tf = require('@tensorflow/tfjs-node-gpu');` it throws following error:
```
internal/modules/cjs/loader.js:1197
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\adam\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1197:18)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\adam\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
```
When I use standard library `const tf = require('@tensorflow/tfjs'); everything works fine.
My setup is:
Windows 10
node.js v13.12.0
npm 6.14.4
tfjs 1.7.2
tfjs-node 1.7.2

**Comment by rthadur** [comment]
@adi-dev you should use only tfjs-node which ships with tfjs. please [refer](https://github.com/tensorflow/tfjs/issues/2536#issuecomment-564662827)

**Comment by adi-dev** [comment]
Sorry, if I duplicate the response, I did this in #2536 by mistake:
I have removed all @tensorflow modules and installed only npm install -g @tensorflow/tfjs-node (and tried -gpu too) but still the same error.
