### ISSUE TITLE
How to fix this error i want to run my bot by node .

### ISSUE THREAD

**Issue by tirthg** [tensorflow/tfjs#3170]
Error: Unknown option:
    at Object.<anonymous> (C:\Users\tng19\Desktop\modmailbot-master\src\config.js:181:11)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\tng19\Desktop\modmailbot-master\src\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)

**Comment by BayanBennett** [comment]
Hi Tirth,

It might be helpful to have some additional information, like code from `modmailbot-master`

Here's the TFJS issue template: https://github.com/tensorflow/tfjs/blob/master/ISSUE_TEMPLATE.md

—Bayan[‌](https://bayanbennett.com)

**Comment by tirthg** [comment]
> Hi Tirth,
> 
> It might be helpful to have some additional information, like code from `modmailbot-master`
> 
> Here's the TFJS issue template: https://github.com/tensorflow/tfjs/blob/master/ISSUE_TEMPLATE.md
> 
> —Bayan[‌](https://bayanbennett.com)

Thanks
