### ISSUE TITLE
Add ability to ignore NaN tests on Node.js backend with CUDA

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#321]
By default, CUDA will set NaNs to 0 (or near zero). We need the ability to either:

a.) handle NaNs differently
b.) Add the ability to turn those off for when CUDA is running:

Output:
```
Failures:
1) relu {"BACKEND":"tensorflow"} propagates NaNs, float32
  Message:
    Error: Arrays differ: actual[5] = 0, expected[5] = NaN.
    Actual:   1,0,0,3,0,0.
    Expected: 1,0,0,3,0,NaN.
  Stack:
    Error: Arrays differ: actual[5] = 0, expected[5] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/test_util.js:57:19)
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/ops/unary_ops_test.js:33:21)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)

2) debug off {"BACKEND":"tensorflow"} no errors where there are nans, and debug mode is disabled
  Message:
    Error: Arrays differ: actual[1] = 0, expected[1] = NaN.
    Actual:   2,0.
    Expected: 2,NaN.
  Stack:
    Error: Arrays differ: actual[1] = 0, expected[1] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/test_util.js:57:19)
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/debug_mode_test.js:38:21)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)

3) debug on {"BACKEND":"tensorflow"} debug mode errors when there are nans, float32
  Message:
    Expected function to throw an Error.
  Stack:
    Error: Expected function to throw an Error.
        at <Jasmine>
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/debug_mode_test.js:21:19)
        at <Jasmine>

4) clip {"BACKEND":"tensorflow"} propagates NaNs
  Message:
    Error: Arrays differ: actual[6] = 50, expected[6] = NaN.
    Actual:   3,-1,0,50,-1,2,50.
    Expected: 3,-1,0,50,-1,2,NaN.
  Stack:
    Error: Arrays differ: actual[6] = 50, expected[6] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/test_util.js:57:19)
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/ops/unary_ops_test.js:1543:21)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)

5) minimum {"BACKEND":"tensorflow"} propagates NaN
  Message:
    Error: Arrays differ: actual[2] = 0.25, expected[2] = NaN.
    Actual:   0.20000000298023224,-0.10000000149011612,0.25.
    Expected: 0.2,-0.1,NaN.
  Stack:
    Error: Arrays differ: actual[2] = 0.25, expected[2] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/test_util.js:57:19)
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:312:21)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)

6) maximum {"BACKEND":"tensorflow"} propagates NaN
  Message:
    Error: Arrays differ: actual[2] = 0.25, expected[2] = NaN.
    Actual:   0.5,0.30000001192092896,0.25.
    Expected: 0.5,0.3,NaN.
  Stack:
    Error: Arrays differ: actual[2] = 0.25, expected[2] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/test_util.js:57:19)
        at UserContext.<anonymous> (/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:66:21)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
```

**Comment by dsmilkov** [comment]
We are leaning towards option 2), by introducing an environment flag so users can do `ENV.set('NAN_PROPAGATION', false)`. On the nodejs side, you can turn this to off, and we can make sure those tests don't run when that env flag is off.
