### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by xnerhu** [tensorflow/tfjs#3231]
#### Describe the problem or feature request

Can't run the app, because of the TensorFlow error. 

```bash
Error: The specified module could not be found.
\\?\C:\Users\xnerhu\app\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1197:18)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\xnerhu\app\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\xnerhu\app\node_modules\ts-node\src\index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:996:32)
```

I ran `node-gyp rebuild` as I saw in similar issues.

```bash
cd node_modules/@tensorflow/tfjs-node-gpu
node-gyp rebuild
```

And I got

```bash
...
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\xnerhu\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xnerhu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

I also tried updating npm and node-gyp, but it didin't work.

#### Code to reproduce the bug / link to feature request
```ts
import * as tf from '@tensorflow/tfjs-node-gpu';

function init() {
  tf.tensor([1, 2, 3, 4]).print();
}

init();
```

#### System details
- Nvidia Cuda 10.1
- Nvidia Cudnn 10.2 7.6.5.32
- Nvidia Graphics Driver 445.87
- Node.js 13.11.0
- Python 2.7.15 (also 3.8 installed, but 2.7 is the default one)
- Visual Studio 2019
- Windows 10 x64 (v1909)

**Comment by rthadur** [comment]
Did you had only tfjs-node-gpu installed or tfjs as well ?

**Comment by yorkie** [comment]
@xnerhu tfjs is using [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) to build its add-ons.

> gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp

This is because node-pre-gyp will read the package.json [`binary`](https://github.com/tensorflow/tfjs/blob/4faed8a04c4e203966365a5c6158feceebd70160/tfjs-node/package.json#L61) and set to binding.gyp, I think you could follow the following script to address what you occurred:
https://github.com/tensorflow/tfjs/blob/4faed8a04c4e203966365a5c6158feceebd70160/tfjs-node/scripts/install.js#L188-L200.

**Comment by xnerhu** [comment]
@rthadur Only `tfjs-node-gpu`.

**Comment by kangyizhang** [comment]
can you run `npm rebuild @tensorflow/tfjs-node build-addon-from-source` in your repo and try again?

**Comment by xnerhu** [comment]
> can you run `npm rebuild @tensorflow/tfjs-node build-addon-from-source` in your repo and try again?

```bash
npm rebuild @tensorflow/tfjs-node-gpu build-addon-from-source

> @tensorflow/tfjs-node-gpu@1.7.4 install C:\Users\xnerhu\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

GPU-windows-1.7.4.zip
* Downloading libtensorflow
[==============================] 2661045/bps 100% 0.0s
* Building TensorFlow Node.js bindings
@tensorflow/tfjs-node-gpu@1.7.4 C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu
```

Still doens't work.

**Comment by xnerhu** [comment]
@yorkie It's weird, because if `node-pre-gyp` failed it should have printed errors.

**Comment by xnerhu** [comment]
I moved to Node v14, updated node-gyp, node-pre-gyp and the error occurs.

**Comment by xnerhu** [comment]
I modified `tfjs/tfjs-node-gpu/scripts/install.js`.

```js
  cp.exec(`node-pre-gyp install ${buildOption}`, (err) => {
    if (err) {
      console.log('node-pre-gyp install failed with error: ' + err);
    }
    if (platform === 'win32') {
      // Move libtensorflow to module path, where tfjs_binding.node locates.
      cp.exec('node --trace-warnings scripts/deps-stage.js symlink ' + modulePath, (err, stdout,  stderr) => {
        if (err) console.log(`Err: ${err}`);
        
        console.log(`\n\nStdout: ${stdout}`);
        console.log(`\n\nStderr: ${stderr}`);
      });
    }
    revertAddonName(origBinary);
  });
```

And it outputs:

```bash
> @tensorflow/tfjs-node-gpu@1.7.4 install C:\Users\xnerhu\Desktop\machine learning\ai\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

GPU-windows-1.7.4.zip
* Downloading libtensorflow
[==============================] 2440407/bps 100% 0.0s
* Building TensorFlow Node.js bindings


Stdout:


Stderr:   * Symlink of lib\napi-v6\tensorflow.dll failed, creating a copy on disk.
(node:17112) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu\deps\lib\tensorflow.dll' -> 'C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tensorflow.dll'
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:17112) Error: ENOENT: no such file or directory, copyfile 'C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu\deps\lib\tensorflow.dll' -> 'C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tensorflow.dll'
(node:17112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)

@tensorflow/tfjs-node-gpu@1.7.4 C:\Users\xnerhu\Desktop\machine learning\test\node_modules\@tensorflow\tfjs-node-gpu
```

**Comment by yorkie** [comment]
`ls -la deps/lib` to list the libraries on your machine?

**Comment by xnerhu** [comment]
```bash
 Directory: C:\Users\xnerhu\Desktop\machine
    learning\test\node_modules\@tensorflow\tfjs-node-gpu\deps\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/14/2019  10:23 PM      879201792 tensorflow.dll
-a----       10/14/2019  10:23 PM       47064458 tensorflow.lib
```

**Comment by yorkie** [comment]
@xnerhu Maybe `node-pre-gyp install --verbose --build-from-source` will give more debug info :)

**Comment by xnerhu** [comment]
I downgraded Node to 12 and it works. It's related with #3236.

**Comment by kangyizhang** [comment]
The error is because of new node NAPI version 6. I have created https://github.com/tensorflow/tfjs/pull/3242 to fix this. Please use node version before 14 for now. The library will support latest node version in the next release.

**Comment by davidkhanpk** [comment]
I am getting this error on server start
"@tensorflow/tfjs": "^2.6.0",
"@tensorflow/tfjs-node": "^2.6.0",
nose_verion:  12.19.0 

`internal/modules/cjs/loader.js:1065
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\..\node_modules\@tensorflow\tfjs-node\lib\napi-v6\tfjs_binding.node`

**Comment by MahdiNicoo** [comment]
Installing nodejs version 12.16 solved the problem

**Comment by Floffah** [comment]
this issue seems to have came back up in node 15
