### ISSUE TITLE
Error: The specified module could not be found. \\?\D:\dawood\webcam\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node

### ISSUE THREAD

**Issue by Dawoodriaz** [tensorflow/tfjs#3309]
i am getting this error when i run my node command 

i have installed on my computer

 

1. Visual Studio 2019 
2.  Node v14.3.0  
3.  npm 6.14.5
4.  windows 10

Steps i have done 

Create empty folder

`npm init` inside the folder

 1. `npm install --save @tensorflow/tfjs-node`

 2. `npm install --save @tensorflow/tfjs-core`

 3. `npm install --save @tensorflow/tfjs-converter`

 4. `npm install --save @tensorflow-models/handpose`

created a `index.js` file

tried to run node `index.js`

getting this error

```
Error: The specified module could not be found.
\\?\D:\dawood\webcam\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\dawood\webcam\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
```

this is my package.json file
```
{
  "name": "webcam",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow-models/handpose": "0.0.4",
    "@tensorflow/tfjs-converter": "^1.7.4",
    "@tensorflow/tfjs-core": "^1.7.4",
    "@tensorflow/tfjs-node": "^1.7.4",
    "bufferutil": "^4.0.1",
    "canvas": "^2.6.1",
    "express": "^4.17.1",
    "glob": "^7.1.6",
    "mimic-response": "^2.1.0",
    "opencv4nodejs": "^5.6.0",
    "socket.io": "^2.3.0",
    "utf-8-validate": "^5.0.2"
  }
}
```

**Comment by TheNewSound** [comment]
Node V14 is supported in the NEXT version of tfjs, for now use V12.
