### ISSUE TITLE
blazeface demo crashes if one selects a different backend and then returns to wasm

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tfjs#3433]
Visit https://storage.googleapis.com/tfjs-models/demos/blazeface/index.html
Select webgl
Select wasm

tfjs-backend-wasm.js:8 Uncaught (in promise) RuntimeError: abort(LinkError: WebAssembly.instantiate(): table import 8 is smaller than initial 112, got 105). Build with -s ASSERTIONS=1 for more info.
    at oe (https://storage.googleapis.com/tfjs-models/demos/blazeface/demo.2ed3f5d8.js:26966:133)
    at https://storage.googleapis.com/tfjs-models/demos/blazeface/demo.2ed3f5d8.js:27020:61

Version 83.0.4103.97 (Official Build) (64-bit) on Windows 10 Pro

**Comment by rthadur** [comment]
I guess this the error which is happening 

`Uncaught (in promise) Error: Backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
    at t.get [as backend] (engine.ts:173)
    at t.makeTensor (engine.ts:636)
    at Nn (tensor_ops.ts:113)
    at On (tensor_ops.ts:213)
    at blazeface.esm.js:17
    at engine.ts:424
    at t.scopedRun (engine.ts:435)
    at t.tidy (engine.ts:422)
    at Qe (globals.ts:182)
    at BlazeFaceModel.getBoundingBoxes (blazeface.esm.js:17)`

**Comment by AlexanderKozhevin** [comment]
@rthadur No, it's not helping
tf.ready().then(()=>{
      tf.setBackend('wasm').then(() => {
        console.log('done');
      });
    })

**Comment by teddybee** [comment]
I had similar issue, when I tried to use webassembly as a backend.
The error:
`Unhandled Rejection (RuntimeError): abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info`

**Comment by rthadur** [comment]
Related PR for wasm support has been merged and also blazeface is deprecated in favour of face-detection model  https://github.com/tensorflow/tfjs-models/tree/master/face-detection , Thank you
