### ISSUE TITLE
tensorflowjs_wizard fails when loading model.js due to UnicodeDecodeError

### ISSUE THREAD

**Issue by danhaus** [tensorflow/tfjs#3477]
#### TensorFlow.js version
1.7.2

#### TensorFlow version
2.1.0

#### OS
macOS Catalina 10.15.5

#### Steps to reproduce
Download this model https://tfhub.dev/tensorflow/tfjs-model/posenet/resnet50/float/1/default/1
Open the downloaded folder and rename `model-stride32.json` to `model.json`
Move back to the parent folder and run `tensorflowjs_wizard`
Input the model path (`./posenet_resnet50_float_1_default_1`)
You will see similar error to this:
```(tfjs-graph-converter) daniel@MacBook-Pro tf-converter % tensorflowjs_wizard
Welcome to TensorFlow.js Converter.
? Please provide the path of model file or the directory that contains model files. 
If you are converting TFHub module please provide the URL.  ./posenet_resnet50_float_1_default_1
Traceback (most recent call last):
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/bin/tensorflowjs_wizard", line 8, in <module>
    sys.exit(pip_main())
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/site-packages/tensorflowjs/converters/wizard.py", line 590, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/site-packages/tensorflowjs/converters/wizard.py", line 598, in main
    run(dry_run)
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/site-packages/tensorflowjs/converters/wizard.py", line 410, in run
    input_params[common.INPUT_PATH])
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/site-packages/tensorflowjs/converters/wizard.py", line 107, in detect_input_format
    if get_tfjs_model_type(filename) == common.TFJS_LAYERS_MODEL_FORMAT:
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/site-packages/tensorflowjs/converters/wizard.py", line 67, in get_tfjs_model_type
    data = json.load(f)
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/daniel/anaconda3/envs/tfjs-graph-converter/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I want to convert the aforementioned tfjs model into tflite. As I cannot find any direct solution, I first try to convert the tfjs model into `keras_saved_model` with the steps described above. Then I'd like to convert that keras model into tflite with the [TensforFlow Lite converter](https://www.tensorflow.org/lite/convert).

Many thanks for any help!

**Comment by startupgurukul** [comment]
Not a solution for issue submitted but i imagine  the original need was for a posenet resnet tflite model, there are few here, https://github.com/google-coral/project-posenet/tree/master/models/resnet

**Comment by danhaus** [comment]
Thanks @startupgurukul! Yes, that looks like what we need!

**Comment by pyu10055** [comment]
@startupgurukul looks like you have found a solution. For the original issue, seems the model file is corrupted. Also posenet model is graph model and it cannot be converted back to saved model.

**Comment by danhaus** [comment]
> @startupgurukul looks like you have found a solution. For the original issue, seems the model file is corrupted. Also posenet model is graph model and it cannot be converted back to saved model.

Actually, we did not manage to use the Google Coral models, as they seem to require special hardware to run. Thanks for your input @pyu10055
