### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization LSTMBlockCell

### ISSUE THREAD

**Issue by INotWant** [tensorflow/tfjs#3496]
#### Describe the problem
Hi

I'm trying to convert a **tf_saved_model** using `tensorflowjs_converter` but I got this error:
```
Traceback (most recent call last):
  File "/Users/tinggao/env_py/tensorflowjs/bin/tensorflowjs_converter", line 10, in <module>
    sys.exit(pip_main())
  File "/Users/tinggao/env_py/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 735, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/Users/tinggao/env_py/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 739, in main
    convert(argv[0].split(' '))
  File "/Users/tinggao/env_py/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 681, in convert
    control_flow_v2=args.control_flow_v2)
  File "/Users/tinggao/env_py/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 494, in convert_tf_saved_model
    weight_shard_size_bytes=weight_shard_size_bytes)
  File "/Users/tinggao/env_py/tensorflowjs/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 143, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
LSTMBlockCell
```
this mean that `tensorflow.contrib.rnn.LSTMBlockCell` can't be supported?

#### TensorFlow.js version
```
tensorflowjs 2.0.1

Dependency versions:
  keras 2.3.0-tf
  tensorflow 2.2.0
```

**Comment by rthadur** [comment]
@INotWant yes above op is a custom op which is not supported in tfjs. 
cc @pyu10055
