### ISSUE TITLE
Tried to download(404): pre-built-binary/napi-v6/2.0.1/CPU-linux-2.0.1.tar.gz

### ISSUE THREAD

**Issue by cespon** [tensorflow/tfjs#3622]
### Software version

**TensorFlow.js**: `@tensorflow/tfjs-node@2.0.1`
**Ubuntu Server**: `20.04`
**Node**: `v14.5.0`

### Description of the problem

I tried to run a very simple app without success. This app uses `@tensorflow/tfjs-node@2.0.1` and I'm triying to execute it in a VPS with Ubuntu Server installed.

When I execute the app:

```
$ node app.js
Overriding the gradient for 'Max'
Overriding the gradient for 'OneHot'
Overriding the gradient for 'PadV2'
Overriding the gradient for 'SpaceToBatchND'
Overriding the gradient for 'SplitV'
/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/dist/index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not "
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/ubuntu/tensorflow-test-node-basic/app.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
```

After the execution of `npm rebuild @tensorflow/tfjs-node build-addon-from-source` I got this:

```
$ npm rebuild @tensorflow/tfjs-node build-addon-from-source

> @tensorflow/tfjs-node@2.0.1 install /home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-2.0.1.tar.gz
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/CPU-linux-2.0.1.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.0.1 and node@14.5.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:176:21)
gyp ERR! System Linux 5.4.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/lib/napi-v6" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/tensorflow-test-node-basic/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.0-29-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/tensorflow-test-node-basic/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/tensorflow-test-node-basic/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v14.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
```

One of the lines says that it couldn't be found  `https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/CPU-linux-2.0.1.tar.gz`. How can I build TensorFlow Node.js bindings?

### Code to reproduce the bug

The folder `/home/ubuntu/tensorflow-test-node-basic` has only two files and the `node_modules` folder created after `npm install` execution.

#### `package.json`
```
{
  "name": "tensorflow-test",
  "version": "1.0.0",
  "main": "app.js",
  "dependencies": {
    "@tensorflow/tfjs-node": "^2.0.1"
  }
}
```

#### `app.js`
```
const tensorflow = require('@tensorflow/tfjs-node')
```

**Comment by rthadur** [comment]
@cespon please check related issue here [https://github.com/tensorflow/tfjs/issues/3577#issuecomment-655831792](url)

**Comment by cespon** [comment]
### Solution
After several tests, I found that **the problem was that `make` and `g++` were not installed**. 

To solve that, execute:

```
sudo apt install make g++
```

### Tests details

Clean installs of modules, using other node versions or renaming paths (like removing whitespaces and special characters) didn't work. 

To find out this solution, after executing `npm install` on my working directory, I executed:

```
node-pre-gyp install --fallback-to-build
```

The output was the following:
``` 
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@12.18.2 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: tftest package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/usr/lib/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/lib/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/usr/lib/node_modules/node-pre-gyp/lib/install.js:241:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/usr/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1138:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:986:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
node-pre-gyp ERR! System Linux 5.4.0-29-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/tftest
node-pre-gyp ERR! node -v v12.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
tftest package.json is not node-pre-gyp ready:
package.json must declare these properties:
binary.module_name
binary.module_path
binary.host
```

The `package.json` was ok, so I browsed to `node_modules/@tensorflow/tfjs-node` and I executed `node-pre-gyp install --fallback-to-build` again. 

The result was:
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@12.18.2 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp http 404 https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.0.1 and node@12.18.2 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.cache/node-gyp/12.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/12.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/12.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:10:17)
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:54:21)
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:69:33)
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:80:22
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.4.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.4.0-29-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v12.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
```

There is a line that says `gyp ERR! stack Error: not found: make`, so I cheked if `make` was installed executing:

```
make 
```

The output was:

```
Command 'make' not found, but can be installed with:

sudo apt install make        # version 4.2.1-1.2, or
sudo apt install make-guile  # version 4.2.1-1.2
```

So I installed it: 

```
sudo apt install make
```

After that, I executed `node-pre-gyp install --fallback-to-build` again. Now the output was:

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@12.18.2 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp http 404 https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.0.1 and node@12.18.2 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v6/2.0.1/tfjs_binding-v2.0.1-node-v72-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.cache/node-gyp/12.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/12.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/12.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/build'
  CXX(target) Release/obj.target/tfjs_binding/binding/tfjs_backend.o
make: g++: Command not found
make: *** [tfjs_binding.target.mk:114: Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 127
make: Leaving directory '/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.4.0-29-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v12.18.2
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/ubuntu/tftest/node_modules/@tensorflow/tfjs-node/lib/napi-v6 --napi_version=6 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
```

Now the error message is different: `make: g++: Command not found`. So, I installed `g++`:

```
sudo apt install g++
```

After that, I executed `npm install` inside `node_modules/@tensorflow/tfjs-node` and everything gone ok.
