### ISSUE TITLE
webgpu: engine().findBackend('cpu') is null

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#3650]
In tfjs-backend-webgpu, run "yarn test --no-single-run --grep='should not allocate GPU memory when CPU forwarding'". Below error will be shown.

FAILED webgpu backend webgpu cpu forwarding turned on test-webgpu {"WEBGPU_CPU_FORWARD":false} should not allocate GPU memory when CPU forwarding
debug.js:21 Expected 48 to equal 0.
    at <Jasmine>
    at Object.<anonymous> (http://localhost:9876/base/src/backend_webgpu_test.js:83:48)
    at step (http://localhost:9876/base/src/backend_webgpu_test.js:48:23)
    at Object.next (http://localhost:9876/base/src/backend_webgpu_test.js:29:53)
    at http://localhost:9876/base/src/backend_webgpu_test.js:23:71
    at <Jasmine>
    at __awaiter (http://localhost:9876/base/src/backend_webgpu_test.js:19:12)
    at UserContext.<anonymous> (http://localhost:9876/base/src/backend_webgpu_test.js:68:84)
    at <Jasmine>
(anonymous) @ debug.js:21
debug.js:21 Expected 24 to equal 40.
    at <Jasmine>
    at Object.<anonymous> (http://localhost:9876/base/src/backend_webgpu_test.js:94:67)
    at step (http://localhost:9876/base/src/backend_webgpu_test.js:48:23)
    at Object.next (http://localhost:9876/base/src/backend_webgpu_test.js:29:53)
    at fulfilled (http://localhost:9876/base/src/backend_webgpu_test.js:20:58)

Above failure has been there a while. The failure reason is engine().findBackend('cpu') is null in backend_webgpu.ts. Not sure why cpu is not registered.

**Comment by qjia7** [comment]
@annxingyuan Can you take a look? Thanks.

**Comment by qjia7** [comment]
@annxingyuan It seems that the cpu backend is still null in my device. Ann, can you reproduce the failure in your side?

**Comment by annxingyuan** [comment]
@qjia7 ah sorry - I think this is the actual fix https://github.com/tensorflow/tfjs/pull/3699
