### ISSUE TITLE
Error during conversion of .h5 model with h5py._hl.dataset.Dataset (MobileBERT)

### ISSUE THREAD

**Issue by AIshutin** [tensorflow/tfjs#3656]
## TensorFlow.js version
2.2.0

#### Describe the problem or feature request

Conversion of MobileBERT from huggingface`s transformers fails with the following error. It seems that it's due to lack of support of h5py._hl.dataset.Dataset in .h5 file. 

```python3
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 735, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 739, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 654, in convert
    weight_shard_size_bytes=weight_shard_size_bytes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 84, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    h5_file, split_by_layer=split_weights_by_layer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 241, in h5_weights_to_tfjs_format
    group = _convert_h5_group(layer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 85, in _convert_h5_group
    group_out += _convert_h5_group(group[key])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 85, in _convert_h5_group
    group_out += _convert_h5_group(group[key])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 85, in _convert_h5_group
    group_out += _convert_h5_group(group[key])
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 83, in _convert_h5_group
    for key in group.keys():
AttributeError: 'Dataset' object has no attribute 'keys'
```

#### Code to reproduce the bug / link to feature request
Make model using huggingface
```python3
from transformers import TFAutoModel
model = TFAutoModel.from_pretrained('google/mobilebert-uncased')
print(model.summary())
model.save_pretrained('model')
```

```bash
tensorflowjs_converter --input_format keras \
                       model/tf_model.h5 \
                       tfjs_target_dir
```

Excuse me, if it's not a bug, but my fault in incorrect usage.

**Comment by rthadur** [comment]
@AIshutin did you try this existing model for MobileBERT [here](https://www.npmjs.com/package/@tensorflow-models/qna)

**Comment by AIshutin** [comment]
Yes, but I need to modify the model a lot. It's easier for me to do this in PyTorch using transformers. But first, I need to convert the original model successfully. Thanks for your fast response.

**Comment by rthadur** [comment]
@AIshutin we don't support the dataset layer in HDF5, thats the reason you are seeing above error.There is no plan in near future to support this.
cc @pyu10055

**Comment by zaidalyafeai** [comment]
I am also interested to convert MobileBERT to tfjs. Is there an easy way to do it ? How was the question answering model converted ?

**Comment by zaidalyafeai** [comment]
I tried to convert the tf hub version 

``` console
tensorflowjs_converter \
    --input_format=tf_hub \
    'https://tfhub.dev/tensorflow/tfjs-model/mobilebert/1' \
    web_model/
```

but I get the following error 
```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 735, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 739, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 692, in convert
    control_flow_v2=args.control_flow_v2)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 639, in convert_tf_hub_module
    module_path = hub.resolve(module_handle)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/module_v2.py", line 52, in resolve
    return registry.resolver(handle)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/compressed_module_resolver.py", line 88, in __call__
    self._lock_file_timeout_sec())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/resolver.py", line 402, in atomic_download
    download_fn(handle, tmp_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/compressed_module_resolver.py", line 83, in download
    response = self._call_urlopen(request)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_hub/compressed_module_resolver.py", line 96, in _call_urlopen
    return url.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by zaidalyafeai** [comment]
Can you help with this @annxingyuan ? What is the convert script you used and do we need to make any changes for the conversion.

**Comment by gaikwadrahul8** [comment]
Hi, @AIshutin 

Apologize for the delayed response and I see we have updated official documentation w.r.t tfjs-converter please refer this [link](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) and I would suggest you to please give it try with latest version.

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFJs team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TFJs [version](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.10.0) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tfjs/blob/master/README.md) to stay up to date with the latest developments which are happening in the Tensorflow.js space.

Thank you for your support and cooperation.
