### ISSUE TITLE
 Tensor.clipByValue does not work for  tensors of dtype int32 in Node backend

### ISSUE THREAD

**Issue by arcman7** [tensorflow/tfjs#3716]
TensorFlow.js version 2.0.1

node version 12.13.0

backend: `"tensorflow"`

OS: Windows 10

Issue: Tensor.clipByValue does not work for  tensors of dtype `int32`.

 Code to reproduce issue:
```
const x = tf.tensor([-1, 2, -3, 4], undefined, 'int32');
x.clipByValue(-2, 4).print();
```
This throws an error with the stack trace:
```
Thrown:
Error: Invalid TF_Status: 3
Message: cannot compute Minimum as input #1(zero-based) was expected to be a int32 tensor but is a float tensor
    at NodeJSKernelBackend.executeSingleOutput (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:192:43)
    at NodeJSKernelBackend.minimum (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:558:21)
    at NodeJSKernelBackend.clip (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:636:25)
    at ENGINE.runKernelFunc.x (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:6882:27)
    at C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3229:55
    at C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3075:22
    at Engine.scopedRun (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3085:23)
    at Engine.tidy (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3074:21)
    at kernelFunc (C:\Users\Ryan\projects\pysc2\node_modules\@tensorflow\tfjs-node\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3229:29)
```

Please note that it appears to work just fine in the browser using the `webgl` backend.

**Comment by arcman7** [comment]
I'm not sure exactly where the issue is in the code base, but just writing this helper method get's me around the issue for now-
```
function clipByValue(x, min, max) {
  return x.where(x.greaterEqual(min)
    .logicalAnd(x.lessEqual(max)), tf.zerosLike(x))
}
```
