### ISSUE TITLE
npm i @tensorflow/tfjs-node fails

### ISSUE THREAD

**Issue by jonaslund** [tensorflow/tfjs#3736]
@tensorflow/tfjs-node: "^2.0.1",
node v13.11.0
python 2.7

```.
$  npm i @tensorflow/tfjs-node

> @tensorflow/tfjs-node@1.7.4 install /path/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-darwin-1.7.4.tar.gz
* Downloading libtensorflow
[==============================] 14665814/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v5/1.7.4/CPU-darwin-1.7.4.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@1.7.4 and node@13.11.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
Traceback (most recent call last):
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 100, in Load
    generator = __import__(generator_name, globals(), locals(), generator_name)
  File ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 36, in <module>
    import hashlib
  File ".pyenv/versions/2.7/lib/python2.7/hashlib.py", line 136, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File ".pyenv/versions/2.7/lib/python2.7/hashlib.py", line 71, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command ".nvm/versions/node/v13.11.0/bin/node" ".nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/path/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/path/node_modules/@tensorflow/tfjs-node/lib/napi-v5" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=5" "--node_napi_label=napi-v5"
gyp ERR! cwd /path/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '.nvm/versions/node/v13.11.0/bin/node .nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/path/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node --module_name=tfjs_binding --module_path=/path/node_modules/@tensorflow/tfjs-node/lib/napi-v5 --napi_version=6 --node_abi_napi=napi --napi_build_version=5 --node_napi_label=napi-v5' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/path/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command ".nvm/versions/node/v13.11.0/bin/node" "/path/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /path/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok

npm WARN node_starter@1.0.0 No repository field.

+ @tensorflow/tfjs-node@1.7.4
updated 1 package and audited 548 packages in 12.968s

20 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by jonaslund** [comment]
Outdated and broken version of Python. Solved with re-installing python through pyenv. pyenv install 2.7.15 
Some issue with homebrew and openssl.
