### ISSUE TITLE
Issue with node

### ISSUE THREAD

**Issue by alezanott** [tensorflow/tfjs#3789]
I'm currently running node on HOOBS (on Raspberry Pi 3). I get this error when running the verbose mode:
```
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/usr/local/bin/node-gyp',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@7.1.0
gyp info using node@12.16.3 | linux | arm
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.7.3"
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 12.16.3
gyp verb command install [ '12.16.3' ]
gyp verb install input version string "12.16.3"
gyp verb install installing version: 12.16.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.16.3
gyp verb build dir attempting to create "build" dir: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/build
gyp verb build dir "build" dir needed to be created? undefined
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/config.gypi
gyp verb common.gypi checking for gypi file: /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hoobs/.cache/node-gyp/12.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hoobs/.cache/node-gyp/12.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hoobs/.cache/node-gyp/12.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "--verbose"
gyp ERR! cwd /home/hoobs/.hoobs/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v7.1.0
gyp ERR! not ok 
```
What could give this kind of error? I've got a plugin that cannot register since it doesn't have the correct node bindings.

**Comment by rthadur** [comment]
@alezanott please check for a similar issue [here](https://github.com/tensorflow/tfjs/issues/3577) , thank you.
