### ISSUE TITLE
model.detect method on Object Detection model throws TypeError: Cannot read property 'read' of undefined

### ISSUE THREAD

**Issue by veejayts** [tensorflow/tfjs#3790]
#### TensorFlow.js version in Node
"dependencies": {
    "@tensorflow/tfjs-automl": "^1.0.0",
    "@tensorflow/tfjs-node": "^2.1.0"
  }

#### The problem
The model is loaded for the tfjs model exported from GCP AutoML. But when the image is fed for detection, it doesn't work. It throws the following error. It throws the error when it hits model.detect(image).

```
TypeError: Cannot read property 'read' of undefined
    at C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:4680:60
    at step (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:77:23)
    at Object.next (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:58:53)
    at C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:51:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:47:12)
    at executeOp$2 (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:4498:64)
    at C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:5729:24
    at executeOp$g (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:5769:7)
    at _loop_1 (C:\Users\tim\Desktop\timo\Projects\Website\co\decode\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:6477:31)
```

#### Code to reproduce the bug
```
const tf = require("@tensorflow/tfjs-node");
const automl = require("@tensorflow/tfjs-automl");
const fs = require("fs");

const model_url = "http://localhost:5000/api/model.json";
const image_path = process.argv.slice(2)[0];

if (!image_path) {
    throw new Error("missing argument: path to image");
}

const image = fs.readFileSync(image_path);
const decoded_image = tf.node.decodeJpeg(image);

async function run() {
    const model = await automl.loadObjectDetection(model_url);
    console.log(model);
    const predictions = await model.detect(decoded_image);
    console.log(predictions);
}
run().catch(console.error);
```

Ran it in the console using this command: `node predict.js ./image.jpg` where `predict.js` is the name of file containing the above code. 

In fact, the official example present at https://github.com/tensorflow/tfjs/tree/master/tfjs-automl/demo/object_detection doesn't work either. It threw a backend not present error which was resolved by importing the `@tensorflow/tfjs-backend-webgl` package. But immediately the above mentioned error was thrown.

The official example by Google over at https://cloud.google.com/vision/automl/object-detection/docs/tensorflow-js-tutorial  doesn't work either, even after fixing the CDN links.

Tried using the following pre-trained model as well but encountered the same error: https://storage.googleapis.com/tfjs-testing/tfjs-automl/object_detection/model.json

**Comment by veejayts** [comment]
Setting the version of "@tensorflow/tfjs-node": "2.0.0" fixed it for me
