### ISSUE TITLE
loadLayersModel: ValueError: If the strides property of a 3D pooling layer is an Array, it is expected to have a length of 3, but received length 4

### ISSUE THREAD

**Issue by sbrl** [tensorflow/tfjs#3873]
#### TensorFlow.js version
2.3.0

#### Browser version
n/a - using Node.js v14.4.0

#### Describe the problem or feature request
When I try to load a saved model, I get the following error:

```jsstacktrace
ValueError: If the strides property of a 3D pooling layer is an Array, it is expected to have a length of 3, but received length 4.
    at new ValueError (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:176:28)
    at AveragePooling3D.Pooling3D [as constructor] (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:15365:23)
    at new AveragePooling3D (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:15440:23)
    at Serializable.fromConfig (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:22846:16)
    at deserializeKerasObject (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:469:29)
    at deserialize (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:4919:12)
    at Sequential.fromConfig (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:11067:25)
    at deserializeKerasObject (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:469:29)
    at deserialize (/home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:4919:12)
    at /home/USERNAME/Documents/repos/PhD-Code/ingester/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:10389:29
```

I am attempting to load the model like so:

```js
this.model = await this.tf.loadLayersModel(`file://${checkpoint_path}`); // checkpoint_path is set to "path/to/model.json"
```

I am saving the model like so:

```js
this.model = this.tf.sequential();

// ........

await this.model.save(checkpoint_path);
```

An example model that is causing the issue: [model.tar.gz](https://github.com/tensorflow/tfjs/files/5163520/model.tar.gz)

#### Code to reproduce the bug / link to feature request
Download the above model, then save + run this code:
```js
"use strict";

import tfjs from "@tensorflow/tfjs-node";

(async () => {
	"use strict";
	let path_to_modeljson = "/tmp/x/model/model.json";
	let model = await tfjs.loadLayersModel(`file://${path_to_modeljson}`);
	model.summary();
})();
```

**Comment by sbrl** [comment]
Is there update on this, @pyu10055? Is there anything else I can provide to assist here? This is a major issue / blocker for my PhD.

**Comment by sbrl** [comment]
Found the problem! I wasn't specifying the parameters for the pooling layers in my model correctly.
