### ISSUE TITLE
can't convert h5 file to json with tensorflowjs converter

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tfjs#3950]
I have downloaded vgg.h5 file and try to convert it. with command 

tensorflowjs_converter --input_format keras ./vgg16.h5 ./

my python version is 3.8 and I also tried 3.7.3 but it's same. tf.__version__ is 2.3.0  what maybe the problem? 
```
(base) pedrojung@pedroui-MacBookPro-2 ~ % tensorflowjs_converter --input_format keras \
                       /Users/pedrojung/vgg16.h5 \
                       ./
Traceback (most recent call last):
  File "/Users/pedrojung/opt/anaconda3/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 666, in convert
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 83, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    groups = conversion.h5_weights_to_tfjs_format(
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 233, in h5_weights_to_tfjs_format
    _check_version(h5file)
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 100, in _check_version
    keras_version = as_text(h5file.attrs['keras_version'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/pedrojung/opt/anaconda3/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'keras_version')"
```

**Comment by rthadur** [comment]
@kotran88 can you please check for a similar issue [here](https://github.com/tensorflow/tfjs/issues/785), what is the version of tfjs ?

**Comment by kotran88** [comment]
the most recent one. 2.4.0

**Comment by rthadur** [comment]
can you please let me know steps you followed to convert ?

**Comment by akshayvr-programmer** [comment]
Hi, recently I was using the tensorflowjs_converter to convert VGG16.h5 file. I ran the sollowing script:
$  tensorflowjs_converter --input_format=keras /c/Users/aksha/Desktop/vgg16_weights_tf_dim_ordering_tf_kernels.h5 /c/Users/aksha/tensorflow_files

The output that I got:
2021-03-04 11:16:47.747396: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-04 11:16:47.747743: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python38\Scripts\tensorflowjs_converter.exe\__main__.py", line 7, in <module>
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\converter.py", line 803, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\converter.py", line 496, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\converter.py", line 85, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    groups = conversion.h5_weights_to_tfjs_format(
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\keras_h5_conversion.py", line 233, in h5_weights_to_tfjs_format
    _check_version(h5file)
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\tensorflowjs\converters\keras_h5_conversion.py", line 100, in _check_version
    keras_version = as_text(h5file.attrs['keras_version'])
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "c:\users\aksha\appdata\local\programs\python\python38\lib\site-packages\h5py\_hl\attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5a.pyx", line 77, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'keras_version')"

When I ran the same command for MobileNet.h5, I got no error. I'm not able to understand what exactly is the problem. Please help.

Akshay V.R.

**Comment by santimirandarp** [comment]
@rthadur  I added an issue that can be reproduce, as the error persists #7349
