### ISSUE TITLE
Saved_model executeasync return mismatch in transpose

### ISSUE THREAD

**Issue by 11mhg** [tensorflow/tfjs#3959]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
Yes, this is code that uses GPT2 openai exported as a saved_model. This saved model takes input tokens and a past context tensor. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow.js installed from (npm or script link):
npm i @tensorflow/tfjs
- TensorFlow.js version (use command below): 
2.4.0
- Tensorflow.js Converter Version:
2.3.0

**Describe the current behavior**
Current behavior leads to the following error on executeAsync:
```
await model.executeAsync({'input_tokens': tf.ones([1,5], dtype='int32'), 'past': tf.zeros([1,12,2,12,1,64], dtype='float32')});
Thrown:
Error: Error in transpose: rank of input 2 must match length of perm 0,1,-1.
    at assert (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:706:15)
    at transpose_ (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:7017:5)
    at transpose__op (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3682:29)
    at forward (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:11520:25)
    at /home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2866:55
    at /home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2705:22
    at Engine.scopedRun (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2715:23)
    at Engine.tidy (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2704:21)
    at kernelFunc (/home/mgasmallah/DCP/dcp-packages/gpt2/js/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:2866:29)
```
**Describe the expected behavior**
Expected behavior should be that the output tensor is generated...

**Standalone code to reproduce the issue**
The reproducable standalone code would require gpt2 model weights and topology.

**Comment by rthadur** [comment]
Can you please provide minimal code to reproduce the error or code after you load the model ?

**Comment by 11mhg** [comment]
The code after loading the model that makes this happen is shown above. Here it is again:
`await model.executeAsync({'input_tokens': tf.ones([1,5], dtype='int32'), 'past': tf.zeros([1,12,2,12,1,64], dtype='float32')});`

Unfortunately the model is too big to provide, but if absolutely necessary I can provide a link to it. However this model works perfectly in python and the tensorflow js converter does not complain about missing ops.

**Comment by 11mhg** [comment]
I've attached the single file version of the model in this zip. If you download this [zip file](https://file.io/P1m9PGhmZCrv) extract the gpt2_single.js file. Then, in a directory that has `@tensorflow/tfjs` installed, run the following in a node repl with the `--max-old-space-size=8192` flag:

```
const tf = require('@tensorflow/tfjs');
const { getModel } = require('./gpt2_single.js');
(async function main(){
  console.log("Beginning model load");
  var model = await getModel();
  console.log("Model loaded");
  await model.executeAsync({'input_tokens': tf.ones([1,1], dtype='int32'), 'past': tf.zeros([1,12,2,12,1,64], dtype='float32')});
})();
``` 
This will reproduce the issue, hope this gives enough information.

**Comment by shmishra99** [comment]
Hi @11mhg ,
Apology for the late response.
Kindly check dimension  and data-type of the `input2` `past` tensor and expected data-type and dimension of the model.
Your `gpt2_single.js` zip file link is no longer valid. Kindly share it again so I can reproduce the issue and help you further. 
Thank You.
