### ISSUE TITLE
Test failure due to undefined behavior of `log` function

### ISSUE THREAD

**Issue by Lewuathe** [tensorflow/tfjs#396]
#### TensorFlow.js version

0.11.5

#### Browser version

macOS 10.13.4 (High Sierra)
- Chrome 66.0.3359.181
- Firefox 60.0.0

#### Describe the problem or feature request

Some tests keep failing due to undefined behavior of `log` function of WebGL. We expects `log` returns `NaN` in case of negative value as well as TensorFlow does. But some browser implementation may return 0 in such case. Actually the behavior of `log` function of GLSL with negative value is [undefined](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/log.xhtml). Since it seems to pass in CI, this failure depends on the client environment (e.g. OS, browser version etc). We may need to make sure `log` returns always `NaN` in case of negative value regardless of browser implementation.

```
Chrome 66.0.3359 (Mac OS X 10.13.4) pow {"BACKEND":"test-webgl","WEBGL_FLOAT_TEXTURE_ENABLED":true,"WEBGL_VERSION":1} gradients: Tensor ^ Tensor FAILED
	Error: Arrays differ: actual[0] = 0, expected[0] = NaN.
	    at <Jasmine>
	    at Object.expectArraysClose (src/test_util.ts:85:12 <- src/test_util.js:123:31)
	    at UserContext.<anonymous> (src/ops/arithmetic_test.ts:657:4 <- src/ops/arithmetic_test.js:2068:33)
	    at <Jasmine>
Chrome 66.0.3359 (Mac OS X 10.13.4) pow {"BACKEND":"test-webgl","WEBGL_FLOAT_TEXTURE_ENABLED":true,"WEBGL_VERSION":2} gradients: Tensor ^ Tensor FAILED
	Error: Arrays differ: actual[0] = 0, expected[0] = NaN.
	    at <Jasmine>
	    at Object.expectArraysClose (src/test_util.ts:85:12 <- src/test_util.js:123:31)
	    at UserContext.<anonymous> (src/ops/arithmetic_test.ts:657:4 <- src/ops/arithmetic_test.js:2068:33)
	    at <Jasmine>
Firefox 60.0.0 (Mac OS X 10.13.0) log {"BACKEND":"test-webgl","WEBGL_FLOAT_TEXTURE_ENABLED":true,"WEBGL_VERSION":1} log propagates NaNs FAILED
	Error: Arrays differ: actual[2] = 0, expected[2] = NaN.
	Actual:   0,NaN,0.
	Expected: 0,NaN,NaN. in src/test_util.js (line 123)
	expectArraysClose@src/test_util.ts:85:12 <- src/test_util.js:123:31
	@src/ops/unary_ops_test.ts:830:4 <- src/ops/unary_ops_test.js:2085:21
	<Jasmine>
Firefox 60.0.0 (Mac OS X 10.13.0) log {"BACKEND":"test-webgl","WEBGL_FLOAT_TEXTURE_ENABLED":true,"WEBGL_VERSION":2} log propagates NaNs FAILED
	Error: Arrays differ: actual[2] = 0, expected[2] = NaN.
	Actual:   0,NaN,0.
	Expected: 0,NaN,NaN. in src/test_util.js (line 123)
	expectArraysClose@src/test_util.ts:85:12 <- src/test_util.js:123:31
	@src/ops/unary_ops_test.ts:830:4 <- src/ops/unary_ops_test.js:2085:21
	<Jasmine>
```

#### Code to reproduce the bug / link to feature request

```
$ yarn test --grep='gradients: Tensor ^ Tensor'
```

**Comment by nsthorat** [comment]
This should be fixed.
