### ISSUE TITLE
Using tensorflowjs for autokeras model deployment

### ISSUE THREAD

**Issue by gbmax** [tensorflow/tfjs#3977]
Hello.
I'm trying to make model with autokeras, and deploy the model to mobile. 
For that, I have to convert generated model to mobile format using tensorflowjs_converter.
Before trying my model, I tested with autokeras regressor  example [here](https://autokeras.com/tutorial/structured_data_regression/),  but conversion failed with following error message.

```
ValueError: The same saveable will be restored with two names: layer_with_weights-0/encoding_layers/6/_table/.ATTRIBUTES/table
```

I tested only saved tf-format because I saw in the tensorflowjs document, keras-format might not be converted completely(frozen model was not made well from tf-saved model, so skipped).
I also used converted sequential model (tf.keras.Sequential(model.layers)), but same error produces.

Test env. when generate and save model:
  - python : 3.6.8
  - tensorflow : 2.3.0
  - autokeras : 1.0.8
  - OS : wsl2, Ubuntu 20.06
  - conda : 4.8.3
Test env. when convert model:
  - python : 3.6.8
  - tensorflow-cpu : 2.3.0 (pip list shows like this)
  - tensorflowjs : 2.4.0
  - OS : wsl2, Ubuntu 20.06

This is the code to create model file(same as example except the last line to save the model).

```
from sklearn.datasets import fetch_california_housing
import numpy as np
import pandas as pd
import tensorflow as tf
import autokeras as ak

house_dataset = fetch_california_housing()
df = pd.DataFrame(
    np.concatenate((
        house_dataset.data, 
        house_dataset.target.reshape(-1,1)),
        axis=1),
    columns=house_dataset.feature_names + ['Price'])
train_size = int(df.shape[0] * 0.9)
df[:train_size].to_csv('train.csv', index=False)
df[train_size:].to_csv('eval.csv', index=False)
train_file_path = 'train.csv'
test_file_path = 'eval.csv'
import pandas as pd
import numpy as np
# x_train as pandas.DataFrame, y_train as pandas.Series
x_train = pd.read_csv('train.csv')
print(type(x_train)) # pandas.DataFrame
y_train = x_train.pop('Price')
print(type(y_train)) # pandas.Series

# Preparing testing data.
x_test = pd.read_csv('eval.csv')
y_test = x_test.pop('Price')
# You can also use numpy.ndarray for x_train and y_train.
x_train = x_train.to_numpy().astype(np.unicode)
y_train = y_train.to_numpy()
x_test = x_test.to_numpy().astype(np.unicode)
y_test = y_test.to_numpy()
# It tries 10 different models.
reg = ak.StructuredDataRegressor(max_trials=3, overwrite=True)
reg.fit(x_train, y_train, epochs=10)
model = reg.export_model()
type(model)
tf.keras.models.save_model(model, "model_test/pb_california", save_format="tf")
```

<< tf_saved_model -> tfjs_graph_model >>
```
(tfjsv) D:\0.Projects\autokeras_test\tfjs\tfjsv>tensorflowjs_converter --input_format tf_saved_model --output_format tfjs_graph_model D:\0.Projects\autokeras_test\model_test\pb_california D:\0.Projects\autokeras_test\model_test\res\
```

2020-09-26 13:32:07.675325: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x24dbfc3d280 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-26 13:32:07.675507: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "D:\0.Projects\autokeras_test\tfjs\pyenv-win\versions\3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\0.Projects\autokeras_test\tfjs\pyenv-win\versions\3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\0.Projects\autokeras_test\tfjs\tfjsv\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 699, in convert
    experiments=args.experiments)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 481, in convert_tf_saved_model
    model = load(saved_model_dir, saved_model_tags)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\saved_model\load.py", line 603, in load
    return load_internal(export_dir, tags, options)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\saved_model\load.py", line 633, in load_internal
    ckpt_options)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\saved_model\load.py", line 131, in __init__
    self._restore_checkpoint()
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\saved_model\load.py", line 330, in _restore_checkpoint
    load_status = saver.restore(variables_path, self._checkpoint_options)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1320, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 914, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\tracking\util.py", line 290, in restore_saveables
    tensor_saveables)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 361, in validate_and_slice_inputs
    _add_saveable(saveables, seen_ops, converted_saveable_object)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 331, in _add_saveable
    saveable.name)
ValueError: The same saveable will be restored with two names: layer_with_weights-0/encoding_layers/6/_table/.ATTRIBUTES/table
WARNING:tensorflow:5 out of the last 5 calls to <function recreate_function.<locals>.restored_function_body at 0x0000024DC1B28268> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function recreate_function.<locals>.restored_function_body at 0x0000024DC1B346A8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

**Comment by gbmax** [comment]
Hello again.
I tested to convert the same model file by program.
the error message seems to be different(not sure).
Code is:
```
tf.keras.models.load_model("model_test/pb_california")
tfjs.converters.save_keras_model(model_tf, 'model_test/tfjs_model')
```
Version info. is: 
```
autokeras.__version =  1.0.8
tensorflow.__version =  2.3.1
tensorflowjs.__version =  2.4.0
python =  3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
```

Error message is as follows: 
=> (message seems to recognize it is h5 format instead of tf format.)
```
--------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-36df9b1cf9d4> in <module>
----> 1 tfjs.converters.save_keras_model(model_tf, 'model_test/tfjs_model')

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflowjs/converters/keras_h5_conversion.py in save_keras_model(model, artifacts_dir, quantization_dtype_map, weight_shard_size_bytes)
    339   """
    340   temp_h5_path = tempfile.mktemp() + '.h5'
--> 341   model.save(temp_h5_path)
    342   topology_json, weight_groups = (
    343       h5_merged_saved_model_to_tfjs_format(temp_h5_path))

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1977     """
   1978     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1979                     signatures, options)
   1980 
   1981   def save_weights(self,

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    129           'or using `save_weights`.')
    130     hdf5_format.save_model_to_hdf5(
--> 131         model, filepath, overwrite, include_optimizer)
    132   else:
    133     saved_model_save.save(model, filepath, overwrite, include_optimizer,

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    117     model_weights_group = f.create_group('model_weights')
    118     model_layers = model.layers
--> 119     save_weights_to_hdf5_group(model_weights_group, model_layers)
    120 
    121     # TODO(b/128683857): Add integration tests between tf.keras and external

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    633   for layer in sorted(layers, key=lambda x: x.name):
    634     g = f.create_group(layer.name)
--> 635     weights = _legacy_weights(layer)
    636     weight_values = K.batch_get_value(weights)
    637     weight_names = [w.name.encode('utf8') for w in weights]

~/miniconda3/envs/tfconv/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py in _legacy_weights(layer)
    882         'Save or restore weights that is not an instance of `tf.Variable` is '
    883         'not supported in h5, use `save_format=\'tf\'` instead. Got a model '
--> 884         'or layer {} with weights {}'.format(layer.__class__.__name__, weights))
    885   return weights

NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer MultiCategoryEncoding with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f35841ea208>, <tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f35841ea588>, <tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f35841ea908>]
```

**Comment by gbmax** [comment]
Hello again.
Another conversion trial.
This time I tried to convert from keras basic example from keras homepage.
(https://keras.io/examples/structured_data/structured_data_classification_from_scratch/)

After model fit(`model.fit(train_ds, epochs=50, validation_data=val_ds)`),
I tried to convert through tensorflowjs : 
```
import tensorflowjs as tfjs
tfjs.converters.save_keras_model(model, 'model_test/tfjs_model')
```
And the result is : 
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-20-799292d80d92> in <module>
      1 import tensorflowjs as tfjs
----> 2 tfjs.converters.save_keras_model(model, 'model_test/tfjs_model')

~/miniconda3/lib/python3.8/site-packages/tensorflowjs/converters/keras_h5_conversion.py in save_keras_model(model, artifacts_dir, quantization_dtype_map, weight_shard_size_bytes)
    339   """
    340   temp_h5_path = tempfile.mktemp() + '.h5'
--> 341   model.save(temp_h5_path)
    342   topology_json, weight_groups = (
    343       h5_merged_saved_model_to_tfjs_format(temp_h5_path))

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1976     ```
   1977     """
-> 1978     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
   1979                     signatures, options)
   1980 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    128           'to the Tensorflow SavedModel format (by setting save_format="tf") '
    129           'or using `save_weights`.')
--> 130     hdf5_format.save_model_to_hdf5(
    131         model, filepath, overwrite, include_optimizer)
    132   else:

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    117     model_weights_group = f.create_group('model_weights')
    118     model_layers = model.layers
--> 119     save_weights_to_hdf5_group(model_weights_group, model_layers)
    120 
    121     # TODO(b/128683857): Add integration tests between tf.keras and external

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    633   for layer in sorted(layers, key=lambda x: x.name):
    634     g = f.create_group(layer.name)
--> 635     weights = _legacy_weights(layer)
    636     weight_values = K.batch_get_value(weights)
    637     weight_names = [w.name.encode('utf8') for w in weights]

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in _legacy_weights(layer)
    879   weights = layer.trainable_weights + layer.non_trainable_weights
    880   if any(not isinstance(w, variables_module.Variable) for w in weights):
--> 881     raise NotImplementedError(
    882         'Save or restore weights that is not an instance of `tf.Variable` is '
    883         'not supported in h5, use `save_format=\'tf\'` instead. Got a model '

NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer StringLookup with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7fcfa843f820>]
```

**Comment by gbmax** [comment]
I am sorry for using wrong function.
Tensorflow Doc. says using `tfjs.converters.save_keras_model()` is for h5 format.
So I changed code as : 
```
model.save("model_test/keras_h5.h5")
tfjs.converters.save_keras_model(model, 'model_test/keras_h5.h5')
```
In this case error ocurred in model.save().
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-13-a0aa7fc13887> in <module>
      1 import tensorflowjs as tfjs
      2 # tf.keras.models.save_model(model, "model_test/keras_pb", save_format="tf")
----> 3 model.save("model_test/keras_h5.h5")
      4 tfjs.converters.save_keras_model(model, 'model_test/keras_h5.h5')

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1976     ```
   1977     """
-> 1978     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
   1979                     signatures, options)
   1980 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    128           'to the Tensorflow SavedModel format (by setting save_format="tf") '
    129           'or using `save_weights`.')
--> 130     hdf5_format.save_model_to_hdf5(
    131         model, filepath, overwrite, include_optimizer)
    132   else:

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    117     model_weights_group = f.create_group('model_weights')
    118     model_layers = model.layers
--> 119     save_weights_to_hdf5_group(model_weights_group, model_layers)
    120 
    121     # TODO(b/128683857): Add integration tests between tf.keras and external

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    633   for layer in sorted(layers, key=lambda x: x.name):
    634     g = f.create_group(layer.name)
--> 635     weights = _legacy_weights(layer)
    636     weight_values = K.batch_get_value(weights)
    637     weight_names = [w.name.encode('utf8') for w in weights]

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in _legacy_weights(layer)
    879   weights = layer.trainable_weights + layer.non_trainable_weights
    880   if any(not isinstance(w, variables_module.Variable) for w in weights):
--> 881     raise NotImplementedError(
    882         'Save or restore weights that is not an instance of `tf.Variable` is '
    883         'not supported in h5, use `save_format=\'tf\'` instead. Got a model '

NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer StringLookup with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7f365c1da670>]
```

**Comment by gbmax** [comment]
Hello again.
This time, I tested my own model, but fit and save the model within the latest tensorflow docker.
converting h5 model succeeded with following command.
```
tensorflowjs_converter --weight_shard_size_bytes 60000000 --input_format keras --output_format tfjs_graph_model D:\0.Projects\autokeras_test\model_test\ak_h5.h5
```
But trying tf model fails with following command.
```
tensorflowjs_converter  --weight_shard_size_bytes 60000000 --input_format tf_saved_model --output_format tfjs_graph_model D:\0.Projects\autokeras_test\model_test\ak_pb D:\0.Projects\autokeras_test\model_test\res\
```
It seems cause of 'not all ops supported...' in the Doc.
I am wondering the fact that  In another tensorflow Doc., I remember that tf format is more reliable than h5 format.

Result is...
```
2020-10-16 18:20:29.648409: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x197c18199a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-16 18:20:29.648871: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-16 18:20:31.245737: I tensorflow/core/grappler/devices.cc:78] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2020-10-16 18:20:31.246435: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-10-16 18:20:31.283567: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-10-16 18:20:31.283817: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 550 nodes (539), 923 edges (912), time = 22.565ms.
2020-10-16 18:20:31.284059: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.492ms.
Traceback (most recent call last):
  File "D:\0.Projects\autokeras_test\tfjs\pyenv-win\versions\3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\0.Projects\autokeras_test\tfjs\pyenv-win\versions\3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\0.Projects\autokeras_test\tfjs\tfjsv\Scripts\tensorflowjs_converter.exe\__main__.py", line 9, in <module>
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\converter.py", line 699, in convert
    experiments=args.experiments)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 552, in convert_tf_saved_model
    experiments=experiments)
  File "d:\0.projects\autokeras_test\tfjs\tfjsv\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 143, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
StringToNumber, IsNan
```

**Comment by gaikwadrahul8** [comment]
Hi, @gbmax 

Apologize for the delayed response and I was able to replicate the issue with above given code by you with latest version of `tensorflowjs 4.4.0` and I'm getting different error, for your reference I have [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/8117457f016d4235c0c63f88e5eff0df/-3977.ipynb) so if have I missed something here please let me know ? 

Could you please give it try from your end with latest version of `tensorflowjs 4.4.0` and let us know still that issue persist  or not ? Thank you!
