### ISSUE TITLE
TypeError: Cannot read property 'nonMaxSuppressionV3Impl' of undefined

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tfjs#4000]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
`NO` - I'm using the example provided in https://github.com/tensorflow/tfjs-models/tree/master/toxicity
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
```
ProductName:    Mac OS X
ProductVersion: 10.14.5
BuildVersion:   18F132
```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
`Not applicable`
- TensorFlow.js installed from (npm or script link):
Latest version from command `npm i @tensorflow/tfjs-node`
- TensorFlow.js version (use command below):
- Browser version:
`Not applicable` using `Node.JS`
- Tensorflow.js Converter Version:
`Not applicable`

**Describe the current behavior**
Error 

```
Platform node has already been set. Overwriting the platform with [object Object].
Platform node has already been set. Overwriting the platform with [object Object].
/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:268
var nonMaxSuppressionV3Impl = tf.kernel_impls.nonMaxSuppressionV3Impl;
                                              ^

TypeError: Cannot read property 'nonMaxSuppressionV3Impl' of undefined
    at Object.<anonymous> (/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:268:47)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs/dist/tf.node.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10
```
**Describe the expected behavior**
the command `npm i @tensorflow/tfjs-node` should succeed.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

I'm using the code provided in https://github.com/tensorflow/tfjs-models/tree/master/toxicity
at which I have added just one line
```
require('@tensorflow/tfjs-node');
```

as suggested by the command resulting from the script execution:

```
$ node test.js 

============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
[
  { label: 'identity_attack', results: [ [Object] ] },
  { label: 'insult', results: [ [Object] ] },
  { label: 'obscene', results: [ [Object] ] },
  { label: 'severe_toxicity', results: [ [Object] ] },
  { label: 'sexual_explicit', results: [ [Object] ] },
  { label: 'threat', results: [ [Object] ] },
  { label: 'toxicity', results: [ [Object] ] }
]
```

The whole script is the following:

```javascript
require('@tensorflow/tfjs-node');
const toxicity = require('@tensorflow-models/toxicity');
// The minimum prediction confidence.
const threshold = 0.9;

// Load the model. Users optionally pass in a threshold and an array of
// labels to include.
toxicity.load(threshold).then(model => {
  const sentences = ['you suck'];

  model.classify(sentences).then(predictions => {
    // `predictions` is an array of objects, one for each prediction head,
    // that contains the raw probabilities for each input along with the
    // final prediction in `match` (either `true` or `false`).
    // If neither prediction exceeds the threshold, `match` is `null`.

    console.log(predictions);
    /*
    prints:
    {
      "label": "identity_attack",
      "results": [{
        "probabilities": [0.9659664034843445, 0.03403361141681671],
        "match": false
      }]
    },
    {
      "label": "insult",
      "results": [{
        "probabilities": [0.08124706149101257, 0.9187529683113098],
        "match": true
      }]
    },
    ...
     */
  });
});
```

The script works fine without the first line `require('@tensorflow/tfjs-node');`. When adding that line I get the error showed above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
`Not applicable` - log reported above

**Comment by tafsiri** [comment]
I just tried your script and could not reproduce the error. Could you post your package.json so we can see what versions of the libraries you are using?

**Comment by loretoparisi** [comment]
@tafsiri yes. Please wait thank you

**Comment by loretoparisi** [comment]
This is the `package.json`

```javascript
{
  "name": "@tensorflow-models/toxicity",
  "version": "1.2.2",
  "description": "Toxicity model in TensorFlow.js",
  "main": "dist/index.js",
  "jsnext:main": "dist/toxicity.esm.js",
  "module": "dist/toxicity.esm.js",
  "unpkg": "dist/toxicity.min.js",
  "jsdelivr": "dist/toxicity.min.js",
  "types": "dist/index.d.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/tensorflow/tfjs-models.git"
  },
  "dependencies": {
    "@tensorflow/tfjs-converter": "^1.3.3",
    "@tensorflow/tfjs-core": "^1.3.3",
    "@tensorflow/tfjs-node": "^2.4.0"
  }
}
```

I remove the `node_modules` folder and then I do 

```
npm install
```

This seems to cause the error here https://github.com/tensorflow/tfjs/issues/3999

Then I do

```
node test.js
```

using the code above and it works ok. But if I put `require('@tensorflow/tfjs-node');` as first line, I get that error:

```
ip-192-168-178-22:toxicity loretoparisi$ node test.js 
Platform node has already been set. Overwriting the platform with [object Object].
Platform node has already been set. Overwriting the platform with [object Object].
/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:268
var nonMaxSuppressionV3Impl = tf.kernel_impls.nonMaxSuppressionV3Impl;
...
```
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
I was able to solve the install issue, previously cited, so now the only issue I have is the one here:

```
ip-192-168-178-22:toxicity loretoparisi$ node test.js Platform node has already been set. Overwriting the platform with [object Object].
Platform node has already been set. Overwriting the platform with [object Object].
/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:268
var nonMaxSuppressionV3Impl = tf.kernel_impls.nonMaxSuppressionV3Impl;
                                              ^

TypeError: Cannot read property 'nonMaxSuppressionV3Impl' of undefined
    at Object.<anonymous> (/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:268:47)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/loretoparisi/Documents/MyProjects/AI/tfjs-models/toxicity/node_modules/@tensorflow/tfjs/dist/tf.node.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

having 

```
$ npm --version
6.14.8
```

and installed the following packages

```
.
├── tfjs
├── tfjs-backend-cpu
├── tfjs-backend-webgl
├── tfjs-converter
├── tfjs-core
├── tfjs-data
├── tfjs-layers
└── tfjs-node
```

**Comment by tafsiri** [comment]
I'm not sure why you modified the package.json of the toxicity model? I wanted to see the package.json of _your project_. The model itself only has peerDependencies on specific versions of tfjs. It looks like you modifying it to add direct dependencies there which does not look like the right way to solve your problem. 

Did you run into an issue with the [install instructions here earlier](https://github.com/tensorflow/tfjs-models/tree/master/toxicity#installation)? I would just try removing the package completely from your project and reinstalling again following those instructions. You should not need to modify the package.json of the model itself.

**Comment by loretoparisi** [comment]
@tafsiri right thank you. So this `package.json` comes from my application (NodeJS). I prefer not to include the examples in the application, but better the code and the model directly (so that I can run it offline), etc. 
Thanks a lot for the help, at the end it works, after struggling a bit with `npm`.

**Comment by 1003657663** [comment]
I get The same problem.
my project is node-red

```
cd ~/.node-red
npm install node-red-contrib-face-recognition
npm install @tensorflow/tfjs-node
```

and then run node-red by 
```
node-red
```

then get 
```
29 Dec 13:48:21 - [info] Node-RED version: v1.2.6
29 Dec 13:48:21 - [info] Node.js  version: v10.19.0
29 Dec 13:48:21 - [info] Linux 5.4.0-58-generic x64 LE
29 Dec 13:48:22 - [info] Loading palette nodes
Platform node has already been set. Overwriting the platform with [object Object].
Platform node has already been set. Overwriting the platform with [object Object].
29 Dec 13:48:23 - [info] Dashboard version 2.26.0 started at /ui
29 Dec 13:48:23 - [warn] ------------------------------------------------------
29 Dec 13:48:23 - [warn] [node-red-contrib-face-recognition/face-api] TypeError: Cannot read property 'nonMaxSuppressionV3I                                              mpl' of undefined
29 Dec 13:48:23 - [warn] ------------------------------------------------------
29 Dec 13:48:23 - [info] Settings file  : /home/songchao/.node-red/settings.js

```

[node-red-contrib-face-recognition/face-api] TypeError: Cannot read property 'nonMaxSuppressionV3I                                              mpl' of undefined
