### ISSUE TITLE
tfjs-node support for saved models does not recognize valid dtypes: uint64

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4004]
Attempting to load `saved_model` that uses `int64` in `tfjs-node` results in failure due to unrecognized data type:

```js
const tf = require('@tensorflow/tfjs-node');
const definitions = await tf.node.getMetaGraphsFromSavedModel(modelPath); // fails
const model = await tf.node.loadSavedModel(modelPath); // also fails
```

```text
(node:8807) UnhandledPromiseRejectionWarning: Error: Unsupported tensor DataType: DT_INT64, try to modify the model in python to convert the datatype
    at mapTFDtypeToJSDtype (/home/vlado/dev/detector/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:473:19)
    at /home/vlado/dev/detector/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:179:58
    at step (/home/vlado/dev/detector/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (/home/vlado/dev/detector/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (/home/vlado/dev/detector/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
```

Example `saved_model` that use `int64` are available on `TFHub`:
- <https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1>
- <https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1>

Same issue for models using `uint8` data type was reported in <https://github.com/tensorflow/tfjs/issues/3930>  
and resolved via code fix <https://github.com/tensorflow/tfjs/pull/3974>  

The same fix should be extended to cover further data types as most of the code is written in a generic way.

Environment: Ubuntu 20.04, NodeJS 14.11.0, TFJS built from master dated 09/30/2020

**Comment by vladmandic** [comment]
Confirmed that models do load correctly with the latest patch, but now I'm running into next issue using same models.
Created a new issue under <https://github.com/tensorflow/tfjs/issues/4011>
