### ISSUE TITLE
[tfjs-converter] InvalidArgumentError when converting BigGAN tfhub model (Input 0 of node module_apply_default/cond/AssignVariableOp)

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#4051]
Hello, I'm not sure if this particular model is just fundamentally not convertible, but if that is the case, then please interpret this bug report instead as a suggestion to improve the tfjs-converter wizard's error messages to make cases like this less confusing.

Note that it seems to work fine with `https://tfhub.dev/google/progan-128/1`. As a random guess, this might have something to do with tensorflow 1.0 vs 2.0, given that [the BigGAN tutorial](https://www.tensorflow.org/hub/tutorials/biggan_generation_with_tf_hub) on tensorflow.org appears in the TFv1 section?

Thanks!

(Oh, also, I wasn't sure where to submit this, since `tf-converter` is part of this repo, but it seems like the problem is in the `tensorflow/tensorflow` repo - I can close and submit to `tensorflow/tensorflow` if that would make more sense.)

-----

# Steps to reproduce:

1. Open up a new Google Colab notebook.
2. Run `!pip install tensorflowjs[wizard]`.
3. Run `!tensorflowjs_wizard`.
4. Enter the URL `https://tfhub.dev/deepmind/biggan-deep-128/1` and use all default options.
5. It gives this output:

```
Loading the module using TF 1.X interface from /tmp/tfhub_modules/3b80c3655a996dda3751743226c6bd181fb511cd.
2020-10-10 01:27:40.548457: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-10 01:27:40.607992: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-10-10 01:27:40.608150: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5fb4dd5e135a): /proc/driver/nvidia/version does not exist
2020-10-10 01:27:40.624690: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz
2020-10-10 01:27:40.624963: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x15cd9c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-10 01:27:40.625008: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Creating a model with inputs ['y', 'z', 'truncation'] and outputs ['module_apply_default/G_trunc_output'].
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:710: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:710: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py:854: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py:854: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Conversion failed, please check error log file /tmp/converter_error.log.
```

And `!cat /tmp/converter_error.log` gives:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/wizard.py", line 611, in run
    converter.convert(arguments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 711, in convert
    experiments=args.experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 773, in convert_tf_hub_module
    experiments=experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 718, in convert_tf_hub_module_v1
    frozen_graph = load_graph(frozen_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/wizard.py", line 611, in run
    converter.convert(arguments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 711, in convert
    experiments=args.experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 773, in convert_tf_hub_module
    experiments=experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 718, in convert_tf_hub_module_v1
    frozen_graph = load_graph(frozen_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.
```

**Comment by pyu10055** [comment]
@josephrocca This model converted properly with the tensorflowjs pip 2.6.0, please verify that. thanks.

**Comment by josephrocca** [comment]
Hi @pyu10055 were you able to convert that biggan model successfully? I may have done something wrong here, since I have very little experience with Python, but I got this error:

```
!cat /tmp/converter_error.log
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/wizard.py", line 611, in run
    converter.convert(arguments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 711, in convert
    experiments=args.experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 773, in convert_tf_hub_module
    experiments=experiments)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 718, in convert_tf_hub_module_v1
    frozen_graph = load_graph(frozen_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node module_apply_default/cond/AssignVariableOp was passed float from module_apply_default/cond/AssignVariableOp/Switch:0 incompatible with expected resource.
```
Version info:
```
!pip show tensorflowjs
```
```
Name: tensorflowjs
Version: 2.6.0
Summary: Python Libraries and Tools for TensorFlow.js
Home-page: https://js.tensorflow.org/
Author: Google LLC
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: six, h5py, tensorflow, tensorflow-hub
Required-by: 
```

**Comment by rthadur** [comment]
@pyu10055 I can confirm the same.

**Comment by josephrocca** [comment]
Hi @rthadur, @pyu10055, I think this was marked as stale by the bot because of the "awaiting response" tag?

**Comment by gaikwadrahul8** [comment]
Hi, @josephrocca 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by josephrocca** [comment]
Hi @gaikwadrahul8 if the bug still reproduces (see "Steps to reproduce"), then this issue should stay open. I haven't tested it again myself since Nov 2020.

**Comment by Varun-S10** [comment]
Hi @josephrocca, Thank you for your patience. We have tried to reproduce this issue. As a workaround, you can bypass the direct TF Hub conversion by using a Python script with TF1 compatibility mode (tf.compat.v1) to load the model, freeze its variables to constants, and save it as a static .pb file. You can then convert this file using the --input_format=tf_frozen_model option. Could you please try this and let us know if it works for you?
