### ISSUE TITLE
webgpu: Many mirrorPad tests fail

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#4091]
Steps to reproduce on my windows platform:
1. Download the latest TFJS code. 'git clone https://github.com/tensorflow/tfjs' 
2. cd tfjs\tfjs-backend-webgpu
3. set CHROME_BIN=C:\Users\jqin7\AppData\Local\Google\Chrome SxS\Application\chrome.exe
4. yarn test --grep=mirrorPad
Below errors will be printed:
Chrome 88.0.4296 (Windows 10.0.0) mirrorPad test-webgpu {"WEBGPU_CPU_FORWARD":false} MirrorPad tensor1d FAILED
        Error: Arrays differ: actual[2] = 3, expected[2] = 1.
            at <Jasmine>
            at expectArraysPredicate (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:125282:13)
            at expectArraysClose (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:125232:10)
            at _callee$ (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92057:29)
            at tryCatch (node_modules/@babel/polyfill/dist/polyfill.js:6517:40)
            at Generator.invoke [as _invoke] (node_modules/@babel/polyfill/dist/polyfill.js:6746:22)
            at Generator.prototype.<computed> [as next] (node_modules/@babel/polyfill/dist/polyfill.js:6569:21)
            at asyncGeneratorStep (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92037:103)
            at _next (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92039:194)
Chrome 88.0.4296 (Windows 10.0.0) mirrorPad test-webgpu {"WEBGPU_CPU_FORWARD":false} MirrorPad tensor2d FAILED
        Error: Arrays differ: actual[1] = 6, expected[1] = 4.
            at <Jasmine>
            at expectArraysPredicate (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:125282:13)
            at expectArraysClose (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:125232:10)
            at _callee2$ (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92096:30)
            at tryCatch (node_modules/@babel/polyfill/dist/polyfill.js:6517:40)
            at Generator.invoke [as _invoke] (node_modules/@babel/polyfill/dist/polyfill.js:6746:22)
            at Generator.prototype.<computed> [as next] (node_modules/@babel/polyfill/dist/polyfill.js:6569:21)
            at asyncGeneratorStep (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92037:103)
            at _next (C:/Users/jqin7/AppData/Local/Temp/karma-typescript-bundle-13512XiYs6A25Ygy0.js:92039:194)
... ...
Chrome 88.0.4296 (Windows 10.0.0): Executed 12 of 3763 (6 FAILED) (skipped 3751) (3.497 secs / 0.501 secs)

**Comment by qjia7** [comment]
@AbdallaGomaa Have you have time to look at this issue? I notice that you implemented this feature. Thanks.

Cc @annxingyuan

**Comment by annxingyuan** [comment]
Hi @qjia7 - just wanted to say that if these failing tests are blocking development on your side in any way, please feel free to submit a PR to disable them for WebGPU :)
