### ISSUE TITLE
TFJS does not work with converted CenterNet models

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#4128]
[CenterNet model](https://tfhub.dev/tensorflow/centernet/resnet50v2_512x512/1) works when loaded as `saved_model` in `tfjs_node` using `loadSavedModel()`, but fails when converted using `tensorflowjs_converter --input_format tf_hub ...` to `graph_model`  
it seems to convert correctly and loads correctly using `loadGraphModel`, but fails during call to `executeAsync()`:

```log
Uncaught (in promise) Error: All tensors passed to tf.addN() must have the same shape
  (anonymous)	@	add_n.js:48
  addN_	@	add_n.js:46
  addN__op	@	operation.js:44
  executeOp	@	arithmetic_executor.js:28
  (anonymous)	@	operation_executor.js:48
  (anonymous)	@	engine.js:314
  scopedRun	@	engine.js:324
  tidy	@	engine.js:313
  tidy	@	globals.js:173
  (anonymous)	@	operation_executor.js:48
  executeOp$h	@	operation_executor.js:90
  processStack	@	graph_executor.js:390
  executeWithControlFlow	@	graph_executor.js:350
```

this is a new error message as code changes from #4100 do fix previously encountered error (see #3903 for details), but it seems it's like peeling an onion :)

environment: tfjs built from master dated 10/24/2020 on ubuntu 20.10

**Comment by vladmandic** [comment]
nice - will test as soon as #4233 is merged.

**Comment by vladmandic** [comment]
Confirmed to work without issues - thanks!
I'm closing this issue.

**Comment by sandhyacs** [comment]
Hi @vladmandic , 
I am also training a centernet model for keypoint detection fro custom input data and converting it into tfjs, but it is throwing some exception as IsNaN is not an ops. Can you please tell how can I load it in tfjs?

**Comment by vladmandic** [comment]
@sandhyacs 

i didn't get that error

```shell
wget https://tfhub.dev/tensorflow/centernet/resnet50v2_512x512_kpts/1?tf-hub-format=compressed
tar xzf 1\?tf-hub-format\=compressed
rm 1\?tf-hub-format\=compressed
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model . graph
```

it throws some warnings as variables are not constant, but conversion finishes without errors and model is usable

**Comment by sandhyacs** [comment]
@vladmandic ,
Thank you so much for the reply. I am using tensorflow 2.2.0 version and tfjs version is 2.1.0. Whenever I am converting saved model, input shape is [1, -1,-1,3] in model.json. But I am doing training for input shape 1,512,512,3. Why is it happening? Is tfjs version is incompatible?

**Comment by vladmandic** [comment]
shape dimension -1 means any number, so it still fits your input of 512.
but yes, you can see from this issue that there were two fixes required to tfjs to support centernet, so i doubt old tfjs 2.2 can work.

**Comment by sandhyacs** [comment]
So, shall I use new tfjs version? And what about tf version? Is it okay tf 2.2.0

**Comment by vladmandic** [comment]
if you take a look at <https://github.com/tensorflow/tfjs/releases>, you can see that fixes are in tfjs 2.8.2 and higher.

**Comment by sandhyacs** [comment]
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model . graph


2021-03-27 18:51:13.596899: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2021-03-27 18:51:13.596925: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-27 18:51:15.308632: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-27 18:51:15.309280: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-27 18:51:15.311392: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-27 18:51:15.311407: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sandhya): /proc/driver/nvidia/version does not exist
2021-03-27 18:51:15.311921: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-27 18:51:24.135791: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-27 18:51:24.135925: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-27 18:51:24.136219: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-27 18:51:24.156549: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2199995000 Hz
2021-03-27 18:51:24.233794: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 1955 nodes (1626), 4919 edges (4583), time = 45.436ms.
  function_optimizer: function_optimizer did nothing. time = 1.001ms.

Traceback (most recent call last):
  File "/home/sandhya/anaconda3/envs/test_conv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 652, in convert_tf_saved_model
    metadata=metadata)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 148, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
IsNan


This error, I am getting.

**Comment by vladmandic** [comment]
are you using centernet from tfhub as i've noted in my conversion notes?  
whats the version of `tensorflowjs_converter` you're using?  
there is no harm of upgrading to latest `pip install -U tensorflowjs`

**Comment by sandhyacs** [comment]
tfjs version: yes i upgraded it.
I am getting error in both tf-hub and my own trained model from object detection api instuctions with tf version 2.2.0.

**Comment by vladmandic** [comment]
not `tfjs`, actual tensorflowjs tools. please post output of `tensorflowjs_converter --version`

**Comment by sandhyacs** [comment]
tensorflowjs_converter --version
2021-03-27 19:05:47.304959: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2021-03-27 19:05:47.304985: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

tensorflowjs 3.3.0

Dependency versions:
  keras 2.4.0
  tensorflow 2.4.0

**Comment by vladmandic** [comment]
only difference i see is tensorflow package should be 2.4.1

**Comment by sandhyacs** [comment]
I did same as you said to upgrade "tensorflowjs_converter --version"

**Comment by vladmandic** [comment]
tensorflowjs tools use tensorflow, so you also need `pip install -U tensorflow`

**Comment by sandhyacs** [comment]
i upgraded it to the latest

**Comment by sandhyacs** [comment]
![Screenshot from 2021-03-27 19-22-36](https://user-images.githubusercontent.com/20237261/112722871-d551a800-8f31-11eb-87c8-d2e1be9c9f80.png)

**Comment by sandhyacs** [comment]
the model from tf-hub is working now.. but the model which i am training is getting same error.
