### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization RandomStandardNormal

### ISSUE THREAD

**Issue by zhangchengtan** [tensorflow/tfjs#4156]
I encountered following error for an unsupported operation while use tensorflowjs_converter convert python model to a tfjs model.

G:\sever_git\ml-agents\modelBoard\saved_model>tensorflowjs_converter --input_format=tf_frozen_model --output_format=tfjs_graph_model --output_node_nam
es=action --saved_model_tags=serve ./frozen_graph_def.pb ./web_model
2020-10-29 14:32:22.020098: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Users\Administrator\Anaconda3\Scripts\tensorflowjs_converter.exe\__main__.py", line 7, in <module>
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 757, in pip_main
    main([' '.join(sys.argv[1:])])
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 761, in main
    convert(argv[0].split(' '))
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorflowjs\converters\converter.py", line 744, in convert
    experiments=args.experiments)
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 489, in convert_tf_frozen_mo
del
    experiments=experiments)
  File "d:\users\administrator\anaconda3\lib\site-packages\tensorflowjs\converters\tf_saved_model_conversion_v2.py", line 146, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
RandomStandardNormal

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by amchaudhari** [comment]
Is this issue resolved? Because I am getting the same error when I include the following sampling layer in my model.

class Sampling(tf.keras.layers.Layer):
	"""Uses (z_mean, z_log_var) to sample z"""

	def call(self, inputs):
		z_mean, z_log_var = inputs
		batch = tf.shape(z_mean)[0]
		dim = tf.shape(z_mean)[1]
		epsilon = tf.random.normal(shape)

		return z_mean + tf.exp(0.5 * z_log_var) * epsilon

Tensorflow version = 2.3.1
Tensorflowjs version = 3.6.0

**Comment by rthadur** [comment]
not yet , this is a feature request and is very low on priority, if you are willing to contribute , here are the contribution guidelines https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md
