### ISSUE TITLE
Unknow error when import SavedModel. NotFoundError: ./tensorflowjs_model.pb.frozen;

### ISSUE THREAD

**Issue by bangoc123** [tensorflow/tfjs#423]
I try to convert SavedModel to JS Model and got this error. Please help me to figure out. Thanks

> Traceback (most recent call last):
  File "/Users/mac/anaconda2/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflowjs/converters/converter.py", line 230, in main
    quantization_dtype=quantization_dtype)
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 253, in convert_tf_saved_model
    graph = load_graph(output_graph + '.frozen', output_node_names)
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 59, in load_graph
    graph_def.ParseFromString(f.read())
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/Users/mac/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./tensorflowjs_model.pb.frozen; No such file or directory
MacBook-Pro-cua-Mac:saved_model_2 mac$

**Comment by pyu10055** [comment]
@bangoc123 It looks like the converter failed to freeze the graph, can you share the command line that you used? thanks.

**Comment by Ladoli** [comment]
Having a similar issue, I used 

      tensorflowjs_converter --input_format=tf_saved_model \MODEL/1529446682 \WEB_MODEL/

as my command to run it.

**Comment by BayanBennett** [comment]
I was running into the same problem.
Manually creating an empty `tensorflowjs_model.pb.frozen` file did the trick.

**Comment by Ladoli** [comment]
@BayanBennett I tried that too, but I got this instead

> Traceback (most recent call last):
>   File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.5/dist-packages/tensorflowjs/converters/converter.py", line 230, in main
>     quantization_dtype=quantization_dtype)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 253, in convert_tf_saved_model
>     graph = load_graph(output_graph + '.frozen', output_node_names)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 65, in load_graph
>     for node in output_node_names.split(','):
> AttributeError: 'NoneType' object has no attribute 'split'

**Comment by BayanBennett** [comment]
@Ladoli 
The `--output_node_names` flag is missing in your command. [Docs](https://github.com/tensorflow/tfjs-converter)

**Comment by nsthorat** [comment]
Looks like this is fixed in the docs!
