### ISSUE TITLE
Adam on  trainable = true/false net part

### ISSUE THREAD

**Issue by lexmulya** [tensorflow/tfjs#4290]
Hello.

I'm a beginner trying to train a GAN network. Found an example https://medium.com/datadriveninvestor/generative-adversarial-network-gan-using-keras-ce1c05cfdfd3
In python, the example works fine, but I need to run it under NodeJS.
I rewrote it in JS - https://pastebin.com/RZt6AtZc
And I get the error
(node: 3988) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 3
Message: Incompatible shapes: [784,1024] vs. [100,256]

I began to understand, under the debugger I realized that the error occurs when the optimizer is running. I changed the optimizer to sgd and the code started executing without error.

It looks like the problem is that trainable = false / true is changing for a part of the network.
In @tensorflow \tfjs-core\src\optimizers\adam_optimizer.ts in line 67, only the index is used, but the problem is that the turkeys are the same and the layer names are different.

**Comment by lina128** [comment]
Hi @lexmulya, would you like to contribute a PR to fix this?

**Comment by lexmulya** [comment]
I have not dealt with this problem yet, there was no time. If I have a solution to this question I will do PR.

**Comment by lina128** [comment]
Got it. No problem, @lexmulya. We'll put this bug fix in our queue, but it will likely take some time. If you need it sooner, feel free to submit a fix PR any time.

**Comment by lexmulya** [comment]
Got it. Thanks!

**Comment by gaikwadrahul8** [comment]
Hi, @lexmulya 

Apologize for the delayed response and I tried to replicate the same issue with latest version of `@tensorflow/tfjs-node": "^4.5.0"` with `Adam` Optimizer and still the same issue exists but it's working as expected with `SGD` Optimizer. For your reference I have added screenshot below so May I know are you still looking the solution with `Adam` Optimizer or for you this issue got resolved, please let us know ? Thank you!

**Here is output error log with `Adam` Optimizer :** 

```
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ node index.js
Platform node has already been set. Overwriting the platform with node.
---------------Epoch 1---------------
---------------Batch 1---------------
/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:216
        var outputMetadata = this.binding.executeOp(name, opAttrs, this.getInputTensorIds(inputs), 1);
                                          ^
Error: Invalid TF_Status: 3
Message: Incompatible shapes: [784,1024] vs. [100,256]
    at NodeJSKernelBackend.executeSingleOutput (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:216:43)
    at Object.kernelFunc (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs-node/dist/kernels/Add.js:29:24)
    at kernelFunc (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4707:32)
    at /Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4767:27
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4572:23)
    at Engine.runKernelFunc (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4763:14)
    at Engine.runKernel (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4636:21)
    at add_ (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8333:19)
    at add__op (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5612:29)
    at /Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:24170:38

Node.js v18.15.0
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ 
```

**Here is output log with SGD Optimizer :**

![image](https://github.com/tensorflow/tfjs/assets/115997457/085fda6d-caec-4537-83b2-3c67a57e51cd)
