### ISSUE TITLE
Error: The Node.js native addon module (tfjs_binding.node) can not be found

### ISSUE THREAD

**Issue by sps014** [tensorflow/tfjs#4310]
I have installed TFJS Node GPU , it gets stucked at end , i tried this mutlipe of times .
![bug](https://user-images.githubusercontent.com/45932883/100348141-83912380-300c-11eb-9ff7-5335bb329149.PNG)
 i tried reinstalling , rebuilding , looked for similar issues but no replay contained solution.

now I can 't compile with GPU backend, For some reason CPU backend works.

following error occurs every time I try to compile with it with GPU with following import
```js
const tf=require("@tensorflow/tfjs-node-gpu")
```

```
Node version 15.0.1
``` 

```
C:\Users\shive\Desktop\Test\nodeapp\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\shive\Desktop\Test\nodeapp\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md 
or file an issue.
    at Object.<anonymous> (C:\Users\shive\Desktop\Test\nodeapp\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:49:11)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\shive\Desktop\Test\nodeapp\index.js:1:10)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
npm ERR! code 1
npm ERR! path C:\Users\shive\Desktop\Test\nodeapp
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shive\AppData\Local\npm-cache\_logs\2020-11-26T11_46_53_847Z-debug.log
```

**Comment by rthadur** [comment]
Can you please try delete node-modules folder and rebuild ?

**Comment by sps014** [comment]
I tried reinstalling nothing worked ,
Tried cleaning modules nothing worked,
Tried creating new node project nothing worked,
Then i downgraded to Node 12.20 from v15 now post install script worked but still i am not able to compile to GPU
```js
tf=require("@tensorflow/tfjs-node-gpu")
```
Not able to import like this, it throws napi error,
I will post error in couple of minutes.

**Comment by sps014** [comment]
Error
```
Error: The specified module could not be found.
\\?\C:\Users\shive\Desktop\Test\nodeapp\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\shive\Desktop\Test\nodeapp\node_modules\@tensorflow\tfjs-node-gpu\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

**Comment by rthadur** [comment]
please take a look at similar issue [here](https://github.com/tensorflow/tfjs/issues/4171) , thank you

**Comment by sps014** [comment]
It did .
Thanks

**Comment by 4skinSkywalker** [comment]
Hi, I made a small guide of the exact steps I followed to install TF on my Windows machine [Guide to Install TensorFlow on Windows](https://gist.github.com/4skinSkywalker/209e89be012abb29859fc6d0f70003d6)
