### ISSUE TITLE
`npm install` succeeds despite errors due to not having Python (in a container)

### ISSUE THREAD

**Issue by ahmetb** [tensorflow/tfjs#4419]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux container (docker) node:14
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): ^2.8.0
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**

1. Running `npm install` in a `docker build step`, with Dockerfile:

	  ```
	  FROM node:14-slim
	  WORKDIR /usr/src/app
	  COPY package*.json ./
	  RUN npm install --only=production
	  COPY . ./
	  CMD [ "node", "index.js" ]
	  ```

2. It succeeds and exits with 0.
3. However, the build log shows errors saying it cannot find Python.

**Describe the expected behavior**

If it can't find python, `npm install` **should fail** and fail the whole build process in turn.

**Standalone code to reproduce the issue**

**Other info / logs** 

Logs from docker build:

```
docker build -t gcr.io/ahmetb-demo/tfjs-cloudrun .
Sending build context to Docker daemon  55.85MB
Step 1/6 : FROM node:14-slim
 ---> 30b595bd6403
Step 2/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> aa273d65905c
Step 3/6 : COPY package*.json ./
 ---> 95c5ad63c38f
Step 4/6 : RUN npm install --only=production
 ---> Running in ba6ed059f4a1
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> @tensorflow/tfjs-node@2.8.0 install /usr/src/app/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-2.8.0.tar.gz
* Downloading libtensorflow

* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/2.8.0/CPU-linux-2.8.0.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@2.8.0 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.19.121-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/usr/src/app/node_modules/@tensorflow/tfjs-node/lib/napi-v7" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=7" "--node_napi_label=napi-v7"
gyp ERR! cwd /usr/src/app/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/@tensorflow/tfjs-node/lib/napi-v7/tfjs_binding.node --module_name=tfjs_binding --module_path=/usr/src/app/node_modules/@tensorflow/tfjs-node/lib/napi-v7 --napi_version=7 --node_abi_napi=napi --napi_build_version=7 --node_napi_label=napi-v7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.19.121-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/app/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok


> core-js@3.8.1 postinstall /usr/src/app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN object-detection@ No description
npm WARN object-detection@ No repository field.
npm WARN object-detection@ No license field.

added 182 packages from 140 contributors and audited 182 packages in 12.534s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container ba6ed059f4a1
 ---> d20320f6d3f5
Step 5/6 : COPY . ./
 ---> c79f02866ef4
Step 6/6 : CMD [ "node", "index.js" ]
 ---> Running in fa4cbd173895
Removing intermediate container fa4cbd173895
 ---> dab5876e0308
Successfully built dab5876e0308
Successfully tagged gcr.io/ahmetb-demo/tfjs-cloudrun:latest
```

It shouldn't succed. 
It clearly says `node-pre-gyp ERR! not ok` but `npm install` succeeds.

**Comment by rthadur** [comment]
We had issues with 2.8.0 , which was rolled back , can you please try with 2.8.1 ?

**Comment by ahmetb** [comment]
The issue was present even on 1.4.0, I don't think it's a recently occurred issue.
