### ISSUE TITLE
div error when tfjs-backend-wasm=2.8.1

### ISSUE THREAD

**Issue by naah69** [tensorflow/tfjs#4433]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code : yes 
- OS Platform and Distribution : macOS 10.14.6
- TensorFlow.js installed from : npm 
- TensorFlow.js version : tfjs-backend-wasm 2.8.1
- Browser version: Chrome 87.0.4280.88
- Tensorflow.js Converter Version:

**Describe the current behavior**

use div in wasm backend,it didn't work.

**Describe the expected behavior**
it will work

**Standalone code to reproduce the issue**

open `chrome://flags/#enable-webassembly-simd` in chrome,and enable `WebAssembly SIMD support.` and `WebAssembly threads support` 

 tfjs-backend-wasm 2.6.0 without `WebAssembly SIMD support.` and `WebAssembly threads support`  works

 tfjs-backend-wasm 2.8.1 without `WebAssembly SIMD support.` and `WebAssembly threads support`  work error

 tfjs-backend-wasm 2.8.1 with `WebAssembly SIMD support.` and `WebAssembly threads support`  work error

```javascript
var point1= tf.tensor2d([[-0.6070004, 0.881     , -0.0700001],
     [-0.5930004, 0.8440001 , -0.069    ],
     [-0.5609999, 0.8100002 , -0.064    ]])
var N=tf.tensor1d([0.015242, -0.054074, -0.3919158])
point1.dot(N).abs().div(N.norm())
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to

```log
Uncaught RuntimeError: abort(Assertion failed: Cannot call unknown function RealDiv, make sure it is exported). Build with -s ASSERTIONS=1 for more info.
    at abort (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js:9:13285)
    at assert (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js:9:6125)
    at getCFunc (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js:9:6211)
    at ccall (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js:9:6765)
    at eval (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.js:9:7337)
    at kernelFunc (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/dist/kernels/binary_kernel.js:52:34)
    at Object.kernelFunc (webpack-internal:///./node_modules/@tensorflow/tfjs-backend-wasm/dist/kernels/binary_kernel.js:55:13)
    at kernelFunc (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:455:30)
    at eval (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:519:27)
    at Engine.scopedRun (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:348:25)
    at Engine.runKernelFunc (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:517:14)
    at Engine.runKernel (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:406:21)
    at div_ (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/ops/div.js:65:59)
    at div__op (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:49:28)
    at Tensor._tensor__WEBPACK_IMPORTED_MODULE_1__.Tensor.div (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/public/chained_ops/div.js:24:64)
    at eval (eval at ransacRodeSegment (webpack-internal:///./src/views/tool/editor/ai/pointcloud/rodeSegment.js), <anonymous>:1:23)
```

**Comment by annxingyuan** [comment]
Could you please provide the version numbers of other tfjs packages you're using on this page (e.g. tfjs-core, tfjs)? I suspect this has to do with a version mismatch (earlier versions of tfjs-core do not export RealDiv).

**Comment by rthadur** [comment]
I tried in latest version with div using wasm backend and it was working as expected , can you please check the latest version ?
