### ISSUE TITLE
Failure to Convert Tensorflow Saved Model to model.json ValueError: cannot create an OBJECT array from memory buffer

### ISSUE THREAD

**Issue by taposh** [tensorflow/tfjs#4466]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): pip installed
-  keras 2.2.4-tf
- tensorflow 2.1.0
- TensorFlow.js version (use command below): 2.8.1
- Browser version: chrome 87.0.4280.88
- Tensorflow.js Converter Version: 2.8.1

**Issue**
_**ValueError: cannot create an OBJECT array from memory buffer**_

**Describe the current behavior**
I have trained a model in Tensorflow and have saved the model. I want to convert the tf_saved_model to model.json 

Model is created using the following code:
```
num_steps_2=200
classifier2 = tf.estimator.DNNClassifier(
    feature_columns=create_feature_columns(input_features, feature_spec),
    hidden_units=[128, 64, 32])
classifier2.train(train_inpf, steps=num_steps_2)

#saving the model
import shutil
inputFn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
  tf.feature_column.make_parse_example_spec(feature_columns_needed))
OUTDIR = module_path
shutil.rmtree(OUTDIR, ignore_errors = True) # start fresh each timemodelBasePath = os.path.join(OUTDIR, "model")
modelPath = classifier2.export_saved_model(module_path, inputFn)
print("model is saved at :", modelPath)
```

I used the following command within my notebook:
`!tensorflowjs_converter --input_format=tf_saved_model --skip_op_check --saved_model_tags=serve --signature_name=serving_default --strip_debug_ops=True --weight_shard_size_bytes=4194304  "/Users/data/data/ckd/models/ckd_Dec-29-2020-00-00-00/1609297437/" "/Users/data/data/ckd/models/output/"`

I get the following error:
`2020-12-29 19:05:03.076396: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-12-29 19:05:03.092798: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8ee0ce94d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-29 19:05:03.092818: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING: Logging before flag parsing goes to stderr.
W1229 19:05:03.280285 4582796736 deprecation.py:506] From /Users/taposh/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1229 19:05:04.476931 4582796736 meta_graph.py:436] Issue encountered when serializing global_step.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
W1229 19:05:04.477355 4582796736 meta_graph.py:436] Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
W1229 19:05:04.477463 4582796736 meta_graph.py:436] Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
2020-12-29 19:05:04.477655: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-12-29 19:05:04.477732: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-12-29 19:05:04.486826: E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node dnn/input_from_feature_columns/input_layer/age_indicator_1/age_lookup/hash_table/table_init/LookupTableImportV2 doesn't exist in graph
W1229 19:05:04.489723 4582796736 deprecation.py:323] From /Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:388: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
W1229 19:05:04.827945 4582796736 deprecation.py:323] From /Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:393: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W1229 19:05:04.828099 4582796736 deprecation.py:323] From /Users/taposh/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2020-12-29 19:05:05.153410: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-12-29 19:05:05.153433: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   debug_stripper: debug_stripper did nothing. time = 0.022ms.
2020-12-29 19:05:05.153437: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   model_pruner: Graph size after: 502 nodes (-8), 597 edges (-8), time = 6.245ms.
2020-12-29 19:05:05.153441: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 498 nodes (-4), 593 edges (-4), time = 30.05ms.
2020-12-29 19:05:05.153444: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 272 nodes (-226), 593 edges (0), time = 9.77ms.
2020-12-29 19:05:05.153448: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 4.877ms.
2020-12-29 19:05:05.153451: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   model_pruner: Graph size after: 272 nodes (0), 593 edges (0), time = 2.654ms.
2020-12-29 19:05:05.153509: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 272 nodes (0), 593 edges (0), time = 9.233ms.
2020-12-29 19:05:05.153514: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 6.764ms.
2020-12-29 19:05:05.153517: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 4.599ms.
2020-12-29 19:05:05.153520: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   debug_stripper: debug_stripper did nothing. time = 0.66ms.
2020-12-29 19:05:05.153524: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   model_pruner: Graph size after: 272 nodes (0), 593 edges (0), time = 2.362ms.
2020-12-29 19:05:05.153527: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 272 nodes (0), 593 edges (0), time = 9.562ms.
2020-12-29 19:05:05.153707: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 6.718ms.
2020-12-29 19:05:05.153713: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 4.525ms.
2020-12-29 19:05:05.153716: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   model_pruner: Graph size after: 272 nodes (0), 593 edges (0), time = 2.69ms.
2020-12-29 19:05:05.153719: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 272 nodes (0), 593 edges (0), time = 9.015ms.
2020-12-29 19:05:05.153723: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 6.161ms.
2020-12-29 19:05:05.153869: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 272 nodes (0), 593 edges (0), time = 4.296ms.
2020-12-29 19:05:05.217058: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-12-29 19:05:05.217086: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   remapper: Graph size after: 265 nodes (-7), 586 edges (-7), time = 2.129ms.
2020-12-29 19:05:05.217091: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 265 nodes (0), 586 edges (0), time = 7.309ms.
2020-12-29 19:05:05.217095: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 265 nodes (0), 586 edges (0), time = 5.159ms.
2020-12-29 19:05:05.217099: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 265 nodes (0), 586 edges (0), time = 3.959ms.
2020-12-29 19:05:05.217102: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   remapper: Graph size after: 265 nodes (0), 586 edges (0), time = 2.478ms.
2020-12-29 19:05:05.217106: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 265 nodes (0), 586 edges (0), time = 8.296ms.
2020-12-29 19:05:05.217193: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   arithmetic_optimizer: Graph size after: 265 nodes (0), 586 edges (0), time = 6.055ms.
2020-12-29 19:05:05.217205: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   dependency_optimizer: Graph size after: 265 nodes (0), 586 edges (0), time = 4.521ms.
Traceback (most recent call last):
  File "/Users/taposh/anaconda3/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 652, in convert_tf_saved_model
    metadata=metadata)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 210, in optimize_graph
    initializer_graph_def, metadata=metadata)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 266, in extract_weights
    global_manifest = extract_const_nodes(graph_def.node)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 231, in extract_const_nodes
    'data': graph_rewrite_util.values_from_const(const)
  File "/Users/taposh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/graph_rewrite_util.py", line 62, in values_from_const
    tensor_value = tensor_util.MakeNdarray(input_tensor)
  File "/Users/taposh/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 598, in MakeNdarray
    dtype=dtype).copy().reshape(shape))
ValueError: cannot create an OBJECT array from memory buffer`

Added this on StackOverflow for more eyes:
https://stackoverflow.com/questions/65501730/tensorflowjs-converter-giving-valueerror-cannot-create-an-object-array-from-mem

**Describe the expected behavior**
expected model.json and weight files to be created in output location

**Comment by taposh** [comment]
Any work around for this?

**Comment by pyu10055** [comment]
@taposh Thank you for reporting this issue. It would be very helpful if you can provide the full code to allow us to reproduce the problem. If you can provide a colab or repl.it example would be great. thanks.

**Comment by taposh** [comment]
@pyu10055  here is my code in colab 

https://colab.research.google.com/drive/1cPmtlV7LMGAJ16WHBEeRko37zBNwWlda?usp=sharing

**Comment by taposh** [comment]
@pyu10055  were you able to review this?

**Comment by taposh** [comment]
@pyu10055  @rthadur any update on this bug !

**Comment by pyu10055** [comment]
Thank you for sharing the colab, I think the input dataset is missing:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-6f3b48cf182c> in <module>()
      6 csv_path = 'sample_data/train.csv'
      7 
----> 8 data = pd.read_csv(csv_path)
      9 # Set the column in the dataset you wish for the model to predict
     10 label_column = 'class'

4 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   2008         kwds["usecols"] = self.usecols
   2009 
-> 2010         self._reader = parsers.TextReader(src, **kwds)
   2011         self.unnamed_cols = self._reader.unnamed_cols
   2012 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'sample_data/train.csv'
```

**Comment by taposh** [comment]
The uploaded file gets removed on Colab when runtime is recycled. I will add code to read from my drive.

**Comment by taposh** [comment]
@pyu10055  code in colab is updated to read file directly from github. You will need to pass to tensorflow converter the file name manually since its on command/shell as opposed to in python.

**Comment by taposh** [comment]
@pyu10055 any update

**Comment by taposh** [comment]
@pyu10055  any update?

**Comment by pyu10055** [comment]
@taposh Sorry for the delay, I took a close look at your colab, I think the problem is caused by use tf.example as the input of the inference graph, which is not supported by TFJS right now. You need to create a signature that has input with the node after the tf.example has been processed. Here are some example code that might help you to create custom input function:

```
def _tfjs_serving_input_fn(feature_spec):
  """Creates an input function for TFJS-node serving."""
  def raw_transforming_serving_input_fn():
    placeholder_features = {}
    for name, value in feature_spec.items():
      batch_dim = tf.TensorShape([None])
      placeholder_features[name] = tf.compat.v1.placeholder(
          dtype=value.dtype,
          shape=batch_dim.concatenate(value.shape),
          name=name)

    return tf.estimator.export.ServingInputReceiver(placeholder_features,
                                                    placeholder_features)

  return raw_transforming_serving_input_fn

export_path = classifier.export_saved_model("trained-model", _tfjs_serving_input_fn(tf.feature_column.make_parse_example_spec(my_feature_columns)))
```
