### ISSUE TITLE
Kernel 'RotateWithOffset' not registered for backend 'tensorflow'

### ISSUE THREAD

**Issue by MiloAkerman** [tensorflow/tfjs#4606]
**System information**
- I have written custom code
- macOS Catalina 10.15.7
- TensorFlow.js installed from npm
- TensorFlow.js version 3.0.0
- Browser version: Not in browser
- Tensorflow.js Converter Version: 3.0.0

**Describe the current behavior**
When running project with Node backend "tensorflow", getting error:

```
(node:2424) UnhandledPromiseRejectionWarning: Error: Kernel 'RotateWithOffset' not registered for backend 'tensorflow'
    at Engine.runKernel(/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3053:19)
    at rotateWithOffset_ (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:20785:22)
    at Object.rotateWithOffset__op [as rotateWithOffset] (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3968:29)
    at HandPipeline.<anonymous> (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:161:49)
    at step (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:48:23)
    at Object.next (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:29:53)
    at fulfilled (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Describe the expected behavior**
Code works without errors

**Steps to reproduce the issue**

1. npm install @tensorflow/tfjs-node
2. Set tf backend to 'tensorflow'
3. Run standard example

**Other info / logs**
```
(node:2424) UnhandledPromiseRejectionWarning: Error: Kernel 'RotateWithOffset' not registered for backend 'tensorflow'
    at Engine.runKernel(/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3053:19)
    at rotateWithOffset_ (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:20785:22)
    at Object.rotateWithOffset__op [as rotateWithOffset] (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3968:29)
    at HandPipeline.<anonymous> (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:161:49)
    at step (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:48:23)
    at Object.next (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:29:53)
    at fulfilled (/Users/me/Documents/Projects/MCH/node_modules/@tensorflow-models/handpose/dist/pipeline.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rthadur** [comment]
@MiloAkerman tensorflow is not a backend , you might check this link for different backends used in tfjs 
https://www.tensorflow.org/js/guide/platform_environment

**Comment by MiloAkerman** [comment]
Alright. I got it fixed by dropping node completely and using sockets to communicate between the browser and my node process. Thank you

**Comment by hadidon** [comment]
@rthadur Do you have any plans to add it?
Thank you

**Comment by hadidon** [comment]
@rthadur Do you have any plans to add it?
Thank you

**Comment by rasti90** [comment]
I have the same problem. any update?

**Comment by brianhumphreys** [comment]
same issue but with "Kernel 'Log1p' " instead of "Kernel 'RotateWithOffset' "

**Comment by hyprstack** [comment]
Does this mean it's currently impossible to run the `@tensorflow-models/face-landmarks-detection` model on a node server? I'm trying to run it in an `expressJs` server to move the heavy lifting from the browser.

```
const tf = require("@tensorflow/tfjs-node");
const faceLandmarksDetection = require("@tensorflow-models/face-landmarks-detection");
const { Buffer } = require("buffer");

....

try {
      const model = await faceLandmarksDetection.load(
        faceLandmarksDetection.SupportedPackages.mediapipeFacemesh
      );
      const img = dataObj.data_url.replace(
        /^data:image\/(png|jpeg);base64,/,
        ""
      );
      const b = Buffer.from(img, "base64");
      const tensor = tf.node.decodeImage(b, 3);

      // Throws error => Error: Kernel 'RotateWithOffset' not registered for backend 'tensorflow'
      const preds = await model.estimateFaces({
        input: tensor,
      });
      console.log(preds);
    } catch (err) {
      console.log(err);
    }
```

**Comment by neckaros** [comment]
any update on this? would be very useful to imrpvoe face landmark detection

seems a solution was suggested in: https://github.com/tensorflow/tfjs/pull/3560#pullrequestreview-446508891 by @tafsiri if i understand correctly
