### ISSUE TITLE
tfjs-node 0.1.7 gives Invalid napi_status: A number was expected

### ISSUE THREAD

**Issue by dsmilkov** [tensorflow/tfjs#471]
On MacOS High Sierra (10.13.5) if I use tfjs-node 0.1.7 (0.1.6 works fine) I get
```
Error: Invalid napi_status: A number was expected
    at NodeJSKernelBackend.executeSingleOutput (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:114:43)
    at NodeJSKernelBackend.conv2d (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:468:21)
    at environment_1.ENV.engine.runKernel.x (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/conv.js:83:90)
    at Engine.runKernel (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/engine.js:73:22)
    at ConvOps.conv2d (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/conv.js:83:44)
    at /Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:11:61
    at Object.Tracking.tidy (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/tracking.js:36:22)
    at Function.descriptor.value [as conv2d] (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:11:26)
    at ConvOps.conv1d (/Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/conv.js:44:27)
    at /Users/smilkov/Downloads/node-examples/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:11:61
```

**Comment by dsmilkov** [comment]
The issue is due to tfjs-layers incorrectly deserializing the `dilation_rate` in model.json and calling conv2d in core with dilation being `[1, [1]]` instead of [1, 1]. This value gets passed verbatim to the TF C bindings, at which point it fails since it expects a [number, number].

There are two PRs already in layers that are going to fix this issue:
- https://github.com/tensorflow/tfjs-layers/pull/245
- https://github.com/tensorflow/tfjs-layers/pull/248

We'll close this as soon as one of them gets in.
