### ISSUE TITLE
[tfjs-react-native] Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'a.substr')

### ISSUE THREAD

**Issue by kaykhancheckpoint** [tensorflow/tfjs#4806]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 20.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `Pixel_3a_API_30_x86.avd`
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version: `npm install @tensorflow/tfjs`, 
- CUDA/cuDNN version:

**Describe the problem**

I'm trying to run some sample function found in your documentation https://js.tensorflow.org/api/latest/#tf.LayersModel.fit in a react-native-app.

if i run this example on the web executing `npm run web` and check the browser window it loads, it works fine.

If however i run the same example by running `npm run web` then scan the QR code using my android phone, or if i hit `a` to run a android emulator, in both cases i get the following error. `[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'a.substr')]`

What is it about the function `do_training_example` that ive introduced that it does not like when running via the QR code on my phone or via the emulator. If i remove this function the error goes.

```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'a.substr')]
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3754:8 in isMobile
at node_modules/@tensorflow/tfjs-backend-webgl/dist/tf-backend-webgl.node.js:1043:17 in <global>
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:161631:39 in get
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:249141:41 in runWebGLProgram
at node_modules/@tensorflow/tfjs-backend-webgl/dist/tf-backend-webgl.node.js:5217:12 in MathBackendWebGL.prototype.uploadToGPU
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:249103:25 in <unknown>
at [native code]:null in map
at node_modules/@tensorflow/tfjs-backend-webgl/dist/tf-backend-webgl.node.js:5016:8 in MathBackendWebGL.prototype.runWebGLProgram
at node_modules/@tensorflow/tfjs-backend-webgl/dist/tf-backend-webgl.node.js:8060:37 in int
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:163816:35 in kernelFunc
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3199:17 in scopedRun$argument_2
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3011:12 in Engine.prototype.scopedRun
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3195:12 in Engine.prototype.runKernelFunc
at node_modules/@tensorflow/tfjs/dist/tf.node.js:3548:12 in f2
at node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:24702:13 in tfc.tidy$argument_0
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3001:126 in scopedRun$argument_2
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3011:12 in Engine.prototype.scopedRun
at [native code]:null in map
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3001:126 in scopedRun$argument_2
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3011:12 in Engine.prototype.scopedRun
at node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:24838:87 in tfc.tidy$argument_0
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3001:126 in scopedRun$argument_2
at node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3011:12 in Engine.prototype.scopedRun
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:206783:36 in <unknown>
at http://192.168.1.104:19001/index.bundle?platform=android&dev=true&hot=false&minify=false:199674:24 in step
at node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16694:22 in step
at node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16694:22 in step
at node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16681:40 in fulfilled
at node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
at node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Any other info / logs**

You can see ive only added the function `do_training_example` and executing that within the `componentDidMount`

App.tsc

```
import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';
import React, { Component } from 'react';
import { Text, View } from 'react-native';
export default class App extends React.Component {
    constructor(props: any) {
        super(props);
        this.state = {
            isTfReady: false,
        };
    }

    async componentDidMount() {
        // Wait for tf to be ready.
        await tf.ready();

        // Signal to the app that tensorflow.js can now be used.
        this.setState({
            isTfReady: true,
        });


        await this.do_training_example();

    }

    do_training_example = async () => {

        const model = tf.sequential({
            layers: [tf.layers.dense({ units: 1, inputShape: [10] })]
        });
        model.compile({ optimizer: 'sgd', loss: 'meanSquaredError' });
        for (let i = 1; i < 5; ++i) {
            const h = await model.fit(tf.ones([8, 10]), tf.ones([8, 1]), {
                batchSize: 4,
                epochs: 3
            });
            console.log("Loss after Epoch " + i + " : " + h.history.loss[0]);
        }

    }


    render() {
        return (
          <View style={{
              flex: 1,
              justifyContent: "center",
              alignItems: "center"
            }}>
            <Text>Hello, world!</Text>
          </View>
        );
    }
}
```

**Comment by carrycooldude** [comment]
I think so promise is here rejecting and you have to use catch for that may be that can be issue but further can you share the link so that I can see and I will give you update on that

**Comment by kaykhancheckpoint** [comment]
@carrycooldude Ye the error message does say promise rejection, im wondering why. Sorry which link do you want me to share you with?

To recreate it, you can just simply use a blank project with tf react native setup and then copy the code in App.js.

Theres nothing else ive added, only the function `do_training_example` which is code i obtained from official docs https://js.tensorflow.org/api/latest/#tf.LayersModel.fit.

**Comment by carrycooldude** [comment]
> @carrycooldude Ye the error message does say promise rejection, im wondering why. Sorry which link do you want me to share you with?
> 
> To recreate it, you can just simply use a blank project with tf react native setup and then copy the code in App.js.
> 
> Theres nothing else ive added, only the function `do_training_example` which is code i obtained from official docs https://js.tensorflow.org/api/latest/#tf.LayersModel.fit.

Okay Let me Try

**Comment by kaykhancheckpoint** [comment]
@carrycooldude im still struggling with this, ive not found out why this is happening. Any ideas?

**Comment by dhiogocorrea** [comment]
@kaykhancheckpoint I was having the save issue with the last @tensorflow/tfjs version (3.2.0) . Downgrading to version 3.0.0 fixed the problem for me

**Comment by kaykhancheckpoint** [comment]
@dhiogocorrea Right, so this is a bug that needs to be fixed as oppose to something i am doing wrong in the setup/build process.

**Comment by kaykhancheckpoint** [comment]
Can confirm after downgrading @tensorflow/tfjs from 3.3.0 to 3.0.0 it works now.

**Comment by sojitko** [comment]
Same here on `expo` while using `expo-gl`. It seems that `tensorflow > 3.0.0` have issues with environment detection.

If you don't want to downgrade and you can wait until this is fixed, knowing your app is only going to run on mobile, you can place this code early in your program to avoid this error:
```
/**
 * Original functions throw an error in:
 * @tensorflow/tfjs-core/dist/tf-core.node.js:3749
 * This may be related to TFJS as it for some reason tries to load node webgl
 * code instead of using expo-gl bridge.
 * Not sure how to figure it out so here's a workaround.
 */
tf.device_util.isMobile = () => true
tf.device_util.isBrowser = () => false
```

**Comment by carrycooldude** [comment]
Yes true this is bug , Version issue

**Comment by mattsoulanille** [comment]
Thanks for the investigation, everyone! It looks like this is caused by the new `WEBGL_FLUSH_THRESHOLD` flag that increases Android webgl performance. [It makes a call to `device_util.isMobile()`](https://github.com/tensorflow/tfjs/compare/tfjs_3.0.0...tfjs_3.3.0#diff-9aa17bb319dc06c7d44dd006aec2c352e14f6ae104296fc9b31ca633def1549eR203) to determine whether it should be enabled or not, and when that call is removed (and replaced with `return 1`), the react native backend works. I'm looking into why this call causes the error.

**Comment by WoodburyShortridge** [comment]
for those wanting to use @tensorflow/tfjs-core 3.3.0 on react native here's a patch:

```
diff --git a/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js b/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
index b058771..5d3b9ca 100644
--- a/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
+++ b/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js
@@ -3749,22 +3749,10 @@ function _isNavigatorDefined() {
     return typeof navigator !== 'undefined' && navigator != null;
 }
 function isMobile() {
-    if (_isNavigatorDefined()) {
-        // tslint:disable-next-line:no-any
-        var a = navigator.userAgent || navigator.vendor || window.opera;
-        // tslint:disable-next-line:max-line-length
-        return /(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i
-            .test(a) ||
-            // tslint:disable-next-line:max-line-length
-            /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i
-                .test(a.substr(0, 4));
-    }
-    return false;
+    return true;
 }
 function isBrowser() {
-    return (typeof window !== 'undefined' && window.document != null) ||
-        //@ts-ignore
-        (typeof WorkerGlobalScope !== 'undefined');
+    return false;
 }
 
 var device_util = {
```

**Comment by MareSeestern** [comment]
Choosing a backend with

`tf.setBackend('cpu')`

solved the problem for me.
