### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization IsNan

### ISSUE THREAD

**Issue by sandhyacs** [tensorflow/tfjs#4886]
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model . graph 

2021-03-31 13:03:49.628617: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.1/lib64
2021-03-31 13:03:49.628834: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-31 13:03:59.920206: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-31 13:03:59.941365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-31 13:03:59.945658: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-31 13:03:59.945774: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sandhya): /proc/driver/nvidia/version does not exist
2021-03-31 13:03:59.956323: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-31 13:04:24.523446: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-03-31 13:04:24.523698: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-03-31 13:04:24.524016: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-31 13:04:24.545770: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2199995000 Hz
2021-03-31 13:04:24.971406: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 1955 nodes (1626), 4919 edges (4583), time = 246.469ms.
  function_optimizer: function_optimizer did nothing. time = 11.713ms.

Traceback (most recent call last):
  File "/home/sandhya/anaconda3/envs/test_conv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 652, in convert_tf_saved_model
    metadata=metadata)
  File "/home/sandhya/anaconda3/envs/test_conv/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 148, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
IsNan

- TensorFlow.js installed from (npm or script link): 3.3.0
- TensorFlow.js version (use command below): 3.3.0

- Tensorflow.js Converter Version: 3.3.0

**Comment by rthadur** [comment]
Hi @sandhyacs , this op is added here https://github.com/tensorflow/tfjs/pull/4858 , these changes are not available in 3.3.0 , will be in next release. Thank you

**Comment by sandhyacs** [comment]
Hello,

When will latest version be release?

**Comment by rthadur** [comment]
Probably next week , Thank you
