### ISSUE TITLE
[tfjs-models] PoseNet demo cannot build successfully

### ISSUE THREAD

**Issue by haoyunfeix** [tensorflow/tfjs#4921]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Window 10, Ubuntu 20.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow.js installed from (npm or script link): **npm**
- TensorFlow.js version: **3.3.0**
- CUDA/cuDNN version:

**Describe the problem**
Cannot start the posenet demo by 'yarn watch'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. `git clone https://github.com/tensorflow/tfjs-models && cd tfjs-models/posenet`
2. `yarn && yarn build`
3. `cd demo && yarn && yarn watch`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
yunfei@yunfei-bj:~/00_yunfei/workspace/github/tfjs-models/posenet/demo$ yarn watch
yarn run v1.22.5
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234
🚨  /home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/coco.js: function __clone() {
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    var node2 = new Node();
    for (var key in this) {
      // Do not clone comments tha...<omitted>... } could not be cloned.
    at Object.serialize (v8.js:257:7)
    at _default (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/@babel/core/lib/transformation/util/clone-deep.js:16:30)
    at normalizeFile (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/@babel/core/lib/transformation/normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/@babel/core/lib/transform-ast.js:20:41)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/gensync/index.js:251:28)
    at Function.sync (/home/yunfei/00_yunfei/workspace/github/tfjs-models/posenet/demo/node_modules/gensync/index.js:89:14)
```

This regression issue happens after https://github.com/tensorflow/tfjs-models/commit/048e44d6a2bae18023e317cc7115f543de9b370c, I don't know the root cause but https://github.com/tensorflow/tfjs-models/pull/637 will fix this build error by revert @babel/core to 7.6.4

**Comment by haoyunfeix** [comment]
@pyu10055 @lina128 PTAL, Thanks

**Comment by rthadur** [comment]
@haoyunfeix thanks for reporting, I can confirm the same issue on Mac OS , @pyu10055 @lina128 should we revert the babel/core version ? if yes I can submit a PR
