### ISSUE TITLE
[wasm]  Error downloading wasm-binaries.tbz2 when yarn build or build-npm

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#4936]
In windows, under tfjs-backend-wasm folder,  yarn build(or build-npm) failed due to Error downloading.
In linux, everything goes well.

When I tried yarn build-npm, it complains:
```
Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2] to C:/users/abc/_bazel_abc/js5lmfgj/external/emscripten_bin_win/temp12762910739068097029/wasm-binaries.tbz2.tar.bz2: GET returned 404 Not Found
```
It seems  file https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2 can not be downloaded by chrome. 
And https://storage.googleapis.com/webassembly doesn't contains windows build.

Then I tried (a cmd used in yarn build):
```
yarn bazel build -c opt //tfjs-backend-wasm/src/cc:tfjs-backend-wasm 
```

It also complains the same file 404:
```
C:\workspace\wasm\tfjs\tfjs-backend-wasm>yarn bazel build -c opt //tfjs-backend-wasm/src/cc:tfjs-backend-wasm
yarn run v1.22.5
$ C:\workspace\wasm\tfjs\tfjs-backend-wasm\node_modules\.bin\bazel build -c opt //tfjs-backend-wasm/src/cc:tfjs-backend-wasm
INFO: Repository emscripten_bin_win instantiated at:
  C:/workspace/wasm/tfjs/WORKSPACE:27:22: in <toplevel>
  C:/users/abc/_bazel_abc/js5lmfgj/external/emsdk/emscripten_deps.bzl:48:21: in emscripten_deps
Repository rule http_archive defined at:
  C:/users/abc/_bazel_abc/js5lmfgj/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2 failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'emscripten_bin_win':
   Traceback (most recent call last):
        File "C:/users/abc/_bazel_abc/js5lmfgj/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2] to C:/users/abc/_bazel_abc/js5lmfgj/external/emscripten_bin_win/temp14758550607092921566/wasm-binaries.tbz2.tar.bz2: GET returned 404 Not Found
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/abc/_bazel_abc/js5lmfgj/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2] to C:/users/abc/_bazel_abc/js5lmfgj/external/emscripten_bin_win/temp14758550607092921566/wasm-binaries.tbz2.tar.bz2: GET returned 404 Not Found
INFO: Repository nodejs_windows_amd64 instantiated at:
  C:/workspace/wasm/tfjs/WORKSPACE:9:13: in <toplevel>
  C:/users/abc/_bazel_abc/js5lmfgj/external/build_bazel_rules_nodejs/index.bzl:77:23: in yarn_install
  C:/users/abc/_bazel_abc/js5lmfgj/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:757:15: in node_repositories
  C:/users/abc/_bazel_abc/js5lmfgj/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:777:18: in _maybe
Repository rule node_repositories_rule defined at:
  C:/users/abc/_bazel_abc/js5lmfgj/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:696:41: in <toplevel>
ERROR: C:/users/abc/_bazel_abc/js5lmfgj/external/emsdk/BUILD:27:6: @emsdk//:binaries depends on @emscripten_bin_win//:all in repository @emscripten_bin_win which failed to fetch. no such package '@emscripten_bin_win//': java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.tbz2] to C:/users/abc/_bazel_abc/js5lmfgj/external/emscripten_bin_win/temp14758550607092921566/wasm-binaries.tbz2.tar.bz2: GET returned 404 Not Found
ERROR: Analysis of target '//tfjs-backend-wasm/src/cc:tfjs-backend-wasm' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.663s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
    Fetching @emscripten_npm_win; Restarting.
    Fetching @xnnpack; Cloning 3bfbdaf00211b313b143af39279bb6bf1f7effc0 of https://github.com/google/XNNPACK.git
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System information**
- TensorFlow.js version: commit 081b28468bf18505326b543f1ec450d725e1dbb4 (HEAD -> master, origin/master, origin/HEAD)
Date:   Wed Apr 14 20:04:45 2021 -0700

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mattsoulanille** [comment]
Thanks for reporting this.

I'm setting up a VM to reproduce it, and I've talked to the author of the Emscripten rules. We have found out that it's caused by an incorrect extension on the download. It should end in `.zip` instead of `.tbz2` for Windows. For example, https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/89202930a98fe7f9ed59b574469a9471b0bda7dd/wasm-binaries.zip, should be downloadable. I'll send a patch to Emscripten once I get it working. However there may be some other Windows comparability issues other than having an incorrect URL, so I can't guarantee this will be a quick fix.

As a workaround, you can use [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by axinging** [comment]
Thanks @mattsoulanille! Then I will close this first.
