### ISSUE TITLE
Delete called on a Tensor not referenced with Node.js worker_threads

### ISSUE THREAD

**Issue by sudo-carson** [tensorflow/tfjs#4947]
Using `tf.tidy` in a Node.js worker thread sometimes causes `Error: Delete called on a Tensor not referenced` if two instances of the thread are running at the same time.

- OS: Windows 10 20H2
- TensorFlow.js version: v3.3.0
- Node version: v14.16.0

```js
// master.js
const { Worker } = require('worker_threads');

const w1 = new Worker('worker.js');
const w2 = new Worker('worker.js');

// worker.js
const { tidy, scalar } = require('@tensorflow/tfjs-node');

tidy(() => {
    const s = scalar(3.14);
});
```

```
Error: Delete called on a Tensor not referenced (tensor_id: 2392)
    at Object.<anonymous> (<anonymous>)
    at NodeJSKernelBackend.disposeData (node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:264:30)
    at Engine.disposeTensor (node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3381:26)
    at Tensor.dispose (node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:2361:21)
    at Engine.scopedRun (node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3017:13)
    at Engine.tidy (node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:3001:21)
    at Object.tidy (node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:8744:19)
```

**Comment by rthadur** [comment]
related PR has been merged , @bmcdorman thanks for the contribution.
