### ISSUE TITLE
import statement error

### ISSUE THREAD

**Issue by NamanPrakash** [tensorflow/tfjs#4987]
whenever I build the project i get this error:
```
(node:21078) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/Me/Documents/NumberRecognition/node_modules/@tensorflow/tfjs-core/dist/public/chained_ops/register_all_chained_ops.js:17
import './abs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Me/Documents/NumberRecognition/node_modules/@tensorflow/tfjs-vis/dist/index.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```
I'm using `node.js` so I tried to insert
```json
"type": "module"
```
but this doesn't work for me either.
so please help.

**Comment by NamanPrakash** [comment]
Nobody is responding so im closing
