### ISSUE TITLE
TypeError: backend.unsortedSegmentSum is not a function

### ISSUE THREAD

**Issue by juhanitolvanen** [tensorflow/tfjs#500]
#### TensorFlow.js version
@tensorflow/tfjs: 0.12.0
@tensorflow/tfjs-node: 0.1.7

#### Browser version
- (Node.js v8.10.0)

#### Describe the problem
I receive the following error:
- when using with @tensorflow/tfjs-node
- after have successfully compiled a sequential model with tf.layers.conv2d and tf.layers.maxPooling2d, and
- when start fitting the model with training data

I can compile and fit the model without tfjs-node (it takes forever to train, though) - so there should not be problems with model or data.

`
(node:24146) UnhandledPromiseRejectionWarning: TypeError: backend.unsortedSegmentSum is not a function
    at environment_1.ENV.engine.runKernel.$x (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/ops/segment_ops.js:35:28)
    at Engine.runKernel (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/engine.js:101:22)
    at SegmentOps.unsortedSegmentSum (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/ops/segment_ops.js:34:41)
    at /Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:11:77
    at Engine.tidy (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/engine.js:83:22)
    at Function.Environment.tidy (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/environment.js:49:35)
    at Function.descriptor.value [as unsortedSegmentSum] (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:11:42)
    at Object.derX [as $x] (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/ops/segment_ops.js:47:39)
    at Object.backpropagateGradients (/Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/tape.js:81:47)
    at /Users/XXXXXXXXXXXXX/node_modules/@tensorflow/tfjs-core/dist/engine.js:274:20
`

**Comment by caisq** [comment]
Any thoughts, @nkreeger ?

**Comment by kangyizhang** [comment]
Hi @juhanitolvanen can you try with the latest version of tfjs-node? We have some updates after @0.1.7
I just tried with a model with tf.layers.conv2d and tf.layers.maxPooling2d, also only run this function without any issue.

**Comment by juhanitolvanen** [comment]
Seems to be working!

**Comment by kangyizhang** [comment]
Glad to hear that it works!
