### ISSUE TITLE
bug/error when installing tfjs-node

### ISSUE THREAD

**Issue by tewni-svg** [tensorflow/tfjs#5066]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10
- TensorFlow.js installed from "npm install `npm i @tensorflow/tfjs-node`
- TensorFlow.js version latest:

**Describe the problem**
after:
`const tfnode = require('@tensorflow/tfjs-node')`

I get:
```

D:\StarCon\src>electron .

node-pre-gyp info This Node instance does not support builds for N-API version 8
node-pre-gyp info This Node instance does not support builds for N-API version 8
App threw an error during load
Error: \\?\D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node is not a valid Win32 application.
\\?\D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
electron .

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\jaakk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'rebuild',
0 verbose cli   '@tensorflow/tfjs-node',
0 verbose cli   '--build-from-source',
0 verbose cli   '--python',
0 verbose cli   'C:\\Users\\jaakk\\AppData\\Local\\Programs\\Python\\Python39\\Python.exe'
0 verbose cli ]
1 info using npm@7.12.1
2 info using node@v12.19.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\StarCon\src\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\jaakk\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\jaakk\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 15ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
29 timing build:queue Completed in 0ms
30 info run @tensorflow/tfjs-node@3.6.1 install node_modules/@tensorflow/tfjs-node node scripts/install.js
31 info run @tensorflow/tfjs-node@3.6.1 install { code: 1, signal: null }
32 timing command:rebuild Completed in 2330ms
33 verbose stack Error: command failed
33 verbose stack     at ChildProcess.<anonymous> (C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
33 verbose stack     at ChildProcess.emit (events.js:314:20)
33 verbose stack     at maybeClose (internal/child_process.js:1021:16)
33 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
34 verbose pkgid @tensorflow/tfjs-node@3.6.1
35 verbose cwd D:\StarCon\src
36 verbose Windows_NT 10.0.19042
37 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jaakk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "@tensorflow/tfjs-node" "--build-from-source" "--python" "C:\\Users\\jaakk\\AppData\\Local\\Programs\\Python\\Python39\\Python.exe"
38 verbose node v12.19.1
39 verbose npm  v7.12.1
40 error code 1
41 error path D:\StarCon\src\node_modules\@tensorflow\tfjs-node
42 error command failed
43 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
44 error CPU-windows-3.6.1.zip
44 error node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
44 error node-pre-gyp info it worked if it ends with ok
44 error node-pre-gyp info using node-pre-gyp@1.0.5
44 error node-pre-gyp info using node@12.19.1 | win32 | x64
44 error node-pre-gyp info build requesting source compile
44 error gyp info it worked if it ends with ok
44 error gyp info using node-gyp@7.1.2
44 error gyp info using node@12.19.1 | win32 | x64
44 error gyp info ok
44 error node-pre-gyp info This Node instance does not support builds for Node-API version 8
44 error gyp info it worked if it ends with ok
44 error gyp info using node-gyp@7.1.2
44 error gyp info using node@12.19.1 | win32 | x64
44 error gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
44 error gyp ERR! find VS
44 error gyp ERR! find VS msvs_version was set from command line or npm config
44 error gyp ERR! find VS - looking for Visual Studio version 2015
44 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
44 error gyp ERR! find VS checking VS2019 (16.8.31005.135) found at:
44 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
44 error gyp ERR! find VS - found "Visual Studio C++ core features"
44 error gyp ERR! find VS - found VC++ toolset: v142
44 error gyp ERR! find VS - found Windows SDK: 10.0.18362.0
44 error gyp ERR! find VS - msvs_version does not match this version
44 error gyp ERR! find VS checking VS2017 (15.9.28307.1525) found at:
44 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
44 error gyp ERR! find VS - found "Visual Studio C++ core features"
44 error gyp ERR! find VS - found VC++ toolset: v141
44 error gyp ERR! find VS - found Windows SDK: 10.0.17763.0
44 error gyp ERR! find VS - msvs_version does not match this version
44 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
44 error gyp ERR! find VS looking for Visual Studio 2015
44 error gyp ERR! find VS - not found
44 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
44 error gyp ERR! find VS
44 error gyp ERR! find VS valid versions for msvs_version:
44 error gyp ERR! find VS - "2019"
44 error gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
44 error gyp ERR! find VS - "2017"
44 error gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
44 error gyp ERR! find VS
44 error gyp ERR! find VS **************************************************************
44 error gyp ERR! find VS You need to install the latest version of Visual Studio
44 error gyp ERR! find VS including the "Desktop development with C++" workload.
44 error gyp ERR! find VS For more information consult the documentation at:
44 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
44 error gyp ERR! find VS **************************************************************
44 error gyp ERR! find VS
44 error gyp ERR! configure error
44 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
44 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
44 error gyp ERR! stack     at C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
44 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
44 error gyp ERR! stack     at C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
44 error gyp ERR! stack     at C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
44 error gyp ERR! stack     at C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
44 error gyp ERR! stack     at C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
44 error gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
44 error gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
44 error gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
44 error gyp ERR! System Windows_NT 10.0.19042
44 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jaakk\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\StarCon\\src\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v7\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=D:\\StarCon\\src\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v7" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=7" "--node_napi_label=napi-v7" "--python=true" "--msvs_version=2015"
44 error gyp ERR! cwd D:\StarCon\src\node_modules\@tensorflow\tfjs-node
44 error gyp ERR! node -v v12.19.1
44 error gyp ERR! node-gyp -v v7.1.2
44 error gyp ERR! not ok
44 error node-pre-gyp ERR! build error
44 error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jaakk\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node --module_name=tfjs_binding --module_path=D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v7 --napi_version=7 --node_abi_napi=napi --napi_build_version=7 --node_napi_label=napi-v7 --python=true --msvs_version=2015' (1)
44 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\StarCon\src\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
44 error node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
44 error node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
44 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
44 error node-pre-gyp ERR! System Windows_NT 10.0.19042
44 error node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\StarCon\\src\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
44 error node-pre-gyp ERR! cwd D:\StarCon\src\node_modules\@tensorflow\tfjs-node
44 error node-pre-gyp ERR! node -v v12.19.1
44 error node-pre-gyp ERR! node-pre-gyp -v v1.0.5
44 error node-pre-gyp ERR! not ok
45 error * Building TensorFlow Node.js bindings
46 verbose exit 1

```

**Comment by tewni-svg** [comment]
Ok, so, I found a fix: I have to rebuild it, but, when i try to conifgure it: `gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp`

**Comment by rthadur** [comment]
@tewni-svg what version of node and tfjs-node you are using ? also can you run npm rebuild @tensorflow/tfjs-node build-addon-from-source in your repo and try again.or can rebuild from scratch.

**Comment by rthadur** [comment]
also please check a related issue here https://github.com/tensorflow/tfjs/issues/4171 , thank you

**Comment by tewni-svg** [comment]
> also please check a related issue here #4171 , thank you

Hey, thank you for responding. 

I did the rebuild, and checked the issue there. Also did the solutions provided there. Now I get this error:
`cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node is not a valid Win32 application.
\\?\D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v4\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:44:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)`

**Comment by tewni-svg** [comment]
> @tewni-svg what version of node and tfjs-node you are using ? also can you run npm rebuild @tensorflow/tfjs-node build-addon-from-source in your repo and try again.or can rebuild from scratch.

PS D:\StarCon\src> node --version
v14.17.0

And the latest tensorflow NPM one

**Comment by tewni-svg** [comment]
Now I have a new error
`D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\StarCon\src\AI\Objects\FindObjects.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)`

**Comment by tewni-svg** [comment]
oops, accidently closed it. My bad, reopened

**Comment by rthadur** [comment]
please check this issue for similar error https://github.com/tensorflow/tfjs/issues/2046#issuecomment-544616086 , are you using a win32 bit ?

**Comment by tewni-svg** [comment]
> please check this issue for similar error [#2046 (comment)](https://github.com/tensorflow/tfjs/issues/2046#issuecomment-544616086) , are you using a win32 bit ?

I have a 64bit machine

**Comment by tewni-svg** [comment]
> please check this issue for similar error [#2046 (comment)](https://github.com/tensorflow/tfjs/issues/2046#issuecomment-544616086) , are you using a win32 bit ?

PS D:\StarCon\src> node -p "process.arch"
ia32

**Comment by tewni-svg** [comment]
> please check this issue for similar error [#2046 (comment)](https://github.com/tensorflow/tfjs/issues/2046#issuecomment-544616086) , are you using a win32 bit ?

I have installed 32bit node, I am reinstalling the 64bit and will let you know. Thank you

**Comment by tewni-svg** [comment]
Okay, so. Now I get this error:
```S D:\StarCon> node -p "process.arch"
x64
PS D:\StarCon> cd src
PS D:\StarCon\src> node .\index.js
D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (D:\StarCon\src\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\StarCon\src\AI\Objects\FindObjects.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
PS D:\StarCon\src> ```

**Comment by tewni-svg** [comment]
HOLY SHIT, I ran the npm rebuild @tensorflow/tfjs-node --build-from-source  again and it works now! Holy fucking shit. It has taken over a week. Thank you! I never tought of reinstalling x64 version. Thank you!!!
 

Solution for anyone else:
Unistall Nodejs
Install 64BIT Of Nodejs
Run `npm rebuild @tensorflow/tfjs-node --build-from-source`
Enjoy

**Comment by tewni-svg** [comment]
Ok, f me. It worked for 1 launch LOL

Rebuilt made the V8 version, but it does not support the V8, how can I build the V7 one?
```D:\StarCon\src>electron .

node-pre-gyp info This Node instance does not support builds for N-API version 8
node-pre-gyp info This Node instance does not support builds for N-API version 8
App threw an error during load
Error: Cannot find module 'D:\StarCon\src\node_modules\@tensorflow\tfjs-node\lib\napi-v7\tfjs_binding.node'
Require stack:``

**Comment by tewni-svg** [comment]
k
