### ISSUE TITLE
Problem installing tfjs-node and tfjs-node-gpu on Windows

### ISSUE THREAD

**Issue by ai-machine-42** [tensorflow/tfjs#5124]
**System information**
- OS Platform and Distribution: Windows 10 20H2 (19042.985)
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.6.0
- CUDA/cuDNN version: 11.3/8.2

**Describe the problem**
Whenever I try installing tfjs-node (or tfjs-node-gpu) using npm (or yarn), I get the following error:
```
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.6.1.zip
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\node_modules\adm-zip\zipFile.js:107
npm ERR!                        throw new Error(Utils.Errors.INVALID_FORMAT);
npm ERR!                              ^
npm ERR!
npm ERR! Error: Invalid or unsupported zip format. No END header found
npm ERR!     at readMainHeader (C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\node_modules\adm-zip\zipFile.js:107:10)
npm ERR!     at new module.exports (C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\node_modules\adm-zip\zipFile.js:19:3)
npm ERR!     at new module.exports (C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\node_modules\adm-zip\adm-zip.js:20:11)
npm ERR!     at WriteStream.<anonymous> (C:\Users\usr\AppData\Roaming\npm\node_modules\@tensorflow\tfjs-node\scripts\resources.js:69:29)
npm ERR!     at WriteStream.emit (node:events:365:28)
npm ERR!     at emitCloseNT (node:internal/streams/destroy:174:10)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usr\AppData\Local\npm-cache\_logs\2021-05-25T19_59_31_630Z-debug.log
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
npm install -g @tensorflow/tfjs-node
```

**Comment by pyu10055** [comment]
@ai-machine-42 are you behind firewall, can you access files on google cloud storage?
https://storage.googleapis.com/

**Comment by ai-machine-42** [comment]
I am not sure, but this is what I get when I go to https://storage.googleapis.com/:
![image](https://user-images.githubusercontent.com/81181661/119780286-4b42a300-bed2-11eb-8462-90d31d105eeb.png)

**Comment by rthadur** [comment]
How about this https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html ? can you access ?

**Comment by ai-machine-42** [comment]
Apparently, my ISP blocks google cloud storage, so I used a VPN to bypass the blocking and now I can access it and the above error is gone. However, now I'm getting a new error:
```
npm ERR! code 1
npm ERR! path C:\Users\usr\Documents\repos\tfjs-test\node_modules\@tensorflow\tfjs-node
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! CPU-windows-3.6.1.zip
npm ERR! * Downloading libtensorflow
npm ERR! node:events:342
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR!
npm ERR! Error: read ECONNRESET
npm ERR!     at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
npm ERR! Emitted 'error' event on ClientRequest instance at:
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:365:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:193:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   errno: -4077,
npm ERR!   code: 'ECONNRESET',
npm ERR!   syscall: 'read'
npm ERR! }
```
and now I'm stuck here.
I've tried all the following but none helped:
* `npm config set registry "http://registry.npmjs.org/"` (using http instead of https)
* `npm config set strict-ssl false`
* using powershell as adminstrator

**Comment by rthadur** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-tfjs) since it is not a bug or feature request. There is also a larger community that reads questions there.
