### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Rutulpatel7077** [tensorflow/tfjs#514]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### Describe the problem or feature request

**_const net  = await posenet.load();  <== Getting error here..._**
```
async function machineLearning(imageElement) {
        const imageScaleFactor = 0.5;
        const flipHorizontal = true;
        outputStride: 16;

        const net  = await posenet.load();  <== Getting error here...
        const pose = await net.estimateSinglePose(imageElement, imageScaleFactor, flipHorizontal, outputStride);
        console.log(pose);
        return pose;
    }
```

**getting UnhandledPromiseRejectionWarning: ReferenceError : XMLHttpRequest is not defined
and then** 

```
at /Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:445:27
    at new Promise (<anonymous>)
    at CheckpointLoader.loadManifest (/Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/p
```

Getting Error on Promise

#### Code to reproduce the bug / link to feature request

Logs:

```
Listening on port 8080
(node:42295) UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined
    at /Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:445:27
    at new Promise (<anonymous>)
    at CheckpointLoader.loadManifest (/Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:444:20)
    at /Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:461:27
    at new Promise (<anonymous>)
    at CheckpointLoader.getCheckpointManifest (/Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:460:24)
    at /Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:478:23
    at new Promise (<anonymous>)
    at CheckpointLoader.getAllVariables (/Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:477:20)
    at Object.<anonymous> (/Users/rpatel/dev/elvis/delete/express-babel/node_modules/@tensorflow-models/posenet/dist/posenet.js:922:53)
(node:42295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:42295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Rutulpatel7077** [comment]
Solved after  putting global variable in node_modules

**Comment by lucasgaspar22** [comment]
Can you please show where did you add this global variable?

**Comment by Rutulpatel7077** [comment]
@lucasgaspar22 

install **xhr2** 

`npm install xhr2`

and put this on first line of this file `node_modules/@tensorflow-models/posenet/dist/posenet.js`

**`global.XMLHttpRequest = require("xhr2");`**

**Comment by Rutulpatel7077** [comment]
@lucasgaspar22  Overall, my suggestion is to go back to python Tensorflow instead of using tf.js 

Because I personally feel they are still developing and you have to solve so many problems by your self.

**Comment by lucasgaspar22** [comment]
Thank you man. I agree with you. I'm just using node because my company
said I needed to .. :(


Thank you a million

2018-07-18 13:55 GMT-03:00 Rutul Patel <notifications@github.com>:

**Comment by Bluebie** [comment]
Why is this closed? I'm running in to the same issue today.
