### ISSUE TITLE
loadSavedModel() throws Error: The SavedModel does not have tags: serve

### ISSUE THREAD

**Issue by playground** [tensorflow/tfjs#5161]
running node v15.7.0, tfjs-node v3.6.1 on Mac Big Sur

This is happening with pre-trained or custom trained models

When try to load saved model with  
```
 const model = await tfnode.node.loadSavedModel(modelPath, 'serve', 'serving_default');
```
It's complaining 
```
Error: The SavedModel does not have tags: serve
```

```
    const modelInfo = await tfnode.node.getMetaGraphsFromSavedModel(modelPath);
    console.dir(modelInfo[0].signatureDefs.serving_default.outputs, { depth: null, maxArrayLength: null });

[ { tags: [ 'serve' ], signatureDefs: { serving_default: [Object] } } ]
{
  detection_anchor_indices: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:0',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 100 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  detection_boxes: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:1',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 100 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 4 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  detection_classes: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:2',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 100 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  detection_multiclass_scores: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:3',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 100 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  detection_scores: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:4',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 100 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  num_detections: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:5',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  raw_detection_boxes: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:6',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 49104 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 4 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  },
  raw_detection_scores: {
    dtype: 'float32',
    tfDtype: 'DT_FLOAT',
    name: 'StatefulPartitionedCall:7',
    shape: [
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 49104 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      },
      {
        wrappers_: null,
        messageId_: undefined,
        arrayIndexOffset_: -1,
        array: [ 1 ],
        pivot_: 1.7976931348623157e+308,
        convertedPrimitiveFields_: {}
      }
    ]
  }
}
```

if load saved model without optional arguments
```
const model = await tfnode.node.loadSavedModel(modelPath)
```
it throws 
```
2021-05-31 18:58:58.942711: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_model
2021-05-31 18:58:59.291324: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-05-31 18:58:59.291368: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_model
2021-05-31 18:59:00.692648: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-05-31 18:59:03.160455: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_model
2021-05-31 18:59:04.360189: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 5417477 microseconds.
2021-05-31 18:59:12.511652: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-05-31 18:59:12.511706: W tensorflow/core/framework/op_kernel.cc:1740] OP_REQUIRES failed at constant_op.cc:79 : Invalid argument: Cannot parse tensor from tensor_proto.
2021-05-31 18:59:12.546008: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-05-31 18:59:12.546526: W tensorflow/core/framework/op_kernel.cc:1740] OP_REQUIRES failed at constant_op.cc:79 : Invalid argument: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

/test-saved-model/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:449
        var outputMetadata = this.binding.runSavedModel(id, this.getMappedInputTensorIds(inputs, inputTensorInfos), inputTensorInfos.map(function (info) { return info.name; }).join(','), outputOpNames.join(','));
                                          ^

Error: Session fail to run with error: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}
```

**Comment by pvaneck** [comment]
First issue can be solved by putting `'serve'` in an array: `['serve']`. Perhaps tfjs-node could check the type of the input argument to check if it's an array and report a better error message if it isn't. However, looks like the key issue here is the `Cannot parse tensor from proto: dtype: DT_VARIANT`. Would be good to see if this dtype is something that can be supported in tfjs-node.

**Comment by playground** [comment]
Is there a work around until this is fixed?

**Comment by pyu10055** [comment]
@playground Does error generate c++ stacktrace, would be helpful to see which files are causing this tensor parsing error.

**Comment by playground** [comment]
@pyu10055 this is the entire error log in console

```
2021-06-03 14:13:41.525368: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: inference_graph/saved_model/
2021-06-03 14:13:41.851410: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-06-03 14:13:41.851648: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: inference_graph/saved_model/
2021-06-03 14:13:43.203539: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-06-03 14:13:45.510813: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: inference_graph/saved_model/
2021-06-03 14:13:46.612228: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 5086861 microseconds.
2021-06-03 14:13:53.786603: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-06-03 14:13:53.786650: W tensorflow/core/framework/op_kernel.cc:1740] OP_REQUIRES failed at constant_op.cc:79 : Invalid argument: Cannot parse tensor from tensor_proto.
2021-06-03 14:13:53.825515: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-06-03 14:13:53.827797: W tensorflow/core/framework/op_kernel.cc:1740] OP_REQUIRES failed at constant_op.cc:79 : Invalid argument: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

/img-recog/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:449
        var outputMetadata = this.binding.runSavedModel(id, this.getMappedInputTensorIds(inputs, inputTensorInfos), inputTensorInfos.map(function (info) { return info.name; }).join(','), outputOpNames.join(','));
                                          ^

Error: Session fail to run with error: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/map/TensorArrayV2_1/_0__cf__0}}]]
    at NodeJSKernelBackend.runSavedModel (/img-recog/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:449:43)
    at TFSavedModel.predict (/img-recog/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:344:37)
    at classify (/img-recog/classify.js:26:25)

```

**Comment by pyu10055** [comment]
@playground Looks like TensorList should have been a supported variant type
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/kernels/tensor_list.cc#L78

Is it possible to share your model forreproducing this problem? thanks

**Comment by playground** [comment]
@pyu10055 here is [the model ](https://drive.google.com/file/d/17PHaiPxtgBex0i-WZ0NrtGiAfZnt2ZKD/view?usp=sharing)

**Comment by pyu10055** [comment]
@playground This looks like a regression error from TensorFlow 2.4.1 binary, as we invesitgate more on the root causes, you can use tfjs-node version 3.3.0 as work around.
The model runs fine with v3.3.0.

**Comment by playground** [comment]
@pyu10055 thank you.

**Comment by playground** [comment]
@pyu10055 nm, I got it working.

**Comment by playground** [comment]
Will this be fixed in the next release?

**Comment by playground** [comment]
Looks like v3.8.0 fixed the issue for Raspberry Pi, I can loadSavedModel and is working as expected.  However, this version appears to have broken for MacOS.

V3.8 is throwing this error: Cannot parse tensor from proto: dtype: DT_VARIANT on Mac
```
2021-07-18 17:24:42.804288: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: ./model
2021-07-18 17:24:43.184558: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2021-07-18 17:24:43.184764: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: ./model
2021-07-18 17:24:44.791726: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-07-18 17:24:47.518694: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: ./model
2021-07-18 17:24:48.886901: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 6082930 microseconds.
loading time:  ./model, 10134.012591004372

2021-07-18 17:24:57.764441: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-07-18 17:24:57.764906: W tensorflow/core/framework/op_kernel.cc:1744] OP_REQUIRES failed at constant_op.cc:78 : Invalid argument: Cannot parse tensor from tensor_proto.
2021-07-18 17:24:57.822917: E tensorflow/core/framework/tensor.cc:555] Could not decode variant with type_name: "tensorflow::TensorList".  Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
2021-07-18 17:24:57.826111: W tensorflow/core/framework/op_kernel.cc:1744] OP_REQUIRES failed at constant_op.cc:78 : Invalid argument: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

Error: Session fail to run with error: Cannot parse tensor from proto: dtype: DT_VARIANT
tensor_shape {
}
variant_val {
  type_name: "tensorflow::TensorList"
  metadata: "\001\000\001\377\377\377\377\377\377\377\377\377\001\030\001"
}

         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/map/TensorArrayV2_1/_9__cf__9}}]]
    at NodeJSKernelBackend.runSavedModel (/object-detection/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:451:43)
    at TFSavedModel.predict (/object-detection/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:362:52)
    at Object.inference (/object-detection/index.js:96:36)
    at Object.checkImage (/object-detection/index.js:86:20)
    at Timeout._onTimeout (/object-detection/index.js:314:14)
```
