### ISSUE TITLE
tensorflow / tfjs-examples have a bug

### ISSUE THREAD

**Issue by starzhouchina** [tensorflow/tfjs#5210]
1.  tfjs-examples  have a bug:
D:\proj_tensorflow\tfjs-examples-master\mobilenet>yarn watch
yarn run v1.22.10
$ cross-env NODE_ENV=development parcel index.html --no-hmr --open
Server running at http://localhost:1234
×  D:\proj_tensorflow\tfjs-examples-master\mobilenet\cat.jpg: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (v8.js:256:7)
    at _default (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\util\clone-deep.js:16:30)
    at normalizeFile (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\normalize-file.js:52:36)
    at normalizeFile.next (<anonymous>)
    at run (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transformation\index.js:31:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\@babel\core\lib\transform-ast.js:20:41)
    at Generator.next (<anonymous>)
    at evaluateSync (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\gensync\index.js:251:28)
    at Function.sync (D:\proj_tensorflow\tfjs-examples-master\mobilenet\node_modules\gensync\index.js:89:14)

how to fix it?

**Comment by rthadur** [comment]
I ran mobilenet on MAC OS , it is running fine , could you please let us know the steps you were following ?

**Comment by starzhouchina** [comment]
I can run mobilenet  demo , it is Ok.  Thank you very much . This example it is OK.
Fixes #

**Comment by cTatu** [comment]
I just tried to run the mobilenet example and throws the same error. I tried it on my pc (opensuse) and also on a docker container with ubuntu, on both the same error:

```
🚨  /home/node/tfjs-examples/mobilenet/cat.jpg: function (prevType) {
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
  this.state.exprAllowed = false;

  if (prevType === types._let || prevType === types._c...<omitted>...
} could not be cloned.
    at Object.serialize (node:v8:333:7)
    at _default (/home/node/tfjs-examples/mobilenet/node_modules/@babel/core/lib/transformation/util/clone-deep.js:22:34)
    at normalizeFile (/home/node/tfjs-examples/mobilenet/node_modules/@babel/core/lib/transformation/normalize-file.js:79:36)
    at normalizeFile.next (<anonymous>)
    at run (/home/node/tfjs-examples/mobilenet/node_modules/@babel/core/lib/transformation/index.js:29:50)
    at run.next (<anonymous>)
    at Function.<anonymous> (/home/node/tfjs-examples/mobilenet/node_modules/@babel/core/lib/transform-ast.js:26:41)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/node/tfjs-examples/mobilenet/node_modules/gensync/index.js:251:28)
    at Function.sync (/home/node/tfjs-examples/mobilenet/node_modules/gensync/index.js:89:14)
```

**Comment by Chrono666** [comment]
Had the same problem with almost all of the examples.
What solved it for me was to remove the plugins from the .babelrc.
before:
`{
  "presets": [
    [
      "env",
      {
        "esmodules": false,
        "targets": {
          "browsers": [
            "> 3%"
          ]
        }
      }
    ]
  ],
  "plugins": [
    "transform-runtime"
  ]
}
`

after:
`{
  "presets": [
    [
      "env",
      {
        "esmodules": false,
        "targets": {
          "browsers": [
            "> 3%"
          ]
        }
      }
    ]
  ]
}`
I also used npm instead of yarn but I do not think this makes much of a difference.
I also did not try it for every example that didn't work but only on the visualize-convnet and data-generator examples.
