### ISSUE TITLE
Problem during conversion from efficientDet model

### ISSUE THREAD

**Issue by ChainYo** [tensorflow/tfjs#5211]
**System information**
- Custom traing on Tensorflow model
- Ubuntu 20.04 LTS / Google Colab (tried it too)
- Tensorflow == 2.5.0

I'm trying to convert an efficientdet model (I re trained it on my own dataset images) : efficientdet_d0_coco17_tpu-32
But it seems that the conversion is failing every time at the same point :

```bash
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 520, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 190, in dispatch_keras_saved_model_to_tensorflowjs_conversion
    model = tf.keras.models.load_model(keras_saved_model_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 155, in load
    keras_loader.finalize_objects()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 622, in finalize_objects
    _finalize_saved_model_layers(layers_revived_from_saved_model)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 820, in _finalize_saved_model_layers
    inputs = infer_inputs_from_restored_call_function(call_fn)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 1138, in infer_inputs_from_restored_call_function
    spec = nest.map_structure(common_spec, spec, spec2)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 867, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 867, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 1128, in common_spec
    common_shape = get_common_shape(x.shape, y.shape)
AttributeError: 'str' object has no attribute 'shape'
```

Is it due to TF v2.5.0. Should I downgrade it to 2.2 or 2.4 ?

This is the command I use to convert the model (SavedModel format)

```bash
!tensorflowjs_converter --input_format=keras_saved_model /content/inference_graph/saved_model /content/saved_model
```

**Comment by rthadur** [comment]
may be , please try with 2.4

**Comment by ChainYo** [comment]
> may be , please try with 2.4

I launch another training (could take some time, even on colab) and I come back.

**Comment by ChainYo** [comment]
News about the model conversion:

I tried it with `tensorflowjs_wizard` cli and it worked with the parameters used in this [blog post](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)

I was probably doing wrong by choosing `YES` when the cli asked for `Do you want to skip op validation`.

I'm going to try it on my web app and see if it's working for real, but the conversion is done finally without having to downgrade to `TF 2.4.0`.
Thanks for help!

**Comment by pyu10055** [comment]
@ChainYo if you skipped op validation, there is a chance that the model may contains unsupported op, which will give you run-time error during model execution.

**Comment by ChainYo** [comment]
> if you skipped op validation, there is a chance that the model may contains unsupported ops, which will give you run-time error during model execution.

Yes, I had some troubles today with the loading of the model in TFJS.

But I found the right way to get the right conversion done with this kind of command:
```bash
tensorflowjs_converter --input_format=tf_saved_model --output_node_names='EfficientDetV1' --saved_model_tags=serve ./saved_model ./web_model
```

It seems that a version upgrade + checking if the `--input_format` was right checked resolved the issue!
