### ISSUE TITLE
[tfjs-node-gpu] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked

### ISSUE THREAD

**Issue by OdaNeo** [tensorflow/tfjs#5249]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.7.0
- Browser version: node@14.17.0
- Tensorflow.js Converter Version:

- CUDA/cuDNN version: 11.3 / 8.2.0
- GPU model and memory: RTX 3060 Laptop 6GB
- GPU driver version: 471.11

**Describe the current behavior**
2021-06-24 13:58:37.573858: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRE
(node:6256) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 5
Message: No algorithm worked!
**Describe the expected behavior**
Should not met Error

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
1. import model add dataset. dataset was create by tf.data.generator and tf.tidy.
2. add 2 layers in model
3. use model.fitDataset()
```
const tf = require('@tensorflow/tfjs-node-gpu')
const getDate = require('./data')
const MOBILE_NET_URL =
    "https://ai-sample.oss-cn-hangzhou.aliyuncs.com/pipcook/models/mobilenet/web_model/model.json"
const main = async () => {
    // load data
    const { ds, classes } = await getDate()
    const mobileNet = await tf.loadLayersModel(MOBILE_NET_URL)
    const model = tf.sequential()
    for (let i = 0; i <= 86; i++) {
        const layer = mobileNet.layers[i]
        layer.trainable = false
        model.add(layer)
    }
    model.add(tf.layers.flatten())
    model.add(tf.layers.dense({
        units: 20,
        activation: 'relu'
    }))
    model.add(tf.layers.dense({
        units: classes.length,
        activation: 'softmax'
    }))
    model.compile({
        loss: "sparseCategoricalCrossentropy",
        optimizer: tf.train.adam(),
        metrics: ["acc"],
    })
    try {
        await model.fitDataset(ds, {
            epochs: 10
        })
    } catch (err) {
        console.log(err)
    }
    await model.save(`file://${process.cwd()}/output`)
}
main()
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
2021-06-24 14:22:12.419290: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-24 14:22:12.453128: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-24 14:22:12.454977: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-24 14:22:13.869883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 Laptop GPU computeCapability: 8.6
coreClock: 1.425GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2021-06-24 14:22:13.869982: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-24 14:22:13.876900: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-24 14:22:13.876976: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-24 14:22:13.879942: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-24 14:22:13.881137: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-24 14:22:13.883657: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-24 14:22:13.886437: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-24 14:22:13.887013: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-24 14:22:13.887114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-24 14:22:14.292530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-24 14:22:14.292627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-06-24 14:22:14.292669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-06-24 14:22:14.292820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4733 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-06-24 14:22:14.293200: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Epoch 1 / 10
2021-06-24 14:22:15.601251: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-24 14:22:17.073182: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-24 14:22:17.077511: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2021-06-24 14:22:17.077981: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!
Error: Invalid TF_Status: 5
Message: No algorithm worked!
    at NodeJSKernelBackend.executeSingleOutput (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\dist\nodejs_kernel_backend.js:211:43)
    at Object.conv2dImpl (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\dist\kernels\Conv2D.js:66:20)
    at Object.kernelFunc (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\dist\kernels\FusedConv2D.js:30:31)
    at kernelFunc (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4666:32)
    at C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4727:27
    at Engine.scopedRun (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4539:23)
    at Engine.runKernelFunc (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4723:14)
    at Engine.runKernel (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4595:21)
    at C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:21865:20
    at forwardFunc (C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5131:25)
```

I just find a similar Error in developer.nvidia.com. As the nvidia employee say, I shoud change the tf.config. But it dont work in tfjs-node-gpu.
```
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```
Here is the link:
https://forums.developer.nvidia.com/t/tensorflow-issue-op-requires-failed-at-conv-ops-fused-impl-h-697-not-found-no-algorithm-worked/167905

**Comment by rthadur** [comment]
@OdaNeo you need to run `yarn enable-gpu` to enable GPU locally.

**Comment by OdaNeo** [comment]
> @OdaNeo you need to run `yarn enable-gpu` to enable GPU locally.

I do it like this:
```
cd node_modules/@tensorflow/tfjs-node-gpu 
npm run enable-gpu
```
And I run this script successfully. Here is the log:
```
$ npm run enable-gpu

> @tensorflow/tfjs-node-gpu@3.7.0 enable-gpu C:\Users\***\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download && yarn && yarn build-addon-from-source

GPU-windows-3.7.0.zip
* Downloading libtensorflow
[==============================] 11323855/bps 100% 0.0s
* Building TensorFlow Node.js bindings
yarn install v1.22.10
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumsta
nces, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more inf
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@tensorflow/tfjs > @tensorflow/tfjs-data@3.7.0" has unmet peer dependency "seedrandom@~2.4.3".
[5/5] Building fresh packages...
success Saved lockfile.
$ node scripts/install.js gpu download
GPU-windows-3.7.0.zip
* Downloading libtensorflow
[==============================] 11306160/bps 100% 0.0s
* Building TensorFlow Node.js bindings
Done in 117.86s.
yarn run v1.22.10
$ node-pre-gyp install --build-from-source
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  tfjs_backend.cc
  win_delay_load_hook.cc
     Creating library C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\build\Release\tfjs_binding.lib and object C:\Users\ljpkw\Documents\CODE\js-ml
  -code\node_modules\@tensorflow\tfjs-node-gpu\build\Release\tfjs_binding.exp
  tfjs_binding.vcxproj -> C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\build\Release\\tfjs_binding.node  
  Copying C:\Users\ljpkw\Documents\CODE\js-ml-code\node_modules\@tensorflow\tfjs-node-gpu\build\Release\/tfjs_binding.node to C:/Users/ljpkw/Documents/CODE/js-ml-code/node_modules
  /@tensorflow/tfjs-node-gpu/lib/napi-v8\tfjs_binding.node
          1 file(s) copied.
Done in 3.72s.
```
But when I build my model, nothing changed, I still met Error.

**Comment by rthadur** [comment]
related to https://github.com/tensorflow/tfjs/issues/5249#issuecomment-868165040
