### ISSUE TITLE
Loading a LayersModel with the HTTP IOHandler does not produce the same result as loading it from file system

### ISSUE THREAD

**Issue by MaximeKjaer** [tensorflow/tfjs#5273]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04, Node 16.3.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.7.0
- Browser version: N/A
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**

Calling `model.fit` on a model that was loaded with `tf.loadLayersModel` from the filesystem works as expected.

However, doing the same thing on a model loaded from a HTTP URL fails with the message `The model needs to be compiled before being used`.

**Describe the expected behavior**

I would expect the above error not to happen. Ideally, loading a model should give the same result no matter where the model was loaded from.

**Standalone code to reproduce the issue**

First, unzip [my-model.zip](https://github.com/tensorflow/tfjs/files/6747283/my-model.zip), so that we have the following files:

- `my-model/model.json`
- `my-model/weights.bin`

Then, start a local HTTP server to serve the `my-model` directory locally:

```bash
python -m http.server --directory my-model
```

Finally, run the following script:

```js
const tf = require("@tensorflow/tfjs-node");
const fetch = require("node-fetch");

async function loadLocalModel() {
  const model = await tf.loadLayersModel(
    tf.io.fileSystem("my-model/model.json")
  );
  await model.fit(tf.ones([2, 28 * 28]), tf.zeros([2, 10]));
}

async function loadRemoteModel() {
  const model = await tf.loadLayersModel(
    tf.io.http("http://localhost:8000/model.json", {
      fetchFunc: fetch,
    })
  );
  await model.fit(tf.ones([2, 28 * 28]), tf.zeros([2, 10]));
}

async function run() {
  console.log("\n---- LOADING LOCAL MODEL ----\n");
  await loadLocalModel();
  console.log("\n---- LOADING REMOTE MODEL ----\n");
  await loadRemoteModel();
}

run();
```

**Other info / logs**

<details><summary>Output of <code>python -m http.server</code></summary>

```
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [01/Jul/2021 11:52:35] "GET /model.json HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2021 11:52:35] "GET /weights.bin HTTP/1.1" 200 -
```

</details>

<details><summary>Output of <code>node bug.js</code></summary>

```
2021-07-01 11:52:35.227362: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

---- LOADING LOCAL MODEL ----

Epoch 1 / 1
eta=0.0 =================================================================> 
100ms 49971us/step - acc=0.00 loss=0.00 

---- LOADING REMOTE MODEL ----

/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16779
        var _this = _super.call(this, message) || this;
                           ^

RuntimeError: The model needs to be compiled before being used.
    at new RuntimeError (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16779:28)
    at Sequential.<anonymous> (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:27575:27)
    at step (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16710:23)
    at Object.next (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16691:53)
    at /home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16684:71
    at new Promise (<anonymous>)
    at __awaiter (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:16680:12)
    at Sequential.fit (/home/maxime/code/tf-bug/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:27572:16)
    at loadRemoteModel (/home/maxime/code/tf-bug/bug.js:17:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

</details>

**Comment by MaximeKjaer** [comment]
I'm noticing that when using the HTTP IOHandler's `.load()` method, the `trainingConfig` field of the model JSON gets dropped. Seems like this could be a linked problem. I'll investigate a bit, and if the fix isn't too complicated, I'll submit a PR to solve this.
