### ISSUE TITLE
Don't automatically attempt to load webgl backend

### ISSUE THREAD

**Issue by DABH** [tensorflow/tfjs#540]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
0.12.3

#### Browser version
Node.js 10.6.0

#### Describe the problem or feature request
When I run a simple example with tfjs and tjfs-node in my terminal, I get warnings about tfjs failing to register the webgl backend.  But I don't care about that, I only want the node/cpu backend.  Is there a way to make tfjs _not_ attempt to register the webgl backend, or, to not throw those warnings/errors?

#### Code to reproduce the bug / link to feature request

```
import * as tf from '@tensorflow/tfjs';

// Node CPU backend
import '@tensorflow/tfjs-node';

...
    const sample: tf.Tensor1D = tf.tensor1d(new Array(5));
...
```

Errors:
```
  console.warn node_modules/@tensorflow/tfjs-core/dist/environment.js:186
    Registration of backend webgl failed

  console.warn node_modules/@tensorflow/tfjs-core/dist/environment.js:187
    Error: WebGL is not supported on this device
        at new MathBackendWebGL (/myrepo/node_modules/@tensorflow/tfjs-core/src/kernels/backend_webgl.ts:392:13)
        at /myrepo/node_modules/@tensorflow/tfjs-core/src/kernels/backend_webgl.ts:1316:22
        at Environment.Object.<anonymous>.Environment.registerBackend (/myrepo/node_modules/@tensorflow/tfjs-core/src/environment.ts:367:23)
        at Object.<anonymous> (/myrepo/node_modules/@tensorflow/tfjs-core/src/kernels/backend_webgl.ts:1315:7)
        at Runtime._execModule (/myrepo/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/myrepo/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/myrepo/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/myrepo/node_modules/@tensorflow/tfjs-core/src/index.ts:21:1)
        at Runtime._execModule (/myrepo/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/myrepo/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/myrepo/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/myrepo/node_modules/@tensorflow/tfjs/src/index.ts:18:1)
        at Runtime._execModule (/myrepo/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/myrepo/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/myrepo/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/myrepo/guide/optimizers/CrossEntropy.ts:10:1)
        at Runtime._execModule (/myrepo/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/myrepo/node_modules/jest-runtime/build/index.js:376:14)
        at Runtime.requireModuleOrMock (/myrepo/node_modules/jest-runtime/build/index.js:463:19)
        at Object.<anonymous> (/myrepo/guide/test/CrossEntropyTests.ts:3:1)
        at Runtime._execModule (/myrepo/node_modules/jest-runtime/build/index.js:694:13)
        at Runtime.requireModule (/myrepo/node_modules/jest-runtime/build/index.js:376:14)
        at /myrepo/node_modules/jest-jasmine2/build/index.js:129:13
        at Generator.next (<anonymous>)
        at step (/myrepo/node_modules/jest-jasmine2/build/index.js:170:30)
        at /myrepo/node_modules/jest-jasmine2/build/index.js:189:14
        at new Promise (<anonymous>)
        at /myrepo/node_modules/jest-jasmine2/build/index.js:167:12
        at jasmine2 (/myrepo/node_modules/jest-jasmine2/build/index.js:138:17)
        at /myrepo/node_modules/jest-runner/build/run_test.js:148:24
        at Generator.next (<anonymous>)
        at step (/myrepo/node_modules/jest-runner/build/run_test.js:270:30)
        at /myrepo/node_modules/jest-runner/build/run_test.js:281:15
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by axa2** [comment]
Maybe https://js.tensorflow.org/api/0.12.0/#setBackend ?

**Comment by DABH** [comment]
Thanks for your suggestion.  Unfortunately, even if I add a `setBackend` call to the backend I want, I still get the error about WebGL.  Very strange!  Any other ideas welcome!

One other possibly relevant thing is I'm running my code via `jest`, so I don't know if that messes up the environment at all -- feels like it shouldn't but just want to give all possible clues to figure out this issue.  Thanks again!

**Comment by bileschi** [comment]
@nkreeger do you know if there is a way to suppress this warning on systems where no GPU backend is expected?

**Comment by nkreeger** [comment]
@DABH which version of `@tensorflow/tfjs` and `@tensorflow/tfjs-node` are you using? Can you supply the full source in a Github gist? Can you also provide output from the Node app? Usually the backend will default to the JS-CPU backend if the node binding fails to load. This is strange that it is defaulting to GPU.

**Comment by nkreeger** [comment]
@DABH something looks off - do you mind hosting this entire project on GitHub and sharing the link here?

**Comment by DABH** [comment]
Here you go! https://github.com/DABH/tftest

(Un)Fortunately I get the same errors with this simple test project.  Run `yarn` to get packages and then `jest ./BasicTests.ts` to try to test.  Hope it's helpful, would love to get to the bottom of this!  Thanks!

**Comment by duhaime** [comment]
I experienced this behavior when importing tfjs-core in a static page that rendered a WebGL canvas on a Linux Mint 19.1 device running recent Chromium. There was no jest in this project...

**Comment by gildniy** [comment]
I got the same issue and for that, I had to add these lines in packages.json:

```
"@tensorflow/tfjs-node": "^3.15.0",
"@tensorflow/tfjs-node-gpu": "^3.15.0",
```

and this import in jest setup file
```
import '@tensorflow/tfjs-node'
```
