### ISSUE TITLE
Node binding not relocatable

### ISSUE THREAD

**Issue by jmorrell** [tensorflow/tfjs#542]
#### TensorFlow.js version
0.1.9

#### Describe the problem or feature request
When installing `@tensorflow/tfjs-node` via npm, the absolute path gets serialized into the installed module. This means that moving the app directory will cause the module to fail to find the bindings. 

This is an issue on Heroku where builds are performed in a different directory than that in which the application is deployed. This is the underlying cause in https://github.com/tensorflow/tfjs/issues/517

You can see the serialized absolute path in the file: `node_modules/@tensorflow/tfjs-node/package.json`

#### Code to reproduce the bug / link to feature request

You can reproduce this locally by installing `@tensorflow/tfjs-node` and then moving the app directory.

`package.json`
```
{
  "name": "tfjs-test",
  "dependencies": {
    "@tensorflow/tfjs-core": "^0.12.5",
    "@tensorflow/tfjs-node": "^0.1.9"
  }
}
```

`index.js`
```
require("@tensorflow/tfjs-node");
console.log("hello world");
```

#### Repro

```
~/support/tfjs-test
❯ npm install
...

~/support/tfjs-test
❯ node index.js
2018-07-24 12:40:36.003087: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
hello world
(node:54739) Warning: N-API is an experimental feature and could change at any time.

~/support/tfjs-test
❯ cd ..

~/support
❯ mv tfjs-test tfjs-test-moved

~/support
❯ cd tfjs-test-moved

~/support/tfjs-test-moved
❯ node index.js
Registration of backend tensorflow failed
Error: dlopen(/Users/jmorrell/support/tfjs-test-moved/node_modules/@tensorflow/tfjs-node/build/Release/tfjs_binding.node, 1): Library not loaded: @rpath/libtensorflow.so
  Referenced from: /Users/jmorrell/support/tfjs-test-moved/node_modules/@tensorflow/tfjs-node/build/Release/tfjs_binding.node
  Reason: image not found
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/jmorrell/support/tfjs-test-moved/node_modules/bindings/bindings.js:81:44)
    at /Users/jmorrell/support/tfjs-test-moved/node_modules/@tensorflow/tfjs-node/dist/index.js:8:60
    at Environment.registerBackend (/Users/jmorrell/support/tfjs-test-moved/node_modules/@tensorflow/tfjs-core/dist/environment.js:175:27)
    at Object.<anonymous> (/Users/jmorrell/support/tfjs-test-moved/node_modules/@tensorflow/tfjs-node/dist/index.js:7:9)
hello world
```

**Comment by rthadur** [comment]
Closing the issue as the commit has been pushed ,please feel free to reopen the issue if this has not been addressed.
