### ISSUE TITLE
[wasm]Error: Kernel 'Complex' not registered for backend 'wasm'

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5440]
Case: 
```
 it('complex', async () => {
    const real = tf.tensor1d([3, 30]);
    const imag = tf.tensor1d([4, 40]);
    const complex = tf.complex(real, imag);
    const res = tf.mul(complex, complex);
    expectArraysClose(await res.data(), [-7, 24, -700, 2400]);
  });
```
Error:
```
Step #23 - "test-wasm-tfjs-backend-wasm":   Message:
Step #23 - "test-wasm-tfjs-backend-wasm":     Error: Kernel 'Complex' not registered for backend 'wasm'
Step #23 - "test-wasm-tfjs-backend-wasm":   Stack:
Step #23 - "test-wasm-tfjs-backend-wasm":     Error: Kernel 'Complex' not registered for backend 'wasm'
Step #23 - "test-wasm-tfjs-backend-wasm":         at Engine.runKernel (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/engine.js:521:23)
Step #23 - "test-wasm-tfjs-backend-wasm":         at complex_ (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/complex.js:59:32)
Step #23 - "test-wasm-tfjs-backend-wasm":         at Object.complex__op [as complex] (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:79:33)
Step #23 - "test-wasm-tfjs-backend-wasm":         at /workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:125:38
Step #23 - "test-wasm-tfjs-backend-wasm":         at step (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:47:23)
Step #23 - "test-wasm-tfjs-backend-wasm":         at Object.next (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:28:53)
Step #23 - "test-wasm-tfjs-backend-wasm":         at /workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:22:71
Step #23 - "test-wasm-tfjs-backend-wasm":         at <Jasmine>
Step #23 - "test-wasm-tfjs-backend-wasm":         at __awaiter (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:18:12)
Step #23 - "test-wasm-tfjs-backend-wasm":         at UserContext.<anonymous> (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops_test.js:118:44)
Step #23 - "test-wasm-tfjs-backend-wasm":         at <Jasmine>
Step #23 - "test-wasm-tfjs-backend-wasm":         at runCallback (timers.js:705:18)
Step #23 - "test-wasm-tfjs-backend-wasm":         at tryOnImmediate (timers.js:676:5)
Step #23 - "test-wasm-tfjs-backend-wasm":         at processImmediate (timers.js:658:5)
Step #23 - "test-wasm-tfjs-backend-wasm":         at process.topLevelDomainCallback (domain.js:126:23)
Step #23 - "test-wasm-tfjs-backend-wasm": Pending:
```

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by Varun-S10** [comment]
Hi @axinging, Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @axinging, Thank you for your patience, we have reproduced the issue. As a workaround, you can compute the real and imaginary parts using standard real-number operations. Could you please try this and let us know if it works for you?
