### ISSUE TITLE
[wasm] Fail on pool avg with input 4,4,1

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5471]
Test case:
```
import * as tf from '@tensorflow/tfjs-core';
import {test_util} from '@tensorflow/tfjs-core';
import {describeWebGPU} from '../test_util';

const expectArraysClose = test_util.expectArraysClose;

describeWebGPU('pool', () => {
  it('x=[4,4,1] f=[1,1] s=2 d=1', async () => {
    // Feed forward.
    const a = tf.tensor3d(
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [4, 4, 1]);

    const windowShape = 1;
    const padding = 0;
    const dilationRate: number = undefined;
    const strides = 2;

    const result =
        tf.pool(a, windowShape, 'avg', padding, dilationRate, strides);

    expect(result.shape).toEqual([2, 2, 1]);
    expectArraysClose(await result.data(), [0, 2, 8, 10]);
  });
});
```

Error logs (From https://console.cloud.google.com/cloud-build/builds/ed8d8469-7e88-4c78-8eb7-2da1c55f7314;step=23?project=learnjs-174218):
```
Failures:
1) avgPool test-wasm {} x=[4,4,1] f=[1,1] s=2 d=1
  Message:
    Error: Arrays differ: actual[1] = 1.6412007614172258e-41, expected[1] = 2.
    Actual:   1.6412007614172258e-41,1.6412007614172258e-41,7.567011707354012e-44,7.371132602816832e-39.
    Expected: 0,2,8,10.
  Stack:
    Error: Arrays differ: actual[1] = 1.6412007614172258e-41, expected[1] = 2.
        at <Jasmine>
        at expectArraysPredicate (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/test_util.js:83:23)
        at expectArraysClose (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/test_util.js:37:16)
        at /workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/avg_pool_test.js:226:28
        at step (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/avg_pool_test.js:47:23)
        at Object.next (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/avg_pool_test.js:28:53)
        at fulfilled (/workspace/link-package-core/node_modules/@tensorflow/tfjs-core/dist/ops/avg_pool_test.js:19:58)
        at process._tickCallback (internal/process/next_tick.js:68:7)
Pending:
```

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
