### ISSUE TITLE
dynamic input sizes are not working with movenet multipose model and tfjs-node

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5515]
[MoveNet MultiPose model](https://storage.googleapis.com/movenet/MoveNet.MultiPose%20Model%20Card.pdf) was released and published on [TFHub](https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1)
  
model is advertised as working with dynamic input sizes, but that results in error during inference using `tfjs-node`:

```log
Error: Invalid TF_Status: 3
Message: output dimensions must be positive
    at NodeJSKernelBackend.executeSingleOutput (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-node@3.8.0/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:211:43)
    at Object.kernelFunc (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-node@3.8.0/node_modules/@tensorflow/tfjs-node/dist/kernels/ResizeBilinear.js:43:27)
    at kernelFunc (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.8.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4672:32)
    at /home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.8.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4733:27
```

editing input in `model.json` to use fixed size resolves the issue: `"tensorShape":{"dim":[{"size":"1"},{"size":"256"},{"size":"256"},{"size":"3"}]}}`

(original `model.json`:)

```json
  "signature": { 
    "inputs": { "input": {"name":"input:0","dtype":"DT_INT32","tensorShape":{"dim":[{"size":"1"},{"size":"-1"},{"size":"-1"},{"size":"3"}]}} },
    "outputs": { "output_0": {"name":"Identity:0","dtype":"DT_FLOAT","tensorShape":{"dim":[{"size":"1"},{"size":"6"},{"size":"56"}]}} }
  },
```

no issues running model using `tfjs-backend-webgl`

environment: tfjs 3.8.0 on ubuntu 21.10

**Comment by ahmedsabie** [comment]
@vladmandic I tested with the following code and got no issues, is there anything different than what you are running? I used tfjs-node 3.8.0

`const tf = require('@tensorflow/tfjs-node');`
 `const model = await tf.loadGraphModel(
    'https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1',
    {fromTFHub: true});`
 `const output =
    model.predict(tf.zeros([1, 256, 256, 3], 'int32'));`
`  console.log(output.dataSync());
`

**Comment by vladmandic** [comment]
@ahmedsabie try using any real JPG file, using synthetic input short-circuits model execution and is rarely useful when testing models.

```js
const fs = require('fs');
const tf = require('@tensorflow/tfjs-node');

async function main() {
  const buf = fs.readFileSync('inputs/model1.jpg');
  const tensor = tf.node.decodeJpeg(buf, 3).expandDims(0);
  const model = await tf.loadGraphModel('https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1', { fromTFHub: true });
  const res = model.predict(tensor);
  const data = await res.data();
  console.log(data);
}

main();
```

```text
Error: Invalid TF_Status: 3
Message: Incompatible shapes: [1,60,40,64] vs. [1,59,40,64]
    at NodeJSKernelBackend.executeSingleOutput (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-node@3.11.0/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:211:43)
    at Object.kernelFunc (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-node@3.11.0/node_modules/@tensorflow/tfjs-node/dist/kernels/Add.js:28:24)
    at kernelFunc (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4541:32)
    at /home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4602:27
    at Engine.scopedRun (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4406:23)
    at Engine.runKernelFunc (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4598:14)
    at Engine.runKernel (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4470:21)
    at add_ (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-converter@3.11.0_@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:11734:19)
    at add__op (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-converter@3.11.0_@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:11577:29)
    at executeOp$j (/home/vlado/dev/movenet/node_modules/.pnpm/@tensorflow+tfjs-converter@3.11.0_@tensorflow+tfjs-core@3.11.0/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:25858:21)
```

**Comment by ahmedsabie** [comment]
@vladmandic I retested with the following 256x256 image: https://bit.ly/3kQAQUH and the following code:
```js
  const buf = fs.readFileSync('man.jpg');
  const tensor = tf.cast(tf.image.resizeBilinear(tf.node.decodeJpeg(buf, 3), [256, 256]), 'int32').expandDims(0);
  console.log(tensor.shape);
  const model = await tf.loadGraphModel('https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1', { fromTFHub: true });
  const res = model.predict(tensor);
  const data = await res.data();
  console.log(data);
}

main();
```

No errors, can you try with the same image? I am wondering if the issue is with a specific image or with a specific platform.

**Comment by vladmandic** [comment]
256x256 is the only resolution thar works, any other resolution causes error. But model is published with variable resolution as input - so either fix the model to actually work with variable resolution or change model input definition to accept only 256!

**Comment by ahmedsabie** [comment]
@vladmandic The documentation asserts that input size must be 1xHxWx3, where H and W need to be a multiple of 32, so it does not support all shapes, nor does the model json being published with variable resolution indicate it taking any input size. I tested with the following code which asserts multiples of 32 work as expected.
```js
  for (let h = 32; w <= 512; h+=32) {
    for (let w = 32; w <= 512; w+=32) {
    const buf = fs.readFileSync('man.jpg');
    const tensor = tf.cast(tf.image.resizeBilinear(tf.node.decodeJpeg(buf, 3), [h, w]), 'int32').expandDims(0);
    console.log(tensor.shape);
    const model = await tf.loadGraphModel('https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1', { fromTFHub: true });
    const res = model.predict(tensor);
  const data = await res.data();
  console.log(data);
    }
  }
```

**Comment by vladmandic** [comment]
That's new - comment on "multiple of 32" was not there when I created this issue, now its in **BOLD** :)  

Given that its documented, its ok to close this issue
