### ISSUE TITLE
[tensorflowjs_converter] InvalidArgumentError: Cannot reshape a tensor with 1001 elements to shape [0,0] (0 elements)

### ISSUE THREAD

**Issue by huan** [tensorflow/tfjs#5517]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 20.04
- TensorFlow.js installed from (npm or script link): `pip install tensorflowjs`
- Tensorflow.js Converter Version:

```sh
$ tensorflowjs_converter  --version
tensorflowjs 3.8.0

Dependency versions:
  keras 2.6.0
  tensorflow 2.6.0
```

**Describe the current behavior**

```sh
$ tensorflowjs_converter \
>     --input_format=tf_frozen_model \
>     --output_node_names final_result \
>     ./tensorflowjs_model.pb \
>     ./web
Traceback (most recent call last):
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 1001 elements to shape [0,0] (0 elements) for '{{node MobilenetV1/Predictions/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](MobilenetV1/Logits/SpatialSqueeze, MobilenetV1/Predictions/Reshape/shape)' with input shapes: [1,1001], [2] and with input tensors computed as partial shapes: input[1] = [0,0].
```

**Describe the expected behavior**

Convert the frozen model to web format

**Standalone code to reproduce the issue**

```sh
$ git clone git@github.com:google/emoji-scavenger-hunt.git
$ cd emoji-scavenger-hunt/dist/model

$ ls -l
total 3568
-rw-rw-r-- 1 huan huan 3580716 Aug 18 00:37 group1-shard1of1
-rw-rw-r-- 1 huan huan   55746 Aug 18 00:37 tensorflowjs_model.pb
-rw-rw-r-- 1 huan huan    9489 Aug 18 00:37 weights_manifest.json

$ tensorflowjs_converter \
>     --input_format=tf_frozen_model \
>     --output_node_names final_result \
>     ./tensorflowjs_model.pb \
>     ./web
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```sh
$ tensorflowjs_converter     --input_format=tf_frozen_model     --output_node_names final_result     ./tensorflowjs_model.pb     ./web
2021-08-20 22:28:16.527933: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-20 22:28:16.527994: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot reshape a tensor with 1001 elements to shape [0,0] (0 elements) for '{{node MobilenetV1/Predictions/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](MobilenetV1/Logits/SpatialSqueeze, MobilenetV1/Predictions/Reshape/shape)' with input shapes: [1,1001], [2] and with input tensors computed as partial shapes: input[1] = [0,0].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huan/.local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 803, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 574, in _dispatch_converter
    tf_saved_model_conversion_v2.convert_tf_frozen_model(
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 518, in convert_tf_frozen_model
    graph = load_graph(frozen_model_path)
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 68, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/home/huan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 1001 elements to shape [0,0] (0 elements) for '{{node MobilenetV1/Predictions/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](MobilenetV1/Logits/SpatialSqueeze, MobilenetV1/Predictions/Reshape/shape)' with input shapes: [1,1001], [2] and with input tensors computed as partial shapes: input[1] = [0,0].
```

Link to https://github.com/huan/emoji-net/issues/3

**Comment by rthadur** [comment]
Frozen models are not supported in latest versions. Thank you

**Comment by huan** [comment]
Hi @rthadur ,

Thanks for the reply.

I think the `frozen models` are still supported according to the help message of tensorflowjs_converter 3.8:

```sh
$ tensorflowjs_converter  --vesion
tensorflowjs 3.8.0

Dependency versions:
  keras 2.6.0
  tensorflow 2.6.0

$ tensorflowjs_converter --help
  --input_format {tf_hub,tf_saved_model,tfjs_layers_model,keras,tf_frozen_model,keras_saved_model}
```

We can see **tf_frozen_model** is listed in the `input_format`.

And also, I can reproduce this problem in the older version of tensorflowjs_converter with version 0.8.5, and the following is the reproduce steps that have the exact same error message outputted as the latest version.

## Reproduce this error with tensorflowjs_converter v0.8.5

### 1. Get a Python 2.7 environment

```sh
$ docker run --rm -ti -v $(pwd):/model ubuntu:18.04 bash
$ apt update && apt install -y python python-pip
```

### 2. Install

```sh
$ pip install tensorflowjs==0.8.5
$ tensorflowjs_converter --version
Using TensorFlow backend.

tensorflowjs 0.8.5

Dependency versions:
  keras 2.2.2
  tensorflow 1.13.1
```

### 3. Convert

```sh
# tensorflowjs_converter \
>     --input_format=tf_frozen_model \
>     --output_node_names final_result \
>     ./tensorflowjs_model.pb \
>     ./web
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/converter.py", line 352, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_pb.py", line 329, in convert_tf_frozen_model
    graph = load_graph(frozen_model_path, output_node_names)
  File "/usr/local/lib/python2.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_pb.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
    raise ValueError(str(e))
ValueError: Cannot reshape a tensor with 1001 elements to shape [0,0] (0 elements) for 'MobilenetV1/Predictions/Reshape' (op: 'Reshape') with input shapes: [1,1001], [2] and with input tensors computed as partial shapes: input[1] = [0,0].
```

**Comment by rthadur** [comment]
As mentioned [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#conversion-flags) it is supported for backward compatibility and we don't think we will be supporting older tfjs(0.86) and tenforflow(1.13) anymore. 

cc @pyu10055 @lina128
