### ISSUE TITLE
[wasm] OOM for some conv2d input on build bots 

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#5652]
Test case: https://github.com/tensorflow/tfjs/pull/5637/commits/976623953e724be45730f8259a0d0944243d4afc
Build log: https://console.cloud.google.com/cloud-build/builds/46b2a97c-0c12-494a-9e7a-51e1627fe072;step=14?project=learnjs-174218
```
$ ./scripts/test-ci.sh
$ tsc && ts-node --transpile-only --skip-ignore -P tsconfig.test.json src/test_node.ts
Platform node has already been set. Overwriting the platform with [object Object].
Started
(node:48) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:48) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
XNN status for xnn_create_average_pooling2d_nhwc_f32 is not successful. 
XNN status for xnn_create_average_pooling2d_nhwc_f32 is not successful. 
XNN status for xnn_create_average_pooling2d_nhwc_f32 is not successful. 
XNN status for xnn_create_max_pooling2d_nhwc_f32 is not successful. 
XNN status for xnn_setup_max_pooling2d_nhwc_f32 is not successful. Got status 2. Use -c dbg to see XNN logs.
XNN status for xnn_create_max_pooling2d_nhwc_f32 is not successful. 
XNN status for xnn_setup_max_pooling2d_nhwc_f32 is not successful. Got status 2. Use -c dbg to see XNN logs.
XNN status for xnn_setup_max_pooling2d_nhwc_f32 is not successful. Got status 2. Use -c dbg to see XNN logs.
failed to asynchronously prepare wasm: RangeError: WebAssembly Instantiation: Out of memory: wasm memory
RangeError: WebAssembly Instantiation: Out of memory: wasm memory
/workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:54
                throw ex;
                ^

RuntimeError: abort(RangeError: WebAssembly Instantiation: Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
    at abort (/workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:9:9596)
    at /workspace/tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.js:9:11594
error Command failed with exit code 7.
...................................**..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ahmedsabie** [comment]
Fixed in #5852.
