### ISSUE TITLE
Gradients of complex numbers not working on node backend (tfjs-node | tfjs-node-gpu)

### ISSUE THREAD

**Issue by MiraiKami** [tensorflow/tfjs#5668]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Professionnal (build 19041.1110)
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not on Mobile device, but here are the laptop's specs :
        Intel Core i7-10875H CPU 2.30GHz
        32Go RAM
        NVIDIA GeForce RTX 2060 6GB
        Operating System x64

TensorFlow.js installed from (npm or script link): npm
TensorFlow.js version (use command below): 3.7.0
Browser version: -
Tensorflow.js Converter Version: -

**Describe the expected behavior**
When trying to compute gradients, I am using the node backend since complex numbers are not well supported on other backends and tfjs-node or tfjs-node-gpu seem to be the only backends with proper complex numbers support.

As mentioned in the title, this gradient computation does not work properly: for a function f : C -> C, the derivative should be f' : C -> C. However, the framework returns real tensors instead of complex ones as shown with the example below.

For instance with a one-variable function :
f(z) = z^2
In our example, z is a complex Tensor with values [1 + 1j, 2 + 3j, 1 + 0j, 1 + 4j].
f(z) is then a tensor with values [0 + 2j, -5 + 12j, 1 + 0j, -15 + 8j].
Our derivative (since we only have one variable for now) should be g(z) = df/dz = 2*z = [2 + 2j, 4 + 6j, 2 + 0j, 2+ 8j] but, the result is only a Real tensor containing only the real part of the derivative: [2, 4, 2, 2].

With a more advanced function, let's say f(z, y) = sqrt(z) / (z\*y), gradients should be the results of formulas df/dz = -1/(2\* x^(3/2) \* y) and df/dy = -1/(sqrt(z)\*y^2).

Let's say z = [1 + 1j, 2 + 3j] and y = [4 + 3j, 0 + 5j]
f(z, y) = [ 0.0856863 + -0.144714j, -0.0496999 + -0.0928651j], that is a tensor with DType Complex64.
now let's compute:
```
g = tf.grads(f)
[dz, dy] = g([z, y])
```

and we have dz = [0.591557, -0.0235702] and dy = [0.0228893, -0.0267864], which are tensors of DType Float32.
These values seem to come out of the blue since the expected result should be:
dz = [0.0147569 + 0.0576001j, 0.0145383 + 0.00140887j] and dy = [-0.00365588 - 0.0334366j, -0.0187573 + 0.00993998j].

**Standalone code to reproduce the issue**
Both examples are written in typescript.
First, compile the source with `tsc` then execute with `node [program.js]`.
Here is the example for the square derivative:
```
import * as tf from "@tensorflow/tfjs-node"
import {Tensor} from "@tensorflow/tfjs-node";

function square(x : Tensor) {
    //x**2
    //derivative = 2*x
    return tf.tidy( () => {
        return x.square();
    });
}

async function main() {
    const z: Tensor = tf.complex([1, 2, 1, 1], [1, 3, 0, 4]);
    z.print(); //[1 + 1j, 2 + 3j, 1 + 0j, 1 + 4j]
    const f_z: Tensor = square(z);
    f_z.print(); //[0 + 2j, -5 + 12j, 1 + 0j, -15 + 8j]

    const g = tf.grads(square);
    const [dz]: Tensor[] = g([z]);
    dz.print(); //[2, 4, 2, 2]
}
main().then();
```

Second (advanced) example :
```
import * as tf from "@tensorflow/tfjs-node"
import {Tensor} from "@tensorflow/tfjs-node";

function sqrtDivmul(x : Tensor, y : Tensor) {
    //sqrt(x)/(x*y)
    //grad for a should be d/dx = -1/(2*(x^3/2)*y)
    //                     d/dy = -1/(sqrt(x)*y^2)
    return tf.tidy( () => {
        return x.sqrt().div(x.mul(y));
    });
}

async function main() {
    const z: Tensor = tf.complex([1, 2], [1, 3]);
    const y: Tensor = tf.complex([4, 0], [3, 5]);
    z.print(); //[1 + 1j, 2 + 3j]
    y.print(); //[4 + 3j, 0 + 5j]
    const f_zy: Tensor = sqrtDivmul(z, y);
    f_zy.print(); //[0.0856863 + -0.144714j, -0.0496999 + -0.0928651j]

    const g = tf.grads(sqrtDivmul);
    const [dz, dy] = g([z, y]);
    dz.print() //[0.591557, -0.0235702] should be [0.0147569 + 0.0576001j, 0.0145383 + 0.00140887j]
    dy.print(); //[0.0228893, -0.0267864] should be [-0.00365588 - 0.0334366j, -0.0187573 + 0.00993998j]
}
main().then();
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The same behavior is observed with tfjs-node and tfjs-node-gpu. For other backends, the  gradients function for complex64 is not supported (as well as some operators documented at https://github.com/tensorflow/tfjs/issues/2409).

In the second example, dz and dy are the only Tensors in g([z, y]) as shown with `console.log(g(z, y]))`:
```
[
  Tensor {
    kept: false,
    isDisposedInternal: false,
    shape: [ 2 ],
    dtype: 'float32',
    size: 2,
    strides: [],
    dataId: {},
    id: 62,
    rankType: '1',
    scopeId: 34
  },
  Tensor {
    kept: false,
    isDisposedInternal: false,
    shape: [ 2 ],
    dtype: 'float32',
    size: 2,
    strides: [],
    dataId: {},
    id: 56,
    rankType: '1',
    scopeId: 34
  }
].
```

**Comment by gaikwadrahul8** [comment]
Hi, @MiraiKami 

Apologize for the delayed response and I tried to replicate the same issue from my end with latest version of `@tensorflow/tfjs-node` and when I tried first example it's seems like working as expected if I'm not wrong for your reference I have added screenshot below and for second example still I'm getting the error and for your reference I have added screenshot below so we will have to dig more into this issue and we'll update you soon. Thank you!

First Example output screenshot :

```
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ node tfjs.js
Platform node has already been set. Overwriting the platform with node.
Tensor
    [1 + 1j, 2 + 3j, 1 + 0j, 1 + 4j]
Tensor
    [0 + 2j, -5 + 12j, 1 + 0j, -15 + 8j]
Tensor
    [2, 4, 2, 2]
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ 
```

Second Example error output screenshot : 

```
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ node tfjs-1.js
Platform node has already been set. Overwriting the platform with node.
Tensor
    [1 + 1j, 2 + 3j]
Tensor
    [4 + 3j, 0 + 5j]
/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:3940
        throw new Error(`Argument '${argName}' passed to '${functionName}' must ` +
              ^

Error: Argument 'x' passed to 'sqrt' must be float32 tensor, but got complex64 tensor
    at assertDtype (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:3940:15)
    at convertToTensor (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:3946:9)
    at sqrt_ (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:4479:16)
    at sqrt__op (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:4024:28)
    at getGlobalTensorClass.sqrt (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/dist/tf.node.js:33352:12)
    at /Users/gaikwadrahul/Desktop/TFJS/tfjs-1.js:45:18
    at /Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4559:22
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)
    at Engine.tidy (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4558:21)
    at Object.tidy (/Users/gaikwadrahul/Desktop/TFJS/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8291:19)

Node.js v18.15.0
gaikwadrahul-macbookpro:TFJS gaikwadrahul$ 

```

**Comment by nileshau-afk** [comment]
Hello @MiraiKami ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @MiraiKami, Thank you for your patience. We have reproduced the issue on our end. As a workaround, you can separate your complex numbers into real and imaginary float32 tensors, run standard gradient calculation on those parts, and then combine the results back into a complex tensor. Could you please try this approach and let us know if it works for you?
