### ISSUE TITLE
Cannot installl on github actions "ubuntu-20.04"

### ISSUE THREAD

**Issue by liron-navon** [tensorflow/tfjs#5674]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: ubuntu-20.04 (github actions)
- TensorFlow.js installed from (npm or script link): npm
- "@tensorflow/tfjs-node": "^3.9.0"
- "@tensorflow/tfjs": "^3.9.0"
- "@tensorflow-models/mobilenet": "^2.1.0"

**Describe the problem**

Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /github/workspace/packages/app/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
at Runtime._loadModule (node_modules/jest-runtime/build/index.js:893:29)
 at Object.<anonymous> (node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
npm install
npm run tests

I'm running tests with jest and mobilenet

**Any other info / logs**
![Screenshot 2021-09-28 at 21 12 00](https://user-images.githubusercontent.com/18119833/135150848-a2ec8341-78e3-48cf-b333-7b27e35ddd70.png)

**Comment by rthadur** [comment]
You might probably missing libc, you might to run `apt install libc-dev or build-essential` , please check a related [so](https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li/51655643#51655643) question. Thank you
