### ISSUE TITLE
unable to change backend to `wasm` in runtime

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#5831]
**environment**: tfjs 3.11.0 on chrome 97

**description**: if `wasm` backend is used first then its possible to switch to `webgl` or `webgpu`
but if any other backend is used first, switching to `wasm` causes error

this code results in error:

```js
for (const backend of ['webgl', 'wasm']) {
  tf.setBackend(backend);
  await tf.ready();
  const element = document.getElementById('image');
  const pixels = tf.browser.fromPixels(element);
  const clone = tf.clone(pixels);
  tf.dispose([pixels, clone]);
}
```

error: 

```text
Uncaught (in promise) RangeError: Invalid typed array length: 8294400
    at new Float32Array (<anonymous>)
    at BackendWasm.typedArrayFromHeap (tfjs.esm.js:69703:16)
    at Object.identity5 [as kernelFunc] (tfjs.esm.js:66904:27)
    at kernelFunc3 (tfjs.esm.js:6935:22)
    at tfjs.esm.js:6976:19
    at _Engine.scopedRun (tfjs.esm.js:6857:19)
    at _Engine.runKernelFunc (tfjs.esm.js:6974:10)
    at _Engine.runKernel (tfjs.esm.js:6894:17)
    at clone_ (tfjs.esm.js:8461:17)
```

but just changing order of backends from `['webgl', 'wasm']` to `['wasm', 'webgl']` works without issues

replacing `webgl` with `webgpu` results in a slightly different error signature, but its the same issue  
although it is IMO more informative - you can see that it starts by using `wasm` but ends using `webgpu` read function?!  

my guess is that swtiching backend to `wasm` doesnt do it properlyt and it still uses `read` method of the previously set backend  

```text
Uncaught (in promise) Error: WebGPU readSync is only available for CPU-resident tensors. <-- but backend is no longer `webgpu`, its `wasm`
    at _WebGPUBackend.readSync (tfjs.esm.js:66313:13)
    at _Engine.readSync (tfjs.esm.js:7285:25)
    at _Engine.moveData (tfjs.esm.js:6820:25)
    at DataStorage.get (tfjs.esm.js:4817:22)
    at BackendWasm.typedArrayFromHeap (tfjs.esm.js:69699:45) <-- backend here is correctly set to `wasm`
```

**Comment by mattsoulanille** [comment]
Thanks for the bug report. I'm having trouble reproducing this error using your example code. Here's what I've done:
```html
<html>
<head>
</head>

<body>
  <img id="image" crossOrigin="anonymous" src="https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"></img>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.11.0/dist/tf-core.js"> </script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl@3.11.0/dist/tf-backend-webgl.js"> </script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.11.0/dist/tf-backend-wasm.js"></script>

  <script>
    async function main() {
        for (const backend of ['webgl', 'wasm']) {
            tf.setBackend(backend);
            await tf.ready();
            const element = document.getElementById('image');
            const pixels = tf.browser.fromPixels(element);
            const clone = tf.clone(pixels);
            clone.print();
            tf.dispose([pixels, clone]);
        }
    }
    main();
  </script>
</body>
</html>
```

This seems to work correctly on Chrome 96 and 98 for me. Did I miss something when reproducing the bug?

**Comment by vladmandic** [comment]
thats exactly it, but now i cannot reproduce as well - thats really weird.
anyhow, closing the issue as non-reproducible. thanks.
