### ISSUE TITLE
tfjs-backend-wasm throws runtime exception: (intermediate value)(intermediate value).apply is not a function

### ISSUE THREAD

**Issue by ayush987goyal** [tensorflow/tfjs#5913]
I am trying to integrate the `@tensorflow/tfjs-backend-wasm` backend module and I get the following error while loading the `blazeface` model:

```
TypeError: (intermediate value)(intermediate value).apply is not a function
    at Object.Module._register_tensor [as registerTensor] (http://localhost:3000/static/js/vendors~main.chunk.js:421342:83)
    at BackendWasm.move (http://localhost:3000/static/js/vendors~main.chunk.js:409353:20)
    at BackendWasm.write (http://localhost:3000/static/js/vendors~main.chunk.js:409308:10)
    at Engine.makeTensor (http://localhost:3000/static/js/vendors~main.chunk.js:463972:28)
    at makeTensor (http://localhost:3000/static/js/vendors~main.chunk.js:493836:57)
    at tensor (http://localhost:3000/static/js/vendors~main.chunk.js:493313:77)
    at Module.decodeWeights (http://localhost:3000/static/js/vendors~main.chunk.js:468140:77)
    at GraphModel.loadSync (http://localhost:3000/static/js/vendors~main.chunk.js:450824:80)
    at GraphModel.load (http://localhost:3000/static/js/vendors~main.chunk.js:450800:17)
    at async loadGraphModel (http://localhost:3000/static/js/vendors~main.chunk.js:451101:3)
```

The following snippet is what I am currently using:

```ts
import * as tf from '@tensorflow/tfjs-core';
import * as blazeface from '@tensorflow-models/blazeface';
import * as tfjsWasm from '@tensorflow/tfjs-backend-wasm';

async function loadModel() {
    tfjsWasm.setWasmPaths(`${BASE_CDN_URL}/wasm/`);
    await tf.setBackend('wasm');

    await tf.ready();
    await blazeface.load();
}
```

Anything that needs to be done apart from this? We are only seeing this in the production build of our library (in which we are trying to use it)

**Comment by rthadur** [comment]
@can you please share your package.json ,what version you are seeing this error ?

**Comment by ayush987goyal** [comment]
@rthadur  These are the dependencies that I am currently using:

```
    "@tensorflow-models/blazeface": "^0.0.7",
    "@tensorflow/tfjs-backend-cpu": "^3.11.0",
    "@tensorflow/tfjs-backend-wasm": "^3.11.0",
    "@tensorflow/tfjs-backend-webgl": "^3.11.0",
    "@tensorflow/tfjs-converter": "^3.11.0",
    "@tensorflow/tfjs-core": "^3.11.0",
```

**Comment by rthadur** [comment]
Did you check the demo here https://github.com/tensorflow/tfjs-models/tree/master/blazeface/demo , it is working as expected. please check

**Comment by ayush987goyal** [comment]
We are using this with a bundler. This seems to happen in context of a bundler and not direct CDN consumption.

**Comment by ayush987goyal** [comment]
Closing the issue since the problem was that that we were using different versions for the library and for thew wasm binaries.
