### ISSUE TITLE
[tjfs-node] Unsupported system: cpu-linux-arm64 in raspberry pi 4

### ISSUE THREAD

**Issue by Ddongddi** [tensorflow/tfjs#5937]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10 (buster) (raspberry pi 4B)
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.12.0 

Installing tfjs-node, raspberry pi gave `Unsupported system: cpu-linux-arm64`.
I used node.js v17.2.0
I ran `npm install @tensorflow/tfjs-node` and this gave the error.

This is the full error: 
```
npm ERR! code 1
npm ERR! path /home/pi/Desktop/coronapredict/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.12.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /home/pi/Desktop/coronapredict/node_modules/@tensorflow/tfjs-node/scripts/install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Unsupported system: cpu-linux-arm64
npm ERR!     at getPlatformLibtensorflowUri (/home/pi/Desktop/coronapredict/node_modules/@tensorflow/tfjs-node/scripts/install.js:106:11)
npm ERR!     at downloadLibtensorflow (/home/pi/Desktop/coronapredict/node_modules/@tensorflow/tfjs-node/scripts/install.js:139:15)
npm ERR!     at async run (/home/pi/Desktop/coronapredict/node_modules/@tensorflow/tfjs-node/scripts/install.js:208:5)
npm ERR! 
npm ERR! Node.js v17.2.0
```

**Comment by rthadur** [comment]
Please check this issue #5173 , this has been resolved with latest versions.

**Comment by Ddongddi** [comment]
It was the latest version of tensorflow.

**Comment by Ddongddi** [comment]
I tried with node.js v16 and v17, and they didn't work.

**Comment by rthadur** [comment]
@Ddongddi can you please share your package.json ?

**Comment by Ddongddi** [comment]
```
{
  "name": "coronapredict",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

```
My package.json file

**Comment by pyu10055** [comment]
@Ddongddi we have support for arm v7 32 bit linux, is your RPI running on arm 64 linux?

**Comment by Ddongddi** [comment]
> @Ddongddi we have support for arm v7 32 bit linux, is your RPI running on arm 64 linux?

Yes. I am running arm 64 debian

**Comment by playground** [comment]
@pyu10055 will there be support for arm64 linux?

**Comment by arnav7633** [comment]
I have the same question especially after raspberry org officially released the 64bit few days back

**Comment by MincoMK** [comment]
Not working in latest version too

**Comment by brzuzak** [comment]
Same issue on rasp_os 64bit node-red2.2.2

**Comment by 444noam** [comment]
same issue on my rpi arm64

**Comment by ZTiKnl** [comment]
same issue on Rock64 / arm64

```bash
SARA@server:~/ai$ node -v
v16.14.2

SARA@server:~/ai$ npm install @tensorflow/tfjs-node
npm ERR! code 1
npm ERR! path /home/SARA/ai/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.15.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /home/SARA/ai/node_modules/@tensorflow/tfjs-node/scripts/install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported system: cpu-linux-arm64
npm ERR!     at getPlatformLibtensorflowUri (/home/SARA/ai/node_modules/@tensorflow/tfjs-node/scripts/install.js:106:11)
npm ERR!     at downloadLibtensorflow (/home/SARA/ai/node_modules/@tensorflow/tfjs-node/scripts/install.js:139:15)
npm ERR!     at async run (/home/SARA/ai/node_modules/@tensorflow/tfjs-node/scripts/install.js:208:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/SARA/.npm/_logs/2022-04-05T19_54_12_497Z-debug-0.log
```

**Comment by ZTiKnl** [comment]
[This workaround](https://github.com/yhwang/node-red-contrib-tf-model) fails for me, but this *might* work on Pi4 and Jetson Nano:
```
SARA@server:~/ai$ npm install @tensorflow/tfjs-node --ignore-scripts

added 124 packages, and audited 151 packages in 24s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

SARA@server:~/ai$ cd node_modules/@tensorflow/tfjs-node/scripts/
SARA@server:~/ai/node_modules/@tensorflow/tfjs-node/scripts$ nano custom-binary.json
SARA@server:~/ai/node_modules/@tensorflow/tfjs-node/scripts$ cd ..
SARA@server:~/ai/node_modules/@tensorflow/tfjs-node$ npm install

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

> @tensorflow/tfjs-node@3.15.0 install
> node scripts/install.js

CPU-linux-3.15.0.tar.gz
* Downloading libtensorflow
https://s3.us.cloud-object-storage.appdomain.cloud/tfjs-cos/libtensorflow-cpu-linux-arm-1.15.0.tar.gz
[==============================] 1357842/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --build-from-source
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.4
node-pre-gyp info using node@16.14.2 | linux | arm64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | linux | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | linux | arm64
gyp info find Python using Python version 3.9.7 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/SARA/ai/node_modules/@tensorflow/tfjs-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/SARA/.cache/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/SARA/.cache/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/SARA/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/SARA/ai/node_modules/@tensorflow/tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | linux | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../binding/tfjs_backend.cc: In function ‘TFE_TensorHandle* tfnodejs::CreateTFE_TensorHandleFromStringArray(napi_env, int64_t*, uint32_t, TF_DataType, napi_value)’:
../binding/tfjs_backend.cc:196:64: error: ‘TF_TString’ was not declared in this scope
                                          array_length * sizeof(TF_TString)));
                                                                ^~~~~~~~~~
../binding/tfjs_backend.cc:196:64: note: suggested alternative: ‘TF_Server’
                                          array_length * sizeof(TF_TString)));
                                                                ^~~~~~~~~~
                                                                TF_Server
../binding/tfjs_backend.cc:198:15: error: ‘t’ was not declared in this scope
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
               ^
../binding/tfjs_backend.cc:198:15: note: suggested alternative: ‘tm’
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
               ^
               tm
../binding/tfjs_backend.cc:198:36: error: ‘TF_TString’ does not name a type; did you mean ‘TF_Server’?
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                    ^~~~~~~~~~
                                    TF_Server
../binding/tfjs_backend.cc:198:47: error: expected ‘>’ before ‘*’ token
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                               ^
../binding/tfjs_backend.cc:198:47: error: expected ‘(’ before ‘*’ token
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                               ^
                                               (
../binding/tfjs_backend.cc:198:48: error: expected primary-expression before ‘>’ token
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                                ^
../binding/tfjs_backend.cc:198:79: error: expected ‘)’ before ‘;’ token
   TF_TString *t = reinterpret_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                                                               ^
                                                                               )
../binding/tfjs_backend.cc:220:5: error: ‘TF_TString_Init’ was not declared in this scope
     TF_TString_Init(t);
     ^~~~~~~~~~~~~~~
../binding/tfjs_backend.cc:220:5: note: suggested alternative: ‘TF_StringDecode’
     TF_TString_Init(t);
     ^~~~~~~~~~~~~~~
     TF_StringDecode
../binding/tfjs_backend.cc:221:5: error: ‘TF_TString_Copy’ was not declared in this scope
     TF_TString_Copy(t, reinterpret_cast<char *>(buffer), cur_array_length);
     ^~~~~~~~~~~~~~~
../binding/tfjs_backend.cc:221:5: note: suggested alternative: ‘TF_StringDecode’
     TF_TString_Copy(t, reinterpret_cast<char *>(buffer), cur_array_length);
     ^~~~~~~~~~~~~~~
     TF_StringDecode
../binding/tfjs_backend.cc: In function ‘void tfnodejs::CopyTFE_TensorHandleDataToStringArray(napi_env, TFE_Context*, TFE_TensorHandle*, napi_value__**)’:
../binding/tfjs_backend.cc:318:3: error: ‘TF_TString’ was not declared in this scope
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
   ^~~~~~~~~~
../binding/tfjs_backend.cc:318:3: note: suggested alternative: ‘TF_Server’
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
   ^~~~~~~~~~
   TF_Server
../binding/tfjs_backend.cc:318:15: error: ‘ts’ was not declared in this scope
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
               ^~
../binding/tfjs_backend.cc:318:15: note: suggested alternative: ‘tm’
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
               ^~
               tm
../binding/tfjs_backend.cc:318:32: error: ‘TF_TString’ does not name a type; did you mean ‘TF_Server’?
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                ^~~~~~~~~~
                                TF_Server
../binding/tfjs_backend.cc:318:43: error: expected ‘>’ before ‘*’ token
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                           ^
../binding/tfjs_backend.cc:318:43: error: expected ‘(’ before ‘*’ token
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                           ^
                                           (
../binding/tfjs_backend.cc:318:44: error: expected primary-expression before ‘>’ token
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                            ^
../binding/tfjs_backend.cc:318:75: error: expected ‘)’ before ‘;’ token
   TF_TString *ts = static_cast<TF_TString *>(TF_TensorData(tensor.tensor));
                                                                           ^
                                                                           )
../binding/tfjs_backend.cc:328:30: error: ‘TF_TString_GetDataPointer’ was not declared in this scope
     const char *raw_string = TF_TString_GetDataPointer(ts);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
../binding/tfjs_backend.cc:329:30: error: ‘TF_TString_GetSize’ was not declared in this scope
     size_t raw_string_size = TF_TString_GetSize(ts);
                              ^~~~~~~~~~~~~~~~~~
../binding/tfjs_backend.cc:329:30: note: suggested alternative: ‘TF_StringEncodedSize’
     size_t raw_string_size = TF_TString_GetSize(ts);
                              ^~~~~~~~~~~~~~~~~~
                              TF_StringEncodedSize
make: *** [tfjs_binding.target.mk:114: Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 4.4.213-rockchip64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--build-from-source" "--module=/home/SARA/ai/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/home/SARA/ai/node_modules/@tensorflow/tfjs-node/lib/napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp ERR! cwd /home/SARA/ai/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --build-from-source --module=/home/SARA/ai/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/SARA/ai/node_modules/@tensorflow/tfjs-node/lib/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/SARA/ai/node_modules/@tensorflow/tfjs-node/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 4.4.213-rockchip64
node-pre-gyp ERR! command "/usr/bin/node" "/home/SARA/ai/node_modules/@tensorflow/tfjs-node/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd /home/SARA/ai/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v16.14.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.4
node-pre-gyp ERR! not ok

npm ERR! code 1
npm ERR! path /home/SARA/ai/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/SARA/.npm/_logs/2022-04-05T22_06_47_054Z-debug-0.log
```

Jetson nano:
```
{
  "tf-lib": "https://s3.us.cloud-object-storage.appdomain.cloud/tfjs-cos/libtensorflow-gpu-linux-arm64-1.15.0.tar.gz"
}
```

Rpi4
```
{
  "tf-lib": "https://s3.us.cloud-object-storage.appdomain.cloud/tfjs-cos/libtensorflow-cpu-linux-arm-1.15.0.tar.gz"
}
```

**Comment by OgulcanCelik** [comment]
@pyu10055 sir, sorry for the mention but I crawled through old issues for M1 and saw your comments and PR related to it. Do we have an ETA for this? This problem also affects M1 users in a way, because docker containers and native images run under `linux-arm64`.

**Comment by Panda-Dreamer** [comment]
Got the same issue on node v18.0.0 with linux debian on arm64

**Comment by MincoMK** [comment]
Is there anyone who can build manually using the bazel?

**Comment by OgulcanCelik** [comment]
> Is there anyone who can build manually using the bazel?

I did today, using m1 mac built it inside a container. Will share the result.

**Comment by aubergene** [comment]
I was having this problem with RPI 4 "Raspbian GNU/Linux 10 (buster)" and somehow managed to get it work but then couldn't update node modules without breaking it. I ended up checking node_modules into git and finding out that the `node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node` I had previous compiled somehow worked but the updated one didn't. I've pushed my file here in case it helps someone or helps with debugging this issue.

[tfjs_binding.node](https://gist.github.com/aubergene/d04d0911cfd4d05e696198bdd23c1c97/raw/f6c31de9f4f51b08e851f59ef3bbaa3335ae8e85/tfjs_binding.node)

**Comment by OgulcanCelik** [comment]
I've successfully compiled libtensorflow following the guide on the readme inside a docker container. https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source

However, from here, I'm stuck. There isn't much information about how to compile node bindings from here, can anyone guide me?

**Comment by MincoMK** [comment]
> I've successfully compiled libtensorflow following the guide on the readme inside a docker container. https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source
> 
> 
> 
> However, from here, I'm stuck. There isn't much information about how to compile node bindings from here, can anyone guide me?

@OgulcanCelik
How to make from libtensorflow to tfjs-node?

**Comment by tamaina** [comment]
Is there any update? I would like to use it with arm64 vps.

**Comment by alexrabin** [comment]
I'm having this issue as well 🙃
