### ISSUE TITLE
Saving a model in MacOS X

### ISSUE THREAD

**Issue by ProgrammingLife** [tensorflow/tfjs#595]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tfjs-node@0.1.11
MacOS X 10.12.5
node v9.4.0

#### Describe the problem or feature request
Trying to train a model and then save it with:
`await model.save('file:///./model');`

And I get a message:
`(node:2792) UnhandledPromiseRejectionWarning: Error: Cannot find any save handlers for URL 'file:///./data/model'`

How to properly save the trained model?

**Comment by caisq** [comment]
@ProgrammingLife  Did you import `tfjs-node` using a line such as `import '@tensorflow/tfjs-node'` or `require('@tensorflow/tfjs-node')`, in addition importing `@tensorflow/tfjs`?

**Comment by nkreeger** [comment]
This is probably related to the fact you don't have a working Node.js package: https://github.com/tensorflow/tfjs/issues/593#issuecomment-412245609

**Comment by caisq** [comment]
@ProgrammingLife So your code doesn't import @tensorflow/tfjs-node. Without importing that package, the machinery for file-system saving and loading won't be there. Another thing to point out here is: if you us relative path, you should do something like 'file://./model' (2 slashes after the colon), instead of "file:///./model" (3 slashes after the colon).

**Comment by ProgrammingLife** [comment]
@caisq, but how to use import?

If I use:
`import * as tf from '@tensorlowjs/tfjs';`

I get:
```
import * as tf from '@tensorlowjs/tfjs';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
```

**Comment by ProgrammingLife** [comment]
Is any other way to get weights out of model? I wanna save and load it manually without using **model.save()** and **model.load()**. Is it possible?

**Comment by caisq** [comment]
@ProgrammingLife 

1. In your package.json, make sure you have included the dependency such as
   "@tensorflow/tfjs-node": "^0.1.11"

2. In your .js file, do after `const tf = require("@tensorflow/tfjs");`: `require('@tensorflow/tfjs-node');`

Let us know if that works.

**Comment by ProgrammingLife** [comment]
Wow it worked! Thanks! 👍

**Comment by JimTheMan** [comment]
didn't work for me :'(
