### ISSUE TITLE
Windows has two failing NaN tests

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#598]
Running `@tensorflow/tfjs-node` currently has two failing unit test:

```
Failures:
1) maxPool test-tensorflow {} [x=[3,3,1] f=[2,2] s=1 ignores NaNs
  Message:
    Error: Arrays differ: actual[2] = NaN, expected[2] = 7.
    Actual:   5,6,NaN,9.
    Expected: 5,6,7,9.
  Stack:
    Error: Arrays differ: actual[2] = NaN, expected[2] = 7.
        at <Jasmine>
        at Object.expectArraysClose (C:\Users\nickk\workspace\tfjs-node\node_modules\@tensorflow\tfjs-core\src\test_util.ts:95:13)
        at UserContext.<anonymous> (C:\Users\nickk\workspace\tfjs-node\node_modules\@tensorflow\tfjs-core\src\ops\pool_test.ts:58:5)
        at <Jasmine>
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)

2) clip test-tensorflow {} propagates NaNs
  Message:
    Error: Arrays differ: actual[6] = 50, expected[6] = NaN.
    Actual:   3,-1,0,50,-1,2,50.
    Expected: 3,-1,0,50,-1,2,NaN.
  Stack:
    Error: Arrays differ: actual[6] = 50, expected[6] = NaN.
        at <Jasmine>
        at Object.expectArraysClose (C:\Users\nickk\workspace\tfjs-node\node_modules\@tensorflow\tfjs-core\src\test_util.ts:95:13)
        at UserContext.<anonymous> (C:\Users\nickk\workspace\tfjs-node\node_modules\@tensorflow\tfjs-core\src\ops\unary_ops_test.ts:2367:5)
        at <Jasmine>
        at runCallback (timers.js:810:20)
        at tryOnImmediate (timers.js:768:5)
        at processImmediate [as _immediateCallback] (timers.js:745:5)
```

It is unclear why these two tests don't propagate NaN. I'll verify with Python on windows soon.

**Comment by nsthorat** [comment]
I assume this is fixed, reopen if I am wrong.

**Comment by nkreeger** [comment]
Yeah this one is fixed - sorry there is one for CUDA & NaNs on windows.
