### ISSUE TITLE
>Unable to install tfjs-node in VSCode.

### ISSUE THREAD

**Issue by thierryntoh24** [tensorflow/tfjs#6029]
> 

I have the same error. I've been reading articles and installing packages (`node-gyp` , `python 3.10` and `node-pre-gyp`) for 4 hours now but still nothing.
Someone should've told me installing will be this difficult. Damn youtube videos, making it so easy with their `npm install tensorfrow/tfjs-node`s.

I tried @MountainAndMorning 's solution but my directory ends at `\node_modules\@tensorflow\tfjs-node`, no `\lib\napi-vx`.

Ive tried literally every suggestion i can find, even this from [here](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) no avail. Still getting this error.

```
PS D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node> node-gyp configure --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
gyp verb find Python - executing "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe" to get version
gyp verb find Python - version is "3.10.2"
gyp info find Python using Python version 3.10.2 found at "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 
16.13.1
gyp verb command install [ '16.13.1' ]
gyp verb install input version string "16.13.1"
gyp verb install installing version: 16.13.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.13.1
gyp verb build dir attempting to create "build" dir: D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build
gyp verb build dir "build" dir needed to be created? No
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp verb find VS looking for Visual Studio 2015
gyp verb find VS - not found
gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16     
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14     
gyp ERR! stack     at C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16    
gyp ERR! stack     at C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
```

It kinda seems like it requires Visual Studio and i just can't anymore.
I'm just giving up at this point.

_Originally posted by @thierryntoh24 in https://github.com/tensorflow/tfjs/issues/4171#issuecomment-1015064824_

**Comment by pyu10055** [comment]
@mattsoulanille this is similar to the windows installation failure hopefully can be solve by providing precompiled binding for windows.

**Comment by thierryntoh24** [comment]
I found a solution at last.
[Here](https://gist.github.com/thierryntoh24/0bbf857e21eaf5acd1fc28cde1eea263)'s a sort of TFJS/Nodeinstallation guide i just wrote.
