### ISSUE TITLE
Error Building TFJS/Node Project | `Error: A dynamic link library (DLL) initialization routine failed.`

### ISSUE THREAD

**Issue by thierryntoh24** [tensorflow/tfjs#6034]
**System information**
- Windows 10 Pro 1909, 18363.1198
- Intel(R) Core (TM) i3 CPU M350 @ 2.27 GHz
- TensorFlow.js installed from (npm or script link): `npm install tensorflow/tfjs-node`
- TensorFlow.js version: ^3.13.0

I run into the following error message when i try to build my TFJS project

```
PS D:\Projects\art-review-bot> npm run build

> art-review-bot@1.0.0 build
> tsc && ts-node src/engine.ts

Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
* Installed TFJS/Node succesfully from npm
* Ran this sample code i got online
 ```
 import TensorFlow from '@tensorflow/tfjs-node'
import MobileNet from '@tensorflow-models/mobilenet'
import fs from 'fs'

let path = '../data/test/IMG_2989.JPG'
const imageBuffer = fs.readFileSync(path)
const tImage = TensorFlow.node.decodeImage(imageBuffer) as TensorFlow.Tensor3D

const classifyImage = async () => {
    const mobilenetmodel = await MobileNet.load()
    const predicton = await mobilenetmodel.classify(tImage)
    console.log('Classificction : ', predicton)
}

if (process.argv.length !== 3)
    throw new Error('Incorrect argument blah blah ')

classifyImage()
```
* Got the error message

What does this mean, and what do i do?
Also, is it possible the problem i steming from my hardware (CPU)?

**Comment by thierryntoh24** [comment]
Also, my `napi_v8` folder contains `tensorflow.ddl` and `tfjs_binding.node` files.
And I'm using `Python 3.10`

**Comment by thierryntoh24** [comment]
What i get when i run `node-gyp configure --verbose`

```PS D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node> node-gyp configure --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@8.4.0
gyp info using node@16.13.1 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
gyp verb find Python - executing "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe" to get version
gyp verb find Python - version is "3.10.2"
gyp info find Python using Python version 3.10.2 found at "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 16.13.1
gyp verb command install [ '16.13.1' ]
gyp verb install input version string "16.13.1"
gyp verb install installing version: 16.13.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9  
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.13.1
gyp verb build dir attempting to create "build" dir: D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2022 (17.0.32112.339) found at:
gyp verb find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v143
gyp verb find VS - found Windows SDK: 10.0.19041.0
gyp info find VS using VS2022 (17.0.32112.339) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\config.gypi
gyp verb common.gypi checking for gypi file: D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exegyp info spawn args [
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',  
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Thierry_Ntoh\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Thierry_Ntoh\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Thierry_Ntoh\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.4.0
gyp ERR! not ok
```

**Comment by thierryntoh24** [comment]
@pyu10055 , here it is

```
PS D:\Projects\art-review-bot> cd node_modules\@tensorflow\tfjs-node
PS D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node> npm build-addon-from-source
Unknown command: "build-addon-from-source"

Did you mean one of these?
    npm run build-addon-from-source # run the "build-addon-from-source" package script
    npm run install-from-source # run the "install-from-source" package script

To see a list of supported npm commands, run:
  npm help
PS D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node> npm run build-addon-from-source

> @tensorflow/tfjs-node@3.13.0 build-addon-from-source
> node-pre-gyp install --build-from-source

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.4        
node-pre-gyp info using node@16.13.1 | win32 | x64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | win32 | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
gyp info find VS using VS2022 (17.0.32112.339) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\nvm\\v16.13.1\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\nvm\\v16.13.1\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Thierry_Ntoh\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Thierry_Ntoh\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Thierry_Ntoh\\AppData\\Roaming\\nvm\\v16.13.1\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Thierry_Ntoh\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Projects\\art-review-bot\\node_modules\\@tensorflow\\tfjs-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.1 | win32 | x64
gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  tfjs_backend.cc
  tfjs_binding.cc
  win_delay_load_hook.cc
     Creating library D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build\Release\tfjs_binding.lib and object D:\Projects\art-review-bot\node_module 
  s\@tensorflow\tfjs-node\build\Release\tfjs_binding.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 833 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  tfjs_binding.vcxproj -> D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build\Release\\tfjs_binding.node
  Copying D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\build\Release\/tfjs_binding.node to D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs 
  -node\lib\napi-v8
          1 file(s) copied.
gyp info ok
node-pre-gyp info ok
```
and then i build the project again

```
PS D:\Projects\art-review-bot> npm run dev 

> art-review-bot@1.0.0 dev
> ts-node src/engine.ts

Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Projects\art-review-bot\node_modules\@tensorflow\tfjs-node\dist\index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
PS D:\Projects\art-review-bot> 
```

**Comment by pyu10055** [comment]
The possibility is that your CPU does not support AVX instructions. See tensorflow issues [here](https://github.com/tensorflow/tensorflow/issues/44110)
You can try tfjs-node-gpu to see if your GPU can be supported.
