### ISSUE TITLE
Unsupported Ops: Dequantize

### ISSUE THREAD

**Issue by WinterTaoTao** [tensorflow/tfjs#611]
```
Traceback (most recent call last):
  File "/Users/winter/virtualenv/ML-Python3/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/Users/winter/virtualenv/ML-Python3/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 272, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/Users/winter/virtualenv/ML-Python3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 325, in convert_tf_frozen_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "/Users/winter/virtualenv/ML-Python3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 113, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
Dequantize

```

Is the Dequantize operation on the schedule to add support?

**Comment by pyu10055** [comment]
@WinterTaoTao we currently only supports int32 and float32 tensor types, can you tell us more about what is your use case for dequnatize op? Thanks!

**Comment by DavidGOrtega** [comment]
coming from TF lite quantization its not only reducing the model size bit also making faster the inference reducing the floating point

**Comment by DavidGOrtega** [comment]
8bit vs 32bit

https://jsperf.com/canvas-pixel-manipulation

**Comment by pyu10055** [comment]
this requires quantization support from core.

**Comment by rthadur** [comment]
We will not support this. Closing this feature request
