### ISSUE TITLE
"Error: Failed to compile fragment shader - 'lessThan' : no matching overloaded function found" when trying to Pad 5D tensor

### ISSUE THREAD

**Issue by IMG-PRCSNG** [tensorflow/tfjs#6167]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): **Using TFJS Benchmark tool on custom model**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **NA**
- TensorFlow.js installed from (npm or script link): https://unpkg.com/@tensorflow/tfjs-core@latest/dist/tf-core.js
- TensorFlow.js version (use command below): **3.13.0**
- Browser version: **Chrome 97.0.4692.71**
- Tensorflow.js Converter Version: **3.9.0**

**Describe the current behavior**
I receive a Fragment Shader Compilation error when trying to load a model that pads a 5D tensor with the following Error

`ERROR: 0:161: 'lessThan' : no matching overloaded function found (webgl_utils.ts:135)`

[Link](https://github.com/tensorflow/tfjs/blob/aa2c7e1daf8b9620fa04c2426dbfb957270859fc/tfjs-backend-webgl/src/pad_gpu.ts#L62) to relevant line in source

I believe this is due to the fact that iVec5 is a generated type (a struct) and lessThan GL operator cannot be applied to it?

**Other info / logs** I
StackTrace:
```
webgl_util.ts:103 Uncaught (in promise) Error: Failed to compile fragment shader.
    at createFragmentShader (webgl_util.ts:103:11)
    at compileProgram (gpgpu_math.ts:101:26)
    at backend_webgl.ts:943:14
    at MathBackendWebGL.getAndSaveBinary (backend_webgl.ts:996:31)
    at MathBackendWebGL.runWebGLProgram (backend_webgl.ts:942:25)
    at Object.padV2 [as kernelFunc] (PadV2.ts:48:26)
    at kernelFunc (engine.ts:644:22)
    at engine.ts:711:23
    at Engine.scopedRun (engine.ts:478:19)
    at Engine.runKernelFunc (engine.ts:707:10)
```
Full Shader - See Line 161
```
#version 300 es
2        precision highp float;
3        precision highp int;
4        precision highp sampler2D;
5        in vec2 resultUV;
6        out vec4 outputColor;
7        const vec2 halfCR = vec2(0.5, 0.5);
8    
9        struct ivec5
10       {
11         int x;
12         int y;
13         int z;
14         int w;
15         int u;
16       };
17   
18       struct ivec6
19       {
20         int x;
21         int y;
22         int z;
23         int w;
24         int u;
25         int v;
26       };
27   
28       uniform float NAN;
29       
30         bool isnan_custom(float val) {
31           return (val > 0.0 || val < 0.0) ? false : val != 0.0;
32         }
33   
34         bvec4 isnan_custom(vec4 val) {
35           return bvec4(isnan_custom(val.x),
36             isnan_custom(val.y), isnan_custom(val.z), isnan_custom(val.w));
37         }
38   
39         #define isnan(value) isnan_custom(value)
40       
41       
42       
43         #define round(value) newRound(value)
44         int newRound(float value) {
45           return int(floor(value + 0.5));
46         }
47   
48         ivec4 newRound(vec4 value) {
49           return ivec4(floor(value + vec4(0.5)));
50         }
51       
52   
53       int imod(int x, int y) {
54         return x - y * (x / y);
55       }
56   
57       int idiv(int a, int b, float sign) {
58         int res = a / b;
59         int mod = imod(a, b);
60         if (sign < 0. && mod != 0) {
61           res -= 1;
62         }
63         return res;
64       }
65   
66       //Based on the work of Dave Hoskins
67       //https://www.shadertoy.com/view/4djSRW
68       #define HASHSCALE1 443.8975
69       float random(float seed){
70         vec2 p = resultUV * seed;
71         vec3 p3  = fract(vec3(p.xyx) * HASHSCALE1);
72         p3 += dot(p3, p3.yzx + 19.19);
73         return fract((p3.x + p3.y) * p3.z);
74       }
75   
76       
77   vec2 uvFromFlat(int texNumR, int texNumC, int index) {
78     int texR = index / texNumC;
79     int texC = index - texR * texNumC;
80     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
81   }
82   vec2 packedUVfrom1D(int texNumR, int texNumC, int index) {
83     int texelIndex = index / 2;
84     int texR = texelIndex / texNumC;
85     int texC = texelIndex - texR * texNumC;
86     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
87   }
88   
89       
90   vec2 packedUVfrom2D(int texelsInLogicalRow, int texNumR,
91     int texNumC, int row, int col) {
92     int texelIndex = (row / 2) * texelsInLogicalRow + (col / 2);
93     int texR = texelIndex / texNumC;
94     int texC = texelIndex - texR * texNumC;
95     return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
96   }
97   
98       
99   vec2 packedUVfrom3D(int texNumR, int texNumC,
100      int texelsInBatch, int texelsInLogicalRow, int b,
101      int row, int col) {
102    int index = b * texelsInBatch + (row / 2) * texelsInLogicalRow + (col / 2);
103    int texR = index / texNumC;
104    int texC = index - texR * texNumC;
105    return (vec2(texC, texR) + halfCR) / vec2(texNumC, texNumR);
106  }
107  
108    
109  
110      float sampleTexture(sampler2D textureSampler, vec2 uv) {
111        return texture(textureSampler, uv).r;
112      }
113    
114  
115      void setOutput(float val) {
116        outputColor = vec4(val, 0, 0, 0);
117      }
118    
119  uniform sampler2D x;
120  uniform int offsetx;
121  uniform float value;
122  
123      ivec5 getOutputCoords() {
124        ivec2 resTexRC = ivec2(resultUV.yx * vec2(1818,
125                               1818));
126  
127        int index = resTexRC.x * 1818 + resTexRC.y;
128  
129        int r = index / 3303783; index -= r * 3303783;int c = index / 157323; index -= c * 157323;int d = index / 687; index -= d * 687;int d2 = index / 3; int d3 = index - d2 * 3;
130  
131        ivec5 outShape = ivec5(r, c, d, d2, d3);
132        return outShape;
133      }
134    
135  
136        
137      float getX(int row, int col, int depth, int depth2) {
138        // Explicitly use integer operations as dot() only works on floats.
139        int index = row * 150528 + col * 672 +
140            depth * 3 + depth2;
141        vec2 uv = uvFromFlat(1552, 1552, index + offsetx);
142        return sampleTexture(x, uv);
143      }
144    
145        float getX(int row, int col, int depth, int depth2, int depth3) {
146          return getX(col, depth, depth2, depth3);
147        }
148      
149      float getXAtOutCoords() {
150        ivec5 coords = getOutputCoords();
151        
152        return getX(coords.x, coords.y, coords.z, coords.w, coords.u);
153      }
154    
155  
156        ivec5 start = ivec5(0,2,2,2,0);
157        ivec5 end = ivec5(1,18,226,226,3);
158  
159        void main() {
160          ivec5 outC = getOutputCoords();
161          if (any(lessThan(outC, start)) || any(greaterThanEqual(outC, end))) {                                                                                                     
162            setOutput(value);
163          } else {
164            ivec5 coords = outC - start;
165            setOutput(getX(coords[0],coords[1],coords[2],coords[3]));
166          }
167        }
168      
```

**Comment by rthadur** [comment]
The error might be because larger image sizes and memory out of bounds , did you get chance to check a similar issue here https://github.com/tensorflow/tfjs/issues/1644 ?

**Comment by IMG-PRCSNG** [comment]
In the issue you linked, you get a context lost error.

But I get an error saying no matching function overload.

ERROR: 0:161: 'lessThan' : no matching overloaded function found (webgl_utils.ts:135)

There is no lessThan function defined for ivec5 input in tfjs WebGL backend folder. And built in functions are only available for built in types (vec2, vec3, etc.)

I rebuilt WebGL backend with custom functions for lessThan, greater than and any, and it works for that use case. But I am not a pro in WebGL and am not that familiar with tfjs to know if it is correct.

**Comment by gaikwadrahul8** [comment]
Hi, @IMG-PRCSNG 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ?

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by IMG-PRCSNG** [comment]
Hi,

I am not sure if it is resolved. I will check the latest version and open a new one with a repro if it still persists.

I will close this for now.

Cheers!
