### ISSUE TITLE
[tfjs-converter] Unsupported Ops: PartitionedCall, BitwiseAnd

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#6172]
**System information**
- TensorFlow.js version (you are using): `tensorflowjs_converter --version` = `3.13.0`
- Are you willing to contribute it (Yes/No): Yes, where possible.

Here's the command I ran:
```
tensorflowjs_converter --input_format=tf_saved_model --output_format=tfjs_graph_model /content/saved_model /content/tfjs_model
```
And here's the full error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 771, in convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 724, in _convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 157, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
PartitionedCall, BitwiseAnd
```

**Comment by gaikwadrahul8** [comment]
Hi, @josephrocca 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and it seems like we haven't implemented these Ops so May I know are you still looking for these Ops in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do it and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by josephrocca** [comment]
Yep, still need them.

**Comment by nileshau-afk** [comment]
Hello @josephrocca ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @josephrocca  ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
