### ISSUE TITLE
tensorflowjs_converter InvalidArgumentError

### ISSUE THREAD

**Issue by iknowleigh** [tensorflow/tfjs#6177]
Whilst trying to convert a TF Saved Model to TFJS Graph Model the conversion fails and throws a InvalidArgumentError.

Command:
`tensorflowjs_converter --input_format=tf_saved_model --saved_model_tags=serve --signature_name=serving_default  ./3.4model.pb ./output`

Versions:
tensorflow              2.6.2
tensorflowjs            3.13.0

Full trace log:
2022-02-25 11:36:17.705521: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-25 11:36:18.237098: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2022-02-25 11:36:18.237169: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-02-25 11:36:18.319180: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 1418 nodes (1389), 2125 edges (2096), time = 52.338ms.
  function_optimizer: function_optimizer did nothing. time = 2.186ms.

WARNING:tensorflow:From /user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:397: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:From /user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:402: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use 'tf.compat.v1.graph_util.convert_variables_to_constants'
WARNING:tensorflow:From /user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py:927: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use 'tf.compat.v1.graph_util.extract_sub_graph'
Traceback (most recent call last):
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node StatefulPartitionedCall/LSTM_92444743/rnn/while/body/_29/AssignVariableOp was passed float from Func/StatefulPartitionedCall/LSTM_92444743/rnn/while/body/_29/input/_318:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 635, in _convert_tf_saved_model
    frozen_graph = _freeze_saved_model_v2(concrete_func, control_flow_v2)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 434, in _freeze_saved_model_v2
    aggressive_inlining=True).graph
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1154, in convert_variables_to_constants_v2
    converted_input_indices)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1080, in _construct_concrete_function
    new_output_names)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 628, in wrap_function
    collections={}),
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node StatefulPartitionedCall/LSTM_92444743/rnn/while/body/_29/AssignVariableOp was passed float from Func/StatefulPartitionedCall/LSTM_92444743/rnn/while/body/_29/input/_318:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/lj/py3.6.8/venv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 771, in convert_tf_saved_model
    metadata=metadata)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 641, in _convert_tf_saved_model
    output_node_names)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 402, in _freeze_saved_model_v1
    sess, meta_graph_def, output_node_names)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 346, in new_func
    return func(*args, **kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 281, in convert_variables_to_constants
    variable_names_denylist=variable_names_blacklist)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1282, in convert_variables_to_constants_from_session_graph
    variable_names_denylist=variable_names_denylist))
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py", line 927, in __init__
    graph_def = graph_util.extract_sub_graph(graph_def, output_node_names)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 346, in new_func
    return func(*args, **kwargs)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 209, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/user/lj/py3.6.8/venv/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 164, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: Identity is not in graph
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).gen_tensor_dict
WARNING:tensorflow:Unresolved object in checkpoint: (root).signatures.serving_default
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details

For reference the TF Saved Model was originally converted from ONNX (opset-10 ) using the following command:
`onnx-tf convert -i ./dna_r9.4.1_e8_fast\@3.4.onnx -o 3.4model.pb`

ONNX model attached
[dna_r9.4.1_e8_fast@3.4.onnx.zip](https://github.com/tensorflow/tfjs/files/8140953/dna_r9.4.1_e8_fast%403.4.onnx.zip)

**Comment by rthadur** [comment]
I believe the preprocessing layers are not supported in tfjs , can you please check related issue here https://github.com/tensorflow/tfjs/issues/3553 for a workaround. Thank you
