### ISSUE TITLE
[tfjs-react-native] error: bundling failed: Error: Unable to resolve module @react-native-community/async-storage from @tensorflow/tfjs-react-native/dist/async_storage_io.js (does not exist in the Haste module map)

### ISSUE THREAD

**Issue by loucadufault** [tensorflow/tfjs#6217]
**System information**
- OS Platform and Distribution: macOS Big Sur 11.5.2 (20G95)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 4XL API 29 Android 10.0
- TensorFlow.js installed from: npm
- TensorFlow.js version: 3.14.0
- tfjs-react-native version: 0.8.0
- CUDA/cuDNN version:
- Java version: 8 (I needed to downgrade from 14, see this issue: https://github.com/gradle/gradle/issues/10248)

**Describe the problem**

I am running into several issues when trying to clone and setup the `integration_rn59` for the purpose of getting it working locally on an android emulator. I have taken what seems like the right steps to solve some of them, but now am unable to solve some issues related to the @react-native-community/async-storage module

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have made the minimal amount of changes to the project to try and solve issues as they occured. Here are the steps I took:
1) Clone this repo, all work done inside the `integration_rn59` directory (did not move it as some config inherits from configs above)
2) Installing the dependencies as indicated in the `package.json` gives peer dep errors, which I bypass with `npm i --legacy-peer-deps`
3) I started running into this error when doing `npx react-native run-android`:

```
> Task :@react-native-community_async-storage:compileDebugJavaWithJavac FAILED  
/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageExpoMigration.java:7: error: cannot find symbol
import androidx.annotation.RequiresApi;
```

I solved this by consulting [this SO answer](https://stackoverflow.com/questions/40380519/error-package-com-android-annotations-does-not-exist/56876517#56876517), which lead me to add:

```
android.useAndroidX=true
android.enableJetifier=true
```
to the `android/gradle.properties` as well as set up jetifier and run `npx jetify`

4) After making these changes, the build for `run-android` started succeeding, but I was getting errors in the bundling (`npx react-native start`. Namely,

<details>

```
Loading dependency graph, done.  
error: bundling failed: Error: Unable to resolve module `@react-native-community/async-storage` from `/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@tensorflow/tfjs-react-native/dist/async_storage_io.js`: Module `@react-native-community/async-storage` does not exist in the Haste module map  
  
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at /Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 DELTA  [android, dev] ./index.js ▓▓▓▓░░░░░░░░░░░░ 25.5% (159/319)::ffff:127.0.0.1 - - [12/Mar/2022:03:15:19 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 DELTA  [android, dev] ./index.js ▓▓▓▓░░░░░░░░░░░░ 25.5% (159/319), failed.
```
</details>

I followed the 4 steps to no avail, then I attempted to solve this by following the suggestion to upgrade to latest TFJS & TFJS-RN in this related issue https://github.com/tensorflow/tfjs/issues/2753
Substituting only these lines in the `package.json` and then cleaning and reinstalling deps:

```
-    "@tensorflow/tfjs": "3.7.0",
-    "@tensorflow/tfjs-react-native": "0.5.0",
+    "@tensorflow/tfjs": "^3.14.0",
+    "@tensorflow/tfjs-react-native": "^0.8.0",
```

I now get a different error, that I am at a loss to solve:

<details>

```
Loading dependency graph, done.
error: bundling failed: SyntaxError: /Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@react-native-async-storage/async-storage/src/index.ts: Unexpected token (2:12)

  1 | import AsyncStorage from './AsyncStorage';
> 2 | import type { AsyncStorageHook, AsyncStorageStatic } from './types';
    |             ^
  3 | 
  4 | export { useAsyncStorage } from './hooks';
  5 | export type { AsyncStorageStatic } from './types';
    at Object.raise (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.unexpected (/Users/me/homep/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:7642:16)
    at Object.expectContextual (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:7608:41)
    at Object.parseImport (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:11168:12)
    at Object.parseImport (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:5316:18)
    at Object.parseStatementContent (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:9927:27)
    at Object.parseStatementContent (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:5372:18)
    at Object.parseStatement (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:9829:17)
    at Object.parseBlockOrModuleBlockBody (//Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:10405:25)
    at Object.parseBlockBody (/Users/me/home/tfjs/tfjs-react-native/integration_rn59/node_modules/@babel/parser/lib/index.js:10392:10)
 DELTA  [android, dev] ./index.js ▓▓▓▓░░░░░░░░░░░░ 26.0% (241/654)::ffff:127.0.0.1 - - [12/Mar/2022:04:57:08 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 DELTA  [android, dev] ./index.js ▓▓▓▓░░░░░░░░░░░░ 26.0% (241/654), failed.

```

</details>

**Any other info / logs**
*Tracebacks included inline*

**Comment by gaikwadrahul8** [comment]
Hi, @loucadufault 

Apologize for the delayed response and It seems like there is package dependancies compatibility issue so could you please try with package dependancies which are mentioned in this [official documentation](https://github.com/tensorflow/tfjs-examples/tree/master/react-native) and let us know whether is it working as expected or not ?

If issue still persists please let us know ? Thank you!

```
"expo": "~44.0.2",
"expo-camera": "^12.1.0",
"expo-file-system": "^13.2.0",
"expo-gl": "^11.1.1",
"expo-gl-cpp": "^11.1.0",
"react": "17.0.1",
"react-native": "~0.64.3",
```
