### ISSUE TITLE
React Native - TypeError: undefined is not an object (evaluating 'env().platform.fetch')

### ISSUE THREAD

**Issue by jysung** [tensorflow/tfjs#6341]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Monterey 12.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): yarn installed
- TensorFlow.js version (use command below):
```
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@tensorflow-models/mobilenet": "^2.1.0",
    "@tensorflow/tfjs": "^3.16.0",
    "@tensorflow/tfjs-backend-cpu": "^3.16.0",
    "@tensorflow/tfjs-backend-webgl": "^3.16.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo-camera": "^12.1.2",
    "expo-gl": "^11.1.2",
    "expo-gl-cpp": "^11.1.1",
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-fs": "^2.19.0",
    "react-native-macos": "^0.64.0-0",
    "react-native-unimodules": "^0.14.10"
```
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**

I am trying to run react native on MacOS. My app is bare RN app (not expo app) but I have installed all the needed expo dependencies as above.

Tried both `@tensorflow-models/mobilenet` and `@tensorflow-models/coco-ssd`, but getting this error.
`tf.ready()` works fine but `load()` gives this error on both models.

```
 ERROR  [TypeError: undefined is not an object (evaluating 'env().platform.fetch')]
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/jysung/jido/visual_search/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/jysung/jido/visual_search/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/jysung/jido/visual_search/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/jysung/jido/visual_search/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/jysung/jido/visual_search/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
 LOG  Unable to symbolicate stack trace: The stack is null
```

`env().platform` is `undefined`. Don't know what that means.

**Describe the expected behavior**

I just want to load models and run detection/prediction.

**Standalone code to reproduce the issue**

```
await tf.ready();
await mobilenet.load();
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
@jysung could you please elaborate steps you are trying to do. Please check the working example here for posenet and image classification here https://github.com/tensorflow/tfjs-examples/tree/master/react-native . Also please remove multiple references of tfjs in package.json , you can use either `cpu` or `webgl`. Thank you
