### ISSUE TITLE
Unsupported Ops: InvertPermutation, TensorScatterUpdate

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#6395]
**System information**
- TensorFlow.js version (you are using): `tensorflowjs_converter --version` = `3.15.0`
- Are you willing to contribute it (Yes/No): I'm willing, but potentially not able - unless I have some guidance from a pro.

Here's the command I ran:
```
tensorflowjs_converter --input_format tf_saved_model ./score_images_grad ./score_images_grad_tfjs
```
And here's the full error:
```
2022-05-11 07:43:23.091436: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 533, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 773, in convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 668, in _convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 157, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
PartitionedCall, InvertPermutation, TensorScatterUpdate
```
There's [already an issue open for PartitionedCall](https://github.com/tensorflow/tfjs/issues/6172), so I omitted that from the title.

**Comment by rthadur** [comment]
cc @pyu10055

**Comment by marcvanzee** [comment]
+1 for InvertPermutation.

**Comment by gaikwadrahul8** [comment]
Hi, @josephrocca 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I see we have implemented this Op [tf.tensorScatterUpdate](https://js.tensorflow.org/api/4.4.0/#tensorScatterUpdate) and it seems like we haven't implemented this Op InvertPermutation yet May I know are you still looking for this Op in TFJs ? 

If someone wants to contribute for this feature then you're always welcome and please feel free to do and please refer these links [Ref-1](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md), [Ref-2](https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md) . Thank you!

**Comment by josephrocca** [comment]
Hi, yep, InvertPermutation is needed

**Comment by nileshau-afk** [comment]
Hello @josephrocca  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @josephrocca  ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
