### ISSUE TITLE
[tflite] Loading tflite with `await import('...')` should work

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#6402]
This code correctly loads the tf-tflite library:
```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.16.0/dist/tf-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu@3.16.0/dist/tf-backend-cpu.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.8/dist/tf-tflite.min.js"></script>
```
But this doesn't:
```html
<script type="module">
  await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.16.0/dist/tf-core.min.js");
  await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu@3.16.0/dist/tf-backend-cpu.min.js");
  await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.8/dist/tf-tflite.min.js");
</script>
```
If I understand correctly, the two should work equivalently (it does with other libraries that I've tried). The latter code uses the wrong location for the `tflite_web_api_cc_simd.js` file which results in a request error. I think this probably has something to do with the scripts trying to use `document.currentScript.src` instead of `import.meta.url`. It should use the latter if running in a module.

**Comment by rthadur** [comment]
@josephrocca please share the error message if possible . Thank you

**Comment by josephrocca** [comment]
@rthadur Sure:

```
Uncaught (in promise) TypeError: $[(b.tfliteWebApiName + "_ModuleFactory")] is not a function
    at $jscomp.generator.Engine_.program_ (tf-tflite.min.js:17:756379)
    at $jscomp.generator.Engine_.nextStep_ (tf-tflite.min.js:17:12479)
    at $jscomp.generator.Engine_.next_ (tf-tflite.min.js:17:11443)
    at $jscomp.generator.Generator_.next (tf-tflite.min.js:17:12924)
    at t (tf-tflite.min.js:17:13343)
```

Note that it makes a request to `https://null.jsbin.com/tflite_web_api_cc_simd.js` in this example: https://jsbin.com/lifelugivi/edit?html,output

jsbin.com for some reason returns an empty response, so there's no request error. If you copy and paste these lines into Chrome browser console on a site that appropriately returns a 404 for non-existent files, then you'll see a request and/or JS-parsing related error:
```
await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@3.16.0/dist/tf-core.min.js");
await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-cpu@3.16.0/dist/tf-backend-cpu.min.js");
await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.8/dist/tf-tflite.min.js");
```
Again, I'm fairly sure this is just because `import.meta.url` needs to be used to get the correct relative/base URL.

**Comment by shmishra99** [comment]
Hi @josephrocca ,
I apologize for the delay in my response. After replicating the issue, I have encountered the same error message `tflite_web_api_client.js:1687 GET file:///Users/sh/TFJS/issue6402/tflite_web_api_cc_simd.js net::ERR_FILE_NOT_FOUND`. It appears that the file `tflite_web_api_cc_simd.js` is being loaded from the local directory instead of the server. Thank you for bringing this issue to our attention.
CC: @jinjingforever

**Comment by nileshau-afk** [comment]
Hello @josephrocca  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @josephrocca, Thank you for your patience, we have reproduced the issue. As a workaround, you can resolve the loading failure by explicitly setting the path to the WASM assets using the setWasmPath method on the loaded tflite module. Could you please try this and let us know if it works for you?
