### ISSUE TITLE
Possible WASM gradient memory leak in e2e tests

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#6518]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian rodete
- TensorFlow.js installed from (npm or script link): GitHub
- TensorFlow.js version (use command below): TODO
- Browser version::

**Describe the current behavior**

Running [grad_layer_test.ts](https://github.com/tensorflow/tfjs/blob/master/e2e/integration_tests/grad_layers_test.ts) against the wasm backend results in this error message:
```
1) can compute grad of prediction
     #SMOKE tf.grad for layers models layers_model wasm {}
     Expected function not to throw, but it threw Error: Backend 'wasm' has an internal memory leak (4 data ids) after running 'fusedMatMul__op'.
    at <Jasmine>
    at Object.<anonymous> (integration_tests/grad_layers_test.ts:49:14 <- integration_tests/grad_layers_test.js:60:24)
    at step (integration_tests/grad_layers_test.js:32:23)
    at Object.next (integration_tests/grad_layers_test.js:13:53)
    at integration_tests/grad_layers_test.js:7:71
    at <Jasmine>
    at __awaiter (integration_tests/grad_layers_test.js:3:12)
    at UserContext.<anonymous> (integration_tests/grad_layers_test.ts:38:42 <- integration_tests/grad_layers_test.js:49:67)
    at <Jasmine>
```
**Describe the expected behavior**
No error

**Standalone code to reproduce the issue**
TODO

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by avmohansai** [comment]
Hello @mattsoulanille   ,
Thank you for bringing this issue to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @mattsoulanille ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
