### ISSUE TITLE
Error: FusedConv2d and DepthwiseConv2d with BiasAdd must have one extra argument: bias

### ISSUE THREAD

**Issue by okyanusoz** [tensorflow/tfjs#6522]
I keep getting Error: FusedConv2d and DepthwiseConv2d with BiasAdd must have one extra argument: bias. when I try model.predict() on a MobileNet model.

The model looks like this in Python (Kaggle notebooks):

```
layer = hub.KerasLayer("https://tfhub.dev/google/imagenet/mobilenet_v3_large_100_224/feature_vector/5",
           trainable=False, input_shape=(224, 224, 3))
model = tf.keras.Sequential([
  normalization_layer,
  layer,
  tf.keras.layers.Dense(len(class_names), activation="softmax")
])
model.compile(
  optimizer=tf.keras.optimizers.Adam(),
  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['acc'])

history = model.fit(train_ds,
                validation_data=val_ds,
                epochs=2)
model.save("model")
```

The converter command (another notebook):

```
tensorflowjs_converter \
--input_format=tf_saved_model \
--output_format=tfjs_graph_model \
--signature_name=serving_default \
--saved_model_tags=serve \
[model path] \
web_model
```

The JS code (my machine) :

const model = await tf.loadGraphModel("file://" + __dirname + "/web_model/model.json")
console.log(new Array(...(await modelPromise).predict(tf.node.decodeImage(blob).resizeBilinear([224,224]).expandDims(0)).dataSync()))

Stack trace:

```
Error: FusedConv2d and DepthwiseConv2d with BiasAdd must have one extra argument: bias.
at fusedConvAndDepthWiseParams (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:27747:19)
at executeOp$g (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:27795:22)
at /Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:28975:65
at /Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4441:22
at Engine.scopedRun (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4451:23)
at Engine.tidy (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4440:21)
at Object.tidy (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8901:19)
at /Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:28975:39
at executeOp (/Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:29019:7)
at /Users/stackoverflow/Desktop/jsmodel/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:29513:35
```

**Comment by okyanusoz** [comment]
When I use another model like PNasNet, this doesn't happen.

**Comment by ahmedsabie** [comment]
@okyanusoz Can you share the saved model? I can't run your code to generate the model since you didn't provide all the values

**Comment by okyanusoz** [comment]
This one, I think: https://www.kaggle.com/datasets/okyanusoz/tensorflowjs-issue-6522-savedmodel
