### ISSUE TITLE
WASM backend in a webworker dev experience is bad

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#6537]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): importScripts in a webworker
- TensorFlow.js version (use command below): 3.18.0
- Browser version: Chrome 102
- Tensorflow.js Converter Version:

**Describe the current behavior**
When running the WASM backend in a webworker,
```
async function WorkerFunc() {
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js");
    await tf.setBackend(backend);
}
```
one of the following errors occurs.
Bad data fetched:
```
tf-backend-wasm.js:5325 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
tf-backend-wasm.js:5325 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
tf-backend-wasm.js:5325 Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f 
tf.min.js:17 Initialization of backend wasm failed
```
Could not load url:
```
tfjs-backend-wasm.js:9 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from tfjs-backend-wasm-simd.wasm
    at instantiateAsync (tfjs-backend-wasm.js:9:13627)
    at createWasm (tfjs-backend-wasm.js:9:14237)
    at tfjs-backend-wasm.js:9:17312
    at backend_wasm.ts:349:14
    at new Promise (<anonymous>)
    at backend_wasm.ts:285:10
    at step (register_all_kernels.ts:230:32)
    at Object.next (register_all_kernels.ts:230:32)
    at fulfilled (register_all_kernels.ts:230:32)
```

This is not a very clear error message, but the problem is the wasm backend is requesting the wrong url. Setting the wasm path first fixes this, but tfjs should surface a better error to the user (or somehow find the correct wasm path). Also see https://github.com/tensorflow/tfjs/issues/6517

**Describe the expected behavior**
TFJS surfaces a descriptive error that tells the user to set the wasm path when they're running in a webworker.

**Standalone code to reproduce the issue**
```
response = `async function WorkerFunc() {
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js");
    importScripts("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js");
    // Uncomment the next line to fix it.
    // tf.wasm.setWasmPaths("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/wasm-out/");
    await tf.setBackend('wasm');

    console.log(tf.getBackend());
    const a = tf.tensor1d([1,2,3]);
    const b = tf.tensor1d([6,5,4]);
    a.add(b).print();
}

WorkerFunc();
`;
blob = new Blob([response], {type: 'application/javascript'});
worker = new Worker(URL.createObjectURL(blob));
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by avmohansai** [comment]
Hello @mattsoulanille   ,
Thank you for bringing this issue to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @mattsoulanille ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
