### ISSUE TITLE
Building tfjs-backend-cpu fails with error

### ISSUE THREAD

**Issue by qipengwang** [tensorflow/tfjs#6560]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7 (Intel)
- TensorFlow.js installed from (npm or script link): source
- TensorFlow.js version:

**Describe the problem**

I just build tfjs from source. I successfully build `tfjs-core`, but when I built `tfjs-backend-cpu`, I face the following error after running `yarn && yarn build`

```shell
yarn run v1.22.19
$ bazel build :tfjs-backend-cpu_pkg
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -88
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at main (/Users/wangqipeng/Desktop/tfjs/tfjs-backend-cpu/node_modules/@bazel/bazelisk/bazelisk.js:55:14)
    at Object.<anonymous> (/Users/wangqipeng/Desktop/tfjs/tfjs-backend-cpu/node_modules/@bazel/bazelisk/bazelisk.js:69:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -88,
  code: 'Unknown system error -88',
  syscall: 'spawn'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(webai) FAIL: 1
```

I install bazel@4.2.2 from `https://github.com/bazelbuild/bazel/releases/tag/4.2.2`. The bazel version I got after running `bazel --version` is 4.2.2

```shell
$ bazel --version                                                    [11:13:05]
bazel 4.2.2
```

**Any other info / logs**

**Comment by mattsoulanille** [comment]
It's possible that the version of Bazelisk we have installed in tfjs-backend-cpu is not up to date and is causing this error. Can you try running `bazel build //tfjs-backend-cpu:tfjs-backend-cpu_pkg` from the root directory of the repository?

**Comment by qipengwang** [comment]
> It's possible that the version of Bazelisk we have installed in tfjs-backend-cpu is not up to date and is causing this error. Can you try running `bazel build //tfjs-backend-cpu:tfjs-backend-cpu_pkg` from the root directory of the repository?
> 
> Edit: You can also try after #6565 is merged

Thanks for you reply, this problem solved.
