### ISSUE TITLE
python lib breaks on import

### ISSUE THREAD

**Issue by OHNONOTAMOTH** [tensorflow/tfjs#6567]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):gentoo
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):pip
- TensorFlow.js version (use command below):which command?
- Browser version:not on browser
- Tensorflow.js Converter Version:idk

**Describe the current behavior**
when I import the python converter lib with
`import tensorflowjs as tjs`
it throws this:
Traceback (most recent call last):
 ```
 File "/home/moth/badtakeai/src/maintain/maintain.py", line 8, in <module>
    import tensorflowjs as tjs
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflowjs/converters/__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflowjs/converters/converter.py", line 37, in <module>
    from tensorflowjs.converters import tf_saved_model_conversion_v2
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 42, in <module>
    import tensorflow_hub as hub
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_hub/__init__.py", line 88, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_hub/estimator.py", line 62, in <module>
    class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 27, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 31, in <module>
    from tensorflow.python.checkpoint import checkpoint as trackable_util
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/checkpoint/checkpoint.py", line 32, in <module>
    from tensorflow.python.checkpoint import graph_view as graph_view_lib
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/checkpoint/graph_view.py", line 19, in <module>
    from tensorflow.python.checkpoint import trackable_view
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/checkpoint/trackable_view.py", line 20, in <module>
    from tensorflow.python.trackable import converter
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/trackable/converter.py", line 23, in <module>
    from tensorflow.python.trackable import data_structures
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/trackable/data_structures.py", line 1103, in <module>
    revived_types.register_revived_type(
  File "/home/moth/.local/lib/python3.9/site-packages/tensorflow/python/saved_model/revived_types.py", line 133, in register_revived_type
    raise AssertionError(f"Duplicate registrations for type '{identifier}'")
AssertionError: Duplicate registrations for type 'trackable_dict_wrapper'
```

**Describe the expected behavior**
exporting

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
my code is :
```
from cmath import exp
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization
import re
import string
from tensorflow.keras import layers
import os.path
import tensorflowjs as tjs

def vectorize_text(text, label):
  text = tf.expand_dims(text, -1)
  return vectorize_layer(text), label

# Model constants.bad
max_features = 20000
embedding_dim = 128
sequence_length = 500

raw_train_ds = tf.keras.preprocessing.text_dataset_from_directory(
    "train/",
    validation_split=0.2,
    subset="training",
    seed=1337,
)

for text_batch, label_batch in raw_train_ds.take(1):
    for i in range(5):
        print(text_batch.numpy()[i])
        print(label_batch.numpy()[i])


def custom_standardization(input_data):
    lowercase = tf.strings.lower(input_data)
    stripped_html = tf.strings.regex_replace(lowercase, "<br />", " ")
    return tf.strings.regex_replace(
        stripped_html, f"[{re.escape(string.punctuation)}]", ""
    )

vectorize_layer = TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode="int",
    output_sequence_length=sequence_length,
)

# Model constants.
max_features = 20000
embedding_dim = 16
sequence_length = 500

# Now that the vocab layer has been created, call `adapt` on a text-only
# dataset to create the vocabulary. You don't have to batch, but for very large
# datasets this means you're not keeping spare copies of the dataset in memory.

# Let's make a text-only dataset (no labels):
text_ds = raw_train_ds.map(lambda x, y: x)
# Let's call `adapt`:
vectorize_layer.adapt(text_ds)

text_input = tf.keras.Input(shape=(1,), dtype=tf.string, name='text')
x = vectorize_layer(text_input)
x = layers.Embedding(max_features + 1, embedding_dim)(x)

# A integer input for vocab indices.
inputs = tf.keras.Input(shape=(None, ), dtype="int64")

# Next, we add a layer to map those vocab indices into a space of dimensionality
# 'embedding_dim'.
x = layers.Embedding(max_features, embedding_dim)(inputs)
x = layers.Dropout(0.5)(x)

# Conv1D + global max pooling
x = layers.Conv1D(128, 9, padding="valid", activation="relu", strides=3)(x)
x = layers.Conv1D(128, 9, padding="valid", activation="relu", strides=3)(x)
x = layers.GlobalMaxPooling1D()(x)

# We add a vanilla hidden layer:
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)

# We project onto a single unit output layer, and squash it with a sigmoid:
predictions = layers.Dense(1, activation="sigmoid", name="predictions")(x)

model = tf.keras.Model(inputs, predictions)

# Compile the model with binary crossentropy loss and an adam optimizer.
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

epochs = 500 

train_ds = raw_train_ds.map(vectorize_text)

model.fit(train_ds, epochs=epochs)

export_model = tf.keras.Sequential([
  vectorize_layer,
  model,
  layers.Activation('sigmoid')
])

export_model.compile(
    loss=tf.losses.BinaryCrossentropy(from_logits=False), optimizer="adam", metrics=['accuracy']
)

export_model.save("model")

tjs.converters.save_keras_model(export_model, "jsm")
# Test it with `raw_test_ds`, which yields raw strings
loss, accuracy = export_model.evaluate(raw_train_ds)
print(accuracy)
```
but it fails on the
`import tensorflowjs as tjs`
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pyu10055** [comment]
you might have duplicated version of tensorflow, can you run `pip3 list` to check what you have installed?

**Comment by ashish-2005** [comment]
Hii @rthadur,

I am facing the same issue on Windows machine, does having duplicated version of TensorFlow the only reason for this?  or is there a more robust solution?

thanks
