### ISSUE TITLE
Building tfjs-backend-webgpu failed

### ISSUE THREAD

**Issue by qipengwang** [tensorflow/tfjs#6580]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow.js installed from (npm or script link): source
- TensorFlow.js version: 3.18.0

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I fail to build tfjs-backend-wengpu from source. I just install the dependencies using `yarn`. then I run `yarn build` and it finished successfully. But then I want to rollup the package using `yarn rollup -c --ci` then I get the following errors:

```shell
yarn run v1.22.19
$ /home/wqp/tfjs_3.18.0/tfjs-backend-webgpu/node_modules/.bin/rollup -c --ci
WARNING:  [object Object]
WARNING:  [object Object]

src/index.ts → dist/tf-backend-webgpu.node.js...
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (12:72) @rollup/plugin-typescript TS1144: '{' or ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (229:72) @rollup/plugin-typescript TS1144: '{' or ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (399:98) @rollup/plugin-typescript TS1144: '{' or ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (399:105) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (399:108) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (431:102) @rollup/plugin-typescript TS1144: '{' or ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (431:109) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (431:112) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (733:51) @rollup/plugin-typescript TS1144: '{' or ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (733:57) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (733:60) @rollup/plugin-typescript TS1005: ';' expected.
WARNING:  (typescript plugin) node_modules/@types/node/assert.d.ts (891:65) @rollup/plugin-typescript TS1005: ';' expected.
[!] (plugin typescript) TypeError: Could not load /home/wqp/tfjs_3.18.0/tfjs-backend-webgpu/src/index.ts: ts.getOutputFileNames is not a function
TypeError: Could not load /home/wqp/tfjs_3.18.0/tfjs-backend-webgpu/src/index.ts: ts.getOutputFileNames is not a function
    at findTypescriptOutput (/home/wqp/tfjs_3.18.0/tfjs-backend-webgpu/node_modules/@rollup/plugin-typescript/dist/index.js:443:33)
    at Object.load (/home/wqp/tfjs_3.18.0/tfjs-backend-webgpu/node_modules/@rollup/plugin-typescript/dist/index.js:801:28)

error Command failed with exit code 1.
```

The dependencies I installed for rollup is: 

```shell
    "@rollup/plugin-commonjs": "^22.0.1",
    "@rollup/plugin-node-resolve": "^13.3.0",
    "@rollup/plugin-typescript": "8.3.0"
```

It seems that the error occurs due to `@rollup/plugin-typescript`. Then I tried all possible versions of `@rollup/plugin-typescript` via following shell. But I cannot rollup tfjs-backend-webgpu as well.

```shell
#!/bin/bash

versions=("2.0.0" "2.0.1" "2.0.2" "2.1.0" "3.0.0" "3.1.0" "3.1.1" "4.0.0" "4.1.0"
          "4.1.1" "4.1.2" "5.0.0" "5.0.1" "5.0.2" "6.0.0" "6.1.0" "8.0.0" "8.1.0"
          "8.1.1" "8.2.0" "8.2.1" "8.2.3" "8.2.4" "8.2.5" "8.3.0" "8.3.1" "8.3.2" "8.3.3")
for ((i=${#versions[@]}-1; i>=0; i--)); do
  version=${versions[$i]}
  yarn add @rollup/plugin-typescript@${version}
  yarn rollup -c --ci
  status=$?
  if [[ $status -eq 0 ]]; then
    echo $version "succeed"
    exit 0
  fi
done

```

Note that I rollup other backends successfully. For example, for tfjs-backend-cpu, the dependencies I installed are as following. But I cannot succeed with same dependencies when building tfjs-backend-webgpu

```shell

$ yarn list | grep rollup
├─ @rollup/plugin-commonjs@11.1.0
│  ├─ @rollup/pluginutils@^3.0.8
├─ @rollup/plugin-node-resolve@7.1.3
│  ├─ @rollup/pluginutils@^3.0.8
├─ @rollup/plugin-typescript@3.1.1
│  ├─ @rollup/pluginutils@^3.0.1
├─ @rollup/pluginutils@3.1.0
├─ rollup-plugin-terser@5.3.1
│  ├─ rollup-pluginutils@^2.8.2
├─ rollup-plugin-visualizer@3.3.2
├─ rollup-pluginutils@2.8.2
├─ rollup@2.75.7

```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by qipengwang** [comment]
Thanks a lot for your reply!

**Comment by qipengwang** [comment]
Another minor question is

**Comment by mattsoulanille** [comment]
`<tfjs>/dist/bin/tfjs-backend-webgpu/tfjs-backend-webgpu_pkg/dist/tfjs-backend-webgpu.min.js` is a copy of `<tfjs>/dist/bin/tfjs-backend-webgpu/tfjs-backend-webgpu.min.js` created by [this Bazel target](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/BUILD.bazel#L52-L63). It's used as part of the npm package creation.
