### ISSUE TITLE
op_list is missed

### ISSUE THREAD

**Issue by qipengwang** [tensorflow/tfjs#6581]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow.js installed from (npm or script link): source
- TensorFlow.js version: 3.18.0

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

When I build tfjs-converter from source, I run `yarn build` successfully. Then I want to rollup tfjs-converter using `yarn rollup -c --ci`, and I get the following error. This error occurs because `tfjs-converter/src/operations/op_list` is missing

```shell
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2307: Cannot find module './op_list/arithmetic'.
src/operations/operation_mapper.ts (24:29)

24 import * as arithmetic from './op_list/arithmetic';
                               ~~~~~~~~~~~~~~~~~~~~~~

Error: @rollup/plugin-typescript TS2307: Cannot find module './op_list/arithmetic'.
    at error (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/rollup/dist/shared/rollup.js:10149:30)
    at throwPluginError (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/rollup/dist/shared/rollup.js:16312:12)
    at Object.error (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/rollup/dist/shared/rollup.js:17320:24)
    at Object.error (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/rollup/dist/shared/rollup.js:16485:38)
    at /home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/@rollup/plugin-typescript/dist/index.js:27:21
    at Array.forEach (<anonymous>)
    at emitDiagnostics (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/@rollup/plugin-typescript/dist/index.js:22:10)
    at Object.transform (/home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/@rollup/plugin-typescript/dist/index.js:465:17)
    at /home/wqp/tfjs_3.18.0/tfjs-converter/node_modules/rollup/dist/shared/rollup.js:17532:25

error Command failed with exit code 1.
```

I check the pervious version of tfjs and find that the `op_list` dir is removed since `tfjs@3.10.0`.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by qipengwang** [comment]
Thanks a lot for your reply
