### ISSUE TITLE
[tfjs-converter] KeyError: 'kernel' when converting tfjs layers model to Keras

### ISSUE THREAD

**Issue by TheCodez** [tensorflow/tfjs#6592]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow.js Converter Version: 3.17.0

**Describe the current behavior**
I'm trying to convert the tensorflow js layer model from this [repo](https://github.com/FIGLAB/EyeMU/tree/master/flask2/static/models/tfjsmodel4) to Keras. However, when executing the script I get a `KeyError: 'kernel'`

The layer causing the issue seems to be `conv2d_1_1/kernel`

**Describe the expected behavior**
The model gets converted correctly without crashing.

**Standalone code to reproduce the issue**
`tensorflowjs_converter --input_format tfjs_layers_model --output_format keras tfjsmodel4/my-model.json my_keras/`

**Other info / logs** 
```
Traceback (most recent call last):
  File "c:\users\micha\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\micha\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python39\Scripts\tensorflowjs_converter.exe\__main__.py", line 7, in <module>
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\converter.py", line 803, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\converter.py", line 553, in _dispatch_converter
    dispatch_tensorflowjs_to_keras_saved_model_conversion(args.input_path,
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\converter.py", line 277, in dispatch_tensorflowjs_to_keras_saved_model_conversion
    model = keras_tfjs_loader.load_keras_model(config_json_path)
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\keras_tfjs_loader.py", line 225, in load_keras_model
    return _deserialize_keras_model(config_json['modelTopology'],
  File "c:\users\micha\appdata\local\programs\python\python39\lib\site-packages\tensorflowjs\converters\keras_tfjs_loader.py", line 92, in _deserialize_keras_model
    weights_list.append(weights_dict[shorten_name])
KeyError: 'kernel'
```

**Comment by rthadur** [comment]
Like Shanqing mentioned at https://github.com/tensorflow/tfjs/issues/1808#issuecomment-557099119, it is not possible to convert tfjs_graph_model to keras_saved_model.

If you have a tfjs_graph_model, you should have a tensorflow model (in keras, tf_hub, tf_saved_model, or tf_frozen_model format, see details here: https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#format-conversion-support-tables) and the tfjs_graph_model was converted from tf modell.
A tf.GraphModel can only be created by loading from a model converted from a TensorFlow SavedModel using the command line converter tool and loaded via tf.loadGraphModel().

You can convert the original model into a format you want to use on mobile native platforms.

**Comment by TheCodez** [comment]
@rthadur Sorry for the late response. In my case it is not a tf js graph model but tf js layer model. I have found another way to do the converting in the mean time. 
Maybe a warning could be added that it isn't supported to avoid confusion in the future?

**Comment by pyu10055** [comment]
@TheCodez Layers model should be convertible to Keras model, can you share the model that cause the error?
Also, I am curious what is the alternative way you succeeded in converting the model?

**Comment by gaikwadrahul8** [comment]
Hi, @TheCodez 

Could you please refer to the above comment by @pyu10055 and also refer to the [official documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter) for tfjs-converter? Thank you!

**Comment by TheCodez** [comment]
@gaikwadrahul8 @pyu10055 sorry for the late response. The model is: https://github.com/FIGLAB/EyeMU/tree/master/flask2/static/models/tfjsmodel4.

If I remember correctly, there was another model in that repo in a different format, which I allowed me to directly convert the model into .onnx without the Keras model step.

**Comment by Varun-S10** [comment]
Hi @TheCodez, Thank you for sharing your workaround to resolve the issue. Since you have confirmed that you found an alternative solution, I will close this issue for now. If you or anyone else encounters this problem again, please feel free to reopen it. Thank you for your understanding.
