### ISSUE TITLE
batchMatMul error

### ISSUE THREAD

**Issue by ran-j** [tensorflow/tfjs#670]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
    "@tensorflow/tfjs": "^0.12.4",
    "@tensorflow/tfjs-core": "^0.12.12",
    "@tensorflow/tfjs-node": "^0.1.11",

 #### Describe the problem or feature request

 I was using normali tensorflow JS on my chatbot but Today when I try to install again and run I got this erro:

```
TypeError: backend.batchMatMul is not a function
    at environment_1.ENV.engine.runKernel.$a (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-core\dist\ops\matmul.js:60:86)
    at C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:115:26
    at Engine.scopedRun (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:95:23)
    at Engine.runKernel (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:113:14)
    at matMul_ (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-core\dist\ops\matmul.js:60:40)
    at Object.matMul (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-core\dist\ops\operation.js:23:29)
    at Object.dot (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\backend\tfjs_backend.js:215:24)
    at C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\layers\core.js:142:28
    at C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:85:22
    at Engine.scopedRun (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:95:23)
    at Engine.tidy (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:84:21)
    at Object.Environment.tidy (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-core\dist\environment.js:45:35)
    at Dense.call (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\layers\core.js:139:28)
    at C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\engine\topology.js:408:36
    at Object.nameScope (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\common.js:25:19)
    at Dense.Layer.apply (C:\Users\Ranieri\Documents\Projetos\Node Js\TensorFlowJS\node_modules\@tensorflow\tfjs-layers\dist\engine\topology.js:392:25)
```

My old project is running great, the same code.

My code:
https://github.com/ran-j/ChatBotNodeJS/blob/master/routes/index.js#L325

**Comment by annxingyuan** [comment]
Hey,

Thanks for filing this. I think the issue might be that the package tfjs currently needs tfjs-core version 0.12.15, but the latest version of tfjs-core is 0.12.16. Our team will resolve this discrepancy soon, but in the meantime, could you confirm that you've installed tfjs-core version 0.12.16? And if so, could you downgrade to 0.12.15 and see whether that resolves the issue?

Sorry - I know this is a hacky workaround - I will let you know once tfjs and tfjs-core are back in sync :)

**Comment by ran-j** [comment]
Thanks with @tensorflow/tfjs-core": " 0.12.15 works.

Its ok and thanks for the help

**Comment by annxingyuan** [comment]
FYI: tfjs now requires the latest version of tfjs-core - so the next time you install packages you should not encounter the `batchMatMul` error.

**Comment by hunterdowns** [comment]
I'm not seeing this as fixed yet. I tried a simple example from tensorflow.js website:
```
const tf = require("@tensorflow/tfjs") ;
require("@tensorflow/tfjs-node") ;


// Train a simple model:
const model = tf.sequential();
model.add(tf.layers.dense({units: 100, activation: 'relu', inputShape: [10]}));
model.add(tf.layers.dense({units: 1, activation: 'linear'}));
model.compile({optimizer: 'sgd', loss: 'meanSquaredError'});

const xs = tf.randomNormal([100, 10]);
const ys = tf.randomNormal([100, 1]);

model.fit(xs, ys, {
  epochs: 100,
  callbacks: {
    onEpochEnd: async (epoch, log) => {
      console.log(`Epoch ${epoch}: loss = ${log.loss}`);
    }
  }
});
```

and this package file

```
{
  "name": "collearn",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow/tfjs": "^0.12.7",
    "@tensorflow/tfjs-core": "^0.12.18",
    "@tensorflow/tfjs-node": "^0.1.14"
  }
}
```

and this is my output from running `node index.js`:

```
cpu backend was already registered. Reusing existing backend
2018-09-04 12:19:44.829945: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
(node:16670) Warning: N-API is an experimental feature and could change at any time.
(node:16670) UnhandledPromiseRejectionWarning: TypeError: backend.batchMatMul is not a function
    at environment_1.ENV.engine.runKernel.$a (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs-core/dist/ops/matmul.js:60:86)
    at /Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:115:26
    at Engine.scopedRun (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:95:23)
    at Engine.runKernel (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:113:14)
    at matMul_ (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs-core/dist/ops/matmul.js:60:40)
    at Object.matMul (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:23:29)
    at Object.dot (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs-layers/dist/backend/tfjs_backend.js:215:24)
    at /Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs-layers/dist/layers/core.js:142:28
    at /Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:85:22
    at Engine.scopedRun (/Users/hunter/Node/collearn/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:95:23)
(node:16670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Then I tried the `mnist-node` example from the tfjs-examples and I get the same error.

Running node version 8.11.4 on a Mac OSX High Sierra

Thoughts?

**Comment by annxingyuan** [comment]
Hey there,

Thanks for bringing this up - the issue is that `tfjs-node` has not caught up to this latest change. To work around this, you could remove the explicit dependency on `tfjs-core` in your `package.json`, and require exactly version 0.12.4 of `tfjs`. So here's what your `package.json` `dependencies` might look like:

```

"dependencies": {
    "@tensorflow/tfjs": "0.12.4",
    "@tensorflow/tfjs-node": "^0.1.14"
  }

```

You might want to remove `node_modules` and then run `yarn` again. Hopefully that will resolve the error!

**Comment by hunterdowns** [comment]
Thanks! That did it. 

One thing to note is that I had just been using `npm` rather than `yarn` and that was asking me to use put an explicit dependency on `tfjs-core` in my `package.json`. Even after changed my package to match what you had suggested it was still asking for the `tfjs-core` dependency. If I put that back it, it failed as before.  

Following exactly what you said, I removed that explicit dependency, switched to `yarn`, and now it's working.  

Thanks again!
