### ISSUE TITLE
Installation of tensorflow/tfjs-node fails

### ISSUE THREAD

**Issue by 99JS** [tensorflow/tfjs#6700]
**System information**
- OS Platform and Distribution: `Microsoft Windows 11 Home, 10.0.22000 Build 22000`
- TensorFlow.js installed from (npm or script link): `npm`
- TensorFlow.js version: "@tensorflow/tfjs": "3.19.0", "@tensorflow/tfjs-node": "3.19.0"
- CUDA/cuDNN version: GPU version tfjs-node

**Describe the problem**

Attempting to install `npm install @tensorflow/tfjs-node-gpu` fails with multiple errors (see below undr Any other info / logs)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Execute `npm install @tensorflow/tfjs-node-gpu`

**Any other info / logs**
```
PS C:\Users\username\Documents\2Sigma> npm install @tensorflow/tfjs-node-gpu
npm ERR! code 1
npm ERR! path C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js gpu download
npm ERR! GPU-windows-3.19.0.zip
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.7.3.zip
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.5.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v8\tfjs_binding.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.19.0/GPU-windows-3.19.0.zip    
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.19.0/GPU-windows-3.19.0.zip
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node-gpu@3.19.0 and node@18.5.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.19.0/GPU-windows-3.19.0.zip
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.5.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@18.5.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\Users\username\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2019 (16.11.32002.261) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - missing any Windows SDK
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16        
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Users\\username\\node_modules\\node\\bin\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\username\\Documents\\2Sigma\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\Users\\username\\Documents\\2Sigma\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
npm ERR! gyp ERR! cwd C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu
npm ERR! gyp ERR! node -v v18.5.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\username\node_modules\node\bin\node.exe C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\username\Documents\2Sigma\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000
npm ERR! node-pre-gyp ERR! command "C:\\Users\\username\\node_modules\\node\\bin\\node.exe" "C:\\Users\\username\\Documents\\2Sigma\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\username\Documents\2Sigma\node_modules\@tensorflow\tfjs-node-gpu
npm ERR! node-pre-gyp ERR! node -v v18.5.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! * Downloading libtensorflow
npm ERR!
npm ERR! * Building TensorFlow Node.js bindings

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2022-08-01T02_49_44_495Z-debug-0.log
PS C:\Users\username\Documents\2Sigma> 
```

**Comment by rthadur** [comment]
please follow this [instruction](https://github.com/nodejs/node-gyp#on-windows) for setting up compilation environment for Windows.

**Comment by 99JS** [comment]
@rthadur Thank you, that solved it for me!

**Comment by Nihal-Naik** [comment]
Any solution?

**Comment by andresmv94** [comment]
same here

**Comment by lminardi1998** [comment]
I have the same issue, cannot install it on windows 10
