### ISSUE TITLE
tfjs-node fails to install with Yarn PnP on MacBook M1 (Node 18)

### ISSUE THREAD

**Issue by vicary** [tensorflow/tfjs#6785]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Apple M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.19.0
- Browser version: N/A
- Tensorflow.js Converter Version: N/A

**Describe the current behavior**
Running `npm i @tensorflow/tfjs-node` on a M1 Macbook Air with Node 18 installed results in an error about napi-v8 prebuild binary not found.

**Describe the expected behavior**
The installation should run normally.

**Standalone code to reproduce the issue**
Not about source code, but about the underlying system instead.

**Other info / logs** 
Please see this build log, where it tries to download prebuild binary of napi-v8 for darwin.
[build.log](https://github.com/tensorflow/tfjs/files/9403240/build.log)

The closest available alternative is napi-v7, the current workaround is falling back to Node 16.

**Comment by rthadur** [comment]
Can you please check these steps before you install tfjs-node 

1. Make sure you are starting your terminal without rosetta. (Which make sure the arch is in arm64)
2. use nvm to install node with arm64 binary.
3. install tfjs-node after that.

For more info can you please refer to this [issue](https://github.com/tensorflow/tfjs/issues/6381). Thank you

**Comment by vicary** [comment]
@rthadur See if this is enough to confirm my arch?

1. I use the terminal in VS Code, it natively supports M1 without Rosetta 2.
2. Running `node -p "process.arch"` gives me _arm64_.
3. The behavior is the same as before. Installing with Node 18 fails, but succeed in Node 16.

In fact I never had the `Illegal instruction: 4` error shown in #6381, my build log is about a missing prebuild binary for napi-v8 where `install.js` tries to grab at https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.19.0/CPU-darwin-3.19.0.tar.gz.

**Comment by rthadur** [comment]
Can you please try with latest release 3.20.0 ?

**Comment by pyu10055** [comment]
@vicary what is your output for `uname -m`?

**Comment by vicary** [comment]
@rthadur Oh yes, it installs with the following warning but when I manually installs `seedrandom` it works like a charm!

```
@tensorflow/tfjs@npm:3.19.0 doesn't provide seedrandom (p1b545), requested by @tensorflow/tfjs-data
```

@pyu10055 It prints *arm64*

**Comment by vicary** [comment]
*Last message was incorrect, I deleted it.*

@rthadur 3.20.0 throws the same error, see the [build.log](https://github.com/tensorflow/tfjs/files/9421851/build.log).

You went to https://storage.googleapis.com/tf-builds and search for `"napi-v8/3.20.0/CPU-darwin"`, nothing matches.

In fact the closest `darwin` is `napi-v7/3.6.1`, nothing afterwards is available there.

@pyu10055 It prints *arm64*

**Comment by pyu10055** [comment]
@vicary can you provide the log after following this:
change directory to `node_models/@tensorflow/tfjs-node` and run `yarn build-addon-from-source`.

**Comment by vicary** [comment]
@pyu10055 When I try `cd node_modules` I noticed I am using Yarn PnP, I should mention it here.

I unzipped the cache zip and ran `yarn build-addon-from-source`, got the same error [build.log](https://github.com/tensorflow/tfjs/files/9429461/build.log).

**Comment by vicary** [comment]
I tried making a new empty project without PnP, it worked.

But many of my projects are using PnP, is it possible to make it work?

**Comment by pyu10055** [comment]
@vicary thank you for the context. We have not used or built for yarn pnp before, so at this moment this is no guarantee it will work. If you have the capacity or interests in figure out a solution and contribute would be awesome.

**Comment by vorg** [comment]
Same issue here with `npm i @tensorflow/tfjs-node@3.21.1`
Node: v18.10.0
MacBookPro with M1

**Comment by vorg** [comment]
Strange as it worked in Terminal.app but not iTerm.app despite neither of them using Rosetta and both logging arm64

**Comment by vicary** [comment]
Gently ping @pyu10055 and @rthadur.

Sorry I don't have enough knowledge on Yarn PnP to make this work myself.

Not urging for your follow ups, just want to keep this open because this is meant to be a long issue waiting for contributions.

**Comment by vctrmn** [comment]
Hello !

Same problem here

```
ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.21.1/CPU-darwin-3.21.1.tar.gz
```

**Comment by butadpj** [comment]
same problem here

```
npm ERR! code 1
npm ERR! path /Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-darwin-4.12.0.tar.gz
npm ERR! https://storage.googleapis.com/tf-builds/libtensorflow_r2_7_darwin_arm64_cpu.tar.gz
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@18.12.1 | darwin | arm64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" (not found)
npm ERR! node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.12.0/CPU-darwin-4.12.0.tar.gz
npm ERR! node-pre-gyp http 404 https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.12.0/CPU-darwin-4.12.0.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.12.0/CPU-darwin-4.12.0.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@4.12.0 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/4.12.0/CPU-darwin-4.12.0.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/butadpj/Library/Caches/node-gyp/18.12.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/butadpj/Library/Caches/node-gyp/18.12.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/butadpj/Library/Caches/node-gyp/18.12.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! action_after_build.target.mk:6: *** target pattern contains no `%'.  Stop.
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 23.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/lib/napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
npm ERR! gyp ERR! cwd /Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node --module_name=tfjs_binding --module_path=/Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node/lib/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 23.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/butadpj/Desktop/projects/AI:ML/basics/setup/node_modules/@tensorflow/tfjs-node
npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! * Downloading libtensorflow
npm ERR! 
npm ERR! * Building TensorFlow Node.js bindings
```
