### ISSUE TITLE
Uncaught (in promise) TypeError: backend.incRef is not a function

### ISSUE THREAD

**Issue by JeongJun-Lee** [tensorflow/tfjs#6807]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.20.0
- Browser version: Chromium 87.0.4280.47
- Tensorflow.js Converter Version: 3.20.0

**Describe the current behavior**
I tried [the tutorial](https://levelup.gitconnected.com/use-tensorflow-js-models-in-offline-applications-a7b5b0c67d4) for offline usage. When I tried it with model data(multi-pose lightning) from tensorflow-hub and tfjs-backend-webgl, errors below comes out:

**Describe the expected behavior**
It should be executed without error.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
Almost same as https://github.com/andypotato/tfjs-electron-template

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

`
2f696093-1d70-48aa-9c63-656f5530b5a9:9551 Uncaught (in promise) TypeError: backend.incRef is not a function
    at Object.identity [as kernelFunc] (2f696093-1d70-48aa-9c63-656f5530b5a9:9551)
    at kernelFunc (2f696093-1d70-48aa-9c63-656f5530b5a9:1115)
    at 2f696093-1d70-48aa-9c63-656f5530b5a9:1195
    at Engine.scopedRun (2f696093-1d70-48aa-9c63-656f5530b5a9:935)
    at Engine.runKernelFunc (2f696093-1d70-48aa-9c63-656f5530b5a9:1188)
    at Engine.runKernel (2f696093-1d70-48aa-9c63-656f5530b5a9:1022)
    at clone_ (2f696093-1d70-48aa-9c63-656f5530b5a9:16906)
    at clone__op (2f696093-1d70-48aa-9c63-656f5530b5a9:192)
    at cloneTensor (2f696093-1d70-48aa-9c63-656f5530b5a9:4311)
    at _callee2$ (2f696093-1d70-48aa-9c63-656f5530b5a9:83305)
`

**Comment by JeongJun-Lee** [comment]
I already checked it, but the last func in the callstack is different from the issue. The func in the #4406 is reshape() ,but in this issue, the func is Object.identity().

**Comment by Sri-harsha99** [comment]
Facing similar issue, but related to reshape(). Trying to load the model in Angular.

Code:
        ```
import * as tf from '@tensorflow/tfjs';

const model = await tf.loadLayersModel('../../assets/model3/model.json');
        console.log(model.predict(tf.tensor(new_sequence,[1,30],'int32')));
```

ERROR Error: Uncaught (in promise): TypeError: webglBackend.incRef is not a function
TypeError: webglBackend.incRef is not a function
    at reshape (Reshape.js:36:18)
    at Object.min [as kernelFunc] (Min.js:37:24)
    at h (engine.js:562:22)
    at engine.js:619:23
    at e.scopedRun (engine.js:436:19)
    at e.runKernelFunc (engine.js:616:10)
    at e.runKernel (engine.js:494:17)
    at min_ (min.js:55:12)
    at Module.min__op (operation.js:44:28)
    at Module.min (math_utils.js:64:12)
    at resolvePromise (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26231:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36

**Comment by shmishra99** [comment]
Hi @JeongJun-Lee ,
I apologize for the delay in responding. In order to investigate the issue you are experiencing, could you please share the reproducible code? I believe the issue is caused by importing the same package with different versions. Please follow the instructions in the [comment](https://github.com/tensorflow/tfjs/issues/4405#:~:text=tafsiri%20commented%20on,in%20your%20project)  and let us know if the issue is resolved. Thank You !!
