### ISSUE TITLE
ValueError: Unsupported Ops in the model before optimization LogSoftmax

### ISSUE THREAD

**Issue by rumschuettel** [tensorflow/tfjs#684]
Hi, I'm trying to convert a .pb file using
```
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='LogSoftmax,concat_40,concat_41' --saved_model_tags=serve test.pb testout/test
```
and get an error
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/foo/opt/anaconda5/envs/nlp-onnx/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/home/foo/opt/anaconda5/envs/nlp-onnx/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 272, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/home/foo/opt/anaconda5/envs/nlp-onnx/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 325, in convert_tf_frozen_model
    skip_op_check=skip_op_check, strip_debug_ops=strip_debug_ops)
  File "/home/foo/opt/anaconda5/envs/nlp-onnx/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 113, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
LogSoftmax
```

tensorflow.js version 
```
Using TensorFlow backend.

tensorflowjs 0.5.7

Dependency versions:
  keras 2.1.6
  tensorflow 1.9.0
```

Is that operation not satisfied? Any way I could add it?
Thanks a lot!
/ J

**Comment by pyu10055** [comment]
@rumschuettel It would be great f you would like to contribute, please refer to this issue for guidance.
tensorflow/tfjs#624

**Comment by prathameshnetake** [comment]
Worked after using --skip_op_check=SKIP_OP_CHECK flag

**Comment by yhwang** [comment]
Hi @pyu10055, I open a PR for LogSoftmax op and you can see the [link](https://github.com/tensorflow/tfjs-core/pull/1342) above. Hope you can provide review/comment. Thanks
