### ISSUE TITLE
LayerNormalization conversion to Graph Model: mean must have the same number of elements as the channels of x

### ISSUE THREAD

**Issue by cosminc98** [tensorflow/tfjs#6864]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: AlmaLinux release 8.6 (Sky Tiger)
- TensorFlow.js installed from: npm
- TensorFlow.js version (use command below): 3.17.0
- Tensorflow.js Converter Version: 3.17.0

**Describe the current behavior**
When converting a model with only a LayerNormalization layer (with the initialized weights; no training) to tensorflow js GraphModel and then using the model from nodejs (with the tfjs-node backend) an error is enountered: 
```
Error: Invalid TF_Status: 3
Message: When is_training=false, mean must have the same number of elements as the channels of x, got 0 and 1
    at NodeJSKernelBackend.executeMultipleOutputs (/usr/lib/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:230:43)
    at /usr/lib/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:62:28
    at /usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4429:22
    at Engine.scopedRun (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4439:23)
    at Engine.tidy (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4428:21)
    at Object.tidy (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10481:19)
    at Object.kernelFunc (/usr/lib/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:29:23)
    at kernelFunc (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4574:32)
    at /usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4634:27
    at Engine.scopedRun (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4439:23)
```

**Describe the expected behavior**
The converted GraphModel outputs the correct values (when compared to the python model).

**Standalone code to reproduce the issue**
Saved model -> Graph model conversion:
```
import tensorflow as tf
from tensorflowjs.converters.tf_saved_model_conversion_v2 import convert_tf_saved_model

def make_model(input_shape):
    inputs = tf.keras.Input(shape=input_shape, name='inputs')
    norm_layer = tf.keras.layers.LayerNormalization()
    outputs = norm_layer(inputs)
    return tf.keras.Model([inputs], [outputs])
    
if __name__ == '__main__':
    model = make_model(
        input_shape=(5,),
    )
    tf.saved_model.save(model, './saved_model')
    convert_tf_saved_model(
        saved_model_dir='./saved_model',
        output_dir='./graph_model',
        control_flow_v2=False,
    )
```
Graph model inference from nodejs:
```
const tf = require('@tensorflow/tfjs-node');
const main = async () => {
    const model = await tf.loadGraphModel(`file://./graph_model/model.json`);
    const inputs = tf.randomUniform([1, 5]);
    const outputs = model.execute(inputs);
    console.log(outputs.arraySync());
};
main();
```

**Comment by ciocancosmin98** [comment]
Experienced a similar problem when using [this method](https://github.com/buzz/mediainfo.js/blob/f6720397f20fde5c70fed625694d2a409edc4724/src/cli.ts#L54-L81).
A quick fix was to use a type cast [here](https://github.com/buzz/mediainfo.js/blob/f6720397f20fde5c70fed625694d2a409edc4724/src/cli.ts#L73):
```typescript
mediainfo = <MediaInfo>await MediaInfoFactory({ format, coverData, full });
```

**Comment by cosminc98** [comment]
Please notify me if more information is required to reproduce the error.

**Comment by pyu10055** [comment]
@cosminc98 thank you for reporting, can you share the original python model and converted tfjs model? It will help the team to expedite the fixes. thanks.

**Comment by cosminc98** [comment]
Sorry for the delay. There isn't much I can tell you about the original python model. I'm trying to convert the decoder half of Conformer from [TensorflowASR](https://github.com/TensorSpeech/TensorFlowASR). At the moment I was testing whether each component can be converted to tfjs graph model separately (tf.while_loops, other layers) and then attempt to convert the greedy decoder as a whole. I cannot provide the tfjs model since this is the problem itself. I can however point you to where to [download](https://drive.google.com/drive/folders/1VAihgSB5vGXwIVTl3hkUk95joxY1YbfW) a pretrained model.

**Comment by gaikwadrahul8** [comment]
Hi, @cosminc98 

Apologize for the delayed response and it seems like there is some packages dependancy issue and I found somewhat [similar issue](https://stackoverflow.com/questions/73333396/tensorflow-js-error-invalid-tf-status-3-message-in0-and-in1-has-differe) over stack-overflow so if possible could you please try with latest version of `@tensorflow/tfjs-node` ? if issue still persists please let us know and I would request you to please help us with `package.json` dependancy file information, In order to expedite the trouble-shooting process to reproduce the issue reported here. Thank you!

**Comment by cosminc98** [comment]
Reproduced the error with the latest version from npm:

Have I written custom code: Yes
OS Platform and Distribution: AlmaLinux release 8.6 (Sky Tiger)
TensorFlow.js installed from: npm
TensorFlow.js version (use command below): 4.2.0
Tensorflow.js Converter Version: 4.3.0

```bash
/usr/lib/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:232
        var outputMetadata = this.binding.executeOp(name, opAttrs, this.getInputTensorIds(inputs), numOutputs);
                                          ^

Error: Invalid TF_Status: 3
Message: When is_training=false, mean must have the same number of elements as the channels of x, got 0 and 1
    at NodeJSKernelBackend.executeMultipleOutputs (/usr/lib/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:232:43)
    at /usr/lib/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:63:28
    at /usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4506:22
    at Engine.scopedRun (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4516:23)
    at Engine.tidy (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4505:21)
    at tidy (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8053:19)
    at Object.kernelFunc (/usr/lib/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:30:32)
    at kernelFunc (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4651:32)
    at /usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4711:27
    at Engine.scopedRun (/usr/lib/node_modules/@tensorflow/tfjs-node/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4516:23)
```

**Comment by gaikwadrahul8** [comment]
Hi, @cosminc98 

Apologize for the inconvenience caused to you and our `google-ml-butler` closed your issue and It seems like our team did some changes in the working behaviour of `google-ml-butler` and concerned team will fix this unexpected behaviour of `google-ml-butler` very soon now I have re-opened your issue. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @cosminc98 

Apologize for the delayed response and I tried to replicate the same issue from the code which you provided in the issue template and first I tried `Saved model -> Graph model conversion` and after that I provided absolute path to downloaded Graph Model and I tried `Graph model inference from Node.js `and I encountered different error `TypeError: model.execute is not a function` I have tried with latest version `@tensorflow/tfjs-node@4.4.0` and `@tensorflow/tfjs-node@4.2.0`, For your reference I have added screenshot below, If have I missed something here please let me know ? Thank you!

CC :@pyu10055

![image](https://user-images.githubusercontent.com/115997457/231421848-356af73f-b9fd-42d6-9e54-5389248677d9.png)

**Comment by gaikwadrahul8** [comment]
Hi, @cosminc98 

Apologize for the delayed response and I was trying to replicate the same issue from my end and I'm also getting the same error message as mentioned above so we'll have to dig more into this issue and will update you soon

Thank you for bringing this issue to our attention, I really appreciate your efforts and time. Thank you!

CC :@pyu10055

Please refer below error log output :
```
gaikwadrahul-macbookpro:test-6864 gaikwadrahul$ node index.js
/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:229
        var outputMetadata = this.binding.executeOp(name, opAttrs, this.getInputTensorIds(inputs), numOutputs);
                                          ^

Error: Invalid TF_Status: 3
Message: When is_training=false, mean must have the same number of elements as the channels of x, got 0 and 1
    at NodeJSKernelBackend.executeMultipleOutputs (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.js:229:43)
    at /Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:63:28
    at /Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4559:22
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)
    at Engine.tidy (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4558:21)
    at tidy (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8304:19)
    at Object.kernelFunc (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-node/dist/kernels/FusedBatchNorm.js:30:32)
    at kernelFunc (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4704:32)
    at /Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4764:27
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/TFJS/test-6864/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)

Node.js v18.17.0
gaikwadrahul-macbookpro:test-6864 gaikwadrahul$ 
```

**Comment by nileshau-afk** [comment]
Hello @cosminc98 ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @cosminc98, Thank you for your patience. We have reproduced the issue. As a workaround, you can dynamically override the FusedBatchNorm kernel in Node.js to execute with is_training: true when the mean tensor is empty, or upgrade your TensorFlow/TFJS converter version to export LayerNormalization decomposed into primitive operations. Could you please try this and let us know if it works for you?
