### ISSUE TITLE
The logs from cloud build is not clear enough for debug

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#6938]
I create a webgl PR https://github.com/tensorflow/tfjs/pull/6932.  The bots informs something is wrong with presubmit.
So I followed the link for logs: 
https://console.cloud.google.com/cloud-build/builds/09063b8c-ed17-4087-8412-52a0e63ce566?project=learnjs-174218

There are failures related to webgl. However, I didn't  find any detailed error info related to my change(See below).  

So can the error info be more specific?

```
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_ios_12_tfjs-backend-webgl1_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_ios_12_tfjs-backend-webgl1_test/test_attempts/attempt_2.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test_attempts/attempt_1.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_chrome_mac_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test_attempts/attempt_1.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-layers:bs_chrome_mac_tfjs-layers_webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test_attempts/attempt_1.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,725 / 9,730] 47 / 52 tests; Testing //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test; 267s remote-cache, linux-sandbox ... (10 actions running)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test_attempts/attempt_1.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_ios_12_tfjs-backend-webgl1_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_ios_12_tfjs-backend-webgl1_test/test.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": 
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAILED: //tfjs-backend-webgl:bs_ios_12_tfjs-backend-webgl1_test (Summary)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_ios_12_tfjs-backend-webgl1_test/test.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_ios_12_tfjs-backend-webgl1_test/test_attempts/attempt_1.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_ios_12_tfjs-backend-webgl1_test/test_attempts/attempt_2.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,726 / 9,730] 48 / 52 tests, 1 failed; Testing //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test; 117s remote-cache, linux-sandbox ... (8 actions running)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,726 / 9,730] 48 / 52 tests, 1 failed; Testing //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test; 199s remote-cache, linux-sandbox ... (8 actions running)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test_attempts/attempt_2.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_chrome_mac_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test_attempts/attempt_2.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-layers:bs_chrome_mac_tfjs-layers_webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test_attempts/attempt_2.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,726 / 9,730] 48 / 52 tests, 1 failed; Testing //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test; 238s remote-cache, linux-sandbox ... (8 actions running)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test_attempts/attempt_2.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,726 / 9,730] 48 / 52 tests, 1 failed; Testing //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test; 199s remote-cache, linux-sandbox ... (8 actions running)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": 
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAILED: //tfjs-backend-webgl:bs_android_9_tfjs-backend-webgl2_test (Summary)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test_attempts/attempt_1.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_android_9_tfjs-backend-webgl2_test/test_attempts/attempt_2.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-layers:bs_chrome_mac_tfjs-layers_webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": 
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAILED: //tfjs-layers:bs_chrome_mac_tfjs-layers_webgl2_test (Summary)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test_attempts/attempt_1.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-layers/bs_chrome_mac_tfjs-layers_webgl2_test/test_attempts/attempt_2.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_chrome_mac_tfjs-backend-webgl2_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": 
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAILED: //tfjs-backend-webgl:bs_chrome_mac_tfjs-backend-webgl2_test (Summary)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test_attempts/attempt_1.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_chrome_mac_tfjs-backend-webgl2_test/test_attempts/attempt_2.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": [9,729 / 9,730] 51 / 52 tests, 4 failed; Testing //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test; 206s remote-cache, linux-sandbox
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAIL: //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test (see /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test.log)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": 
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests": FAILED: //tfjs-backend-webgl:bs_safari_mac_tfjs-backend-webgl1_test (Summary)
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test_attempts/attempt_1.log
Step #2 - "run-cloudbuild": Step #5 - "bazel-tests":       /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/testlogs/tfjs-backend-webgl/bs_safari_mac_tfjs-backend-webgl1_test/test_attempts/attempt_2.log
```

**Comment by qjia7** [comment]
I think these are the errors in your PR https://source.cloud.google.com/results/invocations/883d4e7d-06b2-470d-bf43-3ebe9007897f/targets/%2F%2Ftfjs-backend-webgl:bs_chrome_mac_tfjs-backend-webgl2_test/log

```
Chrome 106.0.0.0 (Mac OS 10.13.6) upload tensors as uniforms webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} large tensor gets uploaded to gpu FAILED
	Expected 12 to be 0.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:387:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94913:35)
	    at <Jasmine>

	Expected 72 to be 40.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:394:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94917:35)
	    at <Jasmine>

Chrome 106.0.0.0 (Mac OS 10.13.6) upload tensors as uniforms webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} large tensor gets uploaded to gpu FAILED
	Expected 12 to be 0.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:387:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94913:35)
	    at <Jasmine>

	Expected 72 to be 40.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:394:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94917:35)
	    at <Jasmine>

Chrome 106.0.0.0 (Mac OS 10.13.6) upload tensors as uniforms webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} large tensor gets uploaded to gpu FAILED
	Expected 12 to be 0.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:387:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94913:35)
	    at <Jasmine>

	Expected 72 to be 40.
	    at <Jasmine>
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/backend_webgl_test.ts:394:29 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:94917:35)
	    at <Jasmine>

Chrome 106.0.0.0 (Mac OS 10.13.6): Executed 3109 of 4499 (8 FAILED) (skipped 11) (0 secs / 1 min 58.607 secs)
Chrome 106.0.0.0 (Mac OS 10.13.6): Executed 3110 of 4499 (8 FAILED) (skipped 11) (0 secs / 1 min 58.669 secs)
Chrome 106.0.0.0 (Mac OS 10.13.6): Executed 3111 of 4499 (8 FAILED) (skipped 11) (0 secs / 1 min 58.67 secs)
Chrome 106.0.0.0 (Mac OS 10.13.6) slice and memory usage webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} slice a tensor, read it and check memory FAILED
	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:720:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97828:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:724:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97830:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:729:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97832:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:734:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97834:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 0.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:738:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97836:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

Chrome 106.0.0.0 (Mac OS 10.13.6) slice and memory usage webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} slice a tensor, read it and check memory FAILED
	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:720:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97828:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:724:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97830:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:729:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97832:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:734:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97834:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 0.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:738:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97836:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

Chrome 106.0.0.0 (Mac OS 10.13.6) slice and memory usage webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} slice a tensor, read it and check memory FAILED
	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:720:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97828:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 24 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:724:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97830:42
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-backend-webgl/src/webgl_ops_test.ts:710:61 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97822:62)
	    at <Jasmine>

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:729:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97832:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 8.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:734:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97834:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

	Expected 40 to be 0.
	    at <Jasmine>
	    at ../../tfjs-backend-webgl/src/webgl_ops_test.ts:738:36 <- tfjs/tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:97836:42
	    at Generator.next (<anonymous>)
	    at fulfilled (tfjs-backend-webgl/src/tfjs-backend-webgl_test_bundle.js:59:27)

**Comment by axinging** [comment]
Thanks @qjia7 , This log is very helpful, and I will close this bug.
