### ISSUE TITLE
Initialization of backend wasm failed

### ISSUE THREAD

**Issue by heliumsea** [tensorflow/tfjs#6942]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Macbook Pro 2021, M1 Pro chip
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.20.0
- Browser version: Chrome Version 105.0.5195.125 (Official Build) (arm64)
- Tensorflow.js Converter Version: N/A
- Web framework: Next.js (based on ReactJS)

**Describe the current behavior**
I put 3 tfjs-backend-wasm*.wasm files in /public folder.
The index.js (entry page of ReactJS) import app.js.
The content of app.js is like this:
```javascript
import * as tf from "@tensorflow/tfjs";
import { setWasmPaths } from '@tensorflow/tfjs-backend-wasm';
function main() {
  console.log("Backend: " + tf.getBackend());
  ...
}

setWasmPaths("/");
tf.setBackend('wasm').then(() => main());
```
I got error message
```
Initialization of backend wasm failed
TypeError: Failed to parse URL from /tfjs-backend-wasm-simd.wasm
    at new Request (node:internal/deps/undici/undici:5573:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6371:25)
    at Object.fetch (node:internal/deps/undici/undici:7200:20)
    at fetch (node:internal/process/pre_execution:216:25)
    at instantiateAsync (/path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6831:24)
    at createWasm (/path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6844:15)
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6910:13
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7356:40
    at new Promise (<anonymous>)
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7303:43
Backend: wasm

%PROGRAM LOG%

TypeError: Failed to parse URL from /tfjs-backend-wasm-simd.wasm
    at new Request (node:internal/deps/undici/undici:5573:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:6371:25)
    at Object.fetch (node:internal/deps/undici/undici:7200:20)
    at fetch (node:internal/process/pre_execution:216:25)
    at instantiateAsync (/path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6831:24)
    at createWasm (/path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6844:15)
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6910:13
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7356:40
    at new Promise (<anonymous>)
    at /path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7303:43
(node:47537) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/path/to/app/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6599
                    throw ex;
                    ^

Error: The highest priority backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
    at Engine.get [as backend] (/path/to/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4201:27)
    at Engine.makeTensor (/path/to/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4732:35)
    at makeTensor (/path/to/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5602:19)
    at Object.tensor (/path/to/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5651:12)
    at linear_test (webpack-internal:///./do_tests.js:26:56)
    at do_test (webpack-internal:///./do_tests.js:70:23)
    at eval (webpack-internal:///./do_tests.js:87:75)

Node.js v18.10.0
```
**Describe the expected behavior**
No error.

**Comment by vladmandic** [comment]
new native fetch implementation in `nodejs` is not complete as it doesn't support filesystem access yet
so if you want to use `wasm` in `nodejs`, you have to disable it and rely on `emscripten` internal implementation.

either `node --no-experimental-fetch` or just add `global.fetch = undefined` near the top of your code.

**Comment by heliumsea** [comment]
I have tried all three methods, but still don't work...

A comprise way to "fix" that is to comment out all computation codes and run the webpage. Then uncomment those codes and NextJS will reload the page. After reloading, there is still the error "TypeError: Failed to parse URL from /tfjs-backend-wasm-simd.wasm" but it can compute rather than exits with error messages.

**Comment by vladmandic** [comment]
Ahhh, thats NextJS, that explains the problems.

By default it tries to do SSR and that's not going to work with TFJS like that (you can see how it reports issues with node loader). You have to explicitly configure Next to treat TFJS as browser side or do a dynamic import of TFJS from a page on-load, so it doesn't get bundled server-side.
