### ISSUE TITLE
regression: model execution failure

### ISSUE THREAD

**Issue by vladmandic** [tensorflow/tfjs#6945]
PR #6904 Add resource initializer support  
causes execution failure for some models that used to previously work without issues.

Issue is in <https://github.com/tensorflow/tfjs/blame/master/tfjs-converter/src/executor/graph_model.ts#L361>

Error:

```log
error uncaughtException TypeError: Cannot read properties of undefined (reading 'img_inputs')
  at node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30706:69
  at Array.reduce (<anonymous>)
  at GraphModel.normalizeInputs (node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30705:32)
  at GraphModel.execute (node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30777:23)
  at human.node-wasm.js:99:175230
```

cc @pyu10055 @ahmedsabie

**Comment by vladmandic** [comment]
@ahmedsabie any updates? for me, this is a blocker for `tfjs` 4.0

**Comment by vladmandic** [comment]
@ahmedsabie here you go:

```js
const tf = require('@tensorflow/tfjs-node');

async function main() {
  const model = await tf.loadGraphModel('https://vladmandic.github.io/human-models/models/mobilefacenet.json');
  const input = tf.randomUniform([1, model.inputs[0].shape[1], model.inputs[0].shape[2], 3], 0, 1, 'float32');
  const output = model.execute(input); // exception: TypeError: Cannot read properties of undefined (reading 'img_inputs')
}

main();
```
