### ISSUE TITLE
"Unsupported Ops in the model before optimization `StatefulPartitionedCall`" despite adding `--control_flow_v2=True`?

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tfjs#6950]
**Summary**
I'm getting this error: "Unsupported Ops in the model before optimization `StatefulPartitionedCall`" even though I've added the `--control_flow_v2=True` flag to the conversion command.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (Google Colab)
- Tensorflow.js Converter Version: 4.0.0

**Standalone code to reproduce the issue**

This Colab generates the Saved Model file, and then runs the `tensorflowjs_converter` command to convert it to the tfjs format:

https://colab.research.google.com/gist/josephrocca/84fc5b035fb3bc5fa68fbe7799e10566

**Other info / logs**

Command:
```
!tensorflowjs_converter --control_flow_v2=True --input_format=tf_saved_model ./decode_latents ./decode_latents_tfjs
```

Output logs:
```
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 818, in convert
    weight_shard_size_bytes, metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/converter.py", line 539, in _dispatch_converter
    metadata=metadata_map)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 1033, in convert_tf_saved_model
    frozen_graph_dir=frozen_graph_dir)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 919, in _convert_tf_saved_model
    metadata=metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 170, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
StatefulPartitionedCall
```

**Comment by pyu10055** [comment]
@josephrocca Is this an JAX model? If so, you might want to try using the direct [JAX conversion support](https://blog.tensorflow.org/2022/08/jax-on-web-with-tensorflowjs.html) in tfjs converter.

**Comment by josephrocca** [comment]
Ah, thanks! That solved it. I was doing what I thought was the same thing that the direct conversion does: I.e. convert to Saved Model, and then convert the Saved Model to tfjs with `tensorflowjs_converter`. Not sure what I did wrong, but I guess there's something I missed in that process. Thanks! I'll close this and let you re-open it if the above `control_flow_v2` problem is deemed to be a bug.
