### ISSUE TITLE
tensorflowjs issue with convert the keras mode using tensorflowjs_converter

### ISSUE THREAD

**Issue by karthi7CK** [tensorflow/tfjs#6983]
**System information**
- OS Linux  (e.g., Linux Ubuntu 16.04):
- TensorFlow.js installed from (cript link):
- Tensorflow 2.10
- TensorFlow.js version:4.0.0

I've created a keras model in a name of model.h5 and I tried to convert the saved model into web application uses with the help of tensorflowjs.

I have used the command tensorflowjs_converter. But I got the below error

**Exception: Error dumping weights, duplicate weight name mean**

**Any other info / logs**
/xg_to_keras$ tensorflowjs_converter --input_format keras /home/divum/xg_to_keras/keras_heart_stroke.h5 /tmp/jsmodel/
2022-10-28 12:02:09.017822: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-28 12:02:09.178121: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-28 12:02:09.178154: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-28 12:02:09.222521: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-28 12:02:09.840244: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-28 12:02:09.840310: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-28 12:02:09.840322: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/divum/xg_to_keras/venv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 817, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 500, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 97, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    conversion.write_artifacts(
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/converters/keras_h5_conversion.py", line 305, in write_artifacts
    weights_manifest = write_weights.write_weights(
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/write_weights.py", line 118, in write_weights
    _assert_no_duplicate_weight_names(weight_groups)
  File "/home/divum/xg_to_keras/venv/lib/python3.8/site-packages/tensorflowjs/write_weights.py", line 346, in _assert_no_duplicate_weight_names
    raise Exception(
Exception: Error dumping weights, duplicate weight name mean

Can someone suggest me the solution for this issue ?

**Comment by pyu10055** [comment]
@karthi7CK The error occurs when the converted model contains weights with the same name, it typically should not happen, if possible can you share the original Keras model?

**Comment by VineetKumar02** [comment]
@rthadur . I'm also facing the same issue. What's the soltuion tot this?
