### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Xiphap** [tensorflow/tfjs#7139]
**Error Info**
/Users/xxx/test/node_modules/@tensorflow/tfjs-core/dist/public/chained_ops/register_all_chained_ops.js:17
import './abs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/xiphap/Desktop/test/node_modules/@tensorflow/tfjs-vis/dist/index.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**What I Do**
```node index.js```

***File In index.js***
import tfvis from '@tensorflow/tfjs-vis'
const values = [
    {x: 123, y: 233},
    {x: 231, y: 133},
]
tfvis.render.scatterplot(
    { name: 'Test' },
    { values },
    {
        xLabel: 'x',
        yLabel: 'y',
        height: 300
    }
);

***Question***
How to fix this? THX!

**System information**
- @tensorflow/tfjs-vis version : 1.5.1
- @tensorflow/tfjs-core version: 
- MacOS version: Ventura 13.0.1
- Node version: v14.21.1

**Comment by Xiphap** [comment]
Nobody response, close it! 😭
