### ISSUE TITLE
TFDF model conversion fails with Unsupported Op SimpleMLInferenceOpWithHandle

### ISSUE THREAD

**Issue by mattsoulanille** [tensorflow/tfjs#7140]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No. [Following this tutorial](https://github.com/tensorflow/tfjs-examples/tree/master/tfdf-adult-gbt).
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 5.19
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): N/A
- TensorFlow.js version (use command below): N/A
- Browser version: N/A
- Tensorflow.js Converter Version: 4.1.0

**Describe the current behavior**
Converting a TFDF model fails with `ValueError: Unsupported Ops in the model before optimization`.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Run the TFDF colab to create a TFDF model. Specifically, I used the Palmer's Penguins model. Save this model and download it. Then, run `tensorflowjs_converter the_saved_model tfjs_output_model`.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "/usr/local/google/home/msoulanille/tfdf_test/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 817, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 528, in _dispatch_converter
    tf_saved_model_conversion_v2.convert_tf_saved_model(
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 1021, in convert_tf_saved_model
    _convert_tf_saved_model(output_dir, saved_model_dir=saved_model_dir,
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 910, in _convert_tf_saved_model
    optimize_graph(frozen_graph, signature,
  File "/usr/local/google/home/msoulanille/tfdf_test/lib/python3.10/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 169, in optimize_graph
    raise ValueError('Unsupported Ops in the model before optimization\n' +
ValueError: Unsupported Ops in the model before optimization
SimpleMLInferenceOpWithHandle
```

**Comment by pyu10055** [comment]
@mattsoulanille I think these [three ops](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L459) are not recorded in the [op_list json](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter/python/tensorflowjs/op_list)
We can either create a tfdf specific flag or added them to the op_list.
