### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by karpenko-eugene** [tensorflow/tfjs#7266]
$ node-gyp configure --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@9.3.1
gyp info using node@16.17.1 | win32 | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe"
gyp verb find Python - executing "C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe" to get version
gyp verb find Python - version is "3.11.0"
gyp info find Python using Python version 3.11.0 found at "C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe"
gyp verb get node dir no --target version specified, falling back to host node version: 16.17.1
gyp verb command install [ '16.17.1' ]
gyp verb install input version string "16.17.1"
gyp verb install installing version: 16.17.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 16.17.1
gyp verb build dir attempting to create "build" dir: D:\www\tfjs-master\tfjs-node\build
gyp verb build dir "build" dir needed to be created? No
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2022 (17.4.33213.308) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v143
gyp verb find VS - found Windows SDK: 10.0.22000.0
gyp info find VS using VS2022 (17.4.33213.308) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: D:\www\tfjs-master\tfjs-node\build\config.gypi
gyp verb config.gypi checking for gypi file: D:\www\tfjs-master\tfjs-node\config.gypi
gyp verb common.gypi checking for gypi file: D:\www\tfjs-master\tfjs-node\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v16.17.1\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\www\\tfjs-master\\tfjs-node\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v16.17.1\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\AppData\\Local\\node-gyp\\Cache\\16.17.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Admin\\AppData\\Local\\node-gyp\\Cache\\16.17.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Admin\\AppData\\Roaming\\nvm\\v16.17.1\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Admin\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\www\\tfjs-master\\tfjs-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\www\\tfjs-master\\tfjs-node\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Admin\AppData\Roaming\nvm\v16.17.1\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd D:\www\tfjs-master\tfjs-node
gyp ERR! node -v v16.17.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

**Comment by gaikwadrahul8** [comment]
Hi, @karpenko-eugene 

Apologize for the delayed response and I tried to replicate the same issue from my end and I'm also getting similar issue on `Windows` machine with `Python 3.11.4` so we'll have to dig more into this issue and will update you soon, thank you for bringing this issue to our attention. Thank you!

CC: @mattsoulanille 

Here is error log :

```
gyp http 200 https://nodejs.org/download/release/v18.16.1/win-x64/node.lib
gyp verb content checksum win-x64/node.lib 72b7fab9381af8f4958c8212f3d4cdfff8c7c5b1e33eaad0e7d5888293568cd5
gyp verb download contents checksum {"node-v18.16.1-headers.tar.gz":"8c72f0861237731a3e292a4be2b6a5b3c0f5114afe3a3a02b5fad35d7b3b2cc2","win-x64/node.lib":"72b7fab9381af8f4958c8212f3d4cdfff8c7c5b1e33eaad0e7d5888293568cd5"}
gyp verb validating download checksum for node-v18.16.1-headers.tar.gz (8c72f0861237731a3e292a4be2b6a5b3c0f5114afe3a3a02b5fad35d7b3b2cc2 == 8c72f0861237731a3e292a4be2b6a5b3c0f5114afe3a3a02b5fad35d7b3b2cc2)
gyp verb validating download checksum for win-x64/node.lib (72b7fab9381af8f4958c8212f3d4cdfff8c7c5b1e33eaad0e7d5888293568cd5 == 72b7fab9381af8f4958c8212f3d4cdfff8c7c5b1e33eaad0e7d5888293568cd5)
gyp verb get node dir target node version installed: 18.16.1
gyp verb build dir attempting to create "build" dir: C:\Users\gaikwadrahul\tfjs-project\build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2019 (16.11.33423.256) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v142
gyp verb find VS - found Windows SDK: 10.0.19041.0
gyp info find VS using VS2019 (16.11.33423.256) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\gaikwadrahul\tfjs-project\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\gaikwadrahul\tfjs-project\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\gaikwadrahul\tfjs-project\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python311\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\gaikwadrahul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaikwadrahul\\tfjs-project\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaikwadrahul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gaikwadrahul\\AppData\\Local\\node-gyp\\Cache\\18.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\gaikwadrahul\\AppData\\Local\\node-gyp\\Cache\\18.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\gaikwadrahul\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\gaikwadrahul\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\gaikwadrahul\\tfjs-project',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\gaikwadrahul\\tfjs-project\\build',
gyp: binding.gyp not found (cwd: C:\Users\gaikwadrahul\tfjs-project) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\gaikwadrahul\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.20348
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gaikwadrahul\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
gyp ERR! cwd C:\Users\gaikwadrahul\tfjs-project
gyp ERR! node -v v18.16.1
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok
PS C:\Users\gaikwadrahul\tfjs-project>
```

**Comment by gaikwadrahul8** [comment]
Hi, @karpenko-eugene 

Apologize for the delayed response and Could you please give it try with `"@tensorflow/tfjs-node": "^3.18.0"` because at the moment we support only this version `"@tensorflow/tfjs-node": "^3.18.0"` for `windows` machine ?

Please refer this similar issue https://github.com/tensorflow/tfjs/issues/7341 and if you face same issue with `"@tensorflow/tfjs-node": "^3.18.0"` please try to downgrade the python version to `3.8` or `3.9 ` and let us know whether your issue is resolving or not ? Thank you!
