### ISSUE TITLE
Infinite loop in tf.loadLayersModel

### ISSUE THREAD

**Issue by thekevinscott** [tensorflow/tfjs#7271]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Node, Mac 13.1
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): `@tensorflow/tfjs-node@4.2.0`
- Tensorflow.js Converter Version: 
```
> tensorflowjs_converter -v
tensorflowjs 3.18.0

Dependency versions:
  keras 2.6.0
  tensorflow 2.6.2
```

**Describe the current behavior**
I'm trying to convert [Maxim](https://github.com/google-research/maxim) to Tensorflow.js. After converting the model and loading into TFJS, Node hangs with no response. (Same behavior is exhibited in browser.)

I've observed similar behavior trying to load MIRNet, though I'm not sure if it's the same issue.

**Describe the expected behavior**
Model should load without an infinite loop, or should report the error.

**Standalone code to reproduce the issue**
I've isolated the model to the first 6 layers, and attached the offending `model.json`. I've also found the bug (or at least, the cause of it).

In the `model.json` is a sixth layer defined as such:

```
          {
            "class_name": "TFOpLambda",
            "config": {
              "name": "tf.nn.gelu",
              "trainable": true,
              "dtype": "float32",
              "function": "nn.gelu"
            },
            "name": "tf.nn.gelu",
            "inbound_nodes": [
              [
                
                "stage_0_encoder_block_0_SplitHeadMultiAxisGmlpLayer_0_in_project",
                0,
                0,
                {
                  "approximate": true
                }
              ]
            ]
          }
```

`inbound_nodes` is in an incorrect format. It should be wrapped in another array:

```
{
            "class_name": "TFOpLambda",
            "config": {
              "name": "tf.nn.gelu",
              "trainable": true,
              "dtype": "float32",
              "function": "nn.gelu"
            },
            "name": "tf.nn.gelu",
            "inbound_nodes": [
              [[
                
                "stage_0_encoder_block_0_SplitHeadMultiAxisGmlpLayer_0_in_project",
                0,
                0,
                {
                  "approximate": true
                }
              ]]
            ]
          }
```

I've created the model with:

```bash
tensorflowjs_converter --input_format=keras_saved_model ./weights.h5 ./output-tfjs-model
```

For the `tf.nn.gelu` layer, [at this line `nodeData`](https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-layers/src/engine/container.ts#L1248) is defined as `['stage_0_encoder_block_0_SplitHeadMultiAxisGmlpLayer_0_in_project', 0, 0, {…}]` (this should be an array in an array).

Then, [on this line, `inputData`](https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-layers/src/engine/container.ts#L1166) is defined as `stage_0_encoder_block_0_SplitHeadMultiAxisGmlpLayer_0_in_project`.

Then, [on this line](https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-layers/src/engine/container.ts#L1174), `inboundLayerName` is defined as `s` (because of `inputData[0];`) and `s` is not a layer present in `createdLayers` so the boolean fails.

[That then leads to this line](https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-layers/src/engine/container.ts#L1175) re-adding the `tf.nn.gelu` layer _back_ into the unprocessed layers, and the cycle repeats infinitely.

If the `model.json` is modified to double-wrap the array, I get an expected error (`No lambda output shape defined for tf.nn.gelu`, which is good because I have yet to define that custom layer).

I'm not sure if this is a problem with `tfjs_converter`, or a problem with the load model code. I'm happy to contribute a PR if someone can point me in the right direction.

[model.zip](https://github.com/tensorflow/tfjs/files/10416032/model.zip)

**Comment by thekevinscott** [comment]
I was able to convert the model as a graph model and implement a custom op and get things working. However, I still think it'd be helpful for TFJS to throw an error, rather than getting stuck without an indication of the loop on a bad layers model.

**Comment by lukepfjo** [comment]
+1 just ran into this same issue converting a ResNet model implemented in Keras. Layers model was missing square brackets just as you mentioned. I also ultimately resolved the issue by converting it to a graph model (on top of a custom op).

@thekevinscott you're a saint for posting this and pointing me in the right direction

For any future Googlers, here's my (fairly sloppy but working) custom `tf.pad` operator:

```js
class PadTensorLayer extends tf.layers.Layer {
    padding: any;
    shape: number[];

    constructor(_: any) {
        super({ });

        // The padding you are adding in the Keras model
        this.padding = [[0, 0], [3, 3], [3, 3], [0, 0]];
        
        // The output shape after padding -- you can get this quickly by printing
        // tensor.shape after the tf.pad operation in your Python Keras code.
        // None = null
        this.shape = [null, 230, 230, 3];
    }

    computeOutputShape(_: any): tf.Shape {
        return this.shape;
    }

    call(input: any, _: any): tf.Tensor | tf.Tensor[] {
        // tf.pad can accept either a tensor or an array of tensors
        if (typeof input === 'object') {
            return Array.prototype.map(t => tf.pad(t, this.padding), input);
        } else {
            return tf.pad(input, this.padding);
        }
    }
    
    getConfig() { return super.getConfig(); }

    getClassName() { return 'PadTensorLayer'; }
    static get className() { return 'PadTensorLayer'; }
}
tf.serialization.registerClass(PadTensorLayer);
```

**Comment by gaikwadrahul8** [comment]
Hi, @thekevinscott 

Apologize for the delayed response and I was trying to load this [model.zip](https://github.com/tensorflow/tfjs/files/10416032/model.zip) as below and I'm getting below error messages so just to confirm, you wanted to show something like below error messages instead of Infinite loop in `tf.loadLayersModel`, May I know have we taken care of this issue ? 

Please let me know if I have missed anything here . Thank you.

Here is error log with `tf.loadLayersModel` :

```
gaikwadrahul-macbookpro:test-7271 gaikwadrahul$ node index.js
/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:273
        var _this = _super.call(this, message) || this;
                           ^

ValueError: Unknown layer: TFOpLambda. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at new ValueError (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:273:28)
    at deserializeKerasObject (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:613:19)
    at deserialize (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:20078:12)
    at processLayer (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:22355:25)
    at Container.fromConfig (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:22379:17)
    at deserializeKerasObject (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:674:29)
    at deserialize (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:20078:12)
    at /Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:25606:29
    at step (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:159:27)
    at Object.next (/Users/gaikwadrahul/Desktop/TFJS/test-7271/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:108:53)

Node.js v18.17.0
gaikwadrahul-macbookpro:test-7271 gaikwadrahul$ 
```

**Comment by thekevinscott** [comment]
Yes, it should show an error rather than getting stuck in an infinite loop.

**Comment by gaikwadrahul8** [comment]
@thekevinscott 

May I know have we taken care of this issue now ? if yes, Please feel free to close the issue if it is resolved. Thank you!

**Comment by thekevinscott** [comment]
You're asking if the issue is still present? Yes, the same model file hangs in `^4.10.0`.

**Comment by gaikwadrahul8** [comment]
Hi, @thekevinscott 

I tried your code snippet from above issue template to replicate the same behaviour from my end with `@tensorflow/tfjs-node@4.10.0` and still it's going in infinite loop so we'll have to dig more into this issue and will update you soon. Thank you!

CC : @mattsoulanille

Here is screenshot for your reference :

![image](https://github.com/tensorflow/tfjs/assets/115997457/a65d20ba-a64d-4a51-a486-ecb75a8b1f40)

**Comment by nileshau-afk** [comment]
Hello @thekevinscott  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @thekevinscott, Thank you for your patience, we have reproduced the issue. As a workaround, you can ensure that the inbound_nodes array entries are properly double-wrapped  either by updating your model JSON file directly or by programmatically wrapping any single-wrapped node entries in your application logic prior to passing the topology to tf.loadLayersModel. Could you please try this and let us know if it works for you?
