### ISSUE TITLE
Error downloading libtensorflow during `npm i --save-dev @tensorflow/tfjs-node-gpu`

### ISSUE THREAD

**Issue by RedKenrok** [tensorflow/tfjs#728]
#### Versions

* cuda 9.0 Patch 4
* cudNN 7.3.0.29
* node 10.11.0
* npm 6.4.1
* python 3.6.6
* pip 18.0
* tensorflow 1.10.0
* tensorflow-gpu 1.10.0

#### Problem

I try to install `@tensorflow/tfjs-node-gpu` using the command: `npm i --save-dev @tensorflow/tfjs-node-gpu`, however during the libtensorflow download I get the error seen below.

```
> @tensorflow/tfjs-node-gpu@0.1.17 install D:\RonDekker\Development\tensor-test\node_modules\@tensorflow\tfjs-node-gpu
> node scripts/install.js gpu download

* Downloading libtensorflow
[==============================] 14576488/bps 100% 0.0s
* Building TensorFlow Node.js bindings
D:\RonDekker\Development\tensor-test\node_modules\@tensorflow\tfjs-node-gpu\scripts\install.js:154
      throw new Error('node-gyp rebuild failed with: ' + err);
      ^

Error: node-gyp rebuild failed with: Error: Command failed: node-gyp rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\RonDekker\Development\tensor-test\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at cp.exec (D:\RonDekker\Development\tensor-test\node_modules\@tensorflow\tfjs-node-gpu\scripts\install.js:154:13)
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @redkenrok/tensor-test@1.0.0-alpha.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node-gpu@0.1.17 install: `node scripts/install.js gpu download`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node-gpu@0.1.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RonDekker\AppData\Roaming\npm-cache\_logs\2018-09-24T14_03_33_151Z-debug.log
```

**Comment by kangyizhang** [comment]
Hi Ron, 

To use tfjs-node-gpu on windows, you will need to use python v2.x , cause the native addon build tool we are using (https://github.com/nodejs/node-gyp) does not support python v3.x.x

Thanks,
Kangyi

**Comment by RedKenrok** [comment]
Hi Kangyi,

Seems to have worked, thank you!

Kind regards,
Ron
