### ISSUE TITLE
'createTensorFromGPUData'  not yet implemented or not found in the registry

### ISSUE THREAD

**Issue by santimirandarp** [tensorflow/tfjs#7285]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow.js installed from (npm or script link):

**Describe the current behavior**

I have a script and so far it runs both in browser and using `ts-node` however, if I do a test with ts-jest I get this cryptic error:
```

. This kernel may not be supported by the tfjs backend you have chosen        at notYetImplemented (tfjs-core/src/backends/backend.ts:159:9) 

   at notYetImplemented (tfjs-core/src/backends/backend.ts:159:9)
      at NodeJSKernelBackend.Object.<anonymous>.KernelBackend.createTensorFromGPUData (tfjs-core/src/backends/backend.ts:139:12)
      at makeTensor (tfjs-core/src/ops/tensor_ops_util.ts:44:27)
      at tensor (tfjs-core/src/ops/tensor.ts:196:10)
      at decodeWeights (tfjs-core/src/io/io_utils.ts:224:19)
      at tfjs-core/src/io/weights_loader.ts:236:13
          at Array.forEach (<anonymous>)
      at tfjs-core/src/io/weights_loader.ts:231:22
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (tfjs-core/src/io/weights_loader.ts:212:25)
      at step (node_modules/tslib/tslib.es6.js:102:23)
      at Object.next (node_modules/tslib/tslib.es6.js:83:53)
      at fulfilled (node_modules/tslib/tslib.es6.js:73:58)

```

The error clearly starts in TS flow so I am trying to check what this could be here first.

**Describe the expected behavior**
Should not produce previous error

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

This uses a library on top so the standalone code wouldn't make sense.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Linchenn** [comment]
It looks like you are using `tf.tensor` API and the first parameter you passed is a Texture or a GPUBuffer somewhere, which is creating tensor from GPU data. However, creating tensor from GPU data is currently only implemented on WebGL backend and WebGPU backend.

For other backends (including node backend), you would use `[tf.browser.fromPixels](https://js.tensorflow.org/api/latest/#browser.fromPixels)` API to create tensor from a image.
@santimirandarp

**Comment by santimirandarp** [comment]
It is odd because I can run the code just fine using `ts-node ./script.ts`

Would it be possible that `jest` is selecting a backend?

**Comment by Linchenn** [comment]
what do you mean `./script.ts`? Could you provide more info to reproduce the error? @santimirandarp

**Comment by santimirandarp** [comment]
Yes. If I run the whole same code that is running with the testing suite (ts-jest) by just doing `ts ./myScript.ts` it runs fine.

I have scoped it [to a line that errors](https://github.com/santimirandarp/extract-faces/blob/f04cfde4d8e18735f73ffd4fd8fb91a89eb1104b/src/utils/loadNodeNN.ts#L26). As I say, it runs that line just fine if I run the main script.

The only way to really reproduce would be to clone that project (mind that is a branch I point to.) @Linchenn

**Comment by santimirandarp** [comment]
Cant research further now but I did this:

* add the line `import ts from "@tensorflow/ts-node"` (didn't solve but I kept it)
* add vitest (didn't solve but I kept it)
* `npm rebuild` or remove `rm -rm node_modules` and reinstall and it runs the tests fine.

**Comment by Linchenn** [comment]
I just reproduced it using jest, thanks!

ts-jest is running on node, instead of browser, causing tfjs use node backend. In this case, you have to make sure the Extract Face API accepts canvas (you passed a canvas in the test) on Node backend. @santimirandarp

**Comment by santimirandarp** [comment]
I am not sure I understand, because the `ts-node extract-face` is doing the same and runs fine

**Comment by Linchenn** [comment]
It looks like you are not using TFJS directly and, the wrong behavior happens on top of TFJS. From the error message, I could only know that you or the Extract Face API are calling `tf.tensor` with a Texture data, which is not implemented on node, but have been implemented on browser. @santimirandarp

**Comment by santimirandarp** [comment]
Thank you. It is rather strange that reinstalling stuff (nothing changed) did work, but I understand your logic now.

**Comment by Linchenn** [comment]
Great to know it works!

**Comment by gaikwadrahul8** [comment]
Hi, @santimirandarp 

Apologize for the delayed response and I see your previous comment, after installing things worked as expected so could you please close this issue if your issue got resolved ? Thank you!
