### ISSUE TITLE
tfjs-node-gpu causes a sementation fault

### ISSUE THREAD

**Issue by ookami125** [tensorflow/tfjs#729]
#### TensorFlow.js version
@tensorflow/tfjs-node-gpu@0.1.17
```
$ node --version
v10.10.0
$ uname -a
Linux pool-100-0-0-20 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Ubuntu 16.04.3 LTS
$ nvidia-smi
Mon Sep 24 11:36:34 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 00000000:41:00.0 Off |                  N/A |
|  0%   45C    P0    37W / 151W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

#### Describe the problem or feature request
Running tfjs-node-gpu is segfaulting on initialization.
```
Output:
2018-09-24 11:30:51.469730: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-24 11:30:52.011300: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-24 11:30:52.011749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 0000:41:00.0
totalMemory: 3.94GiB freeMemory: 3.87GiB
2018-09-24 11:30:52.011764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
Segmentation fault (core dumped)
```

#### Code to reproduce the bug / link to feature request
`require('@tensorflow/tfjs-node-gpu');`

I really don't know where to go from here. I can use the cpu version fine but that is undesirable in the long run. Also it does run the gpu version in python, but python also isn't my favorite language at the moment. I can do a update/upgrade cycle, but in the many times I've upgraded, I've broken things, so I've been avoiding it.

**Comment by kangyizhang** [comment]
Hi @ookami125  could you please check if you have cuda successfully installed on your machine?

**Comment by ookami125** [comment]
does this work for you? libcuda.so does exist towards the bottom.
```
$ ldconfig -p | grep cuda
        libnvrtc.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnvrtc.so.9.0
        libnvrtc.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvrtc.so
        libnvrtc-builtins.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnvrtc-builtins.so.9.0
        libnvrtc-builtins.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvrtc-builtins.so
        libnvgraph.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnvgraph.so.9.0
        libnvgraph.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvgraph.so
        libnvblas.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnvblas.so.9.0
        libnvblas.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvblas.so
        libnvToolsExt.so.1 (libc6,x86-64) => /usr/local/cuda/lib64/libnvToolsExt.so.1
        libnvToolsExt.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvToolsExt.so
        libnpps.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnpps.so.9.0
        libnpps.so (libc6,x86-64) => /usr/local/cuda/lib64/libnpps.so
        libnppitc.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppitc.so.9.0
        libnppitc.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppitc.so
        libnppisu.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppisu.so.9.0
        libnppisu.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppisu.so
        libnppist.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppist.so.9.0
        libnppist.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppist.so
        libnppim.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppim.so.9.0
        libnppim.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppim.so
        libnppig.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppig.so.9.0
        libnppig.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppig.so
        libnppif.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppif.so.9.0
        libnppif.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppif.so
        libnppidei.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppidei.so.9.0
        libnppidei.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppidei.so
        libnppicom.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppicom.so.9.0
        libnppicom.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppicom.so
        libnppicc.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppicc.so.9.0
        libnppicc.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppicc.so
        libnppial.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppial.so.9.0
        libnppial.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppial.so
        libnppc.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libnppc.so.9.0
        libnppc.so (libc6,x86-64) => /usr/local/cuda/lib64/libnppc.so
        libicudata.so.55 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.55
        libicudata.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so
        libcusparse.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcusparse.so.9.0
        libcusparse.so (libc6,x86-64) => /usr/local/cuda/lib64/libcusparse.so
        libcusolver.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcusolver.so.9.0
        libcusolver.so (libc6,x86-64) => /usr/local/cuda/lib64/libcusolver.so
        libcurand.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcurand.so.9.0
        libcurand.so (libc6,x86-64) => /usr/local/cuda/lib64/libcurand.so
        libcuinj64.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcuinj64.so.9.0
        libcuinj64.so (libc6,x86-64) => /usr/local/cuda/lib64/libcuinj64.so
        libcufftw.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcufftw.so.9.0
        libcufftw.so (libc6,x86-64) => /usr/local/cuda/lib64/libcufftw.so
        libcufft.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcufft.so.9.0
        libcufft.so (libc6,x86-64) => /usr/local/cuda/lib64/libcufft.so
        libcudnn.so.7 (libc6,x86-64) => /usr/local/cuda/lib64/libcudnn.so.7
        libcudnn.so (libc6,x86-64) => /usr/local/cuda/lib64/libcudnn.so
        libcudart.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcudart.so.9.0
        libcudart.so (libc6,x86-64) => /usr/local/cuda/lib64/libcudart.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
        libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
        libcublas.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libcublas.so.9.0
        libcublas.so (libc6,x86-64) => /usr/local/cuda/lib64/libcublas.so
        libaccinj64.so.9.0 (libc6,x86-64) => /usr/local/cuda/lib64/libaccinj64.so.9.0
        libaccinj64.so (libc6,x86-64) => /usr/local/cuda/lib64/libaccinj64.so
        libOpenCL.so.1 (libc6,x86-64) => /usr/local/cuda/lib64/libOpenCL.so.1
        libOpenCL.so (libc6,x86-64) => /usr/local/cuda/lib64/libOpenCL.so
```

**Comment by nkreeger** [comment]
@ookami125 hrm.. Can you try one thing - you'll have to checkout the tfjs-node repo.

Please try the following:
```
git clone https://github.com/tensorflow/tfjs-node.git
cd tfjs-node
yarn
rm -rf build/
yarn enable-gpu
node-gyp rebuild --debug
yarn test
```

You might need to install node-gyp (either locally or globally). This builds and runs the tfjs-node with CUDA support and runs the tests in debug mode. You'll probably hit a bad pointer or have some debug output - can you please post here? Next steps are slightly more complicated, but lets try this first :-)

**Comment by ookami125** [comment]
Installed yarn
Installed node-gyp
Reinstalled node (I accidentally broke it)
Node: v8.12.0
I've also kept the host name for clarity this time around.
```
cieric@pool-100-0-0-20:~/src$ rm -rf tfjs-node/
cieric@pool-100-0-0-20:~/src$ git clone https://github.com/tensorflow/tfjs-node.git
Cloning into 'tfjs-node'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1129 (delta 11), reused 3 (delta 3), pack-reused 1110
Receiving objects: 100% (1129/1129), 416.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (763/763), done.
Checking connectivity... done.
cieric@pool-100-0-0-20:~/src$ cd tfjs-node
cieric@pool-100-0-0-20:~/src/tfjs-node$ yarn
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ node scripts/install.js
* Downloading libtensorflow
[==============================] 6574004/bps 100% 0.0s
* Building TensorFlow Node.js bindings
Done in 12.93s.
cieric@pool-100-0-0-20:~/src/tfjs-node$ rm -rf build/
cieric@pool-100-0-0-20:~/src/tfjs-node$ yarn enable-gpu
yarn run v1.10.1
$ node scripts/install.js gpu download && yarn
* Downloading libtensorflow
[==============================] 6578917/bps 100% 0.0s
* Building TensorFlow Node.js bindings
[1/4] Resolving packages...
success Already up-to-date.
$ node scripts/install.js
* Building TensorFlow Node.js bindings
Done in 19.55s.
cieric@pool-100-0-0-20:~/src/tfjs-node$ node-gyp rebuild --debug
module.js:550
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
I've been trying to figure out why node-gyp can't find graceful-fs for about an hour now. What gets me is I even manually added it to node-modules. Excuse my ignorance I only started doing node-gyp stuff really recently so I don't know the full extent of how it works.

**Comment by nkreeger** [comment]
Sounds like your node-package is wedged. I'd recommend using NVM - https://github.com/creationix/nvm

**Comment by ookami125** [comment]
Okay, I guess I really screwed something up at some point. I can't even uninstall node... Could I just get the recommended OS, packages, and versions?

**Comment by nkreeger** [comment]
Windows, Mac OS, and popular Linux distros are your best bet (Ubuntu, Debian, Mint, etc).

**Comment by ookami125** [comment]
Okay I'll try going with latest Ubuntu 18, and from what I see Cuda 9.0 and Cudnn 7.3.0 should work.  Oh, and I guess this issue can be closed, if I somehow run into it again, then we can reopen it or I can open a new one.
