### ISSUE TITLE
TypeError: forwardFunc is not a function

### ISSUE THREAD

**Issue by Rohan-Makwana** [tensorflow/tfjs#7356]
- Running a *pre-trained* __ML5.js__ pose classification model taking input from the __Movenet__ pose detection model.
- I'm getting this error during runtime when the classify function is called on the pre-trained model.
- Tried the solution of deleting the node_modules and re running `npm install` command mentioned in https://github.com/tensorflow/tfjs/issues/2329, but it didn't work.
- tfjs-converter: v3.21.0
- tfjs-core: v3.21.0
- ml5: v0.12.2
- You can find the code over here : https://github.com/Rohan-Makwana/movenet-ml5
-  Complete error log :
   ``` 
    Uncaught (in promise) TypeError: forwardFunc is not a function
    at engine.ts:687:31
    at engine.ts:467:20
    at Engine.scopedRun (engine.ts:478:19)
    at Engine.tidy (engine.ts:465:17)
    at kernelFunc (engine.ts:687:20)
    at engine.ts:710:23
    at Engine.scopedRun (engine.ts:478:19)
    at Engine.runKernelFunc (engine.ts:706:10)
    at slice_ (tf-core.esm.js:17:394980)
    at slice (tf-core.esm.js:17:71801)

**Comment by Neilblaze** [comment]
Seems like a duplicate of [#2329](https://github.com/tensorflow/tfjs/issues/2329)

**Comment by Rohan-Makwana** [comment]
> Seems like a duplicate of [#2329](https://github.com/tensorflow/tfjs/issues/2329)

I have tried all the solutions provided in the particular issue, like uninstalling the node_modules folder and running npm install,  updating some libraries to the latest version but the error still persists.

**Comment by Neilblaze** [comment]
Try cleaning the cache via `npm cache clean --force` & make sure dependencies are up to date. Also, do ensure you don't import `@tensorflow/tfjs` in your component.

**Comment by Rohan-Makwana** [comment]
Thanks for the response, tried the solution you recommended of removing cache and updating to the latest version. Now I have ended up with a new error :
```
App.jsx:121 TypeError: env(...).platform.isTypedArray is not a function
    at isTypedArray (util.ts:137:25)
    at inferShape (tensor_util_env.ts:29:7)
    at tensor (tensor.ts:195:25)
    at Object.decodeWeights (io_utils.ts:224:19)
    at GraphModel.loadSync (graph_model.ts:187:31)
    at graph_model.ts:157:48
    at async loadGraphModel (graph_model.ts:616:3) 
```
Furthermore, to update the packages, I had to use the `--force` flag because of conflicting dependencies. The `ml5`package requires version 1.2.9 of the `@tensorflow/tfjs-converter` package, while some another package installed in my project requires at least version 1.7.4. I tried downgrading the package only to end up with the app crashing. I can't upgrade `ml5` anymore  since I am using the latest version. So I am stuck with this problem, I guess.
