### ISSUE TITLE
tfjs-node install errornpm ERR! command sh -c -- node scripts/install.js

### ISSUE THREAD

**Issue by gbarton** [tensorflow/tfjs#7358]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- 5.15.0-58-generic #64-Ubuntu
- TensorFlow.js installed from (npm or script link): npm install @tensorflow/tfjs-node
- TensorFlow.js version: 4.2.0

**Describe the problem**
Unable to install tfjs-node on linux.  tfjs works fine, but need the CPU version and the file IOhandler to save to disk.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
npm install @tensorflow/tfjs-node
```

Other things tried:

* Updated node/npm versions
* installed latest node-gyp
* Installed latest mapbox node-pre-gyp
* tried all older versions of tfjs-node back to 3.19.0, same errors
* downloaded package tar and played with install.js
  * no matter what I do no output comes from node-pre-gyp on stdout or stderr.
    * this seems to be a node thing, running even `node -v` in the cp.exec gives no output, but `which node-pre-gyp` for example works fine (and finds it btw)
  * running `node-pre-gyp install --fallback-to-build` manually in package directory works fine 

**Any other info / logs**
Last chunk of the npm log:
```
513 timing build:link:node_modules/@mapbox/node-pre-gyp Completed in 4ms
514 timing build:link:node_modules/@tensorflow/tfjs Completed in 3ms
515 timing build:link:node_modules/color-support Completed in 2ms
516 timing build:link:node_modules/mkdirp Completed in 2ms
517 timing build:link:node_modules/nopt Completed in 2ms
518 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/mkdirp Completed in 3ms
519 timing build:link:node_modules/@tensorflow/tfjs-node/node_modules/rimraf Completed in 2ms
520 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/semver Completed in 3ms
521 timing build:link Completed in 6ms
522 info run @tensorflow/tfjs-node@4.2.0 install node_modules/@tensorflow/tfjs-node node scripts/install.js
523 info run @tensorflow/tfjs-node@4.2.0 install { code: 1, signal: null }
524 timing reify:rollback:createSparse Completed in 584ms
525 timing reify:rollback:retireShallow Completed in 0ms
526 timing command:install Completed in 32826ms
527 verbose stack Error: command failed
527 verbose stack     at ChildProcess.<anonymous> (/snap/node/7065/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
527 verbose stack     at ChildProcess.emit (node:events:513:28)
527 verbose stack     at maybeClose (node:internal/child_process:1091:16)
527 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
528 verbose pkgid @tensorflow/tfjs-node@4.2.0
529 verbose cwd /home/gman/wrk/nodetest
530 verbose Linux 5.15.0-58-generic
531 verbose node v18.13.0
532 verbose npm  v8.19.3
533 error code 1
534 error path /home/gman/wrk/nodetest/node_modules/@tensorflow/tfjs-node
535 error command failed
536 error command sh -c -- node scripts/install.js
537 verbose exit 1
538 timing npm Completed in 32993ms
539 verbose unfinished npm timer reify 1675982640484
540 verbose unfinished npm timer reify:build 1675982651854
541 verbose unfinished npm timer build 1675982651855
542 verbose unfinished npm timer build:deps 1675982651855
543 verbose unfinished npm timer build:run:install 1675982651865
544 verbose unfinished npm timer build:run:install:node_modules/@tensorflow/tfjs-node 1675982651866
545 verbose code 1
546 error A complete log of this run can be found in:
546 error     /home/gman/.npm/_logs/2023-02-09T22_44_00_320Z-debug-0.log
```

manually running `node-pre-gyp install --fallback-to-build`

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@18.13.0 | linux | x64
[@tensorflow/tfjs-node] Success: "/home/gman/wrk/nodetest/package/lib/napi-v8/tfjs_binding.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
node-pre-gyp info ok 
```

**Comment by gbarton** [comment]
Hi thanks for replying!  I gave it a go and ran into the same error.  I have the npm logs from the run here.


What was the fix or thing that you saw changed that made it work? Or did you just try the latest and it ran ok?


Console log:
```
gman@gman-lexar:~/wrk/nodetest$ npm install @tensorflow/tfjs-node@4.4.0
npm ERR! code 1
npm ERR! path /home/gman/wrk/nodetest/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
```


NPM Log:
```
752 timing build:link:node_modules/json5 Completed in 6ms
753 timing build:link:node_modules/mkdirp Completed in 6ms
754 timing build:link:node_modules/nopt Completed in 6ms
755 timing build:link:node_modules/resolve Completed in 5ms
756 timing build:link:node_modules/rimraf Completed in 5ms
757 timing build:link:node_modules/semver Completed in 5ms
758 timing build:link:node_modules/which Completed in 5ms
759 timing build:link:node_modules/@mapbox/node-pre-gyp Completed in 7ms
760 timing build:link:node_modules/acorn Completed in 6ms
761 timing build:link:node_modules/color-support Completed in 6ms
762 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/mkdirp Completed in 6ms
763 timing build:link:node_modules/@tensorflow/tfjs-node/node_modules/rimraf Completed in 7ms
764 timing build:link:node_modules/@mapbox/node-pre-gyp/node_modules/semver Completed in 7ms
765 timing build:link Completed in 9ms
766 info run @tensorflow/tfjs-node@4.4.0 install node_modules/@tensorflow/tfjs-node node scripts/install.js
767 info run @tensorflow/tfjs-node@4.4.0 install { code: 1, signal: null }
768 timing reify:rollback:createSparse Completed in 455ms
769 timing reify:rollback:retireShallow Completed in 0ms
770 timing command:install Completed in 53987ms
771 verbose stack Error: command failed
771 verbose stack     at ChildProcess.<anonymous> (/snap/node/7392/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
771 verbose stack     at ChildProcess.emit (node:events:513:28)
771 verbose stack     at maybeClose (node:internal/child_process:1091:16)
771 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
772 verbose pkgid @tensorflow/tfjs-node@4.4.0
773 verbose cwd /home/gman/wrk/nodetest
774 verbose Linux 5.15.0-67-generic
775 verbose node v18.16.0
776 verbose npm  v9.5.1
777 error code 1
778 error path /home/gman/wrk/nodetest/node_modules/@tensorflow/tfjs-node
779 error command failed
780 error command sh -c node scripts/install.js
781 verbose exit 1
782 timing npm Completed in 54023ms
783 verbose unfinished npm timer reify 1682109109520
784 verbose unfinished npm timer reify:build 1682109122437
785 verbose unfinished npm timer build 1682109122438
786 verbose unfinished npm timer build:deps 1682109122439
787 verbose unfinished npm timer build:run:install 1682109122459
788 verbose unfinished npm timer build:run:install:node_modules/@tensorflow/tfjs-node 1682109122459
789 verbose code 1
790 error A complete log of this run can be found in:
790 error     /home/gman/.npm/_logs/2023-04-21T20_31_49_486Z-debug-0.log

```

**Comment by gbarton** [comment]
I had a thought. I'm using snap for node, are you?  I wonder if that's causing the issue?

**Comment by gbarton** [comment]
Success!  I was using the snap version of nodejs this whole time.  I switched to nvm (pretty awesome btw) and installed 18.16.0 and it installed fine, there must be something missing or messed up with the snap version.

So I'm good, whatever the issue was was probably a snap problem this whole time.  Ty for getting me to think about this again.
