### ISSUE TITLE
 tfjs 4.2.0 version issue causing error in Vue3

### ISSUE THREAD

**Issue by myplc** [tensorflow/tfjs#7375]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: none
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.2.0
- Browser version: Vue3 build

**Describe the current behavior**
tfjs 4.2.0
in Vue3 , both error in  build and run serve
about array
etc) tf.tensor([1,2,3,4]) 

I had a problem like this
==================================================================
Uncaught (in promise) TypeError: (0 , _environment__WEBPACK_IMPORTED_MODULE_6__.env)(...).platform.isTypedArray is not a function
    at isTypedArray (util.js:194:71)
    at inferShape (tensor_util_env.js:38:58)
    at Module.tensor (tensor.js:193:85)
    at tfex (tfjs.js:27:66)
    at Proxy.get (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/tf1.vue?vue&type=script&lang=js:33:60)
    at onClick._cache.<computed>._cache.<computed> (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[3]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/tf1.vue?vue&type=template&id=4498369f:21:59)
    at callWithErrorHandling (runtime-core.esm-bundler.js:290:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:298:17)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:473:82) 
=======================================================================
**Standalone code to reproduce the issue**

Resolved by downgrading to version 4.2.0 or lower

**Other info 
Among the syntax used in import tfjs,
Errors in all conditions that receive input as a tf.tensor ([?]) array inside the vue3 script and operate

**Comment by mattsoulanille** [comment]
Thanks for the issue report. Do you have any other TensorFlow.js packages installed? 4.2.0 should have the `isTypedArray` function available on Browser and Node platforms. Maybe another package is using an out of date TensorFlow.js package.

**Comment by shmishra99** [comment]
Hi @myplc,
Could you please refer the following [comment](https://github.com/tensorflow/tfjs/issues/4405#:~:text=tafsiri%20commented%20on,in%20your%20project)? 
As @mattsoulanille mentioned may be inside your `package.json` file you are importing older version along with newer version of TensorFlow.js. The issue has already been addressed in following PR #7489. 
Kindly let us know if it helps. Thank You !!
