### ISSUE TITLE
@tensorflow-models/mobilenet does not work under Node.js

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#740]
Trying to use the `@tensorflow-models/mobilenet` package under Node.js throws the following exception:

2018-09-27 15:25:56.699190: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
(node:98265) Warning: N-API is an experimental feature and could change at any time.
(node:98265) UnhandledPromiseRejectionWarning: Error: browserHTTPRequest is not supported outside the web browser without a fetch polyfill.
    at new BrowserHTTPRequest (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:46:19)
    at Object.browserHTTPRequest (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:247:12)
    at Object.<anonymous> (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:98:50)
    at step (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:42:23)
    at Object.next (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:23:53)
    at /Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:13:12)
    at Object.loadModelInternal (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/models.js:92:12)
    at Object.loadModel (/Users/kreeger/workspace/mn-test/node_modules/@tensorflow/tfjs-layers/dist/exports.js:16:21)
(node:98265) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:98265) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dontmarryme** [comment]
@jthomas hi, is this because the CPU is not supported in tf? would you please give the complete code about how to make node-fetch work? it should be inside the async function? thank you very much.

**Comment by tafsiri** [comment]
@dontmarryme this is because `fetch` does not exist by default on node. So adding this line

```js
global.fetch = require('node-fetch')
```

To the top of your file after installing https://www.npmjs.com/package/node-fetch should do the trick

**Comment by dontmarryme** [comment]
@tafsiri Still not working after added that line, or I am on different issue?

APPLEde-MacBook-Pro-2:mobilenet apple$ node mobilenet.js package.json panda.jpg
cpu backend was already registered. Reusing existing backend
2018-10-23 10:03:28.259707: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
(node:40313) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (/Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1261:9)
    at /Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1322:19
    at new Promise (<anonymous>)
    at fetch (/Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1319:9)
    at BrowserHTTPRequest.<anonymous> (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:163:40)
    at step (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:32:23)
    at Object.next (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:13:53)
    at /Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:3:12)
(node:40313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:40313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
APPLEde-MacBook-Pro-2:mobilenet apple$

**Comment by dontmarryme** [comment]
still can't get it right, I think I have install everything right inside my folder. this is where I started:
http://jamesthom.as/blog/2018/08/07/machine-learning-in-node-dot-js-with-tensorflow-dot-js/

@tafsiri I put global.fetch = require('node-fetch') on top inside the script.js already, still don't work.

APPLEde-MacBook-Pro-2:mobilenet apple$ node script.js mobilenet/model.json panda.jpg
cpu backend was already registered. Reusing existing backend
2018-10-23 18:52:03.945011: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
(node:44077) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (/Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1261:9)
    at /Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1322:19
    at new Promise (<anonymous>)
    at fetch (/Users/apple/Desktop/mobilenet/node_modules/node-fetch/lib/index.js:1319:9)
    at BrowserHTTPRequest.<anonymous> (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:163:40)
    at step (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:32:23)
    at Object.next (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:13:53)
    at /Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/Desktop/mobilenet/node_modules/@tensorflow/tfjs-core/dist/io/browser_http.js:3:12)
(node:44077) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:44077) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tafsiri** [comment]
@dontmarryme `fetch` only works for http(s) protocol. It looks like you changed the protocol to `file://` which wouldn't work with fetch. I'd say you can either go the route of loading the hosted model (and not changing the protocol to file) or following the tutorial code (which doesn't need node-fetch). Have you tried running the code from that tutorial as is (after downloading the necessary files)?

**Comment by dontmarryme** [comment]
@tafsiri thanks for the reply, no, I haven't tried the tutorial, which tutorial link you are referring to? what I want is to run tfjs on node.js, actually I have no background for js so all are very confusing for me, thank you for your guide again!

**Comment by tafsiri** [comment]
@dontmarryme i was referring to the tutorial you linked above http://jamesthom.as/blog/2018/08/07/machine-learning-in-node-dot-js-with-tensorflow-dot-js

Have you tried it when everything is exactly similar to that tutorial? The code you posted has some differences.

**Comment by dontmarryme** [comment]
@tafsiri yes, I have uploaded my code to gitlab:

https://gitlab.com/greenhouseinfo/mobilenet-on-node.js

you may find the downloaded models are put in node-modules/tensorflow-models/mobilenet

**Comment by dontmarryme** [comment]
I now follow the tutorial code loading models from file with file:// without node-fetch: "script.js model.json panda.jpg", but still get the same error messages, any idea?

**Comment by daisy-ycguo** [comment]
I have exactly the same issue with @dontmarryme . Even following the [tutorial](http://jamesthom.as/blog/2018/08/07/machine-learning-in-node-dot-js-with-tensorflow-dot-js), I still meet with error `browserHTTPRequest is not supported outside the web browser without a fetch polyfill.`.

**Comment by daisy-ycguo** [comment]
I finally worked it out.

I use `global.fetch = require('node-fetch')`. In `script.sh` I change the loading mode script from `file` to `https`:
```
  mn.path = `https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_1.0_224/model.json`
  await mn.load()
```

Then I met with an error `Error: Unknown feature TENSORLIKE_CHECK_SHAPE_CONSISTENCY.`

And then , I bump tfjs to the latest release:
```
    "@tensorflow/tfjs": "^0.13.0",
    "@tensorflow/tfjs-node": "^0.1.19",
```

It works for me now.

**Comment by dontmarryme** [comment]
@daisy-ycguo thank you for the replies! it works for me now, but do you know why there's still the compiling error messages? 

2018-10-27 18:54:05.844070: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
classification results: [ { className: 'running shoe', probability: 0.7699763774871826 },
  { className: 'sandal', probability: 0.2003212571144104 },
  { className: 'shoe shop, shoe-shop, shoe store',
    probability: 0.013504834845662117 } ]

**Comment by nkreeger** [comment]
@dontmarryme That isn't a compile error - the TensorFlow library we ship with isn't fully optimized for your machine (but runs on all hardware). It is just a harmless warning - see https://github.com/tensorflow/tfjs/issues/571 for more info.

**Comment by aperkaz** [comment]
Thanks @daisy-ycguo that worked well. I am trying to make it work still with local models, did anyone make it work?
I get the same error message `(node:20391) UnhandledPromiseRejectionWarning: TypeError: Only HTTP(S) protocols are supported` when following the aforementioned tutorial.

**Comment by dontmarryme** [comment]
hello... i made it worked before with node-fetch in 2018, now i bought a new computer and it stops working, i think its the version issue of mobilenet or tfjs? 

*my old files:
https://gitlab.com/greenhouseinfo/mobilenet-on-node.js

*running in max/msp
https://www.youtube.com/watch?v=zp0sc7e_fqM

**Comment by dontmarryme** [comment]
@daisy-ycguo may i know what was your mobilenet version? thanks

**Comment by dontmarryme** [comment]
@aperkaz I found this guy has modified the script and pointed out the modification!
https://sean12697.github.io/blog/2019/07/15/mobilenet-in-nodejs.html
