### ISSUE TITLE
tf.einsum case insensitive

### ISSUE THREAD

**Issue by wangjia184** [tensorflow/tfjs#7404]
**System information**
```
$ tensorflowjs_converter --version
tensorflowjs 4.2.0

Dependency versions:
  keras 2.11.0
  tensorflow 2.11.0
```

**Describe the current behavior**

Einstein notation is case-insensitive in `tf.einsum`.

```
tf.einsum("bhwHW,bHWc->bhwc", attn_score, v)
```

**Describe the expected behavior**

It should be case-sensitive

**Standalone code to reproduce the issue**
Just take the [example code](https://github.com/keras-team/keras-io/blob/master/examples/generative/ddpm.py#L456) from Keras tutorial,  load the weights from the example and exports a saved model.

Then convert to a web model from the save model.
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --saved_model_tags=serve \
    ./saved_model \
    ./www/model
```

Next, try to predict in web browser using this model,  it would fail 

```
Error: Found duplicate axes in input component bhwhw. Support for duplicate axes in input is not implemented yet.
    at Object.K_ [as decodeEinsumEquation] (einsum_util.js:95:13)
    at Object.kernelFunc (Einsum.ts:36:20)
    at n (engine.js:647:22)
    at engine.js:713:23
    at t.scopedRun (engine.js:480:19)
    at t.runKernelFunc (engine.js:709:10)
    at t.runKernel (engine.js:554:17)
    at einsum_ (einsum.js:107:17)
    at Object.einsum__op [as einsum] (operation.js:51:22)
    at matrices_executor.js:43:23
```

The code causing error are `tf.einsum`

```python
        attn_score = tf.einsum("bhwc, bHWc->bhwHW", q, k) * scale
        attn_score = tf.reshape(attn_score, [batch_size, height, width, height * width])

        attn_score = tf.nn.softmax(attn_score, -1)
        attn_score = tf.reshape(attn_score, [batch_size, height, width, height, width])

        proj = tf.einsum("bhwHW,bHWc->bhwc", attn_score, v)
```

To fix the problem, replace `HW` with other letters.

```python
        attn_score = tf.einsum("bhwc, bijc->bhwij", q, k) * scale
        attn_score = tf.reshape(attn_score, [batch_size, height, width, height * width])

        attn_score = tf.nn.softmax(attn_score, -1)
        attn_score = tf.reshape(attn_score, [batch_size, height, width, height, width])

        proj = tf.einsum("bhwij,bijc->bhwc", attn_score, v)
```

It seems einstein notation is case-insensitive in tfjs, but it is case-sensitive in python.

**Comment by Varun-S10** [comment]
Hi @wangjia184, Thank you for your patience. We tried to reproduce the issue, but the code appears to run without errors on our end using the latest version. Please try updating to the latest version of @tensorflow/tfjs to see if that resolves the problem. Could you let us know if this works for you?
