### ISSUE TITLE
Docker container tfjs: model.executeAsync(input) Error: TensorList shape mismatch: Shapes must match

### ISSUE THREAD

**Issue by mkabatek** [tensorflow/tfjs#7420]
Previously working on `node:12`, now not working on `node:18`. If I try and run the following command inside a docker container from image `node:18`

```
const predictions = await model.executeAsync(input)
```

```
Error Error: Invalid TF_Status: 3
Message: Expected multiples[0] >= 0, but got -1111494891 ...
/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:456
        throw new Error(typeof msg === 'string' ? msg : msg());
              ^
Error: TensorList shape mismatch:  Shapes 4096,3072,3 and -272777233,574275007,-272777233 must match
    at Object.assert (/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:456:15)
    at assertShapesMatchAllowUndefinedSize (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:27289:18)
    at fromTensor (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:27826:5)
    at /app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:28206:34
    at step (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:189:27)
    at Object.next (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:138:53)
    at /app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:131:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:117:12)
    at executeOp$i (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:27900:64)
    at /app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:29566:24
    at executeOp (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:29614:7)
    at _loop_1 (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30426:31)
    at GraphExecutor.processStack (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30458:13)
    at GraphExecutor.<anonymous> (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:30378:41)
    at step (/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:189:27)
```

**System information**

Host OS: MacOS 13.1 (22C65)

Using docker image with Dockerfile:
```
FROM node:18
```

- TensorFlow.js installed from (npm or script link):

From package.json

```
"@tensorflow/tfjs": "3.9.0",
"@tensorflow/tfjs-backend-cpu": "3.9.0",
"@tensorflow/tfjs-node": "3.9.0",
```

same behavior with:

```
"@tensorflow/tfjs": "4.2.0",
"@tensorflow/tfjs-backend-cpu": "4.2.0",
"@tensorflow/tfjs-node": "4.2.0",
```

**Comment by mkabatek** [comment]
The problem was on my end - the model was downloaded incorrectly.
