### ISSUE TITLE
Build `tfjs-backend-wasm` occur error: An error occurred during the fetch of repository 'emscripten_bin_mac'

### ISSUE THREAD

**Issue by stephenkingsley** [tensorflow/tfjs#7424]
<em>I use tfjs in my project set wasm backend, so I import `@tensorflow/tfjs-backend-wasm`. The latest version is not include SparseToDense op? Can you release new version?</em>

**System information**
- OS: mac OS Ventura 13.1 Apple M1 chip
- EMSDK: v3.1.32

**Describe the problem**
I cloned this project using Git and navigated to the `tfjs-backend-wasm` folder. I then ran yarn and yarn build, but encountered an error message, which is shown below:

![image](https://user-images.githubusercontent.com/13380370/221743014-067a3126-97c4-40b2-b63b-165f86b71e00.png)

```shell
$ bazel build -c opt :tfjs-backend-wasm_pkg
INFO: Repository emscripten_bin_mac instantiated at:
  /Users/stephen.kingsley/Documents/code/tfjs/WORKSPACE:116:22: in <toplevel>
  /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/emsdk/emscripten_deps.bzl:127:21: in emscripten_deps
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/30b9e46ddcea66e91530559379089002d8b692cf/wasm-binaries.tbz2 failed: class java.net.SocketException Broken pipe (Write failed)
ERROR: An error occurred during the fetch of repository 'emscripten_bin_mac':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/30b9e46ddcea66e91530559379089002d8b692cf/wasm-binaries.tbz2] to /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/emscripten_bin_mac/temp11449498659000995169/wasm-binaries.tbz2.tar.bz2: Broken pipe (Write failed)
ERROR: /Users/stephen.kingsley/Documents/code/tfjs/WORKSPACE:116:22: fetching http_archive rule //external:emscripten_bin_mac: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/30b9e46ddcea66e91530559379089002d8b692cf/wasm-binaries.tbz2] to /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/emscripten_bin_mac/temp11449498659000995169/wasm-binaries.tbz2.tar.bz2: Broken pipe (Write failed)
ERROR: /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/emsdk/BUILD:37:6: @emsdk//:compiler_files depends on @emscripten_bin_mac//:compiler_files in repository @emscripten_bin_mac which failed to fetch. no such package '@emscripten_bin_mac//': java.io.IOException: Error downloading [https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/30b9e46ddcea66e91530559379089002d8b692cf/wasm-binaries.tbz2] to /private/var/tmp/_bazel_stephen.kingsley/e5b0fb562da234be241358f00d6a8c32/external/emscripten_bin_mac/temp11449498659000995169/wasm-binaries.tbz2.tar.bz2: Broken pipe (Write failed)
ERROR: Analysis of target '//tfjs-backend-wasm:tfjs-backend-wasm_pkg' failed; build aborted:
INFO: Elapsed time: 14.747s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 21 targets configured)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. git clone
2. cd tfjs-backend-wasm
3. yarn
4. yarn build
5. oops encountered an error

**Comment by stephenkingsley** [comment]
It's my fault! The core problem is xcode miss. Excute `xcode-select --install` just can fix it.
