### ISSUE TITLE
Test failure on master

### ISSUE THREAD

**Issue by jgartman** [tensorflow/tfjs#751]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
master branch

#### Browser version
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

#### Describe the problem or feature request
The following test is failing for me when I run them locally on my machine:
```
Chrome 69.0.3497 (Mac OS X 10.13.6) Reduction: prod test-webgl2 {"WEBGL_VERSION":2} propagates NaNs FAILED
	Expected 0 to equal NaN.
	    at <Jasmine>
	    at UserContext.<anonymous> (src/ops/reduction_ops_test.ts:864:29 <- src/ops/reduction_ops_test.js:702:34)
	    at <Jasmine>
```

**Comment by davidsoergel** [comment]
Reproduced on my MacBook.  I'm not sure how this got through our automated tests.  I've seen occasional hiccups based on different GPU hardware and such, so that may have something to do with it.  Anyway, thanks for the report-- we'll look into it!

**Comment by dsmilkov** [comment]
Hey, I have a MacBook and it passes. David/Josh can you each send me your laptop spec and the exact OS X version. Thanks!

**Comment by jgartman** [comment]
Sure, I just upgraded to OS X 10.14 (18A391) this past week and I still see the same failure.  Here's a bit more system info:

```
Graphics/Displays:

    Intel HD Graphics 630:

      Chipset Model: Intel HD Graphics 630
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x591b
      Revision ID: 0x0004
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily2 v1

    Radeon Pro 560:

      Chipset Model: Radeon Pro 560
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Dynamic, Max): 4096 MB
      Vendor: AMD (0x1002)
      Device ID: 0x67ef
      Revision ID: 0x00c0
      ROM Revision: 113-C980AJ-927
      VBIOS Version: 113-C9801AU-A02
      EFI Driver Version: 01.00.927
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.29 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily2 v1
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No

```

Issue looks similar to #291

**Comment by dsmilkov** [comment]
Thanks! Josh. I think we can remove that NaN test since it looks like gpu drivers are inconsistent across graphics and explicitly checking for NaN will slow down the whole program. Also looks like TF CUDA doesn't return NaN also (https://github.com/tensorflow/tfjs/issues/321). cc @nsthorat

**Comment by davidsoergel** [comment]
Oops, sorry I missed this thread before.  Just for completeness, my MacBook where I can repro this has the same Intel 630 and a Radeon Pro 555 (very similar to Josh's 560, just mine is the lesser model):

```
Intel HD Graphics 630:

  Chipset Model:	Intel HD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x591b
  Revision ID:	0x0004
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

Radeon Pro 555:

  Chipset Model:	Radeon Pro 555
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Dynamic, Max):	2048 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c7
  ROM Revision:	113-C980AJ-927
  VBIOS Version:	113-C9801AP-A02
  EFI Driver Version:	01.00.927
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
HP ZR30w:
  Resolution:	2560 x 1600
  UI Looks like:	2560 x 1600
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	CN42420R8Q  
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort



```

**Comment by nsthorat** [comment]
@davidsoergel can you still repro this?

**Comment by davidsoergel** [comment]
Yep, I get still get errors that appear to be more or less the same thing:

```
Chrome 73.0.3683 (Mac OS X 10.14.3) Reduction: prod webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} propagates NaNs FAILED
	Error: Arrays differ: actual[0] = 0, expected[0] = NaN.
	    at <Jasmine>
	    at expectArraysPredicate (src/test_util.ts:112:12 <- src/test_util.js:96:19)
	    at expectArraysClose (src/test_util.ts:57:9 <- src/test_util.js:50:12)
	    at Object.expectArraysEqual (src/test_util.ts:144:9 <- src/test_util.js:118:12)
	    at UserContext.<anonymous> (src/ops/reduction_ops_test.ts:1059:4 <- src/ops/reduction_ops_test.js:870:21)
	    at <Jasmine>

Chrome 73.0.3683 (Mac OS X 10.14.3) Reduction: prod webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} propagates NaNs FAILED
	Error: Arrays differ: actual[0] = 0, expected[0] = NaN.
	    at <Jasmine>
	    at expectArraysPredicate (src/test_util.ts:112:12 <- src/test_util.js:96:19)
	    at expectArraysClose (src/test_util.ts:57:9 <- src/test_util.js:50:12)
	    at Object.expectArraysEqual (src/test_util.ts:144:9 <- src/test_util.js:118:12)
	    at UserContext.<anonymous> (src/ops/reduction_ops_test.ts:1059:4 <- src/ops/reduction_ops_test.js:870:21)
	    at <Jasmine>

Chrome 73.0.3683 (Mac OS X 10.14.3) isFinite webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} basic FAILED
	Error: Arrays differ: actual[0] = 1, expected[0] = 0.
	    at <Jasmine>
	    at expectArraysPredicate (src/test_util.ts:112:12 <- src/test_util.js:96:19)
	    at Object.expectArraysClose (src/test_util.ts:57:9 <- src/test_util.js:50:12)
	    at UserContext.<anonymous> (src/ops/unary_ops_test.ts:1692:4 <- src/ops/unary_ops_test.js:1306:21)
	    at <Jasmine>

Chrome 73.0.3683 (Mac OS X 10.14.3) isFinite webgl2 {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} accepts a tensor-like object FAILED
	Error: Arrays differ: actual[0] = 1, expected[0] = 0.
	    at <Jasmine>
	    at expectArraysPredicate (src/test_util.ts:112:12 <- src/test_util.js:96:19)
	    at Object.expectArraysClose (src/test_util.ts:57:9 <- src/test_util.js:50:12)
	    at UserContext.<anonymous> (src/ops/unary_ops_test.ts:1735:4 <- src/ops/unary_ops_test.js:1338:21)
	    at <Jasmine>
```
