### ISSUE TITLE
WebGPU tests fail in BrowserStack without Chrome macOS flag '--disable-vulkan-fallback-to-gl-for-testing'

### ISSUE THREAD

**Issue by gyagp** [tensorflow/tfjs#7631]
When running WebGPU CI in BrowserStack without Chrome macOS flag '--disable-vulkan-fallback-to-gl-for-testing', below errors will be seen. Note that the tests actually run on SwiftShader, instead of Metal. 
But I couldn't reproduce it with macOS at hand (Also based on SwiftShader. But Chrome is M113, which is newer than M112 in the CI).

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7) SLOW 1.178 secs: fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7) SLOW 1.178 secs: fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7): Executed 951 of 4590 (1 FAILED) (skipped 165) (0 secs / 36.036 secs)
Chrome 112.0.0.0 (Mac OS 10.15.7) SLOW 1.178 secs: fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} canvas and image match
Chrome 112.0.0.0 (Mac OS 10.15.7): Executed 951 of 4590 (1 FAILED) (skipped 165) (0 secs / 36.036 secs)
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels, reshape, then do tf.add() FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:147:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49543:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:141:58 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49537:59)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels, reshape, then do tf.add() FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:147:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49543:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:141:58 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49537:59)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels, reshape, then do tf.add() FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:147:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49543:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:141:58 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49537:59)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7): Executed 952 of 4590 (2 FAILED) (skipped 165) (0 secs / 36.038 secs)
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} ImageData 1x1x3 FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:75:30 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49488:41
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:68:36 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49482:37)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} ImageData 1x1x3 FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:75:30 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49488:41
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:68:36 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49482:37)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} ImageData 1x1x3 FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:75:30 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49488:41
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:68:36 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49482:37)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7): Executed 953 of 4590 (3 FAILED) (skipped 165) (0 secs / 36.039 secs)
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels for HTMLCanvasElement FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels for HTMLCanvasElement FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels for HTMLCanvasElement FAILED
	AbortError: Device is lost

Chrome 112.0.0.0 (Mac OS 10.15.7): Executed 954 of 4590 (4 FAILED) (skipped 165) (0 secs / 36.04 secs)
Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels + fromPixels FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:165:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49560:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:154:44 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49549:45)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels + fromPixels FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:165:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49560:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:154:44 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49549:45)
	    at <Jasmine>

Chrome 112.0.0.0 (Mac OS 10.15.7) fromPixels webgpu {"WEBGPU_CPU_FORWARD":false} fromPixels + fromPixels FAILED
	RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
	    at BufferManager.acquireBuffer (tfjs-backend-webgpu/src/buffer_manager.ts:48:28 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:17325:35)
	    at WebGPUBackend.uploadToGPU (tfjs-backend-webgpu/src/backend_webgpu.ts:652:50 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:18635:56)
	    at Object.fromPixels2 [as kernelFunc] (tfjs-backend-webgpu/src/kernels/FromPixels.ts:147:11 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:121806:14)
	    at kernelFunc (tfjs-core/src/engine.ts:647:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3264:28)
	    at ../../tfjs-core/src/engine.ts:713:23 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3307:27
	    at Engine.scopedRun (tfjs-core/src/engine.ts:480:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3182:25)
	    at Engine.runKernelFunc (tfjs-core/src/engine.ts:709:10 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3302:16)
	    at Engine.runKernel (tfjs-core/src/engine.ts:554:17 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3223:23)
	    at fromPixels_ (tfjs-core/src/ops/browser.ts:116:19 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:15686:21)
	    at Object.fromPixels__op (tfjs-core/src/ops/operation.ts:51:22 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:3852:24)
	    at ../../tfjs-core/src/ops/from_pixels_test.ts:165:26 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49560:37
	    at Generator.next (<anonymous>)
	    at tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:72:64
	    at new Promise (<anonymous>)
	    at __async (tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:56:12)
	    at UserContext.<anonymous> (tfjs-core/src/ops/from_pixels_test.ts:154:44 <- tfjs/tfjs-backend-webgpu/src/tfjs-backend-webgpu_test_bundle.js:49549:45)
	    at <Jasmine>

**Comment by mattsoulanille** [comment]
This issue was discovered in #7625. I'm reaching out to BrowserStack about getting Windows tests running and to see if they know why this flag is required, although it may be a Chrome issue (I haven't tested this exact configuration outside of BrowserStack). Let's keep it open for now.

**Comment by mattsoulanille** [comment]
Tested locally on Chrome 112.0.5615.137 on an Apple Silicon mac and it passed the tests without the `--disable-vulkan-fallback-to-gl-for-testing` flag. This version is more similar to the BrowserStack version (112.0.5615.49).

**Comment by gyagp** [comment]
I'm OK to close this issue given we couldn't do much in TensorFlow.js.
