### ISSUE TITLE
[e2e] tf.ready is required on windows but not macOS.

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7636]
If tf.ready is not applied for webgpu:
```
Step #18 - "test-e2e":   #REGRESSION convert_predict webgpu {"WEBGPU_CPU_FORWARD":false}
Step #18 - "test-e2e":     [31mâœ— [39m[31msaved_model_v1.[39m
Step #18 - "test-e2e": 	Error: The highest priority backend 'webgpu' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
Step #18 - "test-e2e": 	    at Engine.get (/tmp/karma-typescript-bundle--4452-tgyjUhIrYUbv-.js:105989:27)
Step #18 - "test-e2e": 	    at Engine.memory (/tmp/karma-typescript-bundle--4452-tgyjUhIrYUbv-.js:106651:25)
Step #18 - "test-e2e": 	    at Object.memory (/tmp/karma-typescript-bundle--4452-tgyjUhIrYUbv-.js:109719:19)
Step #18 - "test-e2e": 	    at integration_tests/convert_predict.ts:101:34 <- integration_tests/convert_predict.js:94:46
Step #18 - "test-e2e": 	    at step (integration_tests/convert_predict.js:33:23)
Step #18 - "test-e2e": 	    at Object.next (integration_tests/convert_predict.js:14:53)
Step #18 - "test-e2e": 	    at fulfilled (integration_tests/convert_predict.js:5:58)
```
If tf.ready is not applied for webgpu or wasm:
```
Step #18 - "test-e2e":   #SMOKE cpu forwarding) wasm {}
Step #18 - "test-e2e":     [31mâœ— [39m[31mshould work for slice.[39m
Step #18 - "test-e2e": 	Error: Backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods
Step #18 - "test-e2e": 	    at Engine.get (/tmp/karma-typescript-bundle--4452-z0qpGWH40YTf-.js:105982:23)
Step #18 - "test-e2e": 	    at Engine.makeTensor (/tmp/karma-typescript-bundle--4452-z0qpGWH40YTf-.js:106520:35)
Step #18 - "test-e2e": 	    at makeTensor (/tmp/karma-typescript-bundle--4452-z0qpGWH40YTf-.js:107409:19)
Step #18 - "test-e2e": 	    at Object.tensor3d (/tmp/karma-typescript-bundle--4452-z0qpGWH40YTf-.js:120456:12)
Step #18 - "test-e2e": 	    at integration_tests/cpu_forwarding_test.ts:55:23 <- integration_tests/cpu_forwarding_test.js:73:29
Step #18 - "test-e2e": 	    at step (integration_tests/cpu_forwarding_test.js:33:23)
Step #18 - "test-e2e": 	    at Object.next (integration_tests/cpu_forwarding_test.js:14:53)
Step #18 - "test-e2e": 	    at integration_tests/cpu_forwarding_test.js:8:71
Step #18 - "test-e2e": 	    at <Jasmine>
Step #18 - "test-e2e": 	    at __awaiter (integration_tests/cpu_forwarding_test.js:4:12)
Step #18 - "test-e2e": 	    at UserContext.<anonymous> (integration_tests/cpu_forwarding_test.ts:54:36 <- integration_tests/cpu_forwarding_test.js:68:55)
Step #18 - "test-e2e": 	    at <Jasmine>
```

**Comment by qjia7** [comment]
@axinging Is this bug still valid?
