### ISSUE TITLE
I can not run the demos of tfjs-models/body-segmentation /demos/

### ISSUE THREAD

**Issue by zhuting233** [tensorflow/tfjs#7679]
I run the live video demo on mac. 
It was build successfully.
when I start yarn watch, it printed a lot of warnings and the error:
```
⚠️  Could not load source file "../../../src/posenet/ops/get_points_confidence.ts" in source map of "node_modules/@tensorflow-models/pose-detection/posenet/ops/get_points_confidence.js".
⚠️  Could not load source file "../../../src/shared/calculators/get_rotated_sub_rect_to_rect_transformation_matrix.ts" in source map of "node_modules/@tensorflow-models/pose-detection/shared/calculators/get_rotated_sub_rect_to_rect_transformation_matrix.js".
⚠️  Could not load source file "../../../src/shared/calculators/calculate_inverse_matrix.ts" in source map of "node_modules/@tensorflow-models/body-segmentation/shared/calculators/calculate_inverse_matrix.js".
⚠️  Could not load source file "../../../src/body_pix/impl/output_rendering_util.ts" in source map of "node_modules/@tensorflow-models/body-segmentation/body_pix/impl/output_rendering_util.js".
🚨  /Users/cao/codes/tfjs-models/body-segmentation/demos/upload_video/node_modules/@tensorflow-models/pose-detection/posenet/ops/get_points_confidence.js:20:23: Cannot resolve dependency '@tensorflow/tfjs-backend-webgpu'
  18 | Object.defineProperty(exports, "__esModule", { value: true });
  19 | exports.getPointsConfidenceGPU = void 0;
> 20 | var tfwebgpu = require("@tensorflow/tfjs-backend-webgpu");
     |                       ^
  21 | var tf = require("@tensorflow/tfjs-core");
  22 | var get_points_confidence_webgpu_1 = require("./get_points_confidence_webgpu");
  23 | function getPointsConfidenceGPU(a, b) {
```
Then I install the @tensorflow/tfjs-backend-webgpu through npm. 
when I open the website. It shows nothing. In the console , the error is:
```
caught Error: Cannot evaluate flag 'CANVAS2D_WILL_READ_FREQUENTLY_FOR_GPU': no evaluation function found.
    at Environment.evaluateFlag (environment.ts:141:13)
    at Environment.get (environment.ts:101:28)
    at Environment.getBool (environment.ts:117:17)
    at parcelRequire.node_modules/@tensorflow/tfjs-backend-webgpu/dist/kernels/FromPixels.js.@tensorflow/tfjs-core (FromPixels.ts:32:32)
    at newRequire (Concat_impl.ts:46:24)
    at localRequire (TopK_impl.ts:51:14)
    at parcelRequire.node_modules/@tensorflow/tfjs-backend-webgpu/dist/register_all_kernels.js.@tensorflow/tfjs-core (register_all_kernels.ts:81:1)
    at newRequire (Concat_impl.ts:46:24)
    at localRequire (TopK_impl.ts:51:14)
    at parcelRequire.node_modules/@tensorflow/tfjs-backend-webgpu/dist/index.js../base (index.ts:19:1)
```
How can I run it correctly? Thanks!

**Comment by Linchenn** [comment]
Could you try other version of tfjs-backend-webgpu? like https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu/v/0.0.1-alpha.10, or ~alpha.9 or ~alpha.11.

I think this is version mismatch, you are using old tfjs package 3.13, while using the lastest webgpu package.

**Comment by zhuting233** [comment]
> Could you try other version of tfjs-backend-webgpu? like https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu/v/0.0.1-alpha.10, or ~alpha.9 or ~alpha.11.
> 
> I think this is version mismatch, you are using old tfjs package 3.13, while using the lastest webgpu package.

Thank you ！It works. But another error occured.
```
dat.gui.min.js:13 Uncaught (in promise) Error: Object "[object Object]" has no property "model"
    at f (dat.gui.min.js:13:5450)
    at e.add (dat.gui.min.js:13:45174)
    at setupDatGui (option_panel.js:98:39)
    at app (index.js:325:9)

```

**Comment by Linchenn** [comment]
Did you add 'model=abc' in your URL? Like: 'http://..../index.html?model=selfie_segmentation'

**Comment by zhuting233** [comment]
> Did you add 'model=abc' in your URL? Like: 'http://..../index.html?model=selfie_segmentation'

I filled in the wrong parameters before，Thank u!!! It works.

I write a html, to handle uploaded images. 
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <!-- <img id="image" src="37.jpg" /> -->

    <div style="margin-top: 20px">
        <label for="upload-directory">点击选择文件夹</label>
        <input
          title="点击选择文件夹"
          id="upload-directory"
          multiple=""
          webkitdirectory=""
          accept="*/*"
          type="file"
          name="html5uploader"
        />
    </div>

    <!-- <canvas id="canvas"></canvas> -->

</body>

<!-- <script src="tfjs-backend-webgl.js" /> -->
<!-- Import @tensorflow/tfjs-core -->
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>

<!-- Adds the WebGL backend to the global backend registry -->
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
<script src="body-segmentation.js">
</script>

<!-- Optional: Include below scripts if you want to use TensorFlow.js runtime. -->
<script src="tfjs-converter.js">
</script>

<!-- Optional: Include below scripts if you want to use MediaPipe runtime. -->
<script src="selfie_segmentation.js">
</script>
<script>

    
    // import * as bodySegmentation from '@tensorflow-models/body-segmentation';    
    // console.log(bodySegmentation)

    


    document
    .querySelector('#upload-directory')
    .addEventListener('input', async function (event) {

        const model = bodySegmentation.SupportedModels.MediaPipeSelfieSegmentation;
        const segmenterConfig = {
            runtime: 'mediapipe', // or 'tfjs'
            solutionPath: 'https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation',
            modelType: 'general'
        }

        for (let file of event.target.files) {
            console.log(file)
            let img = new Image();
            img.src = window.URL.createObjectURL(file);
            console.log(img)
            
            
            const segmenter = await bodySegmentation.createSegmenter(model, segmenterConfig);
            var people = await segmenter.segmentPeople(img);
            console.log(people);
    
            const foregroundColor = { r: 0, g: 0, b: 0, a: 0 };
            const backgroundColor = { r: 0, g: 0, b: 0, a: 255};
            const drawContour = true;
            const foregroundThreshold = 0.4;
    
            const backgroundDarkeningMask = await bodySegmentation.toBinaryMask(people, foregroundColor, backgroundColor, drawContour, foregroundThreshold);
    
            const opacity = 1;
            const maskBlurAmount = 3; // Number of pixels to blur by.
            //const canvas = document.getElementById('canvas');
            
    
            var canvas = document.createElement('canvas');

            people = await bodySegmentation.drawMask(canvas, img, backgroundDarkeningMask, opacity, maskBlurAmount);
            
            var link = document.createElement("a");
            var imgData =canvas.toDataURL({format: 'jpg', quality:1, width:20000, height:4000});
            var strDataURI = imgData.substr(22, imgData.length);
            var blob = dataURLtoBlob(imgData);
            var objurl = URL.createObjectURL(blob);
            link.download = file.name
            link.href = objurl;
            link.click();
    
            function  dataURLtoBlob(dataurl) {
                var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
                bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
                while(n--){
                        u8arr[n] = bstr.charCodeAt(n);
                }
                return new Blob([u8arr], {type:mime});
            }

            segmenter.dispose();// it seems not work
    
          }
    })

    
</script>

</html>
```

It can only handle several pics, then  It shows:
```
[.WebGL-0x13407f84d00] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
index%202.html:1 [.WebGL-0x13407f84d00] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
selfie_segmentation.js:67 Uncaught (in promise) DOMException: Failed to execute 'createImageBitmap' on 'Window': The source image width is 0.
    at Xc (http://127.0.0.1:5500/selfie_segmentation.js:67:231)
    at ra.i (http://127.0.0.1:5500/selfie_segmentation.js:92:185)
    at ua (http://127.0.0.1:5500/selfie_segmentation.js:20:299)
    at va.next (http://127.0.0.1:5500/selfie_segmentation.js:21:91)
    at http://127.0.0.1:5500/selfie_segmentation.js:21:484
    at new Promise (<anonymous>)
    at wa (http://127.0.0.1:5500/selfie_segmentation.js:21:377)
    at E (http://127.0.0.1:5500/selfie_segmentation.js:22:22)
    at kd (http://127.0.0.1:5500/selfie_segmentation.js:90:59)
    at Object.onResults (http://127.0.0.1:5500/selfie_segmentation.js:94:288)
```
and the memery of gpu of chrome used is 7g+.
I tried change the code many times，such as put the segmenter out of the loop, but I failed.
Thanks again for your help。

**Comment by gaikwadrahul8** [comment]
Hi, @zhuting233 

Apologize for the delayed response so May I know your issue got resolved or still are you looking for help ? if yes could you please help me with steps to reproduce the same issue from my end ? Thank you!

**Comment by zhuting233** [comment]
> 

I want to write a html page which can upload a folder of imgs and then it can return the results of the body-segmentation.
So I wrote the html above, but it can only handle several imgs and the memery of gpu of chrome used is increasing unbelievablely.  I searched a lot , but didn't find the solution.
If you want to reproduce the same issue, you can copy the code above and save as index.html. Then open the file with browser.

**Comment by gaikwadrahul8** [comment]
Hi, @zhuting233 

It seems like in your code you're not disposing the created tensors so memory usage are increasing so could you please try to include either tf.tidy or tf.dispose api's in your code which may solve your memory related issue 

1. [tf.tidy](https://js.tensorflow.org/api/latest/#tidy) cleans up all intermediate tensors allocated by fn except those returned by fn. fn must not return a Promise (async functions not allowed). The returned result can be a complex object.

Using this method helps avoid memory leaks. In general, wrap calls to operations in [tf.tidy()](https://js.tensorflow.org/api/latest/#tidy) for automatic memory cleanup.

2. [tf.dispose](https://js.tensorflow.org/api/latest/#dispose) : Disposes any [tf.Tensor](https://js.tensorflow.org/api/latest/#class:Tensor)s found within the provided object.

Could you please try with any one of the api's and let us know whether is it resolving your issue or not ? 

If issue still persists please let us know with error log to dig more into your issue ? Thank you!
