### ISSUE TITLE
NodeJS minimun version

### ISSUE THREAD

**Issue by DavidGOrtega** [tensorflow/tfjs#769]
#### TensorFlow.js version
tfjs-node 0.1.18
#### Browser version
node 4.9.1
#### Describe the problem or feature request
I can't run tfjs on node 4.9.1
First util.promisify has to be a polyfill, once fixed

```js
const util = require('util');
require('util.promisify').shim();
```
Then the backend can't be registered

```

[1008/135136.058:INFO:CONSOLE(191)] "Registration of backend tensorflow failed", source: C:\XXXXXX\node_modules\@tensorflow\tfjs-core\dist\environment.js (191)
[1008/135136.059:INFO:CONSOLE(192)] "Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\XXXXXX\node_modules\@tensorflow\tfjs-node\build\Release\tfjs_binding.node
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at bindings (C:\XXXXX\node_modules\bindings\bindings.js:81:44)
    at C:\XXXXXX\node_modules\@tensorflow\tfjs-core\dist\environment.js:185:27)

```

Any reason to support node 4.9.1? Yes! many many super famous Electron apps that would benefit from TF via extensions

**Comment by bileschi** [comment]
@nkreeger Do we have any guidance on which versions of node are / are not supported?

**Comment by DavidGOrtega** [comment]
I can confirm also that the MOST interesting Node version for interesting applications and commercial purposes V7 is not supported. I'm digging on the error but I would say that maybe it's the promisify dependency that the polyfill is not properly working?

**Comment by DavidGOrtega** [comment]
I see that the bindings uses N-API so, gameover... It belongs to the world v8 and beyond. It's sad since all Adobe CC CEP uses v7.

Unless anyone can tell me the opposite, I think its done. 
Can I have access to your tryouts of WebAssembly? Are they public? for me a 4x/6x speed improvement it's an awesome improvement.
