### ISSUE TITLE
undefined backend (tfjs-node)

### ISSUE THREAD

**Issue by thewh1teagle** [tensorflow/tfjs#7706]
I am using `@tensorflow/tfjs-node` in my project, and I followed the instructions in your [tfjs-node folder](https://github.com/tensorflow/tfjs/tree/master/tfjs-node).
However, I encountered the following error while attempting to load the model:
```shell
TypeError: Cannot read properties of undefined (reading 'backend')
```

<details>

<summary>npm log</summary>

```shell
> npm start

> tlang@1.0.0 start
> tsc & node build\index.js

2023-05-20 14:27:49.002730: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

============================
Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details.
============================
C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4519
        var srcBackend = info.backend;
                              ^

TypeError: Cannot read properties of undefined (reading 'backend')
    at Engine.moveData (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4519:31)
    at DataStorage.get (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:230:28)
    at MathBackendCPU.incRef (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-backend-cpu\dist\tf-backend-cpu.node.js:292:36)
    at Object.reshape [as kernelFunc] (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-backend-cpu\dist\tf-backend-cpu.node.js:3825:13)
    at kernelFunc (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4704:32)
    at C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4764:27
    at Engine.scopedRun (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4569:23)
    at Engine.runKernelFunc (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4760:14)
    at Engine.runKernel (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4633:21)
    at reshape_ (C:\Users\User\Desktop\tlang\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:9622:19)
```

</details>

<details>

<summary>versions and env</summary>

```shell
node: v16.19.0
@tensorflow/tfjs-node: ^4.6.0
OS: Windows 11 x64
```

</details>

You can see the complete code in my github [repo](https://github.com/thewh1teagle/tlang)

**Comment by gaikwadrahul8** [comment]
Hi, @thewh1teagle 

Apologize for the delayed response and I was able to replicate the same issue with same error message which you have mentioned above so we will have to dig more into this issue and we'll update you soon, Thank you for noticing this issue, I really appreciate your efforts and time. For your reference I have added screenshot below. Thank you!

```
gaikwadrahul-macbookpro:tlang-main gaikwadrahul$ node build/index.js

============================
Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details. 
============================
/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4519
        var srcBackend = info.backend;
                              ^

TypeError: Cannot read properties of undefined (reading 'backend')
    at Engine.moveData (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4519:31)
    at DataStorage.get (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:230:28)
    at MathBackendCPU.incRef (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:292:36)
    at Object.reshape [as kernelFunc] (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:3825:13)
    at kernelFunc (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4704:32)
    at /Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4764:27
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)
    at Engine.runKernelFunc (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4760:14)
    at Engine.runKernel (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4633:21)
    at reshape_ (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9622:19)

Node.js v18.15.0
gaikwadrahul-macbookpro:tlang-main gaikwadrahul$ 
```

**Comment by jmpedrosa** [comment]
> Hi, @thewh1teagle
> 
> Apologize for the delayed response and I was able to replicate the same issue with same error message which you have mentioned above so we will have to dig more into this issue and we'll update you soon, Thank you for noticing this issue, I really appreciate your efforts and time. For your reference I have added screenshot below. Thank you!
> 
> ```
> gaikwadrahul-macbookpro:tlang-main gaikwadrahul$ node build/index.js
> 
> ============================
> Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details. 
> ============================
> /Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4519
>         var srcBackend = info.backend;
>                               ^
> 
> TypeError: Cannot read properties of undefined (reading 'backend')
>     at Engine.moveData (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4519:31)
>     at DataStorage.get (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:230:28)
>     at MathBackendCPU.incRef (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:292:36)
>     at Object.reshape [as kernelFunc] (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:3825:13)
>     at kernelFunc (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4704:32)
>     at /Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4764:27
>     at Engine.scopedRun (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)
>     at Engine.runKernelFunc (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4760:14)
>     at Engine.runKernel (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4633:21)
>     at reshape_ (/Users/gaikwadrahul/Desktop/tlang-main/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9622:19)
> 
> Node.js v18.15.0
> gaikwadrahul-macbookpro:tlang-main gaikwadrahul$ 
> ```

#metoo
I'm not the kind of guy that throws some exception to be fixed, but maybe it will help someone, thare are some slight differences: 
@tensorflow\tfjs-core\dist\tf-core.node.js:4519
    var srcBackend = info.backend;
                          ^

TypeError: Cannot read properties of undefined (reading 'backend')
    at Engine.moveData (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4519:31)
    at DataStorage.get (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:230:28)
    at NodeJSKernelBackend.getInputTensorIds (\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:169:43)
    at NodeJSKernelBackend.executeSingleOutput (\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:216:73)
    at Object.kernelFunc (\node_modules\@tensorflow\tfjs-node\dist\kernels\Reshape.js:34:27)
    at kernelFunc (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4704:32)
    at \node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4764:27
    at Engine.scopedRun (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4569:23)
    at Engine.runKernelFunc (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4760:14)
    at Engine.runKernel (\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4633:21)
    
    I've tried, with tfjs, tfjs-node and tfjs-node-gpu with the same results. I'm running this on a conda enviroment with python 2.7 and with nodejs 18.15.0 (also tried with 14)
