### ISSUE TITLE
Invalid Memory Access leads to SIGABRT or SIGSEGV with Tensorflow + nodejs

### ISSUE THREAD

**Issue by ryanhugh** [tensorflow/tfjs#7719]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04 LTS x86_64 and Ubuntu 20.04.6 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.6.0 and 4.1.0
- Browser version: N/A
- Tensorflow.js Converter Version: ?

**Describe the current behavior**

I would like to use `@tensorflow/tfjs-node` in Node.js to run `@vladmandic/face-api` and `nsfwjs` to detect people and identify nsfw content in images. I have it all set up and everything works perfectly while running on my local MacBook (13.3.1 Ventura, M2 ARM). However, when I deploy this to my production servers, they frequently crash with memory errors (SIGABRT or SIGSEGV). 

Usually the memory error is one of these two:

```
corrupted size vs. prev_size
corrupted size vs. prev_size while consolidating
```
But I have also see these as well: 

```
malloc(): unaligned tcache chunk detected
free(): invalid size
munmap_chunk(): invalid pointer
```

This kills the entire Node.js process with a SIGABRT or SIGSEGV which cannot happen in production. I have tried different servers on my hosting provider, different versions of Ubuntu (Ubuntu 22.04 LTS x86_64 and Ubuntu 20.04.6 LTS). I've also tried different Tensorflow versions (4.1.0 and 4.6.0) and Node.js versions (16, 18, 20). I'm confident this is an issue with tensorflow because I ran it and captured this below log where it crashes halfway through a debugging output. 

[tensorflowdebugmode_upload.log](https://github.com/tensorflow/tfjs/files/11576182/tensorflowdebugmode_upload.log)

**Describe the expected behavior**
Not to crash.

**Standalone code to reproduce the issue**
I can reproduce the issue very consistently when running `@vladmandic/face-api`, `nsfwjs` and a few other pure-JS packages on images (eg. `tesseract.js`).

[touploadtogithub.txt](https://github.com/tensorflow/tfjs/files/11576286/touploadtogithub.txt)

**Comment by vladmandic** [comment]
first thing i'd look at is os system logs to see where exactly is the SIG happening.
can be in `nodejs` (not likely), `node-bindings` or bundled `tensorflow.so` itself.

if its in bindings, than issue belongs here.
if its in `tensorflow.so`, well tfjs-node 4.6.0 packages **tensorflow** 2.9.1 while latest is 2.12.0,  
so first thing i'd look is how to get that in to avoid working on something that may-or-may-not already been solved  
(which does need updated bindings), so again, it belongs here

on a total side-note, i've been quite disapointed with built-in `glibc` `malloc` when it gets streched by ML frameworks  
when working with pytorch, i've had much better luck using `tcmalloc`

> sudo apt install libgoogle-perftools-dev  
> sudo ldconfig  
> export LD_PRELOAD=libtcmalloc.so

**Comment by ryanhugh** [comment]
Here's another stack trace: 

```

Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e64eba in tfnodejs::TFJSBackend::InsertHandle(TFE_TensorHandle*) () from /home/ryanhughes/tensorflow-crash-repro/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node
(gdb) bt
#0  0x00007ffff7e64eba in tfnodejs::TFJSBackend::InsertHandle(TFE_TensorHandle*) ()
   from /home/ryanhughes/tensorflow-crash-repro/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node
#1  0x00007ffff7e654d6 in tfnodejs::TFJSBackend::GenerateOutputTensorInfo(napi_env__*, TFE_TensorHandle*) ()
   from /home/ryanhughes/tensorflow-crash-repro/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node
#2  0x00007ffff7e6801f in tfnodejs::TFJSBackend::ExecuteOp(napi_env__*, napi_value__*, napi_value__*, napi_value__*, napi_value__*) ()
   from /home/ryanhughes/tensorflow-crash-repro/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node
#3  0x00007ffff7e6b5f0 in tfnodejs::ExecuteOp(napi_env__*, napi_callback_info__*) ()
   from /home/ryanhughes/tensorflow-crash-repro/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node
#4  0x0000000000c2ee99 in v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke(v8::FunctionCallbackInfo<v8::Value> const&) ()
#5  0x0000000000f1470f in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) ()
#6  0x0000000000f14f7d in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, unsigned long*, int) ()
#7  0x0000000000f15445 in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) ()
#8  0x000000000191cdf6 in Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit ()
```

**Comment by ryanhugh** [comment]
Here's a reproduction repository too:  https://github.com/ryanhugh/tensorflow-crash-repro

**Comment by ryanhugh** [comment]
@mattsoulanille Let me know if you can look into this. Thank you!

**Comment by muhammadsohaib60** [comment]
Hello , it is easy . can I help .

**Comment by muhammadsohaib60** [comment]
1) First dependencies installed latest versions of TensorFlow.js . Use package managers like npm or yarn to update the packages to their latest compatible versions.

**Comment by muhammadsohaib60** [comment]
2) Secondly set breakpoints, inspect variables, and step through the code to identify the exact location where the segmentation fault occurs.

**Comment by ryanhugh** [comment]
@mattsoulanille Let me know if you can look into this. Thank you!

**Comment by ryanhugh** [comment]
Hey all - I just got this code working by re-arranging some Node.js code. Uploaded it to my repo (https://github.com/ryanhugh/tensorflow-crash-repro) No longer blocked by this issue, but it still seems like there is a memory leak in these bindings, tensorflow, or node. I'll let someone from tensorflow investigate.

**Comment by Varun-S10** [comment]
Hi @ryanhugh, Thank you for the update and for sharing your solution. Since you are no longer blocked, we will go ahead and close this issue. However, please feel free to reopen it or start a new one if you encounter further issues related to the memory leak.
