### ISSUE TITLE
Keras H5 to Tensorflowjs model conversion

### ISSUE THREAD

**Issue by dubrovin-sudo** [tensorflow/tfjs#7728]
This template is for miscellaneous issues not covered by the other issue categories.

**I used the following command:**
`!tensorflowjs_converter \
    --input_format=keras \
    --output_format=tfjs_graph_model \
    --saved_model_tags=serve \
    --quantize_float16=* \
    /content/gdrive/MyDrive/deeplav_v3_plus/files/mobilenetv3large_20.h5 \
    /content/gdrive/MyDrive/customTF2/models_to_prod/mobilenetv3large_20_float16`

My keras model- [Link](https://drive.google.com/file/d/1gsXD5ZjMP5vPlUU4mpzFRUbUEV79MIps/view?usp=sharing)
Colab notebook(i use dice as a loss and dice_coeff as a metric) - [Link](https://drive.google.com/file/d/1bptf6BcHJ66Pl3GlCPWkA2o7sS9w8nMN/view?usp=sharing)

**The full conversion log is:**
`WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 46). These functions will not be directly callable after loading.
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_11/FusedBatchNormV3'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_11/FusedBatchNormV3'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_12/FusedBatchNormV3'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_12/FusedBatchNormV3'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_13/FusedBatchNormV3'
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'StatefulPartitionedCall/model_1/batch_normalization_13/FusedBatchNormV3'
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 817, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 508, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_graph_model_conversion(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 148, in dispatch_keras_h5_to_tfjs_graph_model_conversion
    tf_saved_model_conversion_v2.convert_tf_saved_model(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 976, in convert_tf_saved_model
    _convert_tf_saved_model(output_dir, saved_model_dir=saved_model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 851, in _convert_tf_saved_model
    optimized_graph = optimize_graph(frozen_graph, signature,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 204, in optimize_graph
    raise ValueError('Unsupported Ops in the model after optimization\n' +
ValueError: Unsupported Ops in the model after optimization
_FusedBatchNormEx
`

**Comment by gaikwadrahul8** [comment]
Hi, @dubrovin-sudo 

Apologize for the delayed response and If I'm not wrong, It seems like there is Unsupported Ops in the model after optimization `_FusedBatchNormEx` and it seems like we haven't implemented this Op `_FusedBatchNormEx` yet so it's causing the issue to convert that model into Tensorflowjs so most probably this issue will be considered as Feature request for that Op if we haven't implemented yet so we'll update you soon. Thank you for noticing this issue, I really appreciate your time and efforts. Thank you!

**Comment by edge7Lux** [comment]
any update on this?

**Comment by edge7Lux** [comment]
Hi @pyu10055 do we have any news on this?
Thanks

**Comment by nileshau-afk** [comment]
Hello @dubrovin-sudo  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @dubrovin-sudo  ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
