### ISSUE TITLE
Request to add support for SparseReorder and SegmentSum ops [tensorflowjs_converter]

### ISSUE THREAD

**Issue by borinstein** [tensorflow/tfjs#7781]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): 4.4.0
- Are you willing to contribute it (Yes/No): Yes, if I'm able; I have no experience with the internals of TFJS

**Describe the feature and the current behavior/state.**

**Unsupported Ops**: `SegmentSum` and `SparseReorder`

Hi TF.js team,

We have a TF SavedModel which we'd like to convert, using the `tensorflowjs_converter`, for use with TF.js.

When attempting to run the following code to convert the model...
```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    /path/to/saved_model \
    /path/to/tfjs_model
```
...we get the following error:
```
Traceback (most recent call last):
  File "/Users/borinste/.venv/py37/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 827, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 831, in main
    convert(argv[0].split(' '))
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 818, in convert
    weight_shard_size_bytes, metadata_map)
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/converter.py", line 539, in _dispatch_converter
    metadata=metadata_map)
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 988, in convert_tf_saved_model
    frozen_graph_dir=frozen_graph_dir)
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 854, in _convert_tf_saved_model
    experiments=experiments)
  File "/Users/borinste/.venv/py37/lib/python3.7/site-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 152, in optimize_graph
    ', '.join(unsupported))
ValueError: Unsupported Ops in the model before optimization
SparseReorder, SegmentSum
```

Please see [saved_model.zip](https://github.com/tensorflow/tfjs/files/11853730/saved_model.zip) for a toy model which can be used to reproduce the error.

**Question**: per the guidance at https://www.tensorflow.org/js/tutorials/conversion/import_saved_model#supported_operations, would it be possible to add support for these two ops to TensorFlow.js?

Please let me know if you need any more information.

Thanks in advance!

**Will this change the current api? How?**
It will add SparseReorder and SegmentSum

**Who will benefit with this feature?**
Anyone who wishes to convert and use a model contain SparseReorder or SegmentSum ops

**Any Other info.**

**Comment by gaikwadrahul8** [comment]
Hi, @borinstein 

Apologize for the delayed response and I checked [official documentation ](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md) which ops which we support currently for `tensorflowjs_converter` and I see there is [tf.unsortedSegmentSum](https://js.tensorflow.org/api/latest/#unsortedSegmentSum) op available I'm not sure whether it will fulfil requirement of this op `SegmentSum` and for other op `SparseReorder` at the moment we don't support so that op  will be considered as feature request so May I know are you looking both the ops as feature request in the `tensorflowjs_converter` ? Thank you!

**Comment by borinstein** [comment]
Hi, @gaikwadrahul8.

Thanks for the very rapid response!

Yes, we were hoping that adding both the `SegmentSum` and `SparseReorder` ops could be considered as a feature request.

I believe that we encounter `SegmentSum` in our graph by use of [tf.nn.safe_embedding_lookup_sparse](https://www.tensorflow.org/api_docs/python/tf/nn/safe_embedding_lookup_sparse) with `sum` specified as the combiner; I'm not sure how we could eliminate the use of the `SegmentSum` and still use that embedding approach, but I'd definitely be open to suggestions!

**Comment by gaikwadrahul8** [comment]
Hi, @borinstein 

Alright, thank you for the confirmation and now I'm assigning this feature request to dedicated developer team and they'll take appropriate action from their end on the basis of priority and bandwidth so at the moment we're unable to give estimated time for this feature request.  Thank you!

**Comment by borinstein** [comment]
@gaikwadrahul8 thank you very much for considering this request!

**Comment by nileshau-afk** [comment]
Hello @borinstein  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @borinstein  ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
