### ISSUE TITLE
Re: [tensorflow/tfjs] TypeError: Unknown op '_FusedMatMul'. I get this error ( : I'm trying to use qna tensorflow.js model

### ISSUE THREAD

**Issue by Axnjr** [tensorflow/tfjs#7797]
It keeps giving different error now I got : 
Error: No backend found in registry.
    at Engine.getSortedBackends (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4385:19)
    at Engine.initializeBackendsAndReturnBest (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4394:35)
    at Engine.get [as backend] (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4200:31)
    at Engine.makeTensor (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4733:35)
    at makeTensor (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5605:19)
    at tensor (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5654:12)
    at Object.decodeWeights (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5904:29)
    at GraphModel.loadSync (C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:30398:33)
    at C:\Users\yaksh\tensorflowAPI\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:30373:72
    at runMicrotasks (<anonymous>)

**Comment by gaikwadrahul8** [comment]
Hi, @Axnjr 

Thank you for brining this issue to our attention and I tried to use below code snippet to use `qna` model and code is executing as expected but I'm getting result as empty array so May I know are you referring this [official documentation ](https://github.com/tensorflow/tfjs-models/tree/master/qna) to use `qna` model or are you trying to use any custom `qna` model ? if you're using any custom `qna` model then please help us with code-snippet either via codepen or with your github repo  

At the moment qna model is returning an empty array as result, here is similar issue https://github.com/tensorflow/tfjs/issues/7593 and It seems like team is working on it and we'll update you soon. Thank you!


```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.15.0"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Load the qna model. -->
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/qna"> </script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/qna@1.0.1"> </script> -->

</head>

<body>
    <script type="text/javascript">
        const passage = "We belive cats are the real stars of YouTube";
        const question = "What is important to YouTube?";

        // Load the model.
        qna.load().then((model) => {
            console.log(model);
            // Find the answers
            model.findAnswers(question, passage).then((answers) => {
                console.log("Answers: ", answers);
            });
        });
    </script>
</body>

</html>
```
