### ISSUE TITLE
Incorrect summary output 

### ISSUE THREAD

**Issue by lukemovement** [tensorflow/tfjs#7880]
**System information**
- OS: Linux Ubuntu 22.04
- TensorFlow.js npm: 4.9.0
- Environment: Node v18.16.0, ts-node-esm v10.9.1

**Describe the current behavior**
The error message seems to state that the summary of the model is incorrectly printed. This error message does not appear within the code pen link provided, however, it does not finish the training on code pen either.

**Describe the expected behavior**
Not the error message below

**Standalone code to reproduce the issue**
https://codepen.io/Luke-Pring-LukeMovement/pen/MWzzRGO?editors=1012

**Other info / logs** 
/home/luke/Personal/ts-ai/tfjs-core/src/util_base.ts:153
    throw new Error(typeof msg === 'string' ? msg : msg());
          ^
Error: Error in concat3D: Shape of tensors[1] (1,1,128) does not match the shape of the rest (1,50,1) along the non-concatenated axis 1.
    at util.assert (/home/luke/Personal/ts-ai/tfjs-core/src/util_base.ts:153:11)
    at /home/luke/Personal/ts-ai/tfjs-core/src/ops/concat_util.ts:37:7
    at Array.forEach (<anonymous>)
    at Object.assertParamsConsistent (/home/luke/Personal/ts-ai/tfjs-core/src/ops/concat_util.ts:35:10)
    at Object.concat [as kernelFunc] (/home/luke/Personal/ts-ai/tfjs-backend-cpu/src/kernels/Concat.ts:38:16)
    at kernelFunc (/home/luke/Personal/ts-ai/tfjs-core/src/engine.ts:647:22)
    at /home/luke/Personal/ts-ai/tfjs-core/src/engine.ts:713:23
    at Engine.scopedRun (/home/luke/Personal/ts-ai/tfjs-core/src/engine.ts:480:19)
    at Engine.runKernelFunc (/home/luke/Personal/ts-ai/tfjs-core/src/engine.ts:709:10)
    at Engine.runKernel (/home/luke/Personal/ts-ai/tfjs-core/src/engine.ts:554:17)

**Comment by gaikwadrahul8** [comment]
Hi, @lukemovement 

Thank you for bringing this issue to our attention and I tried to replicate the same issue from my end, I'm also getting the same output which you mentioned above, It seems like we have to dig more into this issue and will update you soon. 

I really appreciate your efforts and valuable time, for reference I have added output log below :

```
gaikwadrahul-macbookpro:test-7401 gaikwadrahul$ node index.js
============================
Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details. 
============================
___________________________________________________________________________________________________________________
Layer (type)               Input Shape                 Output shape             Param #     Receives inputs        
===================================================================================================================
input1 (InputLayer)        [[null,null]]               [null,null]              0                                  
___________________________________________________________________________________________________________________
embedding (Embedding)      [[null,null]]               [null,null,128]          9088        input1[0][0]           
___________________________________________________________________________________________________________________
sequential (Sequential)    [[null,null,128]],[[null,nu [null,1,128]             131584      embedding[0][0]        
                                                                                            concat-1[0][0]         
                                                                                            concat-2[0][0]         
                                                                                            concat-3[0][0]         
                                                                                            concat-4[0][0]         
                                                                                            concat-5[0][0]         
                                                                                            concat-6[0][0]         
                                                                                            concat-7[0][0]         
                                                                                            concat-8[0][0]         
                                                                                            concat-9[0][0]         
                                                                                            concat-10[0][0]        
                                                                                            concat-11[0][0]        
                                                                                            concat-12[0][0]        
                                                                                            concat-13[0][0]        
                                                                                            concat-14[0][0]        
                                                                                            concat-15[0][0]        
                                                                                            concat-16[0][0]        
                                                                                            concat-17[0][0]        
                                                                                            concat-18[0][0]        
                                                                                            concat-19[0][0]        
                                                                                            concat-20[0][0]        
                                                                                            concat-21[0][0]        
                                                                                            concat-22[0][0]        
                                                                                            concat-23[0][0]        
                                                                                            concat-24[0][0]        
                                                                                            concat-25[0][0]        
                                                                                            concat-26[0][0]        
                                                                                            concat-27[0][0]        
                                                                                            concat-28[0][0]        
                                                                                            concat-29[0][0]        
___________________________________________________________________________________________________________________
concat-1 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           embedding[0][0]        
                                                                                            sequential[1][0]       
___________________________________________________________________________________________________________________
concat-2 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-1[0][0]         
                                                                                            sequential[2][0]       
___________________________________________________________________________________________________________________
concat-3 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-2[0][0]         
                                                                                            sequential[3][0]       
___________________________________________________________________________________________________________________
concat-4 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-3[0][0]         
                                                                                            sequential[4][0]       
___________________________________________________________________________________________________________________
concat-5 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-4[0][0]         
                                                                                            sequential[5][0]       
___________________________________________________________________________________________________________________
concat-6 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-5[0][0]         
                                                                                            sequential[6][0]       
___________________________________________________________________________________________________________________
concat-7 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-6[0][0]         
                                                                                            sequential[7][0]       
___________________________________________________________________________________________________________________
concat-8 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-7[0][0]         
                                                                                            sequential[8][0]       
___________________________________________________________________________________________________________________
concat-9 (Concatenate)     [[null,null,128],[null,1,12 [null,null,128]          0           concat-8[0][0]         
                                                                                            sequential[9][0]       
___________________________________________________________________________________________________________________
concat-10 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-9[0][0]         
                                                                                            sequential[10][0]      
___________________________________________________________________________________________________________________
concat-11 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-10[0][0]        
                                                                                            sequential[11][0]      
___________________________________________________________________________________________________________________
concat-12 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-11[0][0]        
                                                                                            sequential[12][0]      
___________________________________________________________________________________________________________________
concat-13 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-12[0][0]        
                                                                                            sequential[13][0]      
___________________________________________________________________________________________________________________
concat-14 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-13[0][0]        
                                                                                            sequential[14][0]      
___________________________________________________________________________________________________________________
concat-15 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-14[0][0]        
                                                                                            sequential[15][0]      
___________________________________________________________________________________________________________________
concat-16 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-15[0][0]        
                                                                                            sequential[16][0]      
___________________________________________________________________________________________________________________
concat-17 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-16[0][0]        
                                                                                            sequential[17][0]      
___________________________________________________________________________________________________________________
concat-18 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-17[0][0]        
                                                                                            sequential[18][0]      
___________________________________________________________________________________________________________________
concat-19 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-18[0][0]        
                                                                                            sequential[19][0]      
___________________________________________________________________________________________________________________
concat-20 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-19[0][0]        
                                                                                            sequential[20][0]      
___________________________________________________________________________________________________________________
concat-21 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-20[0][0]        
                                                                                            sequential[21][0]      
___________________________________________________________________________________________________________________
concat-22 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-21[0][0]        
                                                                                            sequential[22][0]      
___________________________________________________________________________________________________________________
concat-23 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-22[0][0]        
                                                                                            sequential[23][0]      
___________________________________________________________________________________________________________________
concat-24 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-23[0][0]        
                                                                                            sequential[24][0]      
___________________________________________________________________________________________________________________
concat-25 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-24[0][0]        
                                                                                            sequential[25][0]      
___________________________________________________________________________________________________________________
concat-26 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-25[0][0]        
                                                                                            sequential[26][0]      
___________________________________________________________________________________________________________________
concat-27 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-26[0][0]        
                                                                                            sequential[27][0]      
___________________________________________________________________________________________________________________
concat-28 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-27[0][0]        
                                                                                            sequential[28][0]      
___________________________________________________________________________________________________________________
concat-29 (Concatenate)    [[null,null,128],[null,1,12 [null,null,128]          0           concat-28[0][0]        
                                                                                            sequential[29][0]      
___________________________________________________________________________________________________________________
dense (Dense)              [[null,1,128]],[[null,1,128 [null,1,71]              9159        sequential[1][0]       
                                                                                            sequential[2][0]       
                                                                                            sequential[3][0]       
                                                                                            sequential[4][0]       
                                                                                            sequential[5][0]       
                                                                                            sequential[6][0]       
                                                                                            sequential[7][0]       
                                                                                            sequential[8][0]       
                                                                                            sequential[9][0]       
                                                                                            sequential[10][0]      
                                                                                            sequential[11][0]      
                                                                                            sequential[12][0]      
                                                                                            sequential[13][0]      
                                                                                            sequential[14][0]      
                                                                                            sequential[15][0]      
                                                                                            sequential[16][0]      
                                                                                            sequential[17][0]      
                                                                                            sequential[18][0]      
                                                                                            sequential[19][0]      
                                                                                            sequential[20][0]      
                                                                                            sequential[21][0]      
                                                                                            sequential[22][0]      
                                                                                            sequential[23][0]      
                                                                                            sequential[24][0]      
                                                                                            sequential[25][0]      
                                                                                            sequential[26][0]      
                                                                                            sequential[27][0]      
                                                                                            sequential[28][0]      
                                                                                            sequential[29][0]      
                                                                                            sequential[30][0]      
___________________________________________________________________________________________________________________
concat (Concatenate)       [[null,1,71],[null,1,71],[n [null,30,71]             0           dense[0][0]            
                                                                                            dense[1][0]            
                                                                                            dense[2][0]            
                                                                                            dense[3][0]            
                                                                                            dense[4][0]            
                                                                                            dense[5][0]            
                                                                                            dense[6][0]            
                                                                                            dense[7][0]            
                                                                                            dense[8][0]            
                                                                                            dense[9][0]            
                                                                                            dense[10][0]           
                                                                                            dense[11][0]           
                                                                                            dense[12][0]           
                                                                                            dense[13][0]           
                                                                                            dense[14][0]           
                                                                                            dense[15][0]           
                                                                                            dense[16][0]           
                                                                                            dense[17][0]           
                                                                                            dense[18][0]           
                                                                                            dense[19][0]           
                                                                                            dense[20][0]           
                                                                                            dense[21][0]           
                                                                                            dense[22][0]           
                                                                                            dense[23][0]           
                                                                                            dense[24][0]           
                                                                                            dense[25][0]           
                                                                                            dense[26][0]           
                                                                                            dense[27][0]           
                                                                                            dense[28][0]           
                                                                                            dense[29][0]           
===================================================================================================================
Total params: 149831
Trainable params: 149831
Non-trainable params: 0
___________________________________________________________________________________________________________________
start training
/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:454
        throw new Error(typeof msg === 'string' ? msg : msg());
              ^

Error: Error in concat3D: Shape of tensors[1] (1,1,128) does not match the shape of the rest (1,30,1) along the non-concatenated axis 1.
    at assert (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:454:15)
    at /Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:27576:13
    at Array.forEach (<anonymous>)
    at Object.assertParamsConsistent (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:27574:12)
    at Object.concat [as kernelFunc] (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:5172:27)
    at kernelFunc (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4704:32)
    at /Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4764:27
    at Engine.scopedRun (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4569:23)
    at Engine.runKernelFunc (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4760:14)
    at Engine.runKernel (/Users/gaikwadrahul/Desktop/TFJS/test-7401/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4633:21)

Node.js v18.17.0
gaikwadrahul-macbookpro:test-7401 gaikwadrahul$ 
```

**Comment by Varun-S10** [comment]
Hi @lukemovement, Thank you for your patience. We have reproduced the issue. As a workaround, please set maskZero to false in your embedding layer to avoid a shape conflict with the automatic padding mask. Could you please try this and let me know if it works for you?
