### ISSUE TITLE
WeChat mini-app doesn't work well with TFJS > 0.10.0

### ISSUE THREAD

**Issue by wangtz** [tensorflow/tfjs#795]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
> 0.10.0
#### Browser version
Wechat mini-app
#### Describe the problem or feature request
thirdScriptError 
 sdk uncaught third Error 
 Could not find a global object 
 Error: Could not find a global object
    at getGlobalNamespace (http://127.0.0.1:43511/appservice/utils/tfjs.js:2:50482)
    at getOrMakeEnvironment (http://127.0.0.1:43511/appservice/utils/tfjs.js:2:50583)
    at http://127.0.0.1:43511/appservice/utils/tfjs.js:2:50734
    at Object.setPrototypeOf.__proto__ (http://127.0.0.1:43511/appservice/utils/tfjs.js:2:69)
    at http://127.0.0.1:43511/appservice/utils/tfjs.js:2:157
    at require (http://127.0.0.1:43511/appservice/__dev__/WAService.js:19:7304)
    at http://127.0.0.1:43511/appservice/__dev__/WAService.js:19:7018
    at http://127.0.0.1:43511/appservice/pages/index/index.js:1:453
    at require (http://127.0.0.1:43511/appservice/__dev__/WAService.js:19:7304)
    at <anonymous>:7:7
#### Code to reproduce the bug / link to feature request
Copy compiled code to a file in wechat mini-app develop tool, and try to import it.

**Comment by nsthorat** [comment]
We have an official tfjs-wechat repo here: https://github.com/tensorflow/tfjs-wechat
