### ISSUE TITLE
Installation issues / Doc unclarity (Ubuntu 20.04)

### ISSUE THREAD

**Issue by jchwenger** [tensorflow/tfjs#7999]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow.js converter installed with pip in a conda env
- TensorFlow.js version: 

*In Python 3.6.8*
```bash
tensorflowjs 3.18.0
Dependency versions:
  keras 2.6.0
  tensorflow 2.6.2

pip 21.3.1
```
*In Python 3.8* 
```bash
tensorflowjs 4.11.0
# error, see below
pip 23.2.1
```

- CUDA/cuDNN version: [Unsure: probably a part of the installation that is taken for granted in the docs? I installed the required dependencies in my other env for the latest Python TF, but for tensorflowjs & tf-nightly-cpu-2.0-preview, where do I find this?]

**Describe the problem**

I'm hoping to find the simplest, and clearest way to install the converter to get students to convert small models from Python to JS, which may prove difficult at this point.

I tried with conda for the base python, followed by pip (hoping I wouldn't have to use pyenv, which would add more install complexity, especially for non MacOS users). Strangely, things seem to be working with python 3.8, but not with 3.6.8.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
conda create -n tfjs-convert python=3.6.8
conda activate tfjs-convert
which pip # correctly points to env pip
pip install tf-nightly-cpu-2.0-preview
pip install tensorflowjs
```
See below the error that I get.

When I do this, however, things *seem* to work out of the box, but that's not in the docs:
```bash
conda create -n tfjs-convert python=3.8
conda activate tfjs-convert
which pip # correctly points to env pip
pip install tensorflowjs # no tf install prior to this
```

I'm assuming (hoping) that *in principle* using a conda env with only python and pip installed should be equivalent to using venv with the same. Could someone confirm that, or confirm that the steps in the docs work on an Ubuntu machine? 

Is there any chance you could either:
1. guarantee that the steps in the docs just work on your end; 
2. see if there's a way for a conda (for python) followed by pip commands would work as well; or even 
3. provide a Docker container that people can just run and that works out of the box?

Also, as you can see, my attempt is with a `.keras` model, which again worked, but isn't present in the readme...?

The functionalities are very nice and promising, and as said I managed to convert a small DCGAN, but the recurrent issues around install, broken libraries links (also in TF updates), are a real barrier of entry (it seems simpler to me now to write a Flask app all in Python rather than guaranteeing the conversion will work)? 

I feel like there's probably a lot of places where I made mistakes here, so I understand if it's a bit difficult to untangle all this, but thanks in advance for any pointers!

**Any other info / logs**

### Error with Python 3.6.8

[In hindsight, probably because the `.keras` format is not supported yet in this version?]

```bash
tensorflowjs_converter --input_format=keras_saved_model ../python/models/dcgan_mnist/e100_generator_mnist.keras  other_dcgan_test

2023-10-11 10:57:05.119439: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.211946: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212087: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212201: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212357: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212469: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.212730: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2023-10-11 10:57:08.213008: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/home/jcw/anaconda3/envs/tfjs-convert/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 813, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 817, in main
    convert(argv[0].split(' '))
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 804, in convert
    weight_shard_size_bytes, metadata_map)
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 520, in _dispatch_converter
    metadata=metadata_map)
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 190, in dispatch_keras_saved_model_to_tensorflowjs_conversion
    model = tf.keras.models.load_model(keras_saved_model_path)
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/keras/saving/saved_model/load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "/home/jcw/anaconda3/envs/tfjs-convert/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 121, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ../DMLAP/python/models/dcgan_mnist/e100_generator_mnist.keras/{saved_model.pbtxt|saved_model.pb}
```

### Seems to work with Python 3.8?

```bash
tfjs tensorflowjs_converter --input_format=keras_saved_model ../python/models/dcgan_mnist/e100_generator_mnist.keras  other_dcgan_test

2023-10-11 11:14:19.008061: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:root:TensorFlow Decision Forests 1.5.0 is compatible with the following TensorFlow Versions: ['2.13.0']. However, TensorFlow 2.13.1 was detected. This can cause issues with the TF API and symbols in the custom C++ ops. See the TF and TF-DF compatibility table at https://github.com/tensorflow/decision-forests/blob/main/documentation/known_issues.md#compatibility-table.
2023-10-11 11:14:22.209841: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
WARNING:tensorflow:From /home/jcw/.local/lib/python3.8/site-packages/keras/src/layers/normalization/batch_normalization.py:883: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/jcw/.local/lib/python3.8/site-packages/keras/src/layers/normalization/batch_normalization.py:883: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
/home/jcw/.local/lib/python3.8/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
2023-10-11 11:14:23.480776: W tensorflow/c/c_api.cc:304] Operation '{name:'batch_normalization_2/moving_mean/Assign' id:213 op device:{requested: '', assigned: ''} def:{{{node batch_normalization_2/moving_mean/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](batch_normalization_2/moving_mean, batch_normalization_2/moving_mean/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
```

### tfjs version error in Python 3.8

```bash
tensorflowjs 4.11.0

Dependency versions:
Traceback (most recent call last):
  File "/home/jcw/anaconda3/envs/dmlap-convert/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/jcw/anaconda3/envs/dmlap-convert/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 958, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/jcw/anaconda3/envs/dmlap-convert/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 962, in main
    convert(argv[0].split(' '))
  File "/home/jcw/anaconda3/envs/dmlap-convert/lib/python3.8/site-packages/tensorflowjs/converters/converter.py", line 888, in convert
    print('  keras %s' % tf.keras.__version__)
  File "/home/jcw/anaconda3/envs/dmlap-convert/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 59, in __getattr__
    return getattr(module, item)
AttributeError: module 'keras.api._v2.keras' has no attribute '__version__'
```

### Note

In none of the environments I create (and even with `conda install pip` to upgrade) does the command ` pip install tensorflowjs[wizard]` works (I'm not sure if the brackets are an option of an older, or newer, version of pip). `pip install tensorflowjs` works, of course, and the wizard ships with it (although I get all sorts of errors and warnings).

**Comment by gaikwadrahul8** [comment]
Hi, @jchwenger 

I apologize for the delayed response. Thank you for bringing this issue to our attention. I believe you are referring to the [official TensorFlow.js documentation](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#getting-started)

I will try to replicate the same behavior on my end using an `Ubuntu 20.04 machine`. It is most likely that the documentation is outdated, but we need to confirm this by replicating the behavior. If we observe the same behavior, we will update the official documentation.

To confirm, did you observe above behaviour on CPU or GPU also after following the [official TensorFlow installation documentation](https://www.tensorflow.org/install/pip#software_requirements) ?

Thank you for your patience and understanding.

**Comment by jchwenger** [comment]
Hi @gaikwadrahul8,

No worries at all, thanks for your reply. Yes indeed, that's what I had in mind. I have a GPU, yes, and can run TF 2.13 without issue, but the tfjs docs specifies a cpu version of TF? Also, tfjs has TF as its dependencies, but does that still mean one should do an install of TF first, and is the latest version compatible? That's the kind of steps that would be nice to have laid out in the docs.

In fact, it's something like [this](https://www.tensorflow.org/install/pip) that would be great to have, so I can tell students, ok, you're on Mac, create an environment, follow these steps, etc.

Thanks in advance!

**Comment by gaikwadrahul8** [comment]
Hi, @jchwenger 

To confirm, is this issue happening only on `MacOS` system or is it happening other OS systems also if that is case then please help us with OS details ?

Currently there is no official GPU support for running TensorFlow on `MacOS` if you're looking to use GPU on MacOS then you'll have to follow these [official documentation](https://developer.apple.com/metal/tensorflow-plugin/) from apple developer forum with `tensorflow-metal`

Yes, you'll have to install Tensorflow on your machine first and to install Tensorflow with CPU then please follow this [official documentation ](https://www.tensorflow.org/install/pip#macos) for `MacOS` , please refer this [Codelab tutorial](https://codelabs.developers.google.com/codelabs/tensorflowjs-convert-python-savedmodel?hl=en#2) which may help you

I see we have updated official documentation to install Tensorflow on `MacOS` with CPU with `Note: Requires Python 3.9–3.11, and pip >= 20.3 for MacOS.`

I agree there should be proper official documentation like Tensorflow installation to tfjs-converter also and we'll update soon on this suggestion.

Meanwhile, could you please follow above steps and let us know, it is resolving your issue or not ? Thank you!

**Comment by jchwenger** [comment]
Oh, no, for me it's happening on Ubuntu 20.04, as I specified in my original issue (which btw did mention that I created a conda env, installed tensorflow cpu with pip, installed tensorflowjs, then ran into errors...)

What I meant was that I would need reliable instructions for various OS-s, _for instance_ Mac, but Windows as well, so that it is possible for me to point people to the right procedure according to each OS!

**Comment by gaikwadrahul8** [comment]
Hi, @jchwenger 

I followed the exact steps which you have mentioned below on my `MacOS M1` with `python 3.8,3.9,3.10 and 3.11` and it's installing as expected but I observed one thing when first time I'm running  `pip install tensorflowjs` command I'm getting below error message but when I'm running the same command again I'm not getting that error message I haven't converted any model to Tensorflow.js I just imported Tensorflow.js 

If you've MacOS system could you please confirm you're also getting the same behaviour or different behaviour which will help us to investigate this issue further, We'll also try to test on other OS systems `Linux` and `Windows`. Thank you!

```
conda create -n tfjs-convert python=3.8
conda activate tfjs-convert
which pip # correctly points to env pip
pip install tensorflowjs # no tf install prior to this
```
**Here is output log with python 3.8 :**
```
(tfjs-convert) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflowjs as tfjs
>>> tfjs.__version__
'4.11.0'
>>> 
(tfjs-convert) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.8.18 (default, Sep 11 2023, 08:17:16) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.13.0'
>>> 
(tfjs-convert) gaikwadrahul-macbookpro:~ gaikwadrahul$ 

```
**Here is output log with python 3.9 :**

```
(tfjs-convert-3.9) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.9.18 (main, Sep 11 2023, 08:25:10) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflowjs as tfjs
>>> tfjs.__version__
'4.11.0'
>>> 
(tfjs-convert-3.9) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.9.18 (main, Sep 11 2023, 08:25:10) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.14.0'
>>> 
(tfjs-convert-3.9) gaikwadrahul-macbookpro:~ gaikwadrahul$ 
```
**Here is output log with python 3.10 :**

```
(tfjs-convert-3.10) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflowjs as tfjs
>>> tfjs.__version__
'4.11.0'
>>> 
(tfjs-convert-3.10) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.14.0'
>>> 
(tfjs-convert-3.10) gaikwadrahul-macbookpro:~ gaikwadrahul$ 

```

**Here is output log with python 3.11 :**

```
(tfjs-convert-3.11) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflowjs as tfjs
>>> tfjs.__version__
'4.11.0'
>>> 
(tfjs-convert-3.11) gaikwadrahul-macbookpro:~ gaikwadrahul$ python
Python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.14.0'
>>> 
(tfjs-convert-3.11) gaikwadrahul-macbookpro:~ gaikwadrahul$ 

```

Please refer below error message which I'm getting when first time I'm running `pip install tensorflowjs` command:

```
Downloading MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (17 kB)
Using cached urllib3-2.0.6-py3-none-any.whl (123 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 064e98b67d7a89e72c37c90254c0a322a0b8d0ce9b68f23286816210e3ef6685
             Got        8460111d7129681c597c0fd8156a64248a1210bd949f0f9b2f9ade0259ea53ec

```

**Comment by jchwenger** [comment]
Hi,

I did one quick test on a conda environment with python 3.11 on a MacBook Air (using Miniforge) and that works like you describe (given that I reckon the problem stems from GPU management in the TF version on Ubuntu, I trust that things would be smoother on Mac?).

Frustratingly, it's on Ubuntu that I run into issues, like this:
```bash
$ tensorflow_wizard
2023-10-16 22:50:01.044782: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-16 22:50:01.044854: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-16 22:50:01.044939: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-16 22:50:02.969401: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Please install PyInquirer using following command:
              pip install PyInquirer==1.0.3
```

(I proceed with `pip install PyInquirer==1.0.3`, and that fails due to:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.13.2 requires prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30, but you have prompt-toolkit 1.0.14 which is incompatible.
```

Oh, something else I noticed that seems missing from the docs: the new recommended format for saving Keras models `.keras`, should that be treated as `--input_format keras_saved_model`? I tried a few options, and that one seemed to work, notwithstanding some warnings (in the Mac env mentioned above). One of the options of the CLI, displayed in `--help` for the `--input_format` is `keras_keras`, which is not described anywhere that I could find.

**Comment by gaikwadrahul8** [comment]
Hi, @jchwenger 

I tried to convert one simple `.keras` model format to `Tensorflow.js` with the help of `tfjs-converter `but it's failing and I'm getting below error so I believe we haven't added support for new `.keras` model format as of now if I'm not wrong, for your reference I have added [gist-file ](https://colab.sandbox.google.com/gist/gaikwadrahul8/540bfba018421a045a3d3a392c4f1260/test-tfjs-7999.ipynb) if that is case then adding support for new .keras model format will be considered as feature request.

Meanwhile, I'll try to test/replicate the same behaviour from my end on other OS systems like `Ubuntu` and `Windows` to update official documentation for [tfjs-converter](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md) if needed.

I really appreciate your efforts and valuable time.thank you for your understanding and patience.



```
2023-10-17 09:29:56.263155: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-17 09:29:56.263264: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-17 09:29:56.263318: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-17 09:29:57.438273: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 958, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 962, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 948, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 618, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 83, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    h5_file = h5py.File(h5_path, 'r')
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by jchwenger** [comment]
Hi @gaikwadrahul8, I just want to say sorry for letting this fall by the wayside. The idea of just using Colab is nice, actually, since at least one avoids having to make sure the cuda/cudnn installation is done properly. 

Note that in your notebook you yourself don't even follow the steps described in the documentation [here](https://github.com/tensorflow/tfjs/tree/master/tfjs-converter#getting-started, and just go `pip install tensorflowjs`! It might be good, given your user base, to make sure that this doc really reflects current use.

Also, I hope the `.keras` format will soon be supported (I've even encountered an issue a few days ago where a `.keras` model saved with TF 2.14 on Colab fails on TF 2.13 on my local machine, so I guess a slight hellishness is likely here to stay, ah well...).

**Comment by gaikwadrahul8** [comment]
Hi, @jchwenger 

I apologize for the inconvenience caused by the stale bot that closed this issue. I have reopened it and the team is working to update the official documentation after testing on different MacOS, Linux and Windows systems . we will update you as soon as possible. Thank you!

**Comment by gun03-hub** [comment]
Hi @gaikwadrahul8 and @pyu10055, I noticed this issue has been open for a while regarding the documentation updates.

I am a Windows user and would love to help validate the installation steps for Windows to close the gap mentioned earlier. Are you still looking for contributors to update the official documentation for non-Linux OSs? If so, I can start testing the current guide on my machine immediately.

**Comment by nileshau-afk** [comment]
Hello @jchwenger ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @jchwenger, Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.

**Comment by jchwenger** [comment]
All good @Varun-S10, if I face it again  I'll reopen.
