### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by ThorvaldAagaard** [tensorflow/tfjs#8030]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 11
- TensorFlow.js installed from npm
- TensorFlow.js version:  3.18

**Describe the problem**
I created a new environment with venv, and executed 
```pip install tensorflowjs```
and got 
```Successfully installed tensorflowjs-3.18.0```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Clean installation to check the converter

**Any other info / logs**
Installed modules
```
(.venv) D:\github\play-card>pip list
Package                      Version
---------------------------- ---------
absl-py                      2.0.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.3.1
flatbuffers                  23.5.26
gast                         0.5.4
google-auth                  2.23.3
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.59.0
h5py                         3.10.0
idna                         3.4
keras                        2.14.0
libclang                     16.0.6
Markdown                     3.5
MarkupSafe                   2.1.3
ml-dtypes                    0.2.0
numpy                        1.26.1
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    20.9
pip                          23.3.1
protobuf                     4.24.4
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pyparsing                    3.1.1
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.14.1
tensorboard-data-server      0.7.1
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-hub               0.12.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
tensorflowjs                 3.18.0
termcolor                    2.3.0
typing_extensions            4.8.0
urllib3                      2.0.7
Werkzeug                     3.0.0
wheel                        0.41.2
wrapt                        1.14.1
```
When calling  tensorflowjs_converter or the wizard I get the same error
```
(.venv) D:\github\play-card>tensorflowjs_converter --help
D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\read_weights.py:28: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.uint8, np.uint16, np.object, np.bool]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\github\play-card\.venv\Scripts\tensorflowjs_converter.exe\__main__.py", line 4, in <module>
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\converters\__init__.py", line 21, in <module>
    from tensorflowjs.converters.converter import convert
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\converters\converter.py", line 35, in <module>
    from tensorflowjs.converters import keras_h5_conversion as conversion
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\converters\keras_h5_conversion.py", line 33, in <module>
    from tensorflowjs import write_weights  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\write_weights.py", line 25, in <module>
    from tensorflowjs import read_weights
  File "D:\github\play-card\.venv\Lib\site-packages\tensorflowjs\read_weights.py", line 28, in <module>
    np.uint8, np.uint16, np.object, np.bool]
                         ^^^^^^^^^
  File "D:\github\play-card\.venv\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?
```
Running python 3.11.0

The error: AttributeError: module 'numpy' has no attribute 'object'.
is related to numpy version, but I tried different versions without success

**Comment by ThorvaldAagaard** [comment]
It looks like this problem is fixed in: https://github.com/tensorflow/tfjs/pull/6625, so the problem seems to be 
```pip install tensorflowjs```
that installs an old version tensorflowjs-3.18.0

Trying to force to latest using 
```pip install tensorflowjs==4.12.0```

give this error:
```
ERROR: Could not find a version that satisfies the requirement tensorflow-decision-forests>=1.5.0 (from tensorflowjs) (from versions: none)
ERROR: No matching distribution found for tensorflow-decision-forests>=1.5.0
````

**Comment by ThorvaldAagaard** [comment]
Ok, it looks like https://pypi.org/project/tensorflow-decision-forests/ is only available on Linux and Mac, so what should I do on Windows 11?

**Comment by ThorvaldAagaard** [comment]
I have installed WSL and converted my model, and the documentation of ```tensorflow_decision_forests``` is fine. 
The only problem is that in current state it is not possible to use tensorflowjs_converter[wizard] on windows, and I did not find that anywhere in the documentation.

**Comment by gaikwadrahul8** [comment]
Hi, @ThorvaldAagaard 

I believe you're installing `pip install tensorflowjs[wizard]` first then to start the conversion wizard use this command `tensorflowjs_wizard` as per our [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#conversion-wizard-tensorflowjs_wizard), if you're following the exact instructions on your `Windows` machine and getting any error messages please help us with error log to investigate this issue further from our end. Thank you!

**Comment by ThorvaldAagaard** [comment]
I did follow the instructions, but there was no mention, that it could not run in windows, but needed to be run in WSL on windows

**Comment by ThorvaldAagaard** [comment]
Thank you. I ended up using WSL for converting the models. But nice with a workaround for windows.
Should we close this issue as the team is aware of the problem?

**Comment by gaikwadrahul8** [comment]
Hi, @ThorvaldAagaard 

You're welcome and yes, team is working on this issue and will fix this issue soon and will update our official documentation, if your issue got resolved please feel free to close this issue. Thank you!

**Comment by Kamal02D** [comment]
this solves the issue for me: 

    np.object = np.object_

to be honest i don't understand what this doing in the background, so be carful but it seemed to work.

**Comment by amanagr1804** [comment]
> this solves the issue for me:
> 
> ```
> np.object = np.object_
> ```
> 
> to be honest i don't understand what this doing in the background, so be carful but it seemed to work.

@Kamal02D where to change 
np.object = np.object_ ???

**Comment by Kamal02D** [comment]
> > this solves the issue for me:
> > ```
> > np.object = np.object_
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to be honest i don't understand what this doing in the background, so be carful but it seemed to work.
> 
> @Kamal02D where to change np.object = np.object_ ???

before  the line that produces the error , or after  the imports

**Comment by alex0590-pixel** [comment]
> > > this solves the issue for me:
> > > ```
> > > np.object = np.object_
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to be honest i don't understand what this doing in the background, so be carful but it seemed to work.
> > 
> > 
> > @Kamal02D where to change np.object = np.object_ ???
> 
> before the line that produces the error , or after the imports

why it doesn't work?
