### ISSUE TITLE
ScatterND tests don't match expected TensorFlow output

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#806]
I'm updating to @tensorflow/tfjs 0.13.2 on the Node bindings and it looks like the scatterND tests are incorrect.

```
Failures:
1) scatterND test-tensorflow {} should work for 2d
  Message:
    Error: Invalid TF_Status: 3
    Message: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [5,3] updates: [3,3]
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:955:17)
        at environment_1.ENV.engine.runKernel.$indices (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:49:33)
        at /usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at scatterND_ (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:48:21)
        at Object.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd_test.ts:28:23)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
        at process.topLevelDomainCallback (domain.js:121:23)

2) scatterND test-tensorflow {} should work for simple 1d
  Message:
    Error: Invalid TF_Status: 3
    Message: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [5] updates: [1]
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:955:17)
        at environment_1.ENV.engine.runKernel.$indices (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:49:33)
        at /usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at scatterND_ (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:48:21)
        at Object.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd_test.ts:40:23)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
        at process.topLevelDomainCallback (domain.js:121:23)

3) scatterND test-tensorflow {} should work for multiple 1d
  Message:
    Error: Invalid TF_Status: 3
    Message: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [5] updates: [3]
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:955:17)
        at environment_1.ENV.engine.runKernel.$indices (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:49:33)
        at /usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at scatterND_ (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:48:21)
        at Object.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd_test.ts:50:23)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
        at process.topLevelDomainCallback (domain.js:121:23)

4) scatterND test-tensorflow {} should sum the duplicated indices
  Message:
    Error: Invalid TF_Status: 3
    Message: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [8] updates: [6]
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:955:17)
        at environment_1.ENV.engine.runKernel.$indices (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:49:33)
        at /usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at scatterND_ (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:48:21)
        at Object.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd_test.ts:89:23)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
        at process.topLevelDomainCallback (domain.js:121:23)

5) scatterND test-tensorflow {} should work for tensorLike input
  Message:
    Error: Invalid TF_Status: 3
    Message: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [5] updates: [3]
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:955:17)
        at environment_1.ENV.engine.runKernel.$indices (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:49:33)
        at /usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at scatterND_ (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd.ts:48:21)
        at Object.scatterND (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/usr/local/google/home/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/scatter_nd_test.ts:99:23)
        at <Jasmine>
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
        at process.topLevelDomainCallback (domain.js:121:23)

Ran 2656 of 2688 specs
2656 specs, 5 failures
Finished in 3.068 seconds
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 
Our op signature matches the generated Python code. I'll look to see if any wrapper APIs do any shaping.

**Comment by nsthorat** [comment]
cc @pyu10055

**Comment by nsthorat** [comment]
Did we ever figure this out, @pyu10055?

**Comment by gaikwadrahul8** [comment]
Hi, @nkreeger 

Apologize for the delayed response and we're re-visiting the older issues to check whether those issues got resolved or not so this issue was happening with too old version of `@tensorflow/tfjs@0.13.2 `so could you please check with latest version of `@tensorflow/tfjs@4.10.0` ? 

We have also updated official documentation w.r.t [tf.scatterND](https://js.tensorflow.org/api/4.10.0/#scatterND)

If issue still persists with latest version of `@tensorflow/tfjs@4.10.0`, let us know with error log so we'll dig more into this issue. Thank you!
