### ISSUE TITLE
React Native real time object detection is too slow 

### ISSUE THREAD

**Issue by fazzysyed** [tensorflow/tfjs#8075]
**The screen is lagging a lot. I have attached the code. Can someone tell me what I am doing wrong?**

import React, { useEffect, useState } from "react";
import { Text, TouchableOpacity, View } from "react-native";
import { Camera } from "expo-camera";
import { StatusBar } from "expo-status-bar";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import * as tf from "@tensorflow/tfjs";
import "@tensorflow/tfjs-react-native";
import { modelURI } from "./modelHandler";
import CameraView from "./CameraView";

const App = () => {
  const [hasPermission, setHasPermission] = useState(null);
  const [type, setType] = useState("back");
  const [model, setModel] = useState(null);
  const [loading, setLoading] = useState({ loading: true, progress: 0 }); // loading state
  const [inputTensor, setInputTensor] = useState([]);

  // model configuration
  const configurations = { threshold: 0.25 };

  useEffect(() => {
    (async () => {
      const { status } = await Camera.requestCameraPermissionsAsync();

      setHasPermission(status === "granted");
      tf.ready().then(async () => {
     

        console.log("backend: " + tf.getBackend());
        const yolov5 = await tf.loadGraphModel(modelURI, {
          onProgress: (fractions) => {
            setLoading({ loading: true, progress: fractions }); // set loading fractions
          },
        }); // load model

        // warming up model
        const dummyInput = tf.ones(yolov5.inputs[0].shape);
        await yolov5.executeAsync(dummyInput);
        tf.dispose(dummyInput);

        // set state
        setInputTensor(yolov5.inputs[0].shape);
        setModel(yolov5);
        setLoading({ loading: false, progress: 1 });
      });
    })();
  }, []);

  return (
    <View className="flex-1 items-center justify-center bg-white">
      {hasPermission ? (
        <>
          {loading.loading ? (
            <Text className="text-lg">
              Loading model... {(loading.progress * 100).toFixed(2)}%
            </Text>
          ) : (
            <View className="flex-1 w-full h-full">
              <View className="flex-1 w-full h-full items-center justify-center">
                <CameraView
                  type={type}
                  model={model}
                  inputTensorSize={inputTensor}
                  config={configurations}
                >
                  <View className="absolute left-0 top-0 w-full h-full flex justify-end items-center bg-transparent z-20">
                    <TouchableOpacity
                      className="flex flex-row items-center bg-transparent border-2 border-white p-3 mb-10 rounded-lg"
                      onPress={() =>
                        setType((current) =>
                          current === "back" ? "front" : "back"
                        )
                      }
                    >
                      <MaterialCommunityIcons
                        className="mx-2"
                        name="camera-flip"
                        size={30}
                        color="white"
                      />
                      <Text className="mx-2 text-white text-lg font-semibold">
                        Flip Camera
                      </Text>
                    </TouchableOpacity>
                  </View>
                </CameraView>
              </View>
            </View>
          )}
        </>
      ) : (
        <View>
          <Text className="text-lg">Permission not granted!</Text>
        </View>
      )}
      <StatusBar style="auto" />
    </View>
  );
};

export default App;

"@tensorflow/tfjs": "^3.20.0",
    "@tensorflow/tfjs-react-native": "^0.8.0",
    "expo": "~46.0.9",

https://github.com/tensorflow/tfjs/assets/24165501/d33fc070-dda0-435e-ab7b-1bf52344400c

**Comment by fazzysyed** [comment]
@gaikwadrahul8 can you please tell me whats the problem what i am doing wrong ?

**Comment by gaikwadrahul8** [comment]
Hi, @fazzysyed 

Apologize for the delayed response and thank you for bringing this issue to our attention, if possible could you please help me with GitHub repo with `package.json` file to clone and instructions/steps to follow to replicate the same behaviour from my end ? 

Thank you for your understanding and patience.

**Comment by fazzysyed** [comment]
https://github.com/Hyuto/yolov5-tfjs-react-native 
is a using this repo

**Comment by gaikwadrahul8** [comment]
Hi, @fazzysyed 

Thank you for sharing the Github repo link, To confirm May I know what all steps you followed so I'll try to replicate the same behavior from my end ? May I know did you try web option or you just installed Expo Go app and scanned QR code ? Thank you.

**Comment by fazzysyed** [comment]
The latest version of Expo Go will be downloaded from the stores, and if the app does not run, you can connect it to the phone to run, and it will automatically download the specific version of Expo Go.

**Comment by fazzysyed** [comment]
any luck @gaikwadrahul8

**Comment by gaikwadrahul8** [comment]
Hi, @fazzysyed 

Apologize for the delayed response and I was trying to replicate the same issue from my end after cloning provided Github repo and following steps which are mentioned in that Github repo but I'm getting below errors so to confirm, did you follow the exact same steps as per Github repo or different ? if you have your own Github repo where you replicate this behavior please share that Github repo with steps

1. `yarn start `Output

```
(base) gaikwadrahul-macbookpro:yolov5-tfjs-react-native gaikwadrahul$ yarn start
yarn run v1.22.21
warning ../../../../package.json: No license field
$ expo start
Starting project at /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native
Starting Metro Bundler

› Metro waiting on exp://127.0.0.1:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: std::__1::system_error: open: /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: std::__1::system_error: open: /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native: Operation not permitted
    at BunserBuf.<anonymous> (/Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (node:events:514:28)
    at BunserBuf.process (/Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/bser/index.js:292:10)
    at /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/bser/index.js:247:12
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Emitted 'error' event on WatchmanWatcher instance at:
    at Client.<anonymous> (/Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/jest-haste-map/build/watchers/WatchmanWatcher.js:150:10)
    at Client.emit (node:events:514:28)
    at BunserBuf.<anonymous> (/Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/fb-watchman/index.js:107:12)
    at BunserBuf.emit (node:events:514:28)
    at /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native/node_modules/bser/index.js:249:12
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  watchmanResponse: {
    error: 'std::__1::system_error: open: /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native: Operation not permitted',
    version: '2023.03.13.00'
  }
}

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2. `expo start` Output :

```
(base) gaikwadrahul-macbookpro:yolov5-tfjs-react-native gaikwadrahul$ expo start
Starting project at /Users/gaikwadrahul/Desktop/TFJS/test-8075/yolov5-tfjs-react-native
Error: Cannot find module 'metro-core'
Require stack:
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/startAsync.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/index.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/bin/cli
- /usr/local/lib/node_modules/expo/bin/cli
Error: Cannot find module 'metro-core'
Require stack:
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/startAsync.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/index.js
- /usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/bin/cli
- /usr/local/lib/node_modules/expo/bin/cli
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/expo/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
(base) gaikwadrahul-macbookpro:yolov5-tfjs-react-native gaikwadrahul$ 
```

After installing the `metro-core` package I'm getting lots of error messages w.r.t to package dependancies even I tried `yarn web` option still did not work, I tried on my MacBook Pro (Apple M1 Pro chip) system

If Am I missing something here please let me know and May I know what Node.js version are you using? 

Thank you for your understanding and cooperation.

**Comment by fazzysyed** [comment]
my node version 
v16.15.0

I am using running it on Apple M1
try this repo
https://github.com/fazzysyed/Tfjs-App

**Comment by gaikwadrahul8** [comment]
Hi, @fazzysyed 

Thank you for providing the information and I have observed the same behavior which you've mentioned, object detection is working slow so we'll have to dig more into this issue because this issue is related with performance 

Thank you for bringing this issue to our attention, I really appreciate your valuable time and efforts. Thank you.

**Comment by alefyufca** [comment]
I'm building an application with these same functions, but when I build it with eas the text doesn't appear, but the objects are detected.

**Comment by fazzysyed** [comment]
@alefyufca you didn't face the slow detection lag? whats your model size?

**Comment by nileshau-afk** [comment]
Hello @fazzysyed  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by fazzysyed** [comment]
Hi @nileshau-afk,

Thanks for the response and for reviewing the issue.

I understand your current priorities. I’m happy to take this up as a community contribution. I’ll fork the repo and go through the TensorFlow.js contribution guidelines before submitting a PR.

I’ll also comment here once I start working on it to avoid duplication.
