### ISSUE TITLE
Tensorflow is not install in python 3.12.1

### ISSUE THREAD

**Issue by Subbyal** [tensorflow/tfjs#8108]
C:\Users\HP>pip install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\Users\HP>pip install torch torchvision torchaudio
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\Users\HP>pip install torch==1.9.1+cpu torchvision==0.10.1+cpu torchaudio==0.9.1+cpu -f https://download.pytorch.org/whl/cpu/stable.html
Looking in links: https://download.pytorch.org/whl/cpu/stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.9.1+cpu

C:\Users\HP>pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

C:\Users\HP>pip install torch torchvision torchaudio
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

C:\Users\HP>pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

C:\Users\HP>pip install --upgrade pip
Requirement already satisfied: pip in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (23.3.2)

C:\Users\HP>pip install --user tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

C:\Users\HP>pip install tensorflow==2.5.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.5.0

C:\Users\HP>python --version
Python 3.12.1

C:\Users\HP>

C:\Users\HP># Create a virtual environment
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\HP>python -m venv myenv

C:\Users\HP>
C:\Users\HP># Activate the virtual environment
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\HP># On Windows
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\HP>myenv\Scripts\activate

(myenv) C:\Users\HP># On Unix or MacOS
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>source myenv/bin/activate
'source' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>
(myenv) C:\Users\HP>
(myenv) C:\Users\HP>
(myenv) C:\Users\HP>pip install tensorflow==2.5.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.5.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(myenv) C:\Users\HP>python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\hp\myenv\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
  Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.2

(myenv) C:\Users\HP>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

(myenv) C:\Users\HP># Create a virtual environment with Python 3.9
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>python -m venv myenv
Error: [Errno 13] Permission denied: 'C:\\Users\\HP\\myenv\\Scripts\\python.exe'

(myenv) C:\Users\HP>
(myenv) C:\Users\HP># Activate the virtual environment
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP># On Windows
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>myenv\Scripts\activate

(myenv) C:\Users\HP># On Unix or MacOS
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>source myenv/bin/activate
'source' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>
(myenv) C:\Users\HP># Install TensorFlow
'#' is not recognized as an internal or external command,
operable program or batch file.

(myenv) C:\Users\HP>pip install tensorflow==2.5.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.5.0

(myenv) C:\Users\HP>pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

(myenv) C:\Users\HP>pip install tf-nightly
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly

(myenv) C:\Users\HP>pip install --upgrade pip
Requirement already satisfied: pip in c:\users\hp\myenv\lib\site-packages (23.3.2)

(myenv) C:\Users\HP>pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

(myenv) C:\Users\HP>pip install tensorflow==2.5.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.5.0

(myenv) C:\Users\HP>

**Comment by Subbyal** [comment]
tensor flow and torch is not compatible with python 3.12.1

**Comment by gaikwadrahul8** [comment]
Hi, @Subbyal 

Thank you for bringing this issue to our attention and please refer this issue thread https://github.com/tensorflow/tensorflow/issues/62003 so could you please give it try with `tf-nightly` by using this command `pip install tf-nightly` with `Python 3.12` on `Linux` system because as per that issue thread discussion first` Python 3.12 `support will come on `Linux` system with `tf-nightly`

Google only builds the `Linux` wheels now so please refer these comments [Ref-1](https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-1826830636), [Ref-2](https://github.com/tensorflow/tensorflow/issues/62003#issuecomment-1832075559)

Thank you for your understanding and patience.

**Comment by Subbyal** [comment]
No I already tried but its Not installing i want to work on tensor flow how can I workSent from my iPhoneOn 27-Dec-2023, at 1:21 AM, gaikwadrahul8 ***@***.***> wrote:﻿
Hi, @Subbyal
Thank you for bringing this issue to our attention and please refer this issue thread tensorflow/tensorflow#62003 so could you please give it try with tf-nightly by using this command pip install tf-nightly with Python 3.12 on Linux system because as per that issue thread discussion firstPython 3.12support will come on Linux system with tf-nightly
Google only builds the Linux wheels now so please refer these comments Ref-1, Ref-2
Thank you for your understanding and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @Subbyal 

I have tried to install `tf-nightly` with `Python 3.12` on `Ubuntu 20.04` system and it's not working as expected I'm getting below error output log and as per my current understanding our relevant team is working on to support `Python 3.12` version   :

```
Building wheels for collected packages: dm-tree
  Building wheel for dm-tree (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dm-tree (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/tree
      copying tree/tree_benchmark.py -> build/lib.linux-x86_64-cpython-312/tree
      copying tree/tree_test.py -> build/lib.linux-x86_64-cpython-312/tree
      copying tree/__init__.py -> build/lib.linux-x86_64-cpython-312/tree
      copying tree/sequence.py -> build/lib.linux-x86_64-cpython-312/tree
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 77, in _check_build_environment
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gaikwadrahul/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 124, in <module>
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7ap5ile_/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 70, in run
        File "<string>", line 80, in _check_build_environment
      RuntimeError: CMake must be installed to build the following extensions: _tree
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dm-tree
Failed to build dm-tree
ERROR: Could not build wheels for dm-tree, which is required to install pyproject.toml-based projects
gaikwadrahul@rahul-ubuntu-tfjs-20:~/tf-testing-with-py-3.12$ 
```



It's working as expected with `Python 3.9`, `Python 3.10` and `Python 3.11` so at the moment workaround is to use one of the Python versions from `Python 3.9` to `Python 3.11 ` instead of `Python 3.12` if it's not mandatory or compulsion to use Tensorflow with Python 3.12 only . 



```
Python 3.11.6 (main, Dec  1 2023, 19:45:02) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2023-12-27 11:19:46.423012: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-27 11:19:46.425507: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:19:46.466622: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-27 11:19:46.466661: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-27 11:19:46.467963: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-27 11:19:46.474809: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:19:46.475087: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-27 11:19:47.397594: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> tf.__version__
'2.15.0'
>>> quit()
gaikwadrahul@rahul-ubuntu-tfjs-20:~/tf-testing-with-py-3.12$  
```

```
gaikwadrahul@rahul-ubuntu-tfjs-20:~/tf-testing-with-py-3.12$ python
Python 3.9.10 (main, Dec  1 2023, 19:04:04) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2023-12-27 11:42:14.420391: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-27 11:42:14.422810: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:42:14.463998: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-27 11:42:14.464037: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-27 11:42:14.465223: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-27 11:42:14.471468: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:42:14.471750: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-27 11:42:15.388905: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> tf.__version__
'2.15.0'
>>> quit()
```

```
gaikwadrahul@rahul-ubuntu-tfjs-20:~/tf-testing-with-py-3.12$ python
Python 3.10.9 (main, Dec  1 2023, 19:24:42) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2023-12-27 11:46:23.568535: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-27 11:46:23.570844: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:46:23.610268: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-27 11:46:23.610320: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-27 11:46:23.611405: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-27 11:46:23.617575: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-27 11:46:23.617819: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-27 11:46:24.553967: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> tf.__version__
'2.15.0'
>>> quit()
gaikwadrahul@rahul-ubuntu-tfjs-20:~/tf-testing-with-py-3.12$ 
```

**Comment by gaikwadrahul8** [comment]
Hi, @Subbyal 

I haven't heard from you for while and this issue is related with Tensorflow core not with Tensorflow.js so please refer this issue thread https://github.com/tensorflow/tensorflow/issues/62003 for future update so at the moment I'm closing this issue now 

If you want please feel free to create new [issue](https://github.com/tensorflow/tensorflow/issues/new/choose) in Tensorflow core Github

Thank you for your understanding and patience.
