### ISSUE TITLE
TypeError: forwardFunc_1 is not a function

### ISSUE THREAD

**Issue by osynkad** [tensorflow/tfjs#8120]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Sonoma 14.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow.js installed from (npm or script link): @tensorflow/tfjs-node
- TensorFlow.js version: 4.15.0
- CUDA/cuDNN version: N/A

**Describe the problem**

I'm currently integrating [face-api.js](https://github.com/justadudewhohacks/face-api.js) for face recognition in my project. To improve performance, I'm installing @tensorflow/tfjs-node as recommended in their documentation.

I've followed the setup instructions provided in https://github.com/tensorflow/tfjs/tree/master/tfjs-node#using-the-binding. However, when executing the script, I'm running into the following issue:

```
TypeError: forwardFunc_1 is not a function
```

**Environment**

Tested with the following node versions:
- 18.19.0
- 20.9.0

Similar issues where I have tested their solutions without any result: #7356, #5608, #2329

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. `npm install @tensorflow/tfjs-node`
2. Use the binding in my script with `const tf = require('@tensorflow/tfjs-node');`
3. Execute the javascript file

**Any other info / logs**
```
/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4746
                out = _this.tidy(function () { return forwardFunc_1(_this.backend, saveFunc_1); });
                                                      ^

TypeError: forwardFunc_1 is not a function
    at /Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4746:55
    at /Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4562:22
    at Engine.scopedRun (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4572:23)
    at Engine.tidy (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4561:21)
    at kernelFunc (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4746:29)
    at /Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4767:27
    at Engine.scopedRun (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4572:23)
    at Engine.runKernelFunc (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4763:14)
    at mul_ (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs-core/dist/ops/binary_ops.js:327:28)
    at Object.mul (/Users/user/Documents/generate-descriptions/node_modules/@tensorflow/tfjs-core/dist/ops/operation.js:46:29)

Node.js v18.19.0
```

**Comment by gaikwadrahul8** [comment]
Hi, @osynkad 

Thank you for bringing this issue to our attention and please refer this [comment](https://github.com/justadudewhohacks/face-api.js/issues/768#issuecomment-798908869) w.r.t [face-api.js](https://github.com/justadudewhohacks/face-api.js) which is obsolete so you can either install obsolete `tfjs-node 1.x` or use newer port of face-api.js from below references :

- https://github.com/vladmandic/face-api
- https://www.npmjs.com/package/@vladmandic/face-api

Please check differences compared to [face-api.js](https://github.com/justadudewhohacks/face-api.js) version` 0.22.2` from [here](https://github.com/vladmandic/face-api?tab=readme-ov-file#differences).

Thank you for your understanding and patience.

**Comment by osynkad** [comment]
> Hi, @osynkad
> 
> Thank you for bringing this issue to our attention and please refer this [comment](https://github.com/justadudewhohacks/face-api.js/issues/768#issuecomment-798908869) w.r.t [face-api.js](https://github.com/justadudewhohacks/face-api.js) which is obsolete so you can either install obsolete `tfjs-node 1.x` or use newer port of face-api.js from below references :
> 
> * https://github.com/vladmandic/face-api
> * https://www.npmjs.com/package/@vladmandic/face-api
> 
> Please check differences compared to [face-api.js](https://github.com/justadudewhohacks/face-api.js) version` 0.22.2` from [here](https://github.com/vladmandic/face-api?tab=readme-ov-file#differences).
> 
> Thank you for your understanding and patience.

That makes sense.

I'll have to look into what the necessary changes are to port to a newer version of `face-api.js`.

Closing this as I now know what is causing the issues. Thanks @gaikwadrahul8 for pointing me in the right direction. 👍
