### ISSUE TITLE
Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor

### ISSUE THREAD

**Issue by alena424** [tensorflow/tfjs#8121]
**System information**
Platform: iOS 
Versions:
```
    "@tensorflow/tfjs": "^4.15.0",
    "@tensorflow/tfjs-react-native": "^1.0.0",
```

**Standalone code to reproduce the issue**
```

const modelJSON = require('../../../assets/ml/model.json')
const modelWeights = require('../../../assets/ml/group1-shard1of1.bin')

export default function Screen() {
  const loadModel = async () => {
    const model = await tf.loadGraphModel(bundleResourceIO(modelJSON, modelWeights)).catch((e) => {
      console.log('[LOADING ERROR] info:', e)
    })
    if (!model) return
    console.log('loaded', model.inputs)

    // model is of shape [-1,16000]
    const inputTensor = tf.randomNormal([1, 16000])
    //Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor
    const prediction = model.predict(inputTensor)
    console.log('prediction', prediction)
  }

  useEffect(() => {
    tf.ready()
      .then(() => {
        console.log('[LOADING] tf.ready()')
        loadModel()
      })
      .catch((e) => {
        console.log('[LOADING ERROR] info:', e)
      })
  }, [])

return null;
}

```
I keep getting error when predict is called, model is loaded correctly.
```
Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor
Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor
```

Of course, I can share the model and the weights if it's necessary.
I am almost giving up on tfjs, thank you for your help!

**Describe the expected behavior**
There should be no error.

**Comment by gaikwadrahul8** [comment]
Hi, @alena424 

Thank you for bringing this issue to our attention and could you please help us with your Github repo link and steps to run  with model and `package.json` file to replicate the same behavior from our end also. Thank you for your understanding and patience.

**Comment by alena424** [comment]
Hello @gaikwadrahul8,

thank you for your quick response.

there is a bare repo with the error created just for the testing purpose: https://github.com/alena424/tensorflowjs-test/tree/master

**Comment by gaikwadrahul8** [comment]
Hi, @alena424 

Thank you for sharing Github repo link to replicate the same issue from our end also and I was trying to replicate the same issue after cloning your Github repo but i'm getting below error log after running `npm run start` command so Am I missing something here from my end ? if so please help/guide me 

Here is error output log after running `npm run start` command :

![image](https://github.com/tensorflow/tfjs/assets/115997457/131d7aaf-81d0-4572-b7fb-e02d931800fc)

**Comment by alena424** [comment]
hmm, I ve never see this error. Are you familiar with expo/react native development?
If not, you could basically just start by running an empty project to make sure everything is working on your machine: `https://docs.expo.dev/get-started/create-a-project/`

=> I only added 2 packages to the empty repo + the code snippet + one change in metro.config.

Which is your dev IO? Have you ran `npm i`?

**Comment by gaikwadrahul8** [comment]
Hi, @alena424

Initially I tried on my own `Mac M1` system and yes I ran `npm install` command to install all the package dependancies mentioned in the `package.json` file before `npm run start` command so I'll try on my `Windows VM` and will see is it showing me the same error message which you've mentioned in your issue template

I tried both the ways by creating empty Expo project and cloning your Github repo directly but still I'm getting the same error output log. Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @alena424 

My bad there was some issue with Expo Go App connection so after adding `"start": "expo start --tunnel"` flag`(--tunnel)` in `"scripts"` that issue got solved and I'm able to replicate the same behavior from my end also so we'll have to dig more into this issue and will get back to you soon. thank you for bringing this issue to our attention, I really appreciate your valuable time and efforts. 

Thank you for your cooperation and patience.

Here is error output log for reference :

```
Logs for your project will appear below. Press Ctrl+C to exit.
Android Bundling complete 8153ms
 LOG  [LOADING] tf.ready()
 LOG  loaded => [{"dtype": "float32", "name": "x", "shape": [-1, 16000]}]
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor
Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor
    at assertDtype (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:249154:22)
    at convertToTensor (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:249162:18)
    at gather_ (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:254508:29)
    at apply (native)
    at gather__op (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:249223:30)
    at executeOp$5 (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:268872:29)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:269294:31)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172528:20)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172538:20)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172523:28)
    at tidy (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:174384:23)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:269293:22)
    at executeOp (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:269324:6)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:270173:36)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172528:20)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172538:20)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:172523:28)
    at tidy (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:174384:23)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:270146:22)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:271599:41)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:271447:39)
    at ?anon_0_ (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:130163:39)
    at next (native)
    at asyncGeneratorStep (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6083:26)
    at _next (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:6102:29)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39557:26)
    at _callTimer (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39436:17)
    at _callReactNativeMicrotasksPass (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39481:17)
    at callReactNativeMicrotasks (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39687:44)
    at __callReactNativeMicrotasks (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3643:46)
    at anonymous (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3417:45)
    at __guard (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3616:15)
    at flushedQueue (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3416:21)
    at callFunctionReturnFlushedQueue (http://jakxoe0.anonymous.8081.exp.direct/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3401:33)
```

**Comment by alena424** [comment]
Alright, let me know if you need anything from my side! Just for reference - I got this model from some basic tensorflow tutorial https://colab.research.google.com/drive/1ll9WJ7ny7TmjMtoqCBECdnigVI25avX9?usp=sharing

**Comment by Josh-Weston** [comment]
Receiving the same error when attempting to use the functional API with custom layers.

```typescript
const stringColumn = tf.tensor2d(['apple', 'banana', 'cherry', 'date'], [4, 1], 'string');
const numericColumns = tf.tensor2d([
    [0.1, 0.5, 2.5, 3],
    [0.2, 1.5, 3.5, 4],
    [0.8, 0.7, 4.5, 5],
    [2.2, 1.1, 5.5, 6]
]);

// Define the graph
const wideInputsString = tf.input({ shape: [1], dtype: 'string' }) // first column of strings should be one-hot-encoded
const wideInputsNumber = tf.input({ shape: [2] }); // next two columns as numbers
const deepInputs = tf.input({ shape: [2] }); // next two column as numbers

const stringLookup = new StringLookup({ outputMode: 'one_hot' });
const ohe = stringLookup.apply(wideInputsString) as tf.SymbolicTensor;

const standardScaler = new StandardScalerLayer();
const standardWide = standardScaler.apply(wideInputsNumber) as tf.SymbolicTensor; // returns a symbolic tensor because it is being called with a symbolic tensor

const minMaxScaler = new MinMaxScalerLayer();
const normDeep = minMaxScaler.apply(deepInputs) as tf.SymbolicTensor; // returns a symbolic tensor because it is being called with a symbolic tensor

const wideInputs = tf.layers.concatenate().apply([ohe, standardWide]) as tf.SymbolicTensor;

// Define the deep part of the model
const deep = tf.layers.dense({ units: 30, activation: 'relu' }).apply(normDeep);
const deepOutput = tf.layers.dense({ units: 30, activation: 'relu' }).apply(deep) as tf.SymbolicTensor;

// Concatenate the wide and deep parts
const combinedOutput = tf.layers.concatenate().apply([wideInputs, deepOutput]);
const output = tf.layers.dense({ units: 1 }).apply(combinedOutput) as tf.SymbolicTensor;

// Define the model (three inputs, one output)
const model = tf.model({ inputs: [wideInputsString, wideInputsNumber, deepInputs], outputs: [output] }); // inputs can only be input layers

// Adapt our layers to our input
stringLookup.adapt(stringColumn);
standardScaler.adapt(numericColumns.slice([0, 0], [-1, 2]));
minMaxScaler.adapt(numericColumns.slice([0, 2], [-1, 2]));

// Compile the model
model.compile({
    optimizer: tf.train.adam(),
    loss: 'meanSquaredError'
});

// Generate some dummy labels for training
const labels = tf.tensor2d([[1], [2], [3], [4]]);

// Train the model
model.fit([stringColumn, numericColumns.slice([0, 0], [-1, 2]), numericColumns.slice([0, 2], [-1, 2])], labels, {
    epochs: 10,
    batchSize: 2,
}).then(() => {
    console.log('Training complete');
    // Optionally, evaluate the model
    const prediction = model.predict([stringColumn, numericColumns.slice([0, 0], [-1, 2]), numericColumns.slice([0, 2], [-1, 2])]) as tf.Tensor;
    prediction.print();
});
```

My `StringLookup` custom layer converts the string tensor into a numeric tensor; however, the code fails when processing the input tensors:

`Error: Argument 'x' passed to 'gather' must be numeric tensor, but got string tensor`

I can track the issue to `tfjs-core/gather.js` which calls the `convertToTensor` function in `tensor_utils_env.js`

```javascript
function assertDtype(expectedDtype, actualDType, argName, functionName) {
    if (expectedDtype === 'string_or_numeric') {
        return;
    }
    if (expectedDtype == null) {
        throw new Error(`Expected dtype cannot be null.`);
    }
    if (expectedDtype !== 'numeric' && expectedDtype !== actualDType ||
        expectedDtype === 'numeric' && actualDType === 'string') {
        throw new Error(`Argument '${argName}' passed to '${functionName}' must ` +
            `be ${expectedDtype} tensor, but got ${actualDType} tensor`);
    }
}

export function convertToTensor(x, argName, functionName, parseAsDtype = 'numeric') {
    if (x instanceof getGlobalTensorClass()) {
        assertDtype(parseAsDtype, x.dtype, argName, functionName);
        return x;
    }
   ...
}
```
As shown, the default for `parsesDtype` is `numeric`, which cannot be influenced from outside of the library. I would like to be able to pass a `string` tensor so I can keep all of the transformations within the model without needing to track them externally.

Thoughts? Maybe I am going about this wrong? Any thoughts and guidance is appreciated.

**Comment by nileshau-afk** [comment]
Hello @alena424 ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the TensorFlow Contribution Guidelines, Tfjs Contributions and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @alena424, Thank you for your patience. We have reproduced the issue. As a workaround, you can wrap bundleResourceIO in a custom handler that re-populates weightSpecs using tf.io.getWeightSpecs(modelJSON.weightsManifest). Could you please try this approach and let us know if it resolves the issue for you?
