### ISSUE TITLE
tfjs converter supported `tf.keras.layers.Conv2DTranspose` ?

### ISSUE THREAD

**Issue by kaka-lin** [tensorflow/tfjs#8148]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: No
- OS Platform and Distribution: MacOS
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.16.0
- Tensorflow.js Converter Version: 4.16.0

**Describe the current behavior**

My model has a layer as below:

```python
tf.keras.layers.Conv2DTranspose(
    self.hidden_size // 4, kernel_size=2, strides=2, name="0.0", data_format="channels_first")
```

I converted this model to `tfjs format` and ran it, encountered an error as below:

```
util_base.ts:153 Uncaught (in promise) Error: Error in conv2dDerInput: depth of input (128) must match input depth for filter 64.
    at Module.assert (util_base.ts:153:1)
    at conv2DBackpropInput_ (conv2d_backprop_input.ts:87:1)
    at conv2DBackpropInput__op (operation.ts:51:1)
    at conv2dTranspose_ (conv2d_transpose.ts:54:1)
    at Module.conv2dTranspose__op (operation.ts:51:1)
    at Module.executeOp (convolution_executor.ts:183:1)
    at operation_executor.ts:69:1
    at engine.ts:469:1
    at Engine.scopedRun (engine.ts:480:1)
    at Engine.tidy (engine.ts:467:1)
```

And then when I edit `conv2d_transpose.js`

```python
return conv2DBackpropInput(outputShape, $x, $filter, strides, pad, 'NHWC', dimRoundingMode);
```

to 

```python
return conv2DBackpropInput(outputShape, $x, $filter, strides, pad, 'NCHW', dimRoundingMode);
```

then occur an error like below:

<img width="692" alt="截圖 2024-01-19 下午12 53 31" src="https://github.com/tensorflow/tfjs/assets/20853096/5c31d098-2dea-4de1-82e7-d9862c0b817f">

**Describe the expected behavior**

Should be run without any error.

**Comment by gaikwadrahul8** [comment]
Hi, @kaka-lin 

Thank you for bringing this issue to our attention and if possible could you please help me with your model and tfjs_converter command which you're using to convert your model into Tensorflow.js model so I'll try to replicate same behavior from my end also ? 

If you're using Google colab to convert your model to Tensorflow.js please help me with that Google colab notebbok.

Thank you for your cooperation and patience.

**Comment by kaka-lin** [comment]
Hi, @gaikwadrahul8 

My tfjs_converter is: 

```sh
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_format=tfjs_graph_model \
    --signature_name=serving_default \
    --saved_model_tags=serve \
    weights/saved_model \
    weights/web_model
```

My model is modified by [transformers/src/transformers/models/sam/modeling_tf_sam.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/sam/modeling_tf_sam.py#L551) and saved to `SaveModel` format.

**Comment by kaka-lin** [comment]
Hi, @gaikwadrahul8

This repo: [kaka-lin/EfficientSAM-tf2-demo](https://github.com/kaka-lin/EfficientSAM-tf2-demo) includes my weights and related inference code, please check it, thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @kaka-lin 

I apologize for the delayed response and I see [official documentation](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/docs/supported_ops.md) of **tfjs_converter supported ops**  for `conv2dTranspose` Op and it's showing not mapped with Tensorflow Op so there's no direct equivalent operation in the TensorFlow backend at this time.

As far my current understanding you can't directly use that API in a TFJs model that needs to be executed by the TensorFlow backend so If you have the expertise create a custom layer that implements transposed convolution using supported TensorFlow ops so please feel free to do that.

Thank you for your cooperation and patience.

**Comment by kaka-lin** [comment]
Hi, @gaikwadrahul8 

I created a custom layer of transposed convolution and found the problem is biasAdd does not support `NCHW`, so would occur the error below:

<img width="692" alt="297961079-5c31d098-2dea-4de1-82e7-d9862c0b817f" src="https://github.com/tensorflow/tfjs/assets/20853096/3d64b28e-e31d-4138-b774-a6ed4038a592">

Also the same as issue #3282.

So I created a custom layer and changed NCHW to NHWC and it works, thank you!

**Comment by nileshau-afk** [comment]
Hello @kaka-lin ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @kaka-lin, Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it. Thank you for your understanding.
