### ISSUE TITLE
Cannot read properties of undefined (reading '_malloc')

### ISSUE THREAD

**Issue by pkesseli** [tensorflow/tfjs#8153]
**System information**
- Windows 10 22H2
- Brave (Chrome 121 on Windows)
- TensorFlow.js installed from: https://www.npmjs.com/package/@tensorflow/tfjs/v/3.20.0
- TensorFlow.js version: 3.20.0
- TFLite.js version: 0.0.1-alpha.9

I encountered this issue https://github.com/tensorflow/tfjs/issues/7893 when using [@tensorflow/tfjs-tflite@0.0.1-alpha.10](https://www.npmjs.com/package/@tensorflow/tfjs-tflite/v/0.0.1-alpha.10). So I regressed to [@tensorflow/tfjs-tflite@0.0.1-alpha.9](https://www.npmjs.com/package/@tensorflow/tfjs-tflite/v/0.0.1-alpha.9), as suggested in the issue. As a consequence of this downgrade, I had to use [@tensorflow/tfjs@3.20.0](https://www.npmjs.com/package/@tensorflow/tfjs/v/3.20.0), as illustrated in https://github.com/tensorflow/tfjs/issues/7789.

With this setup, I tried to load a `.tfilte` model as follows:

```typescript
const modelContent: ArrayBuffer = await modelDownloadWithProgress.arrayBuffer();
console.log(`features: ${JSON.stringify(await getWasmFeatures())}`);
const model: TFLiteModel = await loadTFLiteModel(modelContent)
console.log(`model: ${model}`);
```

The output is the following:
```
features: {"simd":true,"multiThreading":false}
tflite_web_api_client.js:2710 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_malloc')
    at $jscomp.generator.Engine_.eval [as program_] (tflite_web_api_client.js:2710:245)
    at $jscomp.generator.Engine_.nextStep_ (tflite_web_api_client.js:31:105)
    at $jscomp.generator.Engine_.next_ (tflite_web_api_client.js:27:234)
    at $jscomp.generator.Generator_.next (tflite_web_api_client.js:32:73)
    at b (tflite_web_api_client.js:33:73)
```

The referenced line is the following:
```javascript
module$exports$google3$third_party$tensorflow_lite_support$web$tflite_web_api_client.TFLiteWebModelRunner.create = function(a, b) {
    b = void 0 === b ? {} : b;
    var c, d, e, f, g, h, k, l, m, n, p, q, r;
    return $jscomp.asyncExecutePromiseGeneratorProgram(function(t) {
        if (1 == t.nextAddress)
            return c = module$exports$google3$third_party$tensorflow_lite_support$web$task$codegen$common$emscripten_module_loader.EmscriptenModuleLoader.getInstance(module$contents$google3$third_party$tensorflow_lite_support$web$tflite_web_api_client_wasmModulesPath, "tflite_web_api", '"use strict";var Module={};var initializedJS=false;var pendingNotifiedProxyingQueues=[];function threadPrintErr(){var text=Array.prototype.slice.call(arguments).join(" ");console.error(text)}function threadAlert(){var text=Array.prototype.slice.call(arguments).join(" ");postMessage({cmd:"alert",text:text,threadId:Module["_pthread_self"]()})}var err=threadPrintErr;self.alert=threadAlert;Module["instantiateWasm"]=(info,receiveInstance)=>{var instance=new WebAssembly.Instance(Module["wasmModule"],info);receiveInstance(instance);Module["wasmModule"]=null;return instance.exports};self.onunhandledrejection=e=>{throw e.reason??e};self.onmessage=e=>{try{if(e.data.cmd==="load"){Module["wasmModule"]=e.data.wasmModule;Module["wasmMemory"]=e.data.wasmMemory;Module["buffer"]=Module["wasmMemory"].buffer;Module["ENVIRONMENT_IS_PTHREAD"]=true;if(typeof e.data.urlOrBlob=="string"){importScripts(e.data.urlOrBlob)}else{var objectUrl=URL.createObjectURL(e.data.urlOrBlob);importScripts(objectUrl);URL.revokeObjectURL(objectUrl)}tflite_web_api_ModuleFactory(Module).then(function(instance){Module=instance})}else if(e.data.cmd==="run"){Module["__performance_now_clock_drift"]=performance.now()-e.data.time;Module["__emscripten_thread_init"](e.data.pthread_ptr,0,0,1);Module["establishStackSpace"]();Module["PThread"].receiveObjectTransfer(e.data);Module["PThread"].threadInitTLS();if(!initializedJS){Module["__embind_initialize_bindings"]();pendingNotifiedProxyingQueues.forEach(queue=>{Module["executeNotifiedProxyingQueue"](queue)});pendingNotifiedProxyingQueues=[];initializedJS=true}try{Module["invokeEntryPoint"](e.data.start_routine,e.data.arg)}catch(ex){if(ex!="unwind"){if(ex instanceof Module["ExitStatus"]){if(Module["keepRuntimeAlive"]()){}else{Module["__emscripten_thread_exit"](ex.status)}}else{throw ex}}}}else if(e.data.cmd==="cancel"){if(Module["_pthread_self"]()){Module["__emscripten_thread_exit"](-1)}}else if(e.data.target==="setimmediate"){}else if(e.data.cmd==="processProxyingQueue"){if(initializedJS){Module["executeNotifiedProxyingQueue"](e.data.queue)}else{pendingNotifiedProxyingQueues.push(e.data.queue)}}else{err("worker.js received unknown command "+e.data.cmd);err(e.data)}}catch(ex){if(Module["__emscripten_thread_crashed"]){Module["__emscripten_thread_crashed"]()}throw ex}};\n'),
            d = $jscomp,
            e = d.makeIterator,
            t.yield(Promise.all([c.load(), "string" === typeof a ? fetch(a).then(function(u) {
                return u.arrayBuffer()
            }) : Promise.resolve(a)]), 2);
        f = e.call(d, t.yieldResult);
        g = f.next().value;
        h = f.next().value;
        k = g;
        l = h;
        m = new Uint8Array(l);
        n = k._malloc(m.length); // <== k is undefined
        k.HEAPU8.set(m, n);
```

Perhaps this is a result of using a woefully outdated TensorFlow.js version, so my question would be:

- Will there be a @tensorflow/tfjs-tflite@0.0.1-alpha.11 release which resolves https://github.com/tensorflow/tfjs/issues/7893 or
- How can I resolve this issue with version 3.20.0 of TensorFLow.js?

Thanks for any suggestions you can provide!

**Comment by gaikwadrahul8** [comment]
Hi, @pkesseli 

I apologize for the delayed response and could you please help us with your Github repo or sample code snippet (along with `TensorFlow Lite model (.tflite file)`) with complete steps to replicate the same behavior from our end ? Thank you for your cooperation and patience.

**Comment by pkesseli** [comment]
Hi @gaikwadrahul8,

Thanks for your response. I created a minimal repro that you can download here:
https://1drv.ms/f/s!AgTGrw38VMRagvcARXTu4TVM12H8BQ?e=pGg5TE

Steps to reproduce:
```bash
npm install
npm run dev
```

If you browse http://localhost:3000 and look at the development console, you should see the following output:
```
Starting model creation...
model.ts:17 features: {"simd":true,"multiThreading":false}
tflite_web_api_client.js:2710 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_malloc')
    at $jscomp.generator.Engine_.eval [as program_] (tflite_web_api_client.js:2710:245)
    at $jscomp.generator.Engine_.nextStep_ (tflite_web_api_client.js:31:105)
    at $jscomp.generator.Engine_.next_ (tflite_web_api_client.js:27:234)
    at $jscomp.generator.Generator_.next (tflite_web_api_client.js:32:73)
    at b (tflite_web_api_client.js:33:73)
eval @ tflite_web_api_client.js:2710
$jscomp.generator.Engine_.nextStep_ @ tflite_web_api_client.js:31
$jscomp.generator.Engine_.next_ @ tflite_web_api_client.js:27
next @ tflite_web_api_client.js:32
b @ tflite_web_api_client.js:33
```

**Comment by pkesseli** [comment]
Apologies, the link expired today. Renewed it by another two weeks.

**Comment by gaikwadrahul8** [comment]
Hi, @pkesseli

I sincerely apologize for the delayed response and thank you for sharing the workable link and now I'm able to replicate the same behaviour from my end also so we'll have to dig more into this issue and will update you soon. thank you for bringing this issue to our attention.


![image](https://github.com/tensorflow/tfjs/assets/115997457/e0f257bc-6e0d-4b66-8816-b560d8791de3)

Thank you for your understanding and patience.

**Comment by mittalmohit** [comment]
Hello everyone i am using tensor flow lite version @tensorflow/tfjs-tflite@0.0.1-alpha.9 with peer dependency @tensorflow/tfjs@4.9.0. 

also i am trying to load model like:
const tfliteModel = await tflite.loadTFLiteModel('assets/models/litemodal.tflite');
console.log(tfliteModel)

But getting error:
# **Cannot read properties of undefined (reading '_malloc')**

please help

**Comment by sb2702** [comment]
I had the exact same issue as @pkesseli, to the line. I was loading the libraries from a worker module environment (though I think the module environment was the key here)

When trying to run tflite.loadModel, I observed no network requests to load the [tflite_web_api_cc.js](https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10/wasm/tflite_web_api_cc.js) modules, and other files in the remote wasm folder, nor when manually specifying `tflite.setWasmPath()`, neither specifying the remote path nor specifying a local path with the same files hosted seem to work.

I know the model works because I use the same exact model with the same exact library files, to the version, when loaded directly from cdn in a script tag. I'm guessing the libraries by default assume loading from CDN as I've had other errors in the path working with tfjs-lite from npm but never when loading from cdn.

An unelegant workaround that I found was to create a worker that can load the scripts directly from CDN, that seems to work

Parent:
```
 const worker = new Worker(new URL(`@/my_path/tfjs_worker.js', import.meta.url));

 worker.postMessage('Ping from parent');
```

Worker
```
importScripts('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core');
importScripts('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm');
importScripts('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10')


self.onmessage = async function(event) {


    const url = 'http://localhost:port/self/hosted/path';

    tflite.setWasmPath('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10/wasm/')

    const model = await tflite.loadTFLiteModel(url)

    console.log(model)


};

```

The above seems to work for me. I**t doesn't work if you don't specify the remote `setWasmPath`**

**Comment by mittalmohit** [comment]
Thank you @sb2702 . I am able to successfully load model after setWasmPath

tflite.setWasmPath('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10/wasm/')

**Comment by pkesseli** [comment]
Thanks @mittalmohit, that does resolve my issue. However, as mentioned above, due to issue https://github.com/tensorflow/tfjs/issues/7893 I was forced to use @tensorflow/tfjs-tflite@0.0.1-alpha.9. Did you actually get @tensorflow/tfjs-tflite@0.0.1-alpha.10 to work? If so, how did you fix https://github.com/tensorflow/tfjs/issues/7893?

**Comment by maikthomas** [comment]
I am also experiencing both #7893 and this issue.
I'm using module workers so tried using `import()` to get the scripts 
```
        await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.19.0");
        await import("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-tflite@0.0.1-alpha.10"); // also tried alpha.9
```
which works in importing the scripts but no matter how I import the scripts or which version I use I always get the `read properties of undefined (reading '_malloc')` error.
It seems to be some issue loading `tflite_web_api_cc_simd.js`

Is there any other way around this?

**Comment by maikthomas** [comment]
It looks like the code in the API client file is trying to load the simd.js file via `importScripts` which doesn't work in a module worker.
I assume the code is autogenerated since I can't see it in the source code anywhere 
![image](https://github.com/user-attachments/assets/b2f85b02-ef15-430f-a1bf-e3f3e246802a)
![image-1](https://github.com/user-attachments/assets/d8b12a81-04b0-425d-8ba0-160e43b2fb7f)

I think this is the underlying error here.
Possibly related to #6402

**Comment by kirill-konshin** [comment]
Possibly that's because demo uses 3.x TFJS:

```
    "@tensorflow/tfjs-backend-cpu": "3.14.0",
    "@tensorflow/tfjs-core": "3.14.0",
    "@tensorflow/tfjs-tflite": "0.0.1-alpha.8"
```

**Comment by Varun-S10** [comment]
Hi @pkesseli, I noticed your comment mentioning that the issue is now resolved. Since you have confirmed this, I am going to go ahead and close the issue. If you or anyone else encounters this issue again, please feel free to reopen it. Thank you for your understanding
