### ISSUE TITLE
Tensorflow.js Converter: Usage of `save_format` when converting to graph model causes error on Keras 3

### ISSUE THREAD

**Issue by JRF63** [tensorflow/tfjs#8229]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WSL2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow.js installed from (npm or script link): Not applicable
- TensorFlow.js version (use command below): Not applicable
- Browser version: Not applicable
- Tensorflow.js Converter Version: 4.17

**Describe the current behavior**

tensorflow 2.16.1 requires keras>=3.0.0, but I think passing the `save_format` [argument](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/python/tensorflowjs/converters/converter.py#L227) is a [hard error](https://github.com/keras-team/keras/blob/v3.0.0/keras/saving/saving_api.py#L66) in keras>=3.0.0 if the extension is not .h5/.hdf5/.keras (current code is using a .savedmodel).

**Describe the expected behavior**

Avoid using `save_format`.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

```python
from tensorflow_model_optimization.python.core.keras.compat import keras

model = keras.Sequential(
    [
        keras.layers.InputLayer(input_shape=(28, 28)),
        keras.layers.Reshape(target_shape=(28, 28, 1)),
        keras.layers.Conv2D(filters=12, kernel_size=(3, 3), activation="relu"),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(10),
    ]
)

model.compile(
    optimizer="adam",
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

model.save("test.keras")
```

then

```sh
tensorflowjs_converter --input_format=keras --output_format=tfjs_graph_model --quantize_uint8=* test.keras webmodel
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```sh
Traceback (most recent call last):
  File "/home/user/tensorflow-spreads/venv/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 958, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 962, in main
    convert(argv[0].split(' '))
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 948, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 634, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_graph_model_conversion(
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/tensorflowjs/converters/converter.py", line 227, in dispatch_keras_h5_to_tfjs_graph_model_conversion
    model.save(temp_savedmodel_dir, include_optimizer=False, save_format='tf')
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/user/tensorflow-spreads/venv/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 66, in save_model
    raise ValueError(
ValueError: The `save_format` argument is deprecated in Keras 3. Please remove this argument and pass a file path with either `.keras` or `.h5` extension.Received: save_format=tf
```

**Comment by gaikwadrahul8** [comment]
Hi, @JRF63 

I apologize for the delayed response and as far I know the `TensorFlow.js` converter currently does not support converting `Keras` models saved in the new format `.keras` . it's still relatively new and hasn't been fully integrated with the TensorFlow.js converter yet. TensorFlow.js developer team is actively developing the `tfjs-converter` and support for the new `.keras` format might be added in future releases. 

Thank you for bringing this issue to our attention! I've been able to reproduce the problem you described in the issue template. At the moment while we wait for the `tfjs-converter` to support the new `.keras` format, you can use a temporary workaround by simply saving your model in the `.h5` format for TensorFlow.js conversion. I've tested this approach and it seems like working as expected.

For your reference I've created a gist containing your code snippet that demonstrates saving the model in `.h5` format and it's working as expected, please refer this [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/22fc44d604afe1bf5456d60eb337b54f/test-8229.ipynb)

Thank you for your understanding and patience.

**Comment by Satge96** [comment]
Are there any updates regarding the support of .keras models?

**Comment by nileshau-afk** [comment]
Hello @Satge96  ,

Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute) and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @Satge96 ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
