### ISSUE TITLE
Trouble loading a saved model in tfjs-node, "Op type not registered 'DisableCopyOnRead'"

### ISSUE THREAD

**Issue by StratosGiak** [tensorflow/tfjs#8260]
### System Information
- OS Platform and Distribution: Windows 11 and Ubuntu 22.04
- TensorFlow.js installed from: npm
- tfjs-node version: 4.18.0

I have a SavedModel made by exporting [this model](https://github.com/bhky/opennsfw2) using Python with Tensorflow 2.16.1. The model works fine when loaded back into Python, however when I try to load it in Node using `tfjs.node.loadSavedModel()` I get the following errors

```
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:903] tfg_optimizer{} failed: NOT_FOUND: Op type not registered 'DisableCopyOnRead' in binary running on LAPTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
        While importing FunctionDef: __inference__traced_save_11547
        when importing GraphDef to MLIR module in GrapplerHook
E tensorflow/core/framework/node_def_util.cc:630] NodeDef mentions attribute debug_name which is not in the op definition: Op<name=VarHandleOp; signature= -> resource:resource; attr=container:string,default=""; attr=shared_name:string,default=""; attr=dtype:type; attr=shape:shape; attr=allowed_devices:list(string),default=[]; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node Variable}}
I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: ./models/opennsfw2
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:903] tfg_optimizer{} failed: NOT_FOUND: Op type not registered 'DisableCopyOnRead' in binary running on LAPTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
        While importing FunctionDef: __inference__traced_save_11547
        when importing GraphDef to MLIR module in GrapplerHook
I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 1504673 microseconds.
C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:435
        return this.binding.loadSavedModel(path, tags);
                            ^

Error: Failed to load SavedModel: Converting GraphDef to Graph has failed with an error: 'Op type not registered 'DisableCopyOnRead' in binary running on LAPTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.' The binary trying to i
    at NodeJSKernelBackend.loadSavedModelMetaGraph (C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:435:29)
    at Object.<anonymous> (C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\saved_model.js:448:45)
    at step (C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\saved_model.js:49:23)
    at Object.next (C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\saved_model.js:30:53)
    at fulfilled (C:\dev\Projects\nsfw_test\node_modules\@tensorflow\tfjs-node\dist\saved_model.js:21:58)
```

I'm not sure what the problem is, or if it strictly has to do with tfjs to be honest. Is the DisableCopyOnRead op not supported by tfjs-node? Is there a workaround, perhaps by exporting the model some other way? I also tried exporting it in Python with Tensorflow version 2.14.0, the earliest one allowed by the package containing the model, but that had no effect.

**Comment by gaikwadrahul8** [comment]
Hi, @StratosGiak 

I apologize for the delayed response and thank you for bringing this issue to our attention, if possible could you please help us with your Github repo along with converted TensorFlow.js models and complete steps to replicate the same behavior from our end to investigate this issue further from our end ?

Thank you from your cooperation and patience.

**Comment by StratosGiak** [comment]
@gaikwadrahul8 Bumping this once again. I have since tried running this with tfjs-node@2.0.0 and I also tried exporting the model and previous versions of it with Tensorflow 2.12.0, but the same issue persisted

**Comment by crmccar** [comment]
@StratosGiak Did you ever find a solution or workaround?

**Comment by Varun-S10** [comment]
Hi @StratosGiak, Is this issue still happening on your end?

**Comment by StratosGiak** [comment]
Hello, I have long since moved on from this project, but I have restored the repo to test this again: 
https://github.com/StratosGiak/nsfw_test

I updated tfjs to v4.22.0, but unfortunately the problem is not solved. The error message is the same as in the original post

**Comment by Varun-S10** [comment]
Hi @StratosGiak, Apologies for the delay. Thank you for sharing the code to reproduce the issue. We have replicated the issue on our end. We will escalate this to the team for further investigation. Thank you for your patience.

**Comment by Varun-S10** [comment]
Hi @StratosGiak, Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by Varun-S10** [comment]
Hi @StratosGiak, Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it. Thank you for your understanding.
