### ISSUE TITLE
Exception: Error dumping weights, duplicate weight name weight

### ISSUE THREAD

**Issue by kabyanil** [tensorflow/tfjs#8350]
I have a transformer model written from scratch in pytorch, and converted to keras using nobuco. Currently, nobuco only supports tensorflow 2.15.0, so I had to downgrade a bunch of dependencies including jax, jaxlib, and tensorflow-decision-forests. Here is the list of related dependencies with their version numbers -
```
keras                            2.15.0
tensorflow                       2.15.0
tensorflow-datasets              4.9.6
tensorflow-decision-forests      1.8.1
tensorflow-estimator             2.15.0
tensorflow-hub                   0.16.1
tensorflow-io-gcs-filesystem     0.37.1
tensorflow-metadata              1.15.0
tensorflow-probability           0.24.0
tensorflowjs                     4.13.0
tf_keras                         2.15.1
```
After downgrading, nobuco successfully converted the pytorch model to keras (in H5 format). I was then able to convert the keras models into tflite using ```tf.lite.TFLiteConverter.from_keras_model()```. However, using ```tensorflowjs_converter``` doesn't seem to convert the keras model to tfjs format. Here is the error I get -
```
2024-08-02 07:59:21.656726: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-02 07:59:21.656931: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-02 07:59:21.664067: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-02 07:59:24.123131: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 958, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 962, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 948, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 618, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/converter.py", line 98, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    conversion.write_artifacts(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/keras_h5_conversion.py", line 418, in write_artifacts
    weights_manifest = write_weights.write_weights(
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/write_weights.py", line 118, in write_weights
    _assert_no_duplicate_weight_names(weight_groups)
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/write_weights.py", line 346, in _assert_no_duplicate_weight_names
    raise Exception(
Exception: Error dumping weights, duplicate weight name weight
```
Any help in resolving this error would be appreciated!

**Comment by kabyanil** [comment]
Update: I was able to resolve this issue by passing ```constants_to_variables=False``` parameter to ```nobuco.pytorch_to_keras()```.  According to nobuco documentation:

> constants_to_variables: If True, replaces each Pytorch constant tensor with WeightLayer returning corresponding value.
>         Due to how Keras works, this allows multiple layers to use the same set of constants without parameter duplication.

Setting it to false avoids using the same constants in multiple layers.
