### ISSUE TITLE
tfjs_binding.node is not available in node modules. 

### ISSUE THREAD

**Issue by AndreiRD** [tensorflow/tfjs#8377]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 23H2

**Describe the problem**

First it wasn't installing at all so I did like the other issue suggested the following: 

npm install -g node-gyp
npm install --save-exact @tensorflow/tfjs-node@3.1.0

And installation past. But I did not manage to get past the execution issue of missing file as described below

**Any other info / logs** Error description:
C:\Users\Lenovo\Desktop\Programming\Picturefind\node_modules\@tensorflow\tfjs-node\dist\index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\Lenovo\Desktop\Programming\Picturefind\node_modules\@tensorflow\tfjs-node\l
ib\napi-v7\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.   
    at Object.<anonymous> (C:\Users\Lenovo\Desktop\Programming\Picturefind\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\Lenovo\Desktop\Programming\Picturefind\index.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

Node.js v18.13.0

**Comment by gatecrasher777** [comment]
Had a similar problem, solved in my case by copying ```@tensorflow\tfjs-node\lib\napi-v9\tensorflow.dll``` into ```@tensorflow\tfjs-node\lib\napi-v8``` where ```tjfs_binding.node``` is located. In your case, it seems, both those files should be in the ```napi-v7``` folder.

**Comment by AndreiRD** [comment]
Turned out I had not installed C++ update on my Windows. After I made this update, your suggestion worked.
