### ISSUE TITLE
Support node v22 prebuilt binary

### ISSUE THREAD

**Issue by charliez0** [tensorflow/tfjs#8430]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- TensorFlow.js installed from (npm or script link): yarn
- TensorFlow.js version: 4.22.0
- CUDA/cuDNN version: not related

**Describe the problem**
@tfjs-node does not support nodev22.x prebuilt binary

```bash
$ npm view @tensorflow/tfjs-node binary
{
  module_name: 'tfjs_binding',
  module_path: './lib/napi-v{napi_build_version}',
  host: 'https://storage.googleapis.com/tf-builds/pre-built-binary',
  remote_path: './napi-v{napi_build_version}/{version}/',
  napi_versions: [ 3, 4, 5, 6, 7, 8 ]
}
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Kounavi** [comment]
Is there any intention to fix this?
I tried the same using npm and I get a ton of errors:
First error from the logs is here:

```
781 info run @tensorflow/tfjs-node@4.22.0 install node_modules/@tensorflow/tfjs-node node scripts/install.js
782 info run @tensorflow/tfjs-node@4.22.0 install { code: 1, signal: null }
783 verbose stack Error: command failed
783 verbose stack     at promiseSpawn (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
783 verbose stack     at spawnWithShell (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
783 verbose stack     at promiseSpawn (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
783 verbose stack     at runScriptPkg (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
783 verbose stack     at runScript (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
783 verbose stack     at C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
783 verbose stack     at run (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
783 verbose stack     at C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
783 verbose stack     at new Promise (<anonymous>)
783 verbose stack     at callLimit (C:\Users\diakosi7344\AppData\Roaming\nvm\v22.16.0\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
784 verbose pkgid @tensorflow/tfjs-node@4.22.0
785 error code 1
786 error path C:\Users\diakosi7344\workspace\r\node_modules\@tensorflow\tfjs-node
787 error command failed
788 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
789 error CPU-windows-4.22.0.zip
```

**Comment by charliez0** [comment]
Any progresses?

**Comment by seb2010** [comment]
I also second this request. I need to move to node 22 and would need this compatibility...

**Comment by kirillgroshkov** [comment]
We'll need Node 24, and Node 26 (in 2 weeks).

Is there a way the community may help with this issue? Is PR welcome?

**Comment by charliez0** [comment]
> We'll need Node 24, and Node 26 (in 2 weeks).
> 
> Is there a way the community may help with this issue? Is PR welcome?

seems that tfjs development is almost paused lol

**Comment by avmohansai** [comment]
Hello @charliez0 ,
Thank you for bringing this to our attention and for providing a comprehensive overview. We appreciate the time you invested in creating this issue.

Currently, our internal development team is concentrated on other scheduled milestones, so we cannot prioritize this task immediately. However, we would love to see this move forward as a community-led effort.

If you’d like to submit a fix, please fork the repo and open a PR following the [TensorFlow Contribution Guidelines](https://www.tensorflow.org/community/contribute), [Tfjs Contributions ](https://github.com/tensorflow/tfjs/blob/master/tfjs-vis/CONTRIBUTING.md#how-to-contribute)and be sure to link this issue in your PR to avoid duplicate work, kindly leave a comment here if you plan to take this on.

Thank you again for your interest and time.

**Comment by nileshau-afk** [comment]
Hello @charliez0 ,

Thank you for opening this issue. Since this issue has been open for a long time, we are closing this issue for now.
If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
