### ISSUE TITLE
SparseToDense does not properly validate defaultValues to sparse values

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs#844]
Tests fail trying to wire up the SparseToDense tests in Node.js:

```
15) sparseToDense test-tensorflow {} should work for vector
  Message:
    Error: Invalid TF_Status: 3
    Message: cannot compute SparseToDense as input #3(zero-based) was expected to be a int32 tensor but is a float tensor
  Stack:
    Error: Invalid TF_Status: 3
        at <Jasmine>
        at NodeJSKernelBackend.executeSingleOutput (/Users/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:124:41)
        at NodeJSKernelBackend.sparseToDense (/Users/kreeger/workspace/tfjs-node/src/nodejs_kernel_backend.ts:1291:17)
        at environment_1.ENV.engine.runKernel.$sparseIndices (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/sparse_to_dense.ts:73:26)
        at /Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:197:22
        at Engine.scopedRun (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:168:19)
        at Engine.runKernel (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/engine.ts:193:10)
        at sparseToDense_ (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/sparse_to_dense.ts:72:21)
        at Object.sparseToDense (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/operation.ts:46:24)
        at UserContext.<anonymous> (/Users/kreeger/workspace/tfjs-node/node_modules/@tensorflow/tfjs-core/src/ops/sparse_to_dense_test.ts:40:20)
        at <Jasmine>
        at runCallback (timers.js:694:18)
        at tryOnImmediate (timers.js:665:5)
        at processImmediate (timers.js:647:5)
        at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by nsthorat** [comment]
This is now fixed!
