### ISSUE TITLE
WebGL is not supported on this device

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/tfjs#8475]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 15
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 4.22.0
- Browser version: GitHub Actions

**Describe the current behavior**

I wrote a simple loader for tfjs:
```ts
  const tf = await import(/* webpackChunkName: "@tensorflow/tfjs" */ '@tensorflow/tfjs');
  await tf.ready();
```

When I run tests in a headless browser, the test log is full of useless errors - 
```bash
Chrome Headless 131.0.0.0 (Mac OS 10.15.7) WARN: 'Initialization of backend webgl failed'
Chrome Headless 131.0.0.0 (Mac OS 10.15.7) WARN LOG: 'Error: WebGL is not supported on this device
    at new MathBackendWebGL (http://localhost:9876/_karma_webpack_/@tensorflow/webpack:/node_modules/@tensorflow/tfjs-backend-webgl/dist/backend_webgl.js:92:19)
    at Object.factory (http://localhost:9876/_karma_webpack_/@tensorflow/webpack:/node_modules/@tensorflow/tfjs-backend-webgl/dist/base.js:22:36)
    at Engine.initializeBackend (http://localhost:9876/_karma_webpack_/@tensorflow/webpack:/node_modules/@tensorflow/tfjs-core/dist/engine.js:200:50)
    at http://localhost:9876/_karma_webpack_/@tensorflow/webpack:/node_modules/@tensorflow/tfjs-core/dist/engine.js:92:40
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:17:1)
    at executor (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
```
I do not mind the first warning, but the error is redundant. 

Then, if `'gpu' in navigator` (so i assume there is support for WebGPU, I also load:
```ts
    await import(/* webpackChunkName: "@tensorflow/tfjs-backend-webgpu" */ '@tensorflow/tfjs-backend-webgpu');
    await tf.setBackend('webgpu');
```

and get:
```bash
Chrome Headless 131.0.0.0 (Mac OS 10.15.7) WARN: 'TypeError: Cannot read properties of null (reading 'features')
    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/@tensorflow/webpack:/node_modules/@tensorflow/tfjs-backend-webgpu/dist/base.js:31:21)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:17:1)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:369:28)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:2082:39)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:368:34)
    at ZoneImpl.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:111:43)
    at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:2538:40)
Chrome Headless 131.0.0.0 (Mac OS 10.15.7) WARN: 'Initialization of backend webgpu failed'
```

I believe this one is actually an issue in the code. If it is **not supported** it is fine, it should more gracefully report that.

**Describe the expected behavior**

Cleaner tests log.

**Comment by AmitMY** [comment]
Hi! This is not a problem with my macbook. This happens both on my mac (which is version 15) AND in github actions.
This happens in headless runs of our tests.

**Comment by shmishra99** [comment]
Hi @AmitMY , Could you follow this blog to resolve the error? [Link](https://www.partitionwizard.com/partitionmagic/webgl-is-not-supported.html) I'm a bit confused about how you're using the web browser in GitHub Actions. This error seems related to the web browser's WebGL accelerator. Thank You!!

**Comment by AmitMY** [comment]
I am not trying to make WebGL supported, it will not be supported.
I am trying to remove non-useful warnings from flooding my test suite.

This is running inside a headless browser on GitHub actions, from Angular, by using the angular testing tool Karma.
Again, not trying to get WebGL or GPU supported, just to reduce the number of warnings I see

**Comment by shmishra99** [comment]
Hi @AmitMY , 

These warnings are expected for users who are experiencing backend setup issues. If you'd like to suppress all warnings in your test suite, you can modify the `karma.conf.js` file as follows:

```
config.set({
  logLevel: config.LOG_ERROR
});

```
However, this will suppress all warnings, including important ones. If you have suggestions for improving the way warnings are displayed in the `tfjs`, please share them. Thank You!!
