### ISSUE TITLE
tensorflowjs_converter not working

### ISSUE THREAD

**Issue by MI-LA01** [tensorflow/tfjs#913]
#### TensorFlow.js version
N/A
#### Browser version
N/A
#### Describe the problem or feature request

I'm trying to convert a model trained using faster_rcnn_inception_resnet_v2_atrous_coco. However, while running the converter a exception raise. The training was made on Google Colab with tensorflow 1.11.0, python3 and the GPU runtime. 

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=NonMaxSuppressionV3; signature=boxes:float, scores:float, max_output_size:int32, iou_threshold:float, score_threshold:float -> selected_indices:int32>; NodeDef: {{node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/NonMaxSuppressionV3}} = NonMaxSuppressionV3[T=DT_FLOAT](BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Reshape, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Minimum, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/iou_threshold, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/score_threshold). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 272, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 323, in convert_tf_frozen_model
    graph = load_graph(frozen_model_path, output_node_names)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 63, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'T' not in Op<name=NonMaxSuppressionV3; signature=boxes:float, scores:float, max_output_size:int32, iou_threshold:float, score_threshold:float -> selected_indices:int32>; NodeDef: {{node BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/NonMaxSuppressionV3}} = NonMaxSuppressionV3[T=DT_FLOAT](BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Reshape, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Minimum, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/iou_threshold, BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression/score_threshold). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

#### Code to reproduce the bug / link to feature request
The command used for conversion : 
```
tensorflowjs_converter --input_format=tf_saved_model --output_node_names='detection_boxes:0,detection_classes:0,detection_scores:0' '/content/drive/My Drive/app/test02/hail_faster_rcnn_inference_graph/saved_model' '/content/drive/My Drive/app/test02/hail_faster_rcnn_inference_graph_web' 
```

Any help appreciated.

**Comment by caisq** [comment]
@pyu10055 Can you take a look at this issue?

**Comment by pyu10055** [comment]
@MI-LA01 The definition of NonMaxSuppressionV3 is changed recently, which added attr 'T'. 
Yesterday we just released the new version of the tensorflowjs python pip, can you please give it a try again, see if the version we updated to has this change.
If not, you can manually upgrade tensorflow pip to the newest version.

**Comment by MI-LA01** [comment]
@caisq @pyu10055 : Just tested right now and it works. Thx for Your prompt feedback.
