### ISSUE TITLE
Exception when importing latest tfjs-node

### ISSUE THREAD

**Issue by justadudewhohacks** [tensorflow/tfjs#945]
When switching from  tfjs-node 0.1.19 to latest (0.1.21) I am receiving the following error when importing tfjs-node:

```
<...>\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:7
        extendStatics(d, b);
        ^
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (C:\Users\user\dev\face-db\expressions\scraped\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:7:9)
    at C:\Users\user\dev\face-db\expressions\scraped\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:53:5
    at Object.<anonymous> (C:\Users\user\dev\face-db\expressions\scraped\node_modules\@tensorflow\tfjs-node\dist\nodejs_kernel_backend.js:1100:2)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
```

My working environment:
- node: 9.2.0
- npm: 6.4.1
- ts-node: 4.1.0
- typescript: 2.8.4
- tfjs-core: 0.13.8

**Comment by nkreeger** [comment]
Weird. Try deleting your `node_modules` folder and re-running `yarn` or `npm install`.

**Comment by justadudewhohacks** [comment]
Exactly, removing the package-lock.json and clearing node_modules fixed it. Experiencing some weird issues with npm after upgrading to npm 6 lately.

Sorry for bothering...
