### ISSUE TITLE
Unable to convert the embedding layer of a keras estimator

### ISSUE THREAD

**Issue by suyash** [tensorflow/tfjs#947]
Sorry if this is the wrong place to post, the tfjs-converter repo does not have an issue tracker

#### TensorFlow.js Converter version
v0.6.7

#### Browser version
N/A

#### Describe the problem or feature request
Unable to convert a layer from tf_saved_model to FrozenModel

#### Code to reproduce the bug / link to feature request

```py
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, Dense, GlobalAveragePooling1D
from tensorflow.keras.models import Model

inp = Input((16,), name="input_text")
net = Embedding(100, 8)(inp)
net = GlobalAveragePooling1D()(net)
net = Dense(1, activation="sigmoid", name="predictions")(net)

model = Model(inp, net)
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])
model.summary()

runConfig = tf.estimator.RunConfig(model_dir="training", save_checkpoints_secs=60)
estimator = tf.keras.estimator.model_to_estimator(keras_model=model, config=runConfig)

data = tf.data.Dataset.from_tensors((
    np.random.random_sample((8, 16)), 
    np.random.randint(0, 1, (8, 1)),
))
estimator.train(lambda: data.make_one_shot_iterator().get_next())

serving_input_receiver_fn = tf.estimator.export.build_raw_serving_input_receiver_fn({ "input_text": model.input })
estimator.export_saved_model("saved", serving_input_receiver_fn)
```

then to convert the saved model to a FrozenModel do

```
pipenv run tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='predictions/Sigmoid' \
    --saved_model_tags=serve \
    ./saved/1543376701/ \
    ./web
```

It fails with 

```
2018-11-28 09:28:04.532914: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'embedding/embedding_lookup' expects to be colocated with unknown node 'embedding/embedding_lookup/Read/ReadVariableOp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 317, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 291, in convert_tf_saved_model
    graph = load_graph(output_graph + '.frozen', output_node_names)
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 67, in load_graph
    tf.import_graph_def(graph_def, name='')
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/suyash/.local/share/virtualenvs/tfjs_conv_bug-XPvXwdDz/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Node 'embedding/embedding_lookup' expects to be colocated with unknown node 'embedding/embedding_lookup/Read/ReadVariableOp'
```

**Comment by pyu10055** [comment]
there is a known issue with TensorFlow, here is the [link](https://github.com/tensorflow/tensorflow/issues/21889).

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
